- app/build.gradle
- app/src/main/java/org/resolvetosavelives/red/TheActivity.kt
- app/src/main/java/org/resolvetosavelives/red/home/bp/NewBpScreen.kt
- app/src/main/java/org/resolvetosavelives/red/home/bp/NewBpScreenController.kt
- app/src/main/java/org/resolvetosavelives/red/home/bp/NewPatientClicked.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/personal/PatientFullNameTextChanged.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/personal/PatientPersonalDetailsEntryScreen.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/personal/PatientPersonalDetailsEntryScreenController.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/personal/PatientPersonalDetailsProceedClicked.kt
- app/src/main/java/org/resolvetosavelives/red/widgets/UiEvent.kt
- app/src/main/res/layout/screen_patient_personal_details_entry.xml
- app/src/test/java/org/resolvetosavelives/red/home/bp/NewBpScreenControllerTest.kt
- app/src/test/java/org/resolvetosavelives/red/newentry/personal/PatientPersonalDetailsEntryScreenControllerTest.kt
- app/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- quality/pre-push
> MVI in new-bp and patient-personal-details entry screens

- app/src/main/java/org/resolvetosavelives/red/home/bp/NewBpScreen.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/address/PatientAddressEntryEvents.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/address/PatientAddressEntryScreen.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/address/PatientAddressEntryScreenController.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/bp/PatientBpEntryEvents.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/bp/PatientBpEntryScreen.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/bp/PatientBpEntryScreenController.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/bp/PatientBpEntryScreenKey.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/mobile/PatientMobileEntryEvents.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/mobile/PatientMobileEntryScreen.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/mobile/PatientMobileEntryScreenController.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/personal/PatientPersonalDetailsEntryScreenController.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/search/OngoingPatientEntry.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/search/Patient.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/search/PatientDao.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/search/PatientSearchByMobileScreenController.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/search/PatientSearchResultsAdapter.kt
- app/src/main/java/org/resolvetosavelives/red/widgets/Views.kt
- app/src/main/res/layout/screen_patient_address_entry.xml
- app/src/main/res/layout/screen_patient_mobile_entry.xml
- app/src/test/java/org/resolvetosavelives/red/newentry/address/PatientAddressEntryScreenControllerTest.kt
- app/src/test/java/org/resolvetosavelives/red/newentry/bp/PatientBpEntryScreenControllerTest.kt
- app/src/test/java/org/resolvetosavelives/red/newentry/mobile/PatientMobileEntryScreenControllerTest.kt
- app/src/test/java/org/resolvetosavelives/red/newentry/personal/PatientPersonalDetailsEntryScreenControllerTest.kt
- app/src/test/java/org/resolvetosavelives/red/newentry/search/PatientSearchByMobileScreenControllerTest.kt
> Re-architect address entry, blood pressure entry and mobile number entry screens + persist mobile numbers

- README.md
- app/build.gradle
- app/src/debug/res/values/constants.xml
- app/src/main/java/org/resolvetosavelives/red/RedApp.kt
- app/src/main/java/org/resolvetosavelives/red/di/AppComponent.kt
- app/src/main/java/org/resolvetosavelives/red/di/AppModule.kt
- app/src/main/java/org/resolvetosavelives/red/di/NetworkModule.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientPayload.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientPullResponse.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientPushResponse.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientSync.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientSyncApi.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientSyncApiV1.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientSyncConfig.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientSyncModule.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientSyncScheduler.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientSyncWorker.kt
- app/src/main/java/org/resolvetosavelives/red/util/InstantRoomTypeConverter.kt
- app/src/main/res/values/constants.xml
- app/src/test/java/org/resolvetosavelives/red/sync/PatientSyncTest.kt
- build.gradle
> Schedule periodic syncing of patients using WorkManager

- README.md
- app/build.gradle
- app/src/androidTest/java/org/resolvetosavelives/red/AndroidTestJUnitRunner.kt
- app/src/androidTest/java/org/resolvetosavelives/red/TestRedApp.kt
- app/src/androidTest/java/org/resolvetosavelives/red/di/TestAppComponent.kt
- app/src/androidTest/java/org/resolvetosavelives/red/newentry/search/PatientRepositoryAndroidTest.kt
- app/src/androidTest/java/org/resolvetosavelives/red/sync/PatientSyncAndroidTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/resolvetosavelives/red/RedApp.kt
- app/src/main/java/org/resolvetosavelives/red/ReleaseRedApp.kt
- app/src/main/java/org/resolvetosavelives/red/di/AppComponent.kt
- app/src/main/java/org/resolvetosavelives/red/di/AppModule.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/search/PatientRepository.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientPushResponse.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientSync.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientSyncModule.kt
- app/src/main/java/org/resolvetosavelives/red/sync/PatientSyncWorker.kt
- app/src/main/java/org/resolvetosavelives/red/util/Optional.kt
- app/src/main/java/org/resolvetosavelives/red/util/OptionalRxPreferencesConverter.kt
- app/src/test/java/org/resolvetosavelives/red/newentry/search/PatientRepositoryTest.kt
- app/src/test/java/org/resolvetosavelives/red/sync/PatientSyncTest.kt
> Unit tests for syncing and merging of patients

- README.md
Readme: https://github.com/resolvetosavelives/redapp/blob/sn/readme-with-build-steps/README.md
> Update README with steps for downloading and building RedApp

- README.md
@pratul tagging you as a reviewer so that you get annoyed by the email and quickly merge this PR :P
> Update command for accepting Android SDK licenses in README

- app/build.gradle
- app/src/main/java/org/resolvetosavelives/red/RedApp.kt
- app/src/main/java/org/resolvetosavelives/red/di/TheActivityComponent.kt
- app/src/main/java/org/resolvetosavelives/red/facility/Facility.kt
- app/src/main/java/org/resolvetosavelives/red/facility/FacilityRepository.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/DateOfBirthFormatValidator.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/PatientEntryScreen.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/PatientEntryScreenController.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/PatientEntryScreenEvents.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/PatientEntryScreenKey.kt
- app/src/main/java/org/resolvetosavelives/red/patient/OngoingPatientEntry.kt
- app/src/main/java/org/resolvetosavelives/red/patient/PatientRepository.kt
- app/src/main/java/org/resolvetosavelives/red/qrscan/AadhaarScanScreenController.kt
- app/src/main/java/org/resolvetosavelives/red/search/PatientSearchByPhoneScreen.kt
- app/src/main/java/org/resolvetosavelives/red/util/LocalDateRoomTypeConverter.kt
- app/src/main/java/org/resolvetosavelives/red/util/Strings.kt
- app/src/main/res/color/patiententry_radio_button.xml
- app/src/main/res/drawable/ic_arrow_back_24dp.xml
- app/src/main/res/drawable/ic_done_20dp.xml
- app/src/main/res/layout/screen_manual_patient_entry.xml
- app/src/main/res/layout/screen_patient_search_by_phone.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/resolvetosavelives/red/newentry/PatientEntryScreenControllerTest.kt
- app/src/test/java/org/resolvetosavelives/red/patient/OngoingPatientEntryTest.kt
- app/src/test/java/org/resolvetosavelives/red/qrscan/AadhaarScanScreenControllerTest.kt
- build.gradle
- gradle.properties
> Manual patient entry

- app/build.gradle
- app/src/androidTest/java/org/resolvetosavelives/red/bp/sync/BloodPressureSyncAndroidTest.kt
- app/src/androidTest/java/org/resolvetosavelives/red/patient/PatientRepositoryAndroidTest.kt
- app/src/androidTest/java/org/resolvetosavelives/red/patient/PatientSyncAndroidTest.kt
- app/src/main/java/org/resolvetosavelives/red/di/AppModule.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/DateOfBirthAndAgeVisibility.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/DateOfBirthFormatValidator.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/PatientEntryScreen.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/PatientEntryScreenController.kt
- app/src/main/java/org/resolvetosavelives/red/patient/PatientRepository.kt
- app/src/main/java/org/resolvetosavelives/red/qrscan/QrModule.kt
- app/src/main/java/org/resolvetosavelives/red/util/LocalDateRoomTypeConverter.kt
- app/src/main/res/layout/screen_manual_patient_entry.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/org/resolvetosavelives/red/newentry/DateOfBirthFormatValidatorTest.kt
- app/src/test/java/org/resolvetosavelives/red/newentry/PatientEntryScreenControllerTest.kt
> Patient entry: handle none checkbox, format date-of-birth and animate between DOB & age

- app/src/androidTest/java/org/resolvetosavelives/red/patient/PatientSyncAndroidTest.kt
- app/src/debug/res/values/constants.xml
- app/src/main/java/org/resolvetosavelives/red/AppDatabase.kt
- app/src/main/java/org/resolvetosavelives/red/patient/PatientPhoneNumber.kt
- app/src/main/java/org/resolvetosavelives/red/patient/PatientPhoneNumberType.kt
- app/src/main/java/org/resolvetosavelives/red/patient/PatientRepository.kt
- app/src/main/java/org/resolvetosavelives/red/patient/PatientSearchResult.kt
- app/src/main/java/org/resolvetosavelives/red/patient/PatientWithAddressAndPhone.kt
- app/src/main/java/org/resolvetosavelives/red/patient/sync/PatientPayload.kt
- app/src/main/java/org/resolvetosavelives/red/patient/sync/PatientSync.kt
- app/src/main/res/layout/screen_new_bp.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/resolvetosavelives/red/patient/PatientRepositoryTest.kt
- app/src/test/java/org/resolvetosavelives/red/patient/PatientSyncTest.kt
- quality/lint.xml
> Add phone numbers to patient sync 

- app/src/main/java/org/resolvetosavelives/red/di/TheActivityComponent.kt
- app/src/main/java/org/resolvetosavelives/red/newentry/PatientEntryScreen.kt
- app/src/main/java/org/resolvetosavelives/red/patient/Gender.kt
- app/src/main/java/org/resolvetosavelives/red/search/BackButtonClicked.kt
- app/src/main/java/org/resolvetosavelives/red/search/CreateNewPatientClicked.kt
- app/src/main/java/org/resolvetosavelives/red/search/PatientSearchResultsAdapter.kt
- app/src/main/java/org/resolvetosavelives/red/search/PatientSearchScreen.kt
- app/src/main/java/org/resolvetosavelives/red/search/PatientSearchScreenController.kt
- app/src/main/java/org/resolvetosavelives/red/search/PatientSearchScreenEvents.kt
- app/src/main/java/org/resolvetosavelives/red/summary/PatientSummaryScreen.kt
- app/src/main/java/org/resolvetosavelives/red/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/resolvetosavelives/red/summary/PatientSummaryScreenEvents.kt
- app/src/main/java/org/resolvetosavelives/red/summary/PatientSummaryScreenKey.kt
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/resolvetosavelives/red/search/PatientSearchScreenControllerTest.kt
- app/src/test/java/org/resolvetosavelives/red/summary/PatientSummaryScreenControllerTest.kt
> Empty patient summary screen

- .gitignore
- app/build.gradle
- app/src/debug/res/values/strings.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/resolvetosavelives/red/RedApp.kt
- app/src/main/java/org/resolvetosavelives/red/ReleaseRedApp.kt
- app/src/main/resources/sentry.properties
- build.gradle
- gradle.properties
> Add Sentry libraries and configuration

- app/src/debug/AndroidManifest.xml
- app/src/debug/java/org/simple/clinic/DebugClinic.kt
- app/src/main/java/org/simple/clinic/Clinic.kt
- Disable proguard for release build
- Add a DebugClinic application, configure debug build to use that
- Only use Stetho in debug builds
Part of https://github.com/resolvetosavelives/redapp/issues/83.
> Ensure release build works

- app/src/main/java/org/simple/clinic/drugs/selection/PrescribedDrugsScreen.kt
- app/src/main/java/org/simple/clinic/drugs/selection/ProtocolDrugSelectionItem.kt
- app/src/main/java/org/simple/clinic/widgets/Views.kt
- app/src/main/res/drawable/ic_done_16dp.xml
- app/src/main/res/drawable/selector_prescribeddrug_background.xml
- app/src/main/res/layout/list_prescribeddrugs_custom_drug.xml
- app/src/main/res/layout/list_prescribeddrugs_protocol_drug.xml
- app/src/main/res/layout/screen_manual_patient_entry.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
> Design updates for prescriptions screen

- app/build.gradle
- app/src/debug/res/values/constants.xml
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
- app/src/main/res/values/constants.xml
- router/build.gradle
part of https://github.com/resolvetosavelives/redapp/issues/83
> Build all tracks

- app/src/androidTest/java/org/simple/clinic/drugs/sync/PrescriptionSyncAndroidTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheet.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/main/java/org/simple/clinic/di/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/qrscan/AadhaarQrCodeParser.kt
- app/src/main/java/org/simple/clinic/qrscan/AadhaarScanScreen.kt
- app/src/main/java/org/simple/clinic/qrscan/AadhaarScanScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenEvents.kt
- app/src/main/java/org/simple/clinic/summary/SummaryBloodPressureItem.kt
- app/src/main/res/layout/list_patientsummary_add_new_bp_measurement.xml
- app/src/main/res/layout/list_patientsummary_bp_measurement.xml
- app/src/main/res/layout/screen_home.xml
- app/src/main/res/layout/sheet_blood_pressure_entry.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
- app/src/test/java/org/simple/clinic/qrscan/AadhaarScanScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
Bug fixes:
- Summary: done button screen doesn't do anything
- Summary: spacing in blood pressure rows are inconsistent
- Summary: keyboard sometimes overlaps the BP entry sheet
- BP entry now shows three dots for both systolic and diastolic instead of one dot
Also removes the tabs from home screen
> Lotsa bug fixes

- README.md
- app/src/main/java/org/simple/clinic/facility/Facility.kt
- app/src/main/java/org/simple/clinic/facility/FacilityRepository.kt
- app/src/main/java/org/simple/clinic/newentry/DateOfBirthFormatValidator.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreenController.kt
- app/src/main/java/org/simple/clinic/patient/OngoingPatientEntry.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/util/Strings.kt
- app/src/main/res/drawable/ic_filter_20dp.xml
- app/src/main/res/drawable/ic_filter_24dp.xml
- app/src/main/res/layout/screen_manual_patient_entry.xml
- app/src/main/res/layout/screen_patient_search.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/org/simple/clinic/newentry/DateOfBirthFormatValidatorTest.kt
- app/src/test/java/org/simple/clinic/newentry/PatientEntryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/patient/OngoingPatientEntryTest.kt
@dburka / @pratul / @ssrihari this PR adds a few new strings for showing validation errors. They're not very creative, so please improve the if you can. 
We'll also need translations for them. Should we add translations with every new feature change or at the end?
> Patient entry: make the save button persistent + show validation errors

- app/src/main/java/org/simple/clinic/activity/TheActivity.kt
- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/login/phone/LoginPhoneScreen.kt
- app/src/main/java/org/simple/clinic/login/phone/LoginPhoneScreenController.kt
- app/src/main/java/org/simple/clinic/login/phone/LoginPhoneScreenEvents.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationFullNameScreen.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationFullNameScreenController.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameScreenEvents.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameScreenKey.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenController.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenEvents.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenKey.kt
- app/src/main/java/org/simple/clinic/user/OngoingRegistrationEntry.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/main/res/layout/screen_app_lock.xml
- app/src/main/res/layout/screen_login_pin.xml
- app/src/main/res/layout/screen_registration_name.xml
- app/src/main/res/layout/screen_registration_phone.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/org/simple/clinic/login/phone/LoginPhoneScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/registration/name/RegistrationFullNameScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenControllerTest.kt
FYI: the layout isn't ready yet. Govind and I will fix the layouts once all screens for registration are ready.
> Registration: phone and name screens

- app/src/androidTest/java/org/simple/clinic/FakerModule.kt
- app/src/androidTest/java/org/simple/clinic/PatientFaker.kt
- app/src/androidTest/java/org/simple/clinic/bp/sync/BloodPressureSyncAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/drugs/sync/PrescriptionSyncAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientSyncAndroidTest.kt
- Inject `Faker` and `PatientFaker` via Dagger
- Change injected `Faker` instance to generate data specific to India
> Improve Faker and PatientFaker implementation in tests

- app/src/main/java/org/simple/clinic/registration/facility/FacilitiesAdapter.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenController.kt
- app/src/main/res/layout/screen_registration_facility_selection.xml
- app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenControllerTest.kt
Both ListAdapter and FacilitiesAdapter were maintaining the data-set, resulting in two versions existing at the same time everytime ListAdapter ran data-diffing in background
> Fix inconsistent data-set exception in FacilitiesAdapter

- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt
- app/src/main/res/layout/screen_registration_facility_selection.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
> Update error state for facility selection as per the design spec

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/medicalhistory/MedicalHistorySyncAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/communication/Communication.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientAddress.kt
- app/src/main/java/org/simple/clinic/patient/PatientFuzzySearch.kt
- app/src/main/java/org/simple/clinic/patient/PatientPhoneNumber.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
This is in preparation for `Forgot PIN`.
> Add method to clear patient data in Patient Repository

- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/activity/TheActivityController.kt
- app/src/main/java/org/simple/clinic/forgotpin/ForgotPinApiV1.kt
- app/src/main/java/org/simple/clinic/forgotpin/ResetPinRequest.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreen.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenController.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenEvents.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenKey.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinEvents.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinScreen.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinScreenController.kt
- app/src/main/java/org/simple/clinic/login/OtpSmsReceiver.kt
- app/src/main/java/org/simple/clinic/login/applock/ConfirmResetPinDialog.kt
- app/src/main/java/org/simple/clinic/user/ForgotPinResult.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/main/res/layout/screen_app_lock.xml
- app/src/main/res/layout/screen_enterotp.xml
- app/src/main/res/layout/screen_forgotpin_confirmpin.xml
- app/src/main/res/layout/screen_forgotpin_createpin.xml
- app/src/main/res/layout/screen_login_pin.xml
- app/src/main/res/layout/screen_registration_confirm_pin.xml
- app/src/main/res/layout/screen_registration_name.xml
- app/src/main/res/layout/screen_registration_phone.xml
- app/src/main/res/layout/screen_registration_pin.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinScreenControllerTest.kt
- Does not integrate the actual API yet. Uses a dummy implementation in `UserSession`.
> Forgot PIN - Confirm PIN

- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenEvents.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenSavedState.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
> Fix: Schedule Appointment sheet doesn't work if you update medicines

- app/build.gradle
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreen.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenEvents.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
Screenshots are disabled for production builds.
> Allow screenshots on staging and QA builds

- app/schemas/org.simple.clinic.AppDatabase/16.json
- app/src/androidTest/java/org/simple/clinic/MigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/ClinicApp.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/patient/PatientFuzzySearch.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/storage/Migration_15_16.kt
- app/src/main/java/org/simple/clinic/storage/Migration_5_6.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
Change it from using the Spellfix virtual table to using a Levenstein matching query.
> Improve patient fuzzy search.

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
1. Update to Gradle 4.10.2
2. Update Android Gradle Plugin to 3.2.0
> Gradle 3.2.0 Support

- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/drugs/selection/AddNewPrescriptionListItem.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryConfig.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModule.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/SummaryAddNewBpListItem.kt
- app/src/main/java/org/simple/clinic/summary/SummaryBloodPressurePlaceholderListItem.kt
- app/src/main/java/org/simple/clinic/summary/SummaryListAdapterIds.kt
- app/src/main/java/org/simple/clinic/summary/SummaryPrescribedDrugsItem.kt
- app/src/main/res/layout/list_patientsummary_bp_placeholder.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
> Show placeholders for BP measurements

- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreenController.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreenEvents.kt
- app/src/main/java/org/simple/clinic/patient/OngoingPatientEntry.kt
- app/src/main/java/org/simple/clinic/patient/PatientEntryValidationError.kt
- app/src/main/res/layout/screen_manual_patient_entry.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-pa/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/newentry/PatientEntryScreenControllerTest.kt
1. Remove `None` checkbox from phone number and make it optional.
2. Remove `None` checkbox from colony and make it mandatory.
> Patient Entry UI Changes

- app/src/androidTest/java/org/simple/clinic/TestClinicApp.kt
- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/ClinicApp.kt
- app/src/main/java/org/simple/clinic/ReleaseClinicApp.kt
- app/src/main/java/org/simple/clinic/analytics/Analytics.kt
- app/src/main/java/org/simple/clinic/analytics/AnalyticsReporter.kt
- app/src/main/java/org/simple/clinic/analytics/DebugAnalyticsReporter.kt
- app/src/main/java/org/simple/clinic/analytics/HeapAnalyticsReporter.kt
- app/src/main/java/org/simple/clinic/crash/Breadcrumb.kt
- app/src/main/java/org/simple/clinic/crash/CrashBreadcrumbsTimberTree.kt
- app/src/main/java/org/simple/clinic/crash/CrashReporter.kt
- app/src/main/java/org/simple/clinic/crash/CrashReporterModule.kt
- app/src/main/java/org/simple/clinic/crash/SentryCrashReporter.kt
- app/src/main/java/org/simple/clinic/di/AppComponent.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/test/java/org/simple/clinic/ReportAnalyticsEventsTest.kt
- app/src/test/java/org/simple/clinic/analytics/AnalyticsTest.kt
- app/src/test/java/org/simple/clinic/analytics/MockAnalyticsReporter.kt
- app/src/test/java/org/simple/clinic/analytics/NetworkAnalyticsInterceptorTest.kt
- app/src/test/java/org/simple/clinic/analytics/UpdateAnalyticsUserIdTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/newentry/PatientEntryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
- build.gradle
> Forward logs to Sentry as breadcrumbs

- app/src/main/java/org/simple/clinic/user/UserSession.kt
I was accidentally logging the response :/
> Fix: correctly log login result in UserSession [WIP]

- app/build.gradle
- app/src/main/java/org/simple/clinic/drugs/selection/PrescribedDrugsScreen.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/java/org/simple/clinic/widgets/OmegaCenterIconButton.java
- build.gradle
1. Also upgrades support lib to `28.0.0`.
> Update compile SDK to 28

- app/src/androidTest/java/org/simple/clinic/AuthenticationRule.kt
- app/src/androidTest/java/org/simple/clinic/facility/FacilitySyncAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/user/UserSessionAndroidTest.kt
- app/src/main/java/org/simple/clinic/facility/Facility.kt
- app/src/main/java/org/simple/clinic/facility/FacilityPullResponse.kt
- app/src/main/java/org/simple/clinic/facility/FacilityRepository.kt
- app/src/main/java/org/simple/clinic/facility/FacilitySync.kt
- app/src/test/java/org/simple/clinic/sync/ModelSyncTest.kt
Improved `ModelSyncTest` a bit as well.
> Change FacilitySync to use the new Synceable framework.

- RELEASING.md
Add document that describes the release process for the Simple Android app.
> Document a formal release process

- app/src/main/java/org/simple/clinic/patient/fuzzy/AgeFuzzerModule.kt
> Change age fuzziness for patient search

- app/src/androidTest/java/org/simple/clinic/AndroidTestJUnitRunner.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreenController.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentConfig.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentModule.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
FYI: this is behind a feature flag and is currently disabled.
>  Order overdue appointments by keeping high risk patients at the top

- app/src/androidTest/java/org/simple/clinic/facility/FacilityRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/facility/Facility.kt
- app/src/main/java/org/simple/clinic/facility/FacilityRepository.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilitiesUpdateType.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityChangeScreen.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityChangeScreenController.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityChangeScreenEvents.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenController.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenEvents.kt
- app/src/main/res/layout/screen_facility_change.xml
- app/src/main/res/layout/screen_registration_facility_selection.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/facility/change/FacilityChangeScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenControllerTest.kt
Search works, but the UI changes aren't finished yet. What's left:
- The search field should only be shown when facilities are available. See [this](https://zpl.io/2vWEqR5) and [this](zpl.io/aNo67Nd).
- Search query can be highlighted on results. This is a nice to have, but not important.
We can do both these in the next PR, if needed.
> Facility search

- app/build.gradle
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/main/java/org/simple/clinic/patient/filter/PatientSearchContext.kt
- app/src/main/java/org/simple/clinic/patient/filter/SearchContext.kt
- app/src/main/java/org/simple/clinic/patient/filter/SearchPatientByName.kt
- app/src/main/java/org/simple/clinic/patient/filter/SortByTotalSumOfDistances.kt
- app/src/main/java/org/simple/clinic/patient/filter/WeightedLevenshteinSearch.kt
- app/src/test/java/org/simple/clinic/patient/filter/SortByTotalSumOfDistancesTest.kt
- app/src/test/java/org/simple/clinic/patient/filter/WeightedLevenshteinSearchTest.kt
- build.gradle
@saket @sanchita I'd like both of your eyes on the PRs that make up the new fuzzy search implementation since there a lot of changes from what was being done earlier.
FYI: This doesn't introduce any actual changes to the behaviour, just introduces some classes that will be used in a future PR.
> Fuzzy name search method that works on the basis of individual parts in a name and search term

- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/protocolv2/sync/ProtocolSyncAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/protocolv2/Protocol.kt
- app/src/main/java/org/simple/clinic/protocolv2/ProtocolDrug.kt
- app/src/main/java/org/simple/clinic/protocolv2/ProtocolDrugsWithDosage.kt
- app/src/main/java/org/simple/clinic/protocolv2/ProtocolModule.kt
- app/src/main/java/org/simple/clinic/protocolv2/ProtocolPullResponse.kt
- app/src/main/java/org/simple/clinic/protocolv2/ProtocolRepository.kt
- app/src/main/java/org/simple/clinic/protocolv2/ProtocolSyncApiV2.kt
- app/src/main/java/org/simple/clinic/protocolv2/sync/ProtocolPayload.kt
- app/src/main/java/org/simple/clinic/protocolv2/sync/ProtocolSync.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
- app/src/main/java/org/simple/clinic/sync/SyncWorker.kt
- app/src/test/java/org/simple/clinic/sync/ModelSyncTest.kt
This is the second part of the story to Sync protocol drugs from server. Refer the first PR [here](https://github.com/simpledotorg/simple-android/pull/402).
We add ProtocolSync and a Syncable repository for protocols.
> Sync Protocol Drugs

- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/patient/PatientModule.kt
- app/src/main/java/org/simple/clinic/patient/filter/SortByWeightedNameParts.kt
- app/src/test/java/org/simple/clinic/patient/filter/SortByWeightedNamePartsTest.kt
This PR also enables the new fuzzy search feature.
> Sort fuzzy matches by likeliness of individual parts of a name rather than the complete name

- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt
- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureConfig.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureModule.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheet.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetEvents.kt
- app/src/main/java/org/simple/clinic/bp/entry/ConfirmRemoveBloodPressureDialog.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialogController.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialogEvents.kt
- app/src/main/res/layout/sheet_blood_pressure_entry.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-pa/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_v2.xml
- app/src/test/java/org/simple/clinic/bp/BloodPressureRepositoryTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialogControllerTest.kt
The feature to filter deleted BPs from the UI will be done in an upcoming PR.
> Mark blood pressure as deleted

- app/build.gradle
- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureConfig.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureModule.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheet.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerV2.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetEvents.kt
- app/src/main/java/org/simple/clinic/widgets/BottomSheetActivity.kt
- app/src/main/res/layout/sheet_blood_pressure_entry.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/styles_v2.xml
- app/src/sharedTest/java/org/simple/clinic/util/RxErrorsRule.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTestV2.kt
- build.gradle
https://www.pivotaltracker.com/story/show/163052502
Large-ish PR because the new (and incomplete) date entry functionality is behind a feature flag and it involved duplicating a few classes.
> Retro active BP entry (v1)

- app/src/androidTest/java/org/simple/clinic/protocolv2/ProtocolRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/drugs/selectionv2/PrescribedDrugEvents.kt
- app/src/main/java/org/simple/clinic/drugs/selectionv2/PrescribedDrugScreenV2.kt
- app/src/main/java/org/simple/clinic/drugs/selectionv2/PrescribedDrugsScreenControllerV2.kt
- app/src/main/java/org/simple/clinic/drugs/selectionv2/PrescribedDrugsScreenKeyV2.kt
- app/src/main/java/org/simple/clinic/drugs/selectionv2/ProtocolDrugListItem.kt
- app/src/main/java/org/simple/clinic/drugs/selectionv2/dosage/DosageAdapter.kt
- app/src/main/java/org/simple/clinic/drugs/selectionv2/dosage/DosageOption.kt
- app/src/main/java/org/simple/clinic/drugs/selectionv2/dosage/DosagePickerEvents.kt
- app/src/main/java/org/simple/clinic/drugs/selectionv2/dosage/DosagePickerSheet.kt
- app/src/main/java/org/simple/clinic/drugs/selectionv2/dosage/DosagePickerSheetController.kt
- app/src/main/java/org/simple/clinic/protocol/ProtocolDrug.kt
- app/src/main/java/org/simple/clinic/protocol/ProtocolRepository.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryConfig.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModule.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/SummaryPrescribedDrugsItem.kt
- app/src/main/res/layout/list_prescribeddrugs_new_custom_drug.xml
- app/src/main/res/layout/list_prescribeddrugs_protocol_drug_v2.xml
- app/src/main/res/layout/prescribed_drug_with_dosage_list_item.xml
- app/src/main/res/layout/screen_patient_prescribed_drugs_entry_v2.xml
- app/src/main/res/layout/sheet_dosage_picker.xml
- app/src/main/res/values/styles_v2.xml
- app/src/test/java/org/simple/clinic/drugs/selectionv2/DosagePickerSheetControllerTest.kt
- app/src/test/java/org/simple/clinic/drugs/selectionv2/PrescribedDrugsScreenControllerV2Test.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/162948554
- Add new prescription screen behind a feature flag
- Update UI for protocol drugs 
- Open dosage sheet when a protocol drug is selected
This PR does not implement the new UI for Custom prescriptions.
That will be done in a separate story.
> New prescription Screen

- app/src/main/java/org/simple/clinic/bp/sync/BloodPressureSync.kt
- app/src/main/java/org/simple/clinic/drugs/sync/PrescriptionSync.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistorySync.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentSync.kt
- app/src/main/java/org/simple/clinic/overdue/communication/CommunicationSync.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientSync.kt
- app/src/main/java/org/simple/clinic/sync/DataSync.kt
- app/src/main/java/org/simple/clinic/sync/SyncScheduler.kt
- app/src/main/java/org/simple/clinic/sync/SyncWorker.kt
- app/src/main/java/org/simple/clinic/user/User.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/sync/ModelSyncTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/163217054
> Move user authentication checks to the individual Sync classes

- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryQuestionView.kt
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/styles_v2.xml
https://www.pivotaltracker.com/story/show/163449431
https://zpl.io/bzn3Lx7
> Update spacing of medical history rows in summary

- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/163582080 for details
> Fix: BPs saved with an older date may not sync to some devices

- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/storage/files/AndroidFileStorageAndroidTest.kt
- app/src/main/java/org/simple/clinic/reports/ReportsRepository.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/main/java/org/simple/clinic/storage/files/AndroidFileStorage.kt
- app/src/main/java/org/simple/clinic/storage/files/FileCreator.kt
- app/src/main/java/org/simple/clinic/storage/files/FileStorage.kt
- app/src/main/java/org/simple/clinic/util/KotlinFoo.kt
- app/src/test/java/org/simple/clinic/reports/ReportsRepositoryTest.kt
- app/src/test/java/org/simple/clinic/storage/files/AndroidFileStorageTest.kt
- Add `AndroidFileStorage` to abstract platform file I/O from the rest of the system
- Add `ReportsRepository` that interacts with the file storage to save and read reports
Pivotal Story Link: https://www.pivotaltracker.com/story/show/160962208
> Nurse Reports (Part 1)

- app/build.gradle
- app/schemas/org.simple.clinic.AppDatabase/28.json
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/AppComponent.kt
- app/src/main/java/org/simple/clinic/facility/Facility.kt
- app/src/main/java/org/simple/clinic/facility/FacilityPayload.kt
- app/src/main/java/org/simple/clinic/location/Coordinates.kt
- app/src/main/java/org/simple/clinic/storage/Migration_27_28.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/test/java/org/simple/clinic/facility/FacilityPayloadTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- build.gradle
https://www.pivotaltracker.com/story/show/158963954
This PR,
- adds `Coordinates` to Facility schema + database migration
- adds Play Services library
> Location based facility suggestion (part 1)

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/storage/files/AndroidFileStorageAndroidTest.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityChangeScreenController.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/reports/ReportsRepository.kt
- app/src/main/java/org/simple/clinic/storage/files/AndroidFileStorage.kt
- app/src/main/java/org/simple/clinic/storage/files/FileStorage.kt
- app/src/sharedTest/java/org/simple/clinic/util/RxTestUtils.kt
- app/src/test/java/org/simple/clinic/facility/change/FacilityChangeScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- app/src/test/java/org/simple/clinic/reports/ReportsRepositoryTest.kt
- app/src/test/java/org/simple/clinic/storage/files/AndroidFileStorageTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
Pivotal Story: https://www.pivotaltracker.com/story/show/160962208
> Nurse reports (part 3)

- app/src/androidTest/java/org/simple/clinic/bp/sync/BloodPressureSyncAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/drugs/sync/PrescriptionSyncAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/medicalhistory/MedicalHistorySyncAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentSyncAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/overdue/communication/CommunicationSyncAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientSyncAndroidTest.kt
- app/src/debug/java/org/simple/clinic/DebugNotification.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/sync/DataSync.kt
- app/src/main/java/org/simple/clinic/sync/EnumRxPreferenceConverter.kt
- app/src/main/java/org/simple/clinic/sync/SyncConfig.kt
- app/src/main/java/org/simple/clinic/sync/SyncGroup.kt
- app/src/main/java/org/simple/clinic/sync/SyncGroupResult.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
- app/src/main/java/org/simple/clinic/sync/SyncProgress.kt
- app/src/main/java/org/simple/clinic/sync/SyncWorker.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorModule.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorStatusCalculator.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/sync/DataSyncTest.kt
- app/src/test/java/org/simple/clinic/sync/ModelSyncTest.kt
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorStatusCalculatorTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
Pivotol story-> https://www.pivotaltracker.com/story/show/163619292
> Compute sync status for indicator

- app/src/androidTest/java/org/simple/clinic/TestClinicApp.kt
- app/src/main/java/org/simple/clinic/ClinicApp.kt
- app/src/main/java/org/simple/clinic/analytics/Analytics.kt
- app/src/main/java/org/simple/clinic/analytics/NetworkAnalyticsInterceptor.kt
- app/src/main/java/org/simple/clinic/analytics/NetworkCapabilitiesProvider.kt
- app/src/main/java/org/simple/clinic/di/NetworkModule.kt
- app/src/main/java/org/simple/clinic/sync/BatchSize.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
- app/src/main/java/org/simple/clinic/util/AppArchTaskExecutorDelegate.kt
- app/src/test/java/org/simple/clinic/analytics/AnalyticsTest.kt
- app/src/test/java/org/simple/clinic/analytics/NetworkAnalyticsInterceptorTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/163856354
> Improve sync performance

- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityChangeScreenController.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityListItem.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityListItemBuilder.kt
- app/src/main/java/org/simple/clinic/location/LocationRepository.kt
- app/src/main/java/org/simple/clinic/location/LocationUpdate.kt
- app/src/main/java/org/simple/clinic/registration/RegistrationConfig.kt
- app/src/main/java/org/simple/clinic/registration/RegistrationModule.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenController.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenEvents.kt
- app/src/main/java/org/simple/clinic/util/Distance.kt
- app/src/main/java/org/simple/clinic/util/Haversine.kt
- app/src/test/java/org/simple/clinic/facility/change/FacilityChangeScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/facility/change/FacilityListItemBuilderTest.kt
- app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/158963954
This feature isn't complete yet. This PR introduces,
- displaying the progress indicator in facility selection screen until location is received or it times out
- calculating facilities nearby user (the calculation formula will be added in a later PR)
> Read user's location when displaying facilities

- app/schemas/org.simple.clinic.AppDatabase/29.json
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/sync/BaseSyncCoordinatorAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/patient/SyncStatus.kt
- app/src/main/java/org/simple/clinic/storage/Migration_28_29.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/main/java/org/simple/clinic/sync/SyncCoordinator.kt
- app/src/test/java/org/simple/clinic/bp/BloodPressureRepositoryTest.kt
- app/src/test/java/org/simple/clinic/drugs/PrescriptionRepositoryTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- app/src/test/java/org/simple/clinic/sync/SyncCoordinatorTest.kt
https://www.pivotaltracker.com/story/show/161802996
> Remove IN_FLIGHT status from SyncStatus

- app/src/main/java/org/simple/clinic/sync/LastSyncedState.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorModule.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorState.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorStatusCalculator.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewController.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewEvents.kt
- app/src/test/java/org/simple/clinic/sync/LastSyncedStateTest.kt
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorStatusCalculatorTest.kt
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorViewControllerTest.kt
**Pivotol story** -> https://www.pivotaltracker.com/story/show/163755918
**Part 1:**
This PR adds the `SyncIndicatorView` and `SyncIndicatorViewController`
Also, it does a basic implementation of accessing the `SyncProgress` and updating indicator state based on that.
> Initial implementation of SyncIndicatorView

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/location/LocationRepository.kt
- app/src/main/java/org/simple/clinic/location/LocationUpdate.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenController.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenEvents.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreen.kt
- app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/158963954
> Setup location access using FusedLocationProvider

- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenEvents.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/163080975
> Change rules for showing schedule appointment sheet

- app/src/main/java/org/simple/clinic/analytics/Analytics.kt
- app/src/main/java/org/simple/clinic/analytics/OperationTimingTracker.kt
- app/src/test/java/org/simple/clinic/analytics/AnalyticsTest.kt
- app/src/test/java/org/simple/clinic/analytics/OperationTimingTrackerTest.kt
Pivotal Story: https://www.pivotaltracker.com/story/show/164005123
> Add analytics event for reporting timing events

- app/proguard-rules.pro
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- build.gradle
Pivotal Story Link: https://www.pivotaltracker.com/story/show/164005123
> Send timing events for patient search to analytics

- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/ReleaseClinicApp.kt
- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/sync/LastSyncedState.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorConfig.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorModule.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorState.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorStatusCalculator.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewController.kt
- app/src/main/res/drawable/ic_cloud_done_24dp.xml
- app/src/main/res/drawable/ic_cloud_upload_24dp.xml
- app/src/main/res/drawable/ic_sync_24dp.xml
- app/src/main/res/drawable/ic_warning_24dp.xml
- app/src/main/res/layout/sync_indicator.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_v2.xml
- app/src/test/java/org/simple/clinic/sync/LastSyncedStateTest.kt
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorStatusCalculatorTest.kt
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorViewControllerTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/163755918
> Add Sync Indicator UI

- app/schemas/org.simple.clinic.AppDatabase/30.json
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/AppComponent.kt
- app/src/main/java/org/simple/clinic/patient/BusinessId.kt
- app/src/main/java/org/simple/clinic/storage/Migration_29_30.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/164238481
> Add BusinessId model to the Patient model

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatient.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatientsView.kt
https://www.pivotaltracker.com/story/show/163976144
The SQL query is incomplete. I still need to add queries for remaining tables. That will be done once I write full test suite.
> Fetch recent patients

- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewController.kt
- app/src/main/res/layout/screen_patients_v2.xml
- app/src/main/res/values/strings.xml
Pivotol story -> https://www.pivotaltracker.com/story/show/163755918
To test this, you can enable `showRecentPatients` flag in `PatientConfig`
> Add timer to sync indicator

- app/src/main/java/org/simple/clinic/facility/change/FacilityChangeScreenController.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityListItem.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityListItemBuilder.kt
- app/src/main/java/org/simple/clinic/location/Coordinates.kt
- app/src/main/java/org/simple/clinic/location/DistanceCalculator.kt
- app/src/main/java/org/simple/clinic/registration/facility/FacilitiesAdapter.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenController.kt
- app/src/main/res/values/colors_v2.xml
- app/src/test/java/org/simple/clinic/facility/change/FacilityChangeScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/facility/change/FacilityListItemBuilderTest.kt
- app/src/test/java/org/simple/clinic/location/DistanceCalculatorTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/util/CoordinatesTest.kt
This should be my 2nd last PR for finishing this feature:
https://www.pivotaltracker.com/story/show/164135362
Major changes:
- Highlight facility search query with a background color
- Calculation of distance between two `Coordinate`s is moved to `DistanceCalculator`
>  Highlight facility search query with a background color

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatient.kt
https://www.pivotaltracker.com/story/show/163976144
Database fetching is completely working!
> Fetch recent patients Part 1

- app/src/main/java/org/simple/clinic/sync/DataSync.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewController.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewEvents.kt
- app/src/main/res/layout/sync_indicator.xml
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorViewControllerTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/164243208
Part 1 of the story above.
This PR adds manual sync to sync indicator.
> Add manual sync to Sync Indicator

- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewController.kt
- app/src/main/java/org/simple/clinic/sync/indicator/dialog/SyncIndicatorFailureDialog.kt
- app/src/main/res/layout/sync_indicator.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorViewControllerTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/164243208
> Sync failed dialog

- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_v2.xml
Pivotal Story Link: https://www.pivotaltracker.com/story/show/161577651
This needs to be done for showing the new Simple ID  once its associated to the patient.
> Update patient summary header UI

- app/build.gradle
- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/patient/PatientModule.kt
- app/src/main/java/org/simple/clinic/phone/MaskedPhoneCaller.kt
- app/src/main/java/org/simple/clinic/phone/OfflineMaskedPhoneCaller.kt
- app/src/main/java/org/simple/clinic/phone/PhoneModule.kt
- app/src/main/java/org/simple/clinic/phone/PhoneNumberMaskerConfig.kt
- app/src/test/java/org/simple/clinic/phone/OfflineMaskedPhoneCallerTest.kt
- gradle.properties
https://www.pivotaltracker.com/story/show/164462722
> Phone number masking

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/facility/Facility.kt
- app/src/main/java/org/simple/clinic/facility/FacilityRepository.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/overdue/communication/Communication.kt
- app/src/main/java/org/simple/clinic/overdue/communication/CommunicationRepository.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/protocol/Protocol.kt
- app/src/main/java/org/simple/clinic/protocol/ProtocolRepository.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
- app/src/main/java/org/simple/clinic/sync/SynceableRepository.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewController.kt
- app/src/main/res/layout/sync_indicator.xml
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorViewControllerTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/164393783
> Show sync as pending when a record is updated

- app/src/main/java/org/simple/clinic/patient/shortcode/UuidShortCode.kt
- app/src/main/java/org/simple/clinic/patient/shortcode/UuidShortCodeCreator.kt
- app/src/test/java/org/simple/clinic/patient/shortcode/UuidShortCodeCreatorTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/164563506
> Add "UuidShortCodeCreator" to generate short codes from UUIDs

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/164200231
> Mark appointment as visited

- app/src/main/res/values/strings.xml
Pivotol story -> https://www.pivotaltracker.com/story/show/164627422
> Update display message when manual sync fails

- app/src/main/java/org/simple/clinic/patient/recent/RecentPatientEvents.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatientItem.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatientsView.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatientsViewController.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/res/layout/recent_patient_item_view.xml
- app/src/main/res/layout/recent_patients.xml
- app/src/test/java/org/simple/clinic/patient/recent/RecentPatientsViewControllerTest.kt
Pivotol story -> 
https://www.pivotaltracker.com/story/show/164533339
https://www.pivotaltracker.com/story/show/164564290
> Add clicks to Recent patients

- app/schemas/org.simple.clinic.AppDatabase/31.json
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/summary/addphone/MissingPhoneReminderRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheet.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/main/java/org/simple/clinic/storage/Migration_30_31.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryConfig.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModule.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenEvents.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialog.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialogController.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialogEvents.kt
- app/src/main/java/org/simple/clinic/summary/addphone/MissingPhoneReminder.kt
- app/src/main/java/org/simple/clinic/summary/addphone/MissingPhoneReminderRepository.kt
- app/src/main/res/layout/dialog_patientsummary_addphone.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialogControllerTest.kt
https://www.pivotaltracker.com/story/show/163448748
Large PR because it includes a database migration and `UpdatePhoneDialog` was duplicated to `AddPhoneDialog`.
> Remind user to add missing phone number

- app/src/main/java/org/simple/clinic/home/HomePagerAdapter.kt
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-pa/strings.xml
- app/src/main/res/values/strings.xml
Pivotal Story Link: https://www.pivotaltracker.com/story/show/164656161
> Rename home screen tab "Reports" -> "Progress"

- app/src/main/java/org/simple/clinic/home/patients/PatientsScreen.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenEvents.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreenController.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreenEvents.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreenResult.kt
- app/src/main/java/org/simple/clinic/widgets/qrcodescanner/QrCodeScannerView.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdScreenControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/164493040
> Send scanned BP passport codes via the screen router

- app/src/main/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentEvents.kt
- app/src/main/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentSheet.kt
- app/src/main/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentSheetController.kt
- app/src/main/res/layout/sheet_remove_appointment.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentSheetControllerTest.kt
https://www.pivotaltracker.com/story/show/164068865
> "Patient has already visited" feature

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/businessid/BusinessIdMetaAdapterAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/NetworkModule.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientModule.kt
- app/src/main/java/org/simple/clinic/patient/PatientProfile.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessIdMeta.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessIdMetaAdapter.kt
- app/src/main/java/org/simple/clinic/patient/businessid/MoshiBusinessIdMetaAdapter.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/164629790
> Add support for Meta models in BusinessId

- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/164692590
> Rename 'cancel' button of update/add phone dialog to 'skip'

- app/src/main/java/org/simple/clinic/home/patients/PatientsScreen.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/res/layout/recent_patients.xml
- app/src/main/res/layout/screen_patients.xml
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/164630895
> Hide sync indicator when the user is waiting for approval

- app/src/main/java/org/simple/clinic/drugs/selection/dosage/DosagePickerSheet.kt
- app/src/main/java/org/simple/clinic/home/report/ReportsScreen.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatientsView.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/java/org/simple/clinic/sync/indicator/dialog/SyncIndicatorFailureDialog.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/164721840
> Forward screen destroys to the controller from screens

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/164687599
> Add BusinessId related methods to PatientRepository

- app/src/main/java/org/simple/clinic/patient/recent/RecentPatientsView.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatientsViewController.kt
- app/src/main/res/drawable/patients_recentpatients_header_container_background.xml
- app/src/main/res/drawable/recentpatients_empty_state_background.xml
- app/src/main/res/layout/recent_patients.xml
- app/src/main/res/layout/screen_patients.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/patient/recent/RecentPatientsViewControllerTest.kt
I was trying to fix a bug in recent patients, but I'll need admin access to sandbox before I can continue my investigation. This PR contains changes I made in the meanwhile to clean up some code.
https://www.pivotaltracker.com/n/projects/2184102/stories/164720063
> Clean up recent patients

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatient.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatientsViewController.kt
- app/src/test/java/org/simple/clinic/patient/recent/RecentPatientsViewControllerTest.kt
https://www.pivotaltracker.com/story/show/164824779
> Fix recent patient SQL query to pick up BP from all facilities

- app/src/main/java/org/simple/clinic/addidtopatient/AddIdToPatient.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatientsView.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/summary/OpenIntention.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryCaller.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenEvents.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenKey.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/164752710
Once this is merged in, we can work on the different screens in BP Passport v1 independently.
> Finish up plumbing work for BP Passport

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientConfig.kt
- app/src/main/java/org/simple/clinic/patient/PatientModule.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- app/src/test/java/org/simple/clinic/patient/recent/RecentPatientsViewControllerTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/164655585
Part 1:
This PR just adds a query to check if a patient is defaulter.
> Add query to check if a patient is defaulter

- app/build.gradle
> Neat logs for test(s) execution

- app/build.gradle
- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/di/NetworkModule.kt
- app/src/main/java/org/simple/clinic/patient/PatientModule.kt
- app/src/main/java/org/simple/clinic/phone/PhoneNumberMaskerConfig.kt
- app/src/main/java/org/simple/clinic/remoteconfig/ConfigReader.kt
- app/src/main/java/org/simple/clinic/remoteconfig/FirebaseConfigReader.kt
- build.gradle
Small improvement to https://www.pivotaltracker.com/story/show/164954589
@vinaysshenoy please feel free to make changes yourself instead of leaving review comments. I won't be able to make any more changes :)
> Introduce an abstraction over FirebaseRemoteConfig

- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/help/HelpSyncAndroidTest.kt
- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/help/HelpApi.kt
- app/src/main/java/org/simple/clinic/help/HelpModule.kt
- app/src/main/java/org/simple/clinic/help/HelpRepository.kt
- app/src/main/java/org/simple/clinic/help/HelpSync.kt
- app/src/main/java/org/simple/clinic/home/HomeModule.kt
- app/src/main/java/org/simple/clinic/home/HomeScreen.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenConfig.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenController.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreen.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreenController.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreenKey.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
- app/src/main/java/org/simple/clinic/widgets/Views.kt
- app/src/main/res/drawable/ic_help_outline_24dp.xml
- app/src/main/res/layout/screen_help.xml
- app/src/main/res/menu/home.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/colors_v2.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/help/HelpRepositoryTest.kt
- app/src/test/java/org/simple/clinic/home/HomeScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/home/help/HelpScreenControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/164758290
> Add help screen

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatient.kt
https://www.pivotaltracker.com/story/show/164687980
> Exclude deleted entries while fetching recent patients

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentSyncAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentConfig.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentModule.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentSync.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientConfig.kt
- app/src/main/java/org/simple/clinic/patient/PatientModule.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetController.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- app/src/test/java/org/simple/clinic/patient/recent/RecentPatientsViewControllerTest.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetControllerTest.kt
- app/src/test/java/org/simple/clinic/sync/ModelSyncTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/164655585
> Use AppointmentSyncApiV3

- app/schemas/org.simple.clinic.AppDatabase/33.json
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/NetworkModule.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentPayload.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentSync.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetController.kt
- app/src/main/java/org/simple/clinic/storage/Migration_32_33.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetControllerTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/165143985
This story is in continuation to the story for adding defaulters to Overdue:
https://www.pivotaltracker.com/story/show/164655585
> Add `appointment_type` to  Appointment

- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/util/identifierdisplay/IdentifierDisplayAdapterAndroidTest.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/patient/businessid/Identifier.kt
- app/src/main/java/org/simple/clinic/patient/shortcode/DigitFilter.kt
- app/src/main/java/org/simple/clinic/patient/shortcode/UuidShortCodeCreatorModule.kt
- app/src/main/java/org/simple/clinic/util/identifierdisplay/BpPassportTextConverter.kt
- app/src/main/java/org/simple/clinic/util/identifierdisplay/IdentifierDisplayAdapter.kt
- app/src/main/java/org/simple/clinic/util/identifierdisplay/IdentifierDisplayAdapterModule.kt
- app/src/test/java/org/simple/clinic/patient/shortcode/DigitFilterTest.kt
- app/src/test/java/org/simple/clinic/util/identifierdisplay/IdentifierDisplayAdapterTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165080249
> Add a mechanism to format an Identifier for display

- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreen.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreenController.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreenEvents.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreenKey.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchValidationError.kt
- app/src/main/java/org/simple/clinic/newentry/clearbutton/ClearFieldImageButton.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchScreenController.kt
- app/src/test/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/search/PatientSearchScreenControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/164980438
> Add screen to search for a patient after scanning a BP passport

- app/src/androidTest/java/org/simple/clinic/util/identifierdisplay/IdentifierDisplayAdapterAndroidTest.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/util/Unicode.kt
- app/src/main/java/org/simple/clinic/util/identifierdisplay/BpPassportDisplayFormatter.kt
- app/src/main/java/org/simple/clinic/util/identifierdisplay/BpPassportTextConverter.kt
- app/src/main/java/org/simple/clinic/util/identifierdisplay/IdentifierDisplayAdapter.kt
- app/src/main/java/org/simple/clinic/util/identifierdisplay/IdentifierDisplayAdapterModule.kt
- app/src/main/java/org/simple/clinic/util/identifierdisplay/UnknownDisplayFormatter.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/util/identifierdisplay/IdentifierDisplayAdapterTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165271096
> Add capability to render Identifier types to the IdentifierDisplayAdapter

- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientEvents.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientSheet.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientSheetController.kt
- app/src/main/res/layout/sheet_link_id_with_patient.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_v2.xml
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/summary/linkId/LinkIdWithPatientSheetControllerTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/165211601
Part 1 of the story above. This PR creates a new bottom sheet `LinkIdWithPatient`
> Add link id with patient screen

- README.md
Required by their TOS: https://pullreminders.com/badge
> Add a pullreminders.com badge to README

- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreen.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreenKey.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreen.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/res/layout/screen_addidtopatientsearch.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_v2.xml
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/164980438
> Complete Add ID to Patient search screen

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientSheet.kt
- app/src/main/res/layout/sheet_link_id_with_patient.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_v2.xml
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/165211601
> Open LinkIdWithPatientSheet from PatientSummaryScreen

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/OngoingNewPatientEntry.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165344520
This is part 1 of the story which adds the necessary changes in the repository to create a new patient with a `BusinessId`. This feature will be completed in the next PR which makes the changes to the `PatientEntryScreen`.
> Add support for registering a new patient with an Identifier

- app/src/androidTest/java/org/simple/clinic/TestClinicApp.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/patient/PatientConfig.kt
- app/src/main/java/org/simple/clinic/patient/PatientModule.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165406792
> Make patient config remotely configurable

- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreenController.kt
- app/src/main/java/org/simple/clinic/widgets/Views.kt
- app/src/main/res/drawable/background_patiententry_identifier.xml
- app/src/main/res/layout/screen_manual_patient_entry.xml
- app/src/main/res/layout/screen_patient_edit.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_v2.xml
- app/src/test/java/org/simple/clinic/newentry/PatientEntryScreenControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165344520
> Display Identifier in PatientEntryScreen

- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreen.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchresults/AddIdToPatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientSheet.kt
- app/src/main/java/org/simple/clinic/text/style/TextAppearanceWithLetterSpacingSpan.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165437478
> Add support for letter spacing in text appearance spans

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165378803
> Bp passport app bar display

- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatient.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatientItem.kt
- app/src/main/res/layout/see_all_item_view.xml
- app/src/main/res/values/strings.xml
Added UI to be able to show "See All" button but I'm not showing it right away. Will include the button once the entire flow works.
https://www.pivotaltracker.com/story/show/164762062
> Recent patient complete log

- app/src/main/res/values/strings.xml
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165556379
> Change label of Scan Card button on Patients Screen to match design

- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientView.kt
- app/src/main/java/org/simple/clinic/widgets/BottomSheetActivity.kt
- app/src/main/java/org/simple/clinic/widgets/BottomSheetAnimations.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165489494
> Animate Link ID with patient sheet

- app/src/main/java/org/simple/clinic/activity/TheActivity.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreen.kt
- app/src/main/java/org/simple/clinic/screen/FullScreenKeyChangeAnimator.kt
- app/src/main/java/org/simple/clinic/screen/FullScreenKeyChangeNoOpAnimator.kt
- app/src/main/java/org/simple/clinic/screen/KeyChangeAnimatorModule.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- router/src/main/java/org/simple/clinic/router/screen/BaseViewGroupKeyChanger.kt
- router/src/main/java/org/simple/clinic/router/screen/FullScreenKeyChanger.kt
- router/src/main/java/org/simple/clinic/router/screen/KeyChangeAnimator.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165555614
> Disable Screen Change Animations

- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165489588
> Stop app initialization for LeakCanary before ClinicApp is initialized

- app/src/androidTest/java/org/simple/clinic/editpatient/PatientEditScreenUiTest.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165558745
> Handle back clicks after linking ID with patient

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/RecentPatient.kt
- app/src/main/java/org/simple/clinic/patient/recent/RecentPatientItem.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientScreenItemTypes.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreen.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreenController.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreenEvents.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreenKey.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientEvents.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientItem.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsView.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsViewController.kt
- app/src/main/res/layout/recent_patients_screen.xml
- app/src/main/res/layout/screen_patients.xml
- app/src/main/res/layout/see_all_item_view.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/recentpatient/RecentPatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/recentpatientsview/RecentPatientsViewControllerTest.kt
Pending tasks:
- ~Add tests for `RecentPatientsScreenController`~
- Segregate patients by day
https://www.pivotaltracker.com/story/show/164762062
> Recent patients screen

- app/build.gradle
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientItem.kt
- app/src/main/res/values/strings.xml
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165490945
> Disable Kotlin view extensions

- app/src/main/java/org/simple/clinic/addidtopatient/searchresults/AddIdToPatientSearchResultsScreen.kt
- app/src/main/res/layout/screen_addidtopatientsearch.xml
- app/src/main/res/layout/screen_addidtopatientsearchresults.xml
- app/src/main/res/values/strings.xml
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165593907
> Clean up UI in add ID to patient screens

- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/165634751
> Show LinkIdWithPatientView in PatientSummaryScreen if not shown already

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/patient/PatientConfig.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165671916
> Enable BP Passport scanning feature

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165669043
> Fix: BP Passports do not sync when added to an existing patient

- app/schemas/org.simple.clinic.AppDatabase/34.json
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/help/HelpSyncAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentPayload.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentSync.kt
- app/src/main/java/org/simple/clinic/storage/Migration_33_34.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165758893
> Support appointment sync api v3

- app/src/main/java/org/simple/clinic/patient/filter/WeightedLevenshteinSearch.kt
- app/src/test/java/org/simple/clinic/patient/filter/WeightedLevenshteinSearchTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165784640
> Ignore all non-letter characters when searching for patients

- app/src/main/java/org/simple/clinic/overdue/AppointmentModule.kt
This PR flips the flag to enable the appointment sync API.
> Enable AppointmentSync v3

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/patient/RecentPatient.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientScreenItemTypes.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreen.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreenController.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsItemType.kt
- app/src/main/java/org/simple/clinic/util/TimeFunctions.kt
- app/src/main/res/layout/recentpatient_date_header_item_view.xml
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/recentpatient/RecentPatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/util/TimeFunctionsTest.kt
Pending task:
- Format date
https://www.pivotaltracker.com/story/show/164762062
> Recent patients segregate by day

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/di/DateFormatterModule.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientRelativeTimeStampGenerator.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientScreenItemTypes.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreenController.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsView.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsViewController.kt
- app/src/test/java/org/simple/clinic/recentpatient/RecentPatientRelativeTimeStampGeneratorTest.kt
- app/src/test/java/org/simple/clinic/recentpatient/RecentPatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/recentpatientsview/RecentPatientsViewControllerTest.kt
- Date formatting is done
- "See All" button is shown
https://www.pivotaltracker.com/story/show/164762062
> Recent patient segregate by day

- app/src/main/java/org/simple/clinic/remoteconfig/RemoteConfigSync.kt
- app/src/main/java/org/simple/clinic/sync/DataSync.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/java/org/simple/clinic/util/ErrorResolver.kt
- app/src/test/java/org/simple/clinic/util/ErrorResolverTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165876930
> Add Unauthorized sync error type

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/sync/BloodPressureMeasurementPayload.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/drugs/sync/PrescribedDrugPayload.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt
- app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistoryPayload.kt
- app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistorySync.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentPayload.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentSync.kt
- app/src/main/java/org/simple/clinic/patient/PatientAddress.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientSync.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
Pivotol story-> https://www.pivotaltracker.com/story/show/165883804
> Add recorded_at to payloads

- app/src/main/java/org/simple/clinic/ClinicApp.kt
- app/src/main/java/org/simple/clinic/user/UnauthorizeUser.kt
- app/src/test/java/org/simple/clinic/user/UnauthorizeUserTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165876930
> Set user logged in status to unauthorised on 401 http error

- build.gradle
- gradle.properties
See commit message for more information.
> Fix problems with code minification

- app/schemas/org.simple.clinic.AppDatabase/36.json
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/drugs/sync/PrescribedDrugPayload.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt
- app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistorySync.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentSync.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientAddress.kt
- app/src/main/java/org/simple/clinic/patient/PatientPhoneNumber.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientSync.kt
- app/src/main/java/org/simple/clinic/storage/Migration_35_36.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/165968346
This is a large-ish PR because we had to remove column from all tables in one commit so that we can write a single migration.
This story is not complete as you can see when you open the story in Pivotol.
One of the tasks remaining is "Removing recorded_at from all payloads".
This will be done in another PR, since this is already a huge PR.
> Remove recorded-at from all tables except Patient and BP

- app/src/androidTest/java/org/simple/clinic/AuthenticationRule.kt
- app/src/androidTest/java/org/simple/clinic/storage/files/AndroidFileStorageAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/user/UserSessionAndroidTest.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/main/java/org/simple/clinic/storage/files/AndroidFileStorage.kt
- app/src/main/java/org/simple/clinic/storage/files/FileOperations.kt
- app/src/main/java/org/simple/clinic/storage/files/FileStorage.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/test/java/org/simple/clinic/storage/files/AndroidFileStorageTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165961128
> Clear patient data when logging out

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/drugs/sync/PrescribedDrugPayload.kt
- app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistoryPayload.kt
- app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistorySync.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentPayload.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentSync.kt
- app/src/main/java/org/simple/clinic/patient/PatientAddress.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientSync.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/165968346
> Remove recordedAt from payloads

- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/main/java/org/simple/clinic/di/AppComponent.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/main/java/org/simple/clinic/patient/RecentPatient.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreenController.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsViewController.kt
- app/src/main/java/org/simple/clinic/storage/Migration_34_35.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/test/java/org/simple/clinic/bp/BloodPressureRepositoryTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
- app/src/test/java/org/simple/clinic/recentpatient/RecentPatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/recentpatientsview/RecentPatientsViewControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/165054655
> Update queries to use BP recordedAt

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenController.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchViewController.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewController.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- app/src/test/java/org/simple/clinic/searchresultsview/PatientSearchViewControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166083420
> Provide logged in user to PatientRepository methods

- app/src/main/res/layout/see_all_item_view.xml
https://www.pivotaltracker.com/story/show/165962172
> SEE ALL button should take up full width in recent patients list

- app/src/main/java/org/simple/clinic/analytics/Analytics.kt
- app/src/main/java/org/simple/clinic/user/ReportPendingRecordsToAnalytics.kt
- app/src/test/java/org/simple/clinic/analytics/AnalyticsTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/user/ReportPendingRecordsToAnalyticsTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165961128
> Add class to report pending records to Analytics

- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsViewController.kt
- app/src/test/java/org/simple/clinic/recentpatientsview/RecentPatientsViewControllerTest.kt
Show it only when longer than recent patient limit.
https://www.pivotaltracker.com/story/show/165962163
> Show see all in recent patients only when the list is too long

- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsViewController.kt
- app/src/test/java/org/simple/clinic/recentpatientsview/RecentPatientsViewControllerTest.kt
Reverts simpledotorg/simple-android#661
> Revert "Show see all in recent patients only when the list is too long"

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/ClinicApp.kt
- app/src/main/java/org/simple/clinic/ReleaseClinicApp.kt
- app/src/main/java/org/simple/clinic/analytics/Analytics.kt
- app/src/main/java/org/simple/clinic/analytics/AnalyticsReporter.kt
- app/src/main/java/org/simple/clinic/analytics/DebugAnalyticsReporter.kt
- app/src/main/java/org/simple/clinic/analytics/HeapAnalyticsReporter.kt
- app/src/main/java/org/simple/clinic/analytics/UpdateAnalyticsUserId.kt
- app/src/test/java/org/simple/clinic/ReportAnalyticsEventsTest.kt
- app/src/test/java/org/simple/clinic/analytics/AnalyticsTest.kt
- app/src/test/java/org/simple/clinic/analytics/MockAnalyticsReporter.kt
- app/src/test/java/org/simple/clinic/analytics/UpdateAnalyticsUserIdTest.kt
- app/src/test/java/org/simple/clinic/newentry/PatientEntryScreenControllerTest.kt
- build.gradle
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166151512
> Reset analytics user identity when user gets logged out

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/test/java/org/simple/clinic/bp/BloodPressureRepositoryTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166263263
> Reduce coupling between BloodPressureRepository and UserSession

- app/src/main/res/layout/recent_patients_screen.xml
https://www.pivotaltracker.com/story/show/166231990
> Grey bar is cut off at the top in recent patients list

- app/src/main/res/layout/recent_patients_screen.xml
https://www.pivotaltracker.com/story/show/166231990
> Fix: Remove top padding in recent patients list

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialogController.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/test/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialogControllerTest.kt
Pivotol story-> https://www.pivotaltracker.com/story/show/166119194
> Update patient recorded-at when bp is deleted

- app/src/main/java/org/simple/clinic/bp/sync/BloodPressureSyncApi.kt
- app/src/main/java/org/simple/clinic/drugs/sync/PrescriptionSyncApi.kt
- app/src/main/java/org/simple/clinic/facility/FacilitySyncApi.kt
- app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistorySyncApi.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentSyncApi.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientSyncApi.kt
- app/src/main/java/org/simple/clinic/protocol/ProtocolSyncApi.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166278675
> Add static X-RESYNC-TOKEN headers to sync apis

- app/src/main/java/org/simple/clinic/summary/RelativeTimestampGenerator.kt
- app/src/test/java/org/simple/clinic/summary/RelativeTimestampGeneratorTest.kt
https://www.pivotaltracker.com/story/show/165962179
> Handle dates in recent patients correctly

- app/src/main/res/layout/sheet_phone_mask.xml
https://www.pivotaltracker.com/story/show/166267416
> Text getting chopped off in phone masking bottom sheet

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreenController.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetController.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166266668
> Reduce coupling between AppointmentRepository and UserSession

- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/medicalhistory/MedicalHistoryRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166347559
> Add database methods to figure out if patient data has changed since a given time

- app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/drugs/selection/dosage/DosagePickerSheetController.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryController.kt
- app/src/test/java/org/simple/clinic/drugs/PrescriptionRepositoryTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/DosagePickerSheetControllerTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/PrescribedDrugsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166433244
> Reduce coupling between UserSession and Prescription Repository

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/RecentPatient.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsViewController.kt
- app/src/test/java/org/simple/clinic/recentpatientsview/RecentPatientsViewControllerTest.kt
https://www.pivotaltracker.com/story/show/165000437
> When appointment is updated in overdue, patient should not show up in recent patients

- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165961128
> Report pending records to analytics when logout happens

- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/main/java/org/simple/clinic/drugs/selection/dosage/DosagePickerSheetController.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryController.kt
- app/src/main/java/org/simple/clinic/home/overdue/appointmentreminder/AppointmentReminderSheetController.kt
- app/src/main/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentScreenController.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetController.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/DosagePickerSheetControllerTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryControllerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/appointmentreminder/AppointmentReminderSheetControllerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166491353
> Finish bottom sheets when user becomes unauthorized

- app/src/main/res/layout/sheet_phone_mask.xml
https://www.pivotaltracker.com/story/show/166492020
> Fix phone mask sheet button shadow cutoff

- app/build.gradle
- app/src/main/java/org/simple/clinic/appupdate/AppUpdateConfig.kt
- app/src/main/java/org/simple/clinic/appupdate/AppUpdateData.kt
- app/src/main/java/org/simple/clinic/appupdate/AppUpdateModule.kt
- app/src/main/java/org/simple/clinic/appupdate/CheckAppUpdateAvailability.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/test/java/org/simple/clinic/appupdate/CheckAppUpdateAvailabilityTest.kt
- build.gradle
Pivotol story -> https://www.pivotaltracker.com/story/show/163619300
> Check app updates available

- app/src/main/java/org/simple/clinic/home/overdue/OverdueListAdapter.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/res/layout/item_overdue_list_patient.xml
https://www.pivotaltracker.com/story/show/166178394
> Fix scrolling issues with overdue screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/login/applock/AppLockScreen.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockScreenController.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreen.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreenController.kt
- app/src/main/java/org/simple/clinic/security/pin/PinEntryCardController.kt
- app/src/main/java/org/simple/clinic/security/pin/PinEntryCardView.kt
- app/src/main/java/org/simple/clinic/security/pin/PinEntryCardViewEvents.kt
- app/src/test/java/org/simple/clinic/login/applock/AppLockScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/login/pin/LoginPinScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/security/pin/PinEntryCardControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166693699
> Change PinEntryCardView to accept the PIN to be verified externally

- app/src/main/java/org/simple/clinic/appupdate/dialog/AppUpdateDialog.kt
- app/src/main/res/values/strings.xml
Pivotol story -> https://www.pivotaltracker.com/story/show/163619300
> Add App update dialog

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/37.json
- app/src/androidTest/java/org/simple/clinic/AuthenticationRule.kt
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/user/UserDaoAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/user/UserSessionAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/NetworkModule.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/storage/Migration_36_37.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/main/java/org/simple/clinic/user/UserStatus.kt
- app/src/test/java/org/simple/clinic/activity/TheActivityControllerTest.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
https://www.pivotaltracker.com/story/show/165815995
> Convert UserStatus to sealed class for forward compatibility

- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityUiChangeProducer.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityView.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityViewController.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityViewState.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityViewStateProducer.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/SchedulersProvider.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/widgets/ScreenCreated.kt
- app/src/test/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityUiChangeProducerTest.kt
- app/src/test/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityViewControllerTest.kt
- app/src/test/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityViewStateProducerTest.kt
- app/src/test/java/org/simple/clinic/allpatientsinfacility/TrampolineSchedulersProvider.kt
- doc/arch/new-arch-wip.md
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166784275
> Add business logic for all patients in facility view

- app/build.gradle
- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchViewController.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsItemType.kt
- app/src/main/java/org/simple/clinic/widgets/PatientSearchResultView.kt
- app/src/main/res/layout/list_patient_search.xml
- app/src/main/res/layout/view_patient_search_result.xml
- app/src/test/java/org/simple/clinic/searchresultsview/PatientSearchViewControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166811630
This was actually done as a part of #702, but was broken out for easier review.
> Extract PatientSearchResultViewHolder to different file

- app/src/main/java/org/simple/clinic/appupdate/AppUpdateData.kt
- app/src/main/java/org/simple/clinic/appupdate/AppUpdateModule.kt
- app/src/main/java/org/simple/clinic/appupdate/AppUpdateState.kt
- app/src/main/java/org/simple/clinic/appupdate/CheckAppUpdateAvailability.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsModule.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreen.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
Pivotol story -> https://www.pivotaltracker.com/n/projects/2184102/stories/163619300
There is one part of this story left. Creating Remote config for this feature.
> Show App update dialog

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/appupdate/AppUpdateConfig.kt
- app/src/main/java/org/simple/clinic/appupdate/AppUpdateModule.kt
- app/src/main/java/org/simple/clinic/appupdate/CheckAppUpdateAvailability.kt
- app/src/test/java/org/simple/clinic/appupdate/CheckAppUpdateAvailabilityTest.kt
https://www.pivotaltracker.com/story/show/163619300
> Add remote config for showing app update

- app/src/main/java/org/simple/clinic/ViewControllerBinding.kt
- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityListAdapter.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityListItem.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityResultsAdapter.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityUi.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityUiChangeProducer.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityUiController.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityUiState.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityUiStateProducer.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityView.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/di/AllPatientsInFacilityModule.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/util/DefaultSchedulersProvider.kt
- app/src/main/java/org/simple/clinic/widgets/recyclerview/ViewHolderX.kt
- app/src/main/res/layout/list_allpatientsinfacility_facility_header.xml
- app/src/main/res/layout/view_allpatientsinfacility.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_v2.xml
- app/src/test/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityListItemTest.kt
- app/src/test/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityUiChangeProducerTest.kt
- app/src/test/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityUiControllerTest.kt
- app/src/test/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityUiStateProducerTest.kt
- quality/lint.xml
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166811630
> Add All Patients In Facility View

- app/src/main/java/org/simple/clinic/appupdate/CheckAppUpdateAvailability.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/167088502
> Fix possible crash while checking app update availability

- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/ClinicApp.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/167100496
> Enable Traceur only in the Debug build type

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreenController.kt
https://www.pivotaltracker.com/story/show/165275614
> Overdue bug fix

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/RecentPatient.kt
Sidenote: It's ironic how dead patients are _last seen recent patients_! 🙃 
https://www.pivotaltracker.com/story/show/167010237
> Exclude dead patients from recent patients list

- app/build.gradle
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityListAdapter.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityListItem.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityUiEvents.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityView.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchScreen.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchScreenController.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchScreenEvents.kt
- app/src/main/res/layout/screen_patient_search.xml
- app/src/main/res/layout/view_allpatientsinfacility.xml
- app/src/main/res/values/dimens.xml
- app/src/test/java/org/simple/clinic/search/PatientSearchScreenControllerTest.kt
- build.gradle
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166754208
> Hook up all patients in facility view to UI

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/RecentPatient.kt
https://www.pivotaltracker.com/story/show/166924338
> Patient edits should not affect recent patients

- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreen.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreenController.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreenEvents.kt
- app/src/main/java/org/simple/clinic/newentry/clearbutton/ClearFieldImageButton.kt
- app/src/main/res/layout/screen_addidtopatientsearch.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreenControllerTest.kt
- quality/lint.xml
Pivotal Story Link: https://www.pivotaltracker.com/story/show/167085326
> Show alphabetical patient log in add ID to patient search screen

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreen.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityUiEvents.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityView.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchScreen.kt
- app/src/main/java/org/simple/clinic/widgets/FindOrRegisterPatientToolbar.kt
- app/src/main/res/drawable/background_findorregister_toolbar.xml
- app/src/main/res/layout/screen_patient_search.xml
- app/src/main/res/layout/view_findorregisterpatient_toolbar.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_v2.xml
Pivotal Story Link: https://www.pivotaltracker.com/story/show/167283610
> Add new toolbar design to patient search screen

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/40.json
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/medicalhistory/MedicalHistoryRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/NetworkModule.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/medicalhistory/Answer.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryQuestionView.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt
- app/src/main/java/org/simple/clinic/medicalhistory/OngoingMedicalHistoryEntry.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenEvents.kt
- app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistoryPayload.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/storage/Migration_39_40.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenEvents.kt
- app/src/main/java/org/simple/clinic/summary/SummaryMedicalHistoryItem.kt
- app/src/sharedTest/java/org/simple/clinic/util/RxTestUtils.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/167163238
> Change Medical History Answer enum to be forward compatible

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/phonemask/PatientDetails.kt
- app/src/main/java/org/simple/clinic/home/overdue/phonemask/PhoneMaskBottomSheet.kt
- app/src/main/java/org/simple/clinic/home/overdue/phonemask/PhoneMaskBottomSheetController.kt
- app/src/test/java/org/simple/clinic/home/overdue/phonemask/PhoneMaskBottomSheetControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/167284393
> Fix: Patient details sometimes does not get filled in phone mask sheet

- app/src/main/java/org/simple/clinic/addidtopatient/searchresults/AddIdToPatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchViewController.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchPatientBy.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsViewEvents.kt
- app/src/test/java/org/simple/clinic/searchresultsview/PatientSearchViewControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/167343626
> Add support for different search inputs when searching for patient

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/PartitionSearchResultsByVisitedFacility.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PartitionSearchResultsByVisitedFacility.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchResults.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchViewController.kt
- app/src/test/java/org/simple/clinic/patient/PartitionSearchResultsByVisitedFacilityTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- app/src/test/java/org/simple/clinic/searchresultsview/PatientSearchViewControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165212154
> Move partitioning of search results to the patient results controller

- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PartitionSearchResultsByVisitedFacility.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchViewController.kt
- app/src/test/java/org/simple/clinic/patient/PartitionSearchResultsByVisitedFacilityTest.kt
- app/src/test/java/org/simple/clinic/searchresultsview/PatientSearchViewControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/167343626
> Search by phone number in patient search view

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchresults/AddIdToPatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchCriteria.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchViewController.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchPatientBy.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchPatientInput.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsViewEvents.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- app/src/test/java/org/simple/clinic/searchresultsview/PatientSearchViewControllerTest.kt
Pivotal story link: https://www.pivotaltracker.com/story/show/167343626
> Add phone number search support to patient repository

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetEvents.kt
- app/src/main/java/org/simple/clinic/patient/OngoingEditPatientEntry.kt
- app/src/main/java/org/simple/clinic/patient/OngoingNewPatientEntry.kt
- app/src/main/java/org/simple/clinic/widgets/ageanddateofbirth/UserInputDateValidator.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
- app/src/test/java/org/simple/clinic/editpatient/PatientEditScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/newentry/PatientEntryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/newentry/UserInputDateValidatorTest.kt
- app/src/test/java/org/simple/clinic/patient/OngoingNewPatientEntryTest.kt
https://www.pivotaltracker.com/story/show/167453590
> Remove deprecated validate function from UserInputDateValidator

- app/src/androidTest/java/org/simple/clinic/AuthenticationRule.kt
- app/src/androidTest/java/org/simple/clinic/user/UserSessionAndroidTest.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenController.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingScreenController.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/registration/register/RegistrationLoadingScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/167487181
> Fix: Clear OngoingRegistrationEntry after registration

- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
https://www.pivotaltracker.com/story/show/167533992
> Fix: Refresh user status  on Patient Screen

- app/schemas/org.simple.clinic.AppDatabase/44.json
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/TestClinicApp.kt
- app/src/androidTest/java/org/simple/clinic/user/UserSessionAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreenController.kt
- app/src/main/java/org/simple/clinic/login/LoginModule.kt
- app/src/main/java/org/simple/clinic/login/LoginOtpSmsListenerImpl.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreenController.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreenEvents.kt
- app/src/main/java/org/simple/clinic/login/pin/UpdateLoginEntryWithEnteredPin.kt
- app/src/main/java/org/simple/clinic/registration/FindUserResult.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenController.kt
- app/src/main/java/org/simple/clinic/storage/Migration_43_44.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/main/java/org/simple/clinic/user/OngoingLoginEntry.kt
- app/src/main/java/org/simple/clinic/user/RequestLoginOtp.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/login/pin/LoginPinScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/user/RequestLoginOtpTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166632435
> Stop creating a local user during login

- doc/arch/006-forward-compatibility-for-enums.md
This PR is a draft, can you please provide feedback so that I can iterate on it before we merge this?
> Add ADR for enum forward compatibility.

- app/src/main/java/org/simple/clinic/addidtopatient/searchresults/AddIdToPatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchCriteria.kt
- app/src/main/java/org/simple/clinic/search/InputValidator.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchScreen.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchScreenController.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchScreenEvents.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchValidationError.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreenKey.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchViewController.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchPatientInput.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsViewEvents.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/search/PatientSearchScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/searchresultsview/PatientSearchViewControllerTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/167343636
> Add phone number input to PatientSearchScreen

- app/src/androidTest/java/org/simple/clinic/TestClinicApp.kt
- app/src/main/java/org/simple/clinic/ClinicApp.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/sync/DataSyncOnApprovalModule.kt
- app/src/main/java/org/simple/clinic/sync/IDataSyncOnApproval.kt
- app/src/main/java/org/simple/clinic/sync/SyncDataOnApproval.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/sync/SyncDataOnApprovalTest.kt
https://www.pivotaltracker.com/story/show/167533992
Refer the below conversation for details:
https://github.com/simpledotorg/simple-android/pull/742#discussion_r308116594
> Inititate data sync only when user logs in and gets approved

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
https://www.pivotaltracker.com/story/show/167454899
> Fix: crash when scrolling on overdue list

- app/src/androidTest/java/org/simple/clinic/user/UserSessionAndroidTest.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
https://www.pivotaltracker.com/story/show/167595572
> Fix: Facility selection is not working

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/java/org/simple/clinic/patient/OngoingNewPatientEntry.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsController.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreenEvents.kt
- app/src/main/res/layout/screen_manual_patient_entry.xml
- app/src/test/java/org/simple/clinic/search/results/PatientSearchResultsControllerTest.kt
https://www.pivotaltracker.com/story/show/167343744
https://www.pivotaltracker.com/story/show/165674789
> Prefill  phone number when registering patient from phone number search

- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenController.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenController.kt
- app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceDialog.kt
- app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceDialogController.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/main/res/layout/screen_registration_phone.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceDialogControllerTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
Pivotal Story Link: https://www.pivotaltracker.com/story/show/166571175
> Add "logged out on this device" dialog

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/PatientProfile.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
https://www.pivotaltracker.com/story/show/167702689
> Fix: Duplicate results when searching patients by phone number

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt
- app/src/main/java/org/simple/clinic/patient/shortcode/UuidShortCode.kt
- app/src/main/java/org/simple/clinic/patient/shortcode/UuidShortCodeCreator.kt
- app/src/main/java/org/simple/clinic/util/identifierdisplay/BpPassportDisplayFormatter.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- app/src/test/java/org/simple/clinic/patient/shortcode/UuidShortCodeCreatorTest.kt
https://www.pivotaltracker.com/story/show/167310717
> Add searchByShortCode in PatientRepository to search using short code

- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreen.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreenController.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreenEvents.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchValidationError.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/InputValidator.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchresults/AddIdPatientSearchResultsScreenEvents.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchresults/AddIdToPatientSearchResultsController.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchresults/AddIdToPatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/addidtopatient/searchresults/AddIdToPatientSearchResultsScreenKey.kt
- app/src/main/java/org/simple/clinic/patient/OngoingNewPatientEntry.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchScreen.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsController.kt
- app/src/main/res/layout/screen_addidtopatientsearch.xml
- app/src/main/res/layout/screen_patient_search.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/addidtopatient/searchresults/AddIdToPatientSearchResultsControllerTest.kt
- app/src/test/java/org/simple/clinic/search/results/PatientSearchResultsControllerTest.kt
https://www.pivotaltracker.com/story/show/167343644
> Add search by phone number support to add ID to patient search flow

- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreenController.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreenEvents.kt
- app/src/main/java/org/simple/clinic/scanid/ShortCodeInput.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsItemType.kt
- app/src/main/java/org/simple/clinic/widgets/PatientSearchResultItemView.kt
- app/src/main/java/org/simple/clinic/widgets/qrcodescanner/QrCodeScannerView.kt
- app/src/main/res/layout/list_patient_search.xml
- app/src/main/res/layout/screen_scan_simple.xml
- app/src/main/res/layout/view_patient_search_result.xml
- app/src/main/res/layout/view_qrcode_scanner.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/scanid/ShortCodeInputTest.kt
https://www.pivotaltracker.com/story/show/167310717
> Add short code search

- CHANGELOG.md
- app/build.gradle
- app/src/main/java/org/simple/clinic/summary/SummaryBloodPressureListItem.kt
- app/src/main/java/org/simple/clinic/summary/SummaryPrescribedDrugsItem.kt
- app/src/main/java/org/simple/clinic/widgets/PrimarySolidButtonWithFrame.kt
- app/src/main/res/layout/list_patientsummary_add_new_bp_measurement.xml
- app/src/main/res/layout/list_patientsummary_bp_measurement.xml
- app/src/main/res/layout/list_patientsummary_bp_placeholder.xml
- app/src/main/res/layout/list_patientsummary_medicalhistory.xml
- app/src/main/res/layout/list_patientsummary_prescription_drug.xml
- app/src/main/res/layout/list_patientsummary_prescriptions.xml
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-pa/strings.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_v2.xml
https://www.pivotaltracker.com/story/show/167669127
> Patient summary designs

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
https://www.pivotaltracker.com/story/show/167870079
> Exclude deleted patients from the app

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchView.kt
- app/src/main/res/layout/patient_search_view.xml
https://www.pivotaltracker.com/story/show/167997753
> Show search results loader

- app/src/main/java/org/simple/clinic/Globals.kt
- app/src/main/java/org/simple/clinic/patient/shortcode/UuidShortCodeCreatorModule.kt
- app/src/main/java/org/simple/clinic/plumbing/AsyncOp.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreenController.kt
- app/src/main/java/org/simple/clinic/scanid/ShortCodeInput.kt
- app/src/main/java/org/simple/clinic/scanid/ShortCodeValidationError.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultEvent.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultState.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultStateProducer.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultUi.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultUiChangeProducer.kt
- app/src/main/res/layout/screen_scan_simple.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/scanid/ShortCodeInputTest.kt
- app/src/test/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultStateProducerTest.kt
- app/src/test/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultUiChangeProducerTest.kt
**Pivotal Story:** https://www.pivotaltracker.com/story/show/167310717
Also includes,
* Distinguish between empty BP passport code and short BP passport code
* Tweak UI for Scan ID screen
> Add State/Ui Change Producer logic for Shortcode Search Screen

- CHANGELOG.md
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/ClinicApp.kt
- app/src/main/java/org/simple/clinic/ReleaseClinicApp.kt
- app/src/main/java/org/simple/clinic/analytics/Analytics.kt
- app/src/main/java/org/simple/clinic/analytics/AnalyticsReporter.kt
- app/src/main/java/org/simple/clinic/analytics/DebugAnalyticsReporter.kt
- app/src/main/java/org/simple/clinic/analytics/ErrorSwallowingReporter.kt
- app/src/main/java/org/simple/clinic/analytics/HeapAnalyticsReporter.kt
- app/src/main/java/org/simple/clinic/analytics/MixpanelAnalyticsReporter.kt
- app/src/main/java/org/simple/clinic/analytics/UpdateAnalyticsUserId.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/test/java/org/simple/clinic/analytics/AnalyticsTest.kt
- app/src/test/java/org/simple/clinic/analytics/ErrorSwallowingReporterTest.kt
- app/src/test/java/org/simple/clinic/analytics/MockAnalyticsReporter.kt
- app/src/test/java/org/simple/clinic/analytics/UpdateAnalyticsUserIdTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
- build.gradle
- gradle.properties
https://www.pivotaltracker.com/story/show/167965001
> Integrate Mixpanel into the app

- app/src/main/res/drawable/background_rounded_clearbutton.xml
- app/src/main/res/drawable/green_circle.xml
- app/src/main/res/drawable/overdue_call_button_background.xml
- app/src/main/res/layout/item_overdue_list_patient.xml
- app/src/main/res/layout/patients_user_status_approved.xml
- app/src/main/res/layout/screen_patient_search.xml
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/main/res/values/styles_v2.xml
https://www.pivotaltracker.com/story/show/168071226
> Make tap targets larger

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bp/BloodPressureModule.kt
https://www.pivotaltracker.com/story/show/168134010
> Fix: crash on trying to create a new BP

- app/src/main/java/org/simple/clinic/ViewControllerBinding.kt
- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PartitionSearchResultsByVisitedFacility.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchResults.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchView.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchViewController.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsItemType.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultScreen.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultScreenKey.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultState.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultStateProducer.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultUi.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultUiChangeProducer.kt
- app/src/main/res/layout/patient_search_view.xml
- app/src/main/res/layout/screen_scan_simple.xml
- app/src/main/res/layout/screen_shortcode_search_result.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/patient/PartitionSearchResultsByVisitedFacilityTest.kt
- app/src/test/java/org/simple/clinic/searchresultsview/PatientSearchViewControllerTest.kt
- app/src/test/java/org/simple/clinic/searchresultsview/SearchResultsItemTypeTest.kt
- app/src/test/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultStateProducerTest.kt
- app/src/test/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultUiChangeProducerTest.kt
Final PR for this story.
Pivotol story -> https://www.pivotaltracker.com/story/show/167310717
> Show Shortcode Search results

- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt
- app/src/main/java/org/simple/clinic/scanid/ui/ShortCodeSpanWatcher.kt
- app/src/main/java/org/simple/clinic/text/style/TrailingSpaceForCharacterSpan.kt
- app/src/main/java/org/simple/clinic/util/TextWatcherAdapter.kt
In the short code input field, the hint is formatted in the following way - `123 4567`. This PR adds the same kind of formatting for the text that is being entered inside the `EditText`.
> Format short code in the same format as its hint

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/di/AppInfoHttpInterceptor.kt
https://www.pivotaltracker.com/story/show/168101061
> Add device timezone, offset and locale to request headers

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchResults.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultScreen.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultState.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultStateProducer.kt
- app/src/main/java/org/simple/clinic/util/identifierdisplay/BpPassportDisplayFormatter.kt
- app/src/main/java/org/simple/clinic/util/identifierdisplay/ShortCodeFormatter.kt
- app/src/main/res/layout/screen_scan_simple.xml
- app/src/main/res/values/styles_v2.xml
Closing review comments for the PR https://github.com/simpledotorg/simple-android/pull/780
> Short code screen fixes for feedback

- app/src/androidTest/java/org/simple/clinic/security/pin/BruteForceProtectionAndroidTest.kt
- app/src/debug/java/org/simple/clinic/di/DebugBruteForceProtectionModule.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreen.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreenController.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreenEvents.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchView.kt
- app/src/main/java/org/simple/clinic/security/pin/BruteForceProtection.kt
- app/src/main/java/org/simple/clinic/security/pin/BruteForceProtectionConfig.kt
- app/src/main/java/org/simple/clinic/security/pin/BruteForceProtectionModule.kt
- app/src/main/java/org/simple/clinic/security/pin/BruteForceProtectionState.kt
- app/src/main/java/org/simple/clinic/summary/SummaryMedicalHistoryItem.kt
- app/src/main/java/org/simple/clinic/sync/LastSyncedState.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorStatusCalculator.kt
- app/src/main/java/org/simple/clinic/user/OngoingRegistrationEntry.kt
- app/src/test/java/org/simple/clinic/security/pin/BruteForceProtectionTest.kt
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorStatusCalculatorTest.kt
https://www.pivotaltracker.com/story/show/167310592
> Fixes for internationalization

- app/src/main/res/layout/screen_patient_summary.xml
https://www.pivotaltracker.com/story/show/168071226
> Fix padding on back button in patient summary screen

- doc/QUIRKS.md
https://www.pivotaltracker.com/story/show/164136671
> Add dev environment quirks

- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/di/TestAppModule.kt
- app/src/androidTest/java/org/simple/clinic/di/TestClockModule.kt
- app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/security/pin/BruteForceProtectionAndroidTest.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetController.kt
- app/src/sharedTest/java/org/simple/clinic/util/TestClocks.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetControllerTest.kt
- app/src/test/java/org/simple/clinic/util/TimeFunctionsTest.kt
https://www.pivotaltracker.com/story/show/168165692
> Clean up appointment repository tests

- app/schemas/org.simple.clinic.AppDatabase/46.json
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/di/NetworkModule.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/home/patients/illustration/DayOfMonth.kt
- app/src/main/java/org/simple/clinic/home/patients/illustration/HomescreenIllustration.kt
- app/src/main/java/org/simple/clinic/home/patients/illustration/HomescreenIllustrationModule.kt
- app/src/main/java/org/simple/clinic/storage/Migration_45_46.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/main/java/org/simple/clinic/util/RoomEnumTypeConverter.kt
- app/src/main/java/org/simple/clinic/widgets/ageanddateofbirth/UserInputDateValidator.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/home/patients/illustration/DayOfMonthMoshiTypeAdapterTest.kt
- app/src/test/java/org/simple/clinic/home/patients/illustration/MonthRoomTypeConverterTest.kt
https://www.pivotaltracker.com/story/show/168311301
> Illustration database models

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
https://www.pivotaltracker.com/story/show/168342965
> Improve tests for loading overdue appointments

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/facility/Facility.kt
- app/src/main/java/org/simple/clinic/facility/FacilityPayload.kt
- app/src/main/java/org/simple/clinic/patient/PatientAddress.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt
https://www.pivotaltracker.com/story/show/168187635
> Remove hardcoded country from the app

- CHANGELOG.md
- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/ClinicApp.kt
- app/src/main/java/org/simple/clinic/ReleaseClinicApp.kt
https://www.pivotaltracker.com/story/show/168530182
> Sync everything when the app starts

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreenController.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/168165692
> Use User clock in appointment repository instead of UTC clock

- app/src/main/java/org/simple/clinic/editpatient/PatientEditScreenController.kt
- app/src/main/java/org/simple/clinic/util/RxFoo.kt
- app/src/main/java/org/simple/clinic/util/TimeFunctions.kt
- app/src/test/java/org/simple/clinic/editpatient/PatientEditScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/util/TimeFunctionsTest.kt
https://www.pivotaltracker.com/story/show/168563767
> Change time functions to use the user clock

- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/168694650
> Stop opening new BP sheet after registering a new patient

- app/src/main/java/org/simple/clinic/summary/PatientSummaryConfig.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModule.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/SummaryBloodPressureListItem.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/168558948
> Make BPs editable for a configurable duration only

- app/src/main/java/org/simple/clinic/settings/SettingsEffect.kt
- app/src/main/java/org/simple/clinic/settings/SettingsLogic.kt
- app/src/main/java/org/simple/clinic/settings/SettingsModel.kt
- app/src/test/java/org/simple/clinic/settings/SettingsInitTest.kt
https://www.pivotaltracker.com/story/show/166437675
> Add view to display the current user's name

- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffect.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEvent.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientModel.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientUpdate.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientViewRenderer.kt
- app/src/main/java/org/simple/clinic/editpatient/EditablePatientEntry.kt
- app/src/main/java/org/simple/clinic/editpatient_old/OngoingEditPatientEntryChanged.kt
- app/src/main/java/org/simple/clinic/editpatient_old/PatientEditScreenController.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientAddress.kt
- app/src/main/java/org/simple/clinic/patient/PatientPhoneNumber.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenCreatedTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenFormTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenSaveTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditablePatientEntryTest.kt
This PR contains changes that were discussed in #840, except
* ~~Make scrolling to first field in effect handler a discrete effect~~ (Not doing this as discussed because it is an implementation detail).
> Add schedulers to effects, remove copy constructors from effect handler, and add `PatientSavedEvent`.

- app/src/main/java/org/simple/clinic/settings/SettingsEffectHandler.kt
- app/src/main/java/org/simple/clinic/settings/SettingsEvent.kt
- app/src/main/java/org/simple/clinic/settings/SettingsLogic.kt
- app/src/test/java/org/simple/clinic/settings/SettingsEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/settings/SettingsUpdateTest.kt
https://www.pivotaltracker.com/story/show/166437675
> Implement Settings logic to update the model

- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreenController.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreenEvents.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryUi.kt
- app/src/test/java/org/simple/clinic/newentry/PatientEntryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/newentry/UserInputDateValidatorTest.kt
- app/src/test/java/org/simple/clinic/newentry/clearbutton/ClearFieldImageButtonControllerTest.kt
1. Extracted the view interface
2. Cleaned tests and replaced mocks with real implementations
3. Introduce a sealed class for events
> Prep patient entry screen for strangulation

- app/src/main/java/org/simple/clinic/settings/SettingsScreen.kt
- app/src/main/java/org/simple/clinic/settings/SettingsUi.kt
- app/src/main/java/org/simple/clinic/settings/SettingsUiRenderer.kt
- app/src/main/res/drawable/ic_settings_account_24dp.xml
- app/src/main/res/drawable/ic_settings_phone_24dp.xml
- app/src/main/res/layout/screen_settings.xml
- app/src/main/res/values/colors_v2.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/settings/SettingsUiRendererTest.kt
- quality/lint.xml
https://www.pivotaltracker.com/story/show/166437675
The integration with the Mobius and the rest of the app will be done in the final PR after #851 gets merged.
> Add Settings view

- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
https://www.pivotaltracker.com/story/show/168866105
> Update userUuid when user updates the patient BP

- .codeclimate.yml
- app/src/main/java/org/simple/clinic/activity/TheActivity.kt
- app/src/main/java/org/simple/clinic/crash/CrashBreadcrumbsTimberTree.kt
- router/src/main/java/org/simple/clinic/router/screen/BaseViewGroupKeyChanger.kt
- router/src/main/java/org/simple/clinic/router/screen/FullScreenKeyChanger.kt
- router/src/main/java/org/simple/clinic/router/screen/ScreenRouter.kt
https://www.pivotaltracker.com/story/show/168944244
See https://sentry.io/organizations/resolve-to-save-lives/issues/1255821343/ for an example of the extra breadcrumbs added.
> Add better observability into the Screen Router

- app/src/main/res/layout/screen_home.xml
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/main/res/values/styles_v2.xml
Fix spacing designs as per https://zpl.io/VkGA8GM
> Fix and extract spacing styles of edit button from patient summary

- app/src/main/java/org/simple/clinic/settings/Language.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageEffect.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageEvent.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageLogic.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageModel.kt
- app/src/test/java/org/simple/clinic/settings/changelanguage/ChangeLanguageInitTest.kt
- app/src/test/java/org/simple/clinic/settings/changelanguage/ChangeLanguageUpdateTest.kt
> Add mobius logic for updating the user language

- app/src/main/java/org/simple/clinic/settings/Language.kt
- app/src/main/java/org/simple/clinic/settings/SettingsRepository.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageEffectHandler.kt
- app/src/test/java/org/simple/clinic/settings/changelanguage/ChangeLanguageEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/settings/changelanguage/ChangeLanguageInitTest.kt
- app/src/test/java/org/simple/clinic/settings/changelanguage/ChangeLanguageUpdateTest.kt
> Add update language effect handlers

- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/res/layout/screen_manual_patient_entry.xml
- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/168949014
> Add consent text

- app/schemas/org.simple.clinic.AppDatabase/48.json
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/NetworkModule.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/ReminderConsent.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientSync.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientSyncApi.kt
- app/src/main/java/org/simple/clinic/storage/Migration_47_48.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
https://www.pivotaltracker.com/story/show/168949014
> Patient consent api changes

- app/build.gradle
- app/schemas/org.simple.clinic.AppDatabase/49.json
- app/schemas/org.simple.clinic.AppDatabase/50.json
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/bp/sync/BloodPressureMeasurementPayload.kt
- app/src/main/java/org/simple/clinic/di/AppComponent.kt
- app/src/main/java/org/simple/clinic/encounter/Encounter.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/storage/Migration_48_49.kt
- app/src/main/java/org/simple/clinic/storage/Migration_49_50.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- app/src/main/java/org/simple/clinic/util/UuidGenerator.kt
- app/src/test/java/org/simple/clinic/bp/BloodPressureRepositoryTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- build.gradle
Pivotol story -> https://www.pivotaltracker.com/story/show/168448997
FYI: This PR has two database schema files hence the high LOC.
> Add encounter model and link to BPs

- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/settings/Language.kt
- app/src/main/java/org/simple/clinic/settings/SettingsModule.kt
- app/src/main/java/org/simple/clinic/settings/SettingsRepositoryImpl.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageEvent.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageListItem.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageModel.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageScreen.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageUi.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageUiRenderer.kt
- app/src/main/res/color/changelanguage_radio_button.xml
- app/src/main/res/layout/list_change_language_view.xml
- app/src/main/res/layout/screen_change_language.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/settings/changelanguage/ChangeLanguageListItemTest.kt
- app/src/test/java/org/simple/clinic/settings/changelanguage/ChangeLanguageUiRendererTest.kt
- quality/lint.xml
This is a large PR, but most of it is boilerplate around UI and a layout resource.
> UI for change language screen

- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/settings/Language.kt
- app/src/main/java/org/simple/clinic/settings/PreferencesSettingsRepository.kt
- app/src/main/java/org/simple/clinic/settings/SettingsModule.kt
- app/src/main/java/org/simple/clinic/settings/SettingsRepositoryImpl.kt
- app/src/main/java/org/simple/clinic/util/RxOptional.kt
- app/src/test/java/org/simple/clinic/settings/PreferencesSettingsRepositoryTest.kt
- app/src/test/java/org/simple/clinic/settings/SettingsRepositoryImplTest.kt
> Implement platform logic in SettingsRepository

- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageEffect.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageEffectHandler.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageInit.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageModel.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageScreen.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageUpdate.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/UiActions.kt
- app/src/test/java/org/simple/clinic/settings/changelanguage/ChangeLanguageEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/settings/changelanguage/ChangeLanguageInitTest.kt
- app/src/test/java/org/simple/clinic/settings/changelanguage/ChangeLanguageUpdateTest.kt
> Restart the activity after the language is changed

- app/schemas/org.simple.clinic.AppDatabase/51.json
- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/encounter/Encounter.kt
- app/src/main/java/org/simple/clinic/encounter/sync/EncounterPayload.kt
- app/src/main/java/org/simple/clinic/encounter/sync/EncounterPullResponse.kt
- app/src/main/java/org/simple/clinic/encounter/sync/EncounterPushRequest.kt
- app/src/main/java/org/simple/clinic/storage/Migration_50_51.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
https://www.pivotaltracker.com/story/show/168947291
> Add syncStatus to Encounter

- app/src/main/res/layout/screen_change_language.xml
- app/src/main/res/layout/screen_settings.xml
- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/169175505
> Add a hint to the settings screen when there is no selected language

- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/169226695
> Change hint in settings screen when the language is not selected

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/encounter/EncounterRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bp/sync/BloodPressureMeasurementPayload.kt
- app/src/main/java/org/simple/clinic/encounter/Encounter.kt
- app/src/main/java/org/simple/clinic/encounter/EncounterAndObservations.kt
- app/src/main/java/org/simple/clinic/encounter/EncounterRepository.kt
- app/src/main/java/org/simple/clinic/encounter/ObservationsForEncounter.kt
- app/src/main/java/org/simple/clinic/encounter/sync/EncounterPayload.kt
https://www.pivotaltracker.com/story/show/168947291
> Add Encounter repository

- app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreen.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreen.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreen.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationFullNameScreen.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreen.kt
- app/src/main/res/layout/screen_enterotp.xml
- app/src/main/res/layout/screen_registration_confirm_pin.xml
- app/src/main/res/layout/screen_registration_facility_selection.xml
- app/src/main/res/layout/screen_registration_location_permission.xml
- app/src/main/res/layout/screen_registration_name.xml
- app/src/main/res/layout/screen_registration_pin.xml
https://www.pivotaltracker.com/story/show/169280383
> Fix soft keyboard not showing up automatically during registration

- app/src/main/java/org/simple/clinic/newentry/PatientEntryEvent.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryModel.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryUpdate.kt
- app/src/main/java/org/simple/clinic/patient/OngoingNewPatientEntry.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/res/layout/screen_manual_patient_entry.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/newentry/PatientEntryUpdateTest.kt
https://www.pivotaltracker.com/story/show/168949014
> Reminder consent UI

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/activity/PlaceholderScreenKey.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingScreen.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivity.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityEffect.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityEffectHandler.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityEvent.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityInit.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityModel.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityUpdate.kt
- app/src/main/java/org/simple/clinic/setup/UiActions.kt
- app/src/main/res/layout/screen_placeholder.xml
- app/src/test/java/org/simple/clinic/setup/SetupActivityEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/setup/SetupActivityInitTest.kt
- app/src/test/java/org/simple/clinic/setup/SetupActivityUpdateTest.kt
https://www.pivotaltracker.com/n/projects/2358313/stories/169253555
The final PR in this set of PRs will change `SetupActivity` to be the launcher activity.
> Do not show onboarding screen if the user has already completed onboarding in Setup Activity

- app/src/main/java/org/simple/clinic/selectcountry/Country.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryEffect.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryEvent.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryInit.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryModel.kt
- app/src/test/java/org/simple/clinic/selectcountry/SelectCountryInitTest.kt
> Initial setup for the Select Country screen

- app/src/main/java/org/simple/clinic/appconfig/AppConfigRepository.kt
- app/src/main/java/org/simple/clinic/appconfig/Country.kt
- app/src/main/java/org/simple/clinic/selectcountry/ManifestFetchError.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryEffect.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryEvent.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryModel.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryUpdate.kt
- app/src/test/java/org/simple/clinic/security/pin/PinEntryCardControllerTest.kt
- app/src/test/java/org/simple/clinic/selectcountry/SelectCountryInitTest.kt
- app/src/test/java/org/simple/clinic/selectcountry/SelectCountryUpdateTest.kt
> Select country logic

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/main/TheActivityConfig.kt
- router/src/main/java/flow/StateSizeLogger.kt
- router/src/main/java/org/simple/clinic/router/screen/ScreenRouter.kt
See [THIS](https://sentry.io/share/issue/8dc985c628804f458ca452372cae8e97/) crash report for an example of what the breadcrumbs would look like.
> Add instrumentation for tracking the size of saved states in TheActivity

- app/src/main/java/org/simple/clinic/appconfig/AppConfigRepository.kt
- app/src/main/java/org/simple/clinic/appconfig/ManifestFetchResult.kt
- app/src/main/java/org/simple/clinic/selectcountry/ManifestFetchError.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryEffectHandler.kt
- app/src/main/java/org/simple/clinic/selectcountry/UiActions.kt
- app/src/test/java/org/simple/clinic/selectcountry/SelectCountryEffectHandlerTest.kt
> Implement the effect handler for the select country screen

- CHANGELOG.md
- app/build.gradle
- app/src/main/java/org/simple/clinic/home/overdue/phonemask/PhoneMaskBottomSheet.kt
- app/src/main/java/org/simple/clinic/home/overdue/phonemask/PhoneMaskBottomSheetController.kt
- app/src/main/java/org/simple/clinic/phone/PhoneNumberMaskerConfig.kt
- app/src/main/res/layout/sheet_phone_mask.xml
- app/src/test/java/org/simple/clinic/home/overdue/OverdueScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/phonemask/PhoneMaskBottomSheetControllerTest.kt
- app/src/test/java/org/simple/clinic/phone/PhoneDialerTest.kt
- gradle.properties
https://www.pivotaltracker.com/story/show/169197806
> Add a remote toggle for secure calling

- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryModel.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryScreen.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryUi.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryUiRenderer.kt
- app/src/main/java/org/simple/clinic/selectcountry/adapter/Event.kt
- app/src/main/java/org/simple/clinic/selectcountry/adapter/SelectableCountryItem.kt
- app/src/main/java/org/simple/clinic/selectcountry/adapter/SelectableCountryItemDiffCallback.kt
- app/src/main/res/color/selectcountry_radio_button.xml
- app/src/main/res/layout/list_selectcountry_country_view.xml
- app/src/main/res/layout/screen_selectcountry.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/selectcountry/SelectCountryUiRendererTest.kt
- app/src/test/java/org/simple/clinic/selectcountry/adapter/SelectableCountryItemTest.kt
- quality/lint.xml
This is a large-ish PR, but a lot of it are layout resource files.
The UI also is currently non-functional and just includes the layout resource. The next PR will hook this view up to the mobius loop and add in the navigation logic.
> UI implementation for the country selection screen

- app/src/androidTest/java/org/simple/clinic/encounter/EncounterRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/encounter/Encounter.kt
- app/src/main/java/org/simple/clinic/encounter/EncounterRepository.kt
https://www.pivotaltracker.com/story/show/169616318
> Fix sync for deleted BP within an existing Encounter

- app/src/main/java/org/simple/clinic/appconfig/AppConfigModule.kt
- app/src/main/java/org/simple/clinic/appconfig/Country.kt
- app/src/main/java/org/simple/clinic/appconfig/displayname/CountryDisplayNameFetcher.kt
- app/src/main/java/org/simple/clinic/appconfig/displayname/CountryDisplayNameFetcherModule.kt
- app/src/main/java/org/simple/clinic/appconfig/displayname/PlatformCountryDisplayNameFetcher.kt
- app/src/main/java/org/simple/clinic/di/InjectorProviderContextWrapper.kt
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
- app/src/main/java/org/simple/clinic/selectcountry/ManifestFetchError.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryEvent.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryModel.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryScreen.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryScreenInjector.kt
- app/src/main/java/org/simple/clinic/selectcountry/adapter/SelectableCountryItem.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivity.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityComponent.kt
- app/src/main/res/layout/screen_selectcountry.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/selectcountry/adapter/SelectableCountryItemTest.kt
> Wire the mobius loop with the select country screen

- app/src/main/java/org/simple/clinic/appconfig/AppConfigModule.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreen.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt
- app/src/main/res/layout/screen_enterotp.xml
- app/src/main/res/layout/screen_registration_phone.xml
- app/src/main/res/layout/sheet_phone_mask.xml
- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/169472237
> Use the selected country to display country dialling codes

- app/build.gradle
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/user/UserSessionAndroidTest.kt
- app/src/main/java/org/simple/clinic/appconfig/AppConfigRepository.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingScreen.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryScreen.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryScreenKey.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivity.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityEffect.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityEffectHandler.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityEvent.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityModel.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityModule.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityUpdate.kt
- app/src/main/java/org/simple/clinic/setup/UiActions.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/main/java/org/simple/clinic/util/Optional.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/setup/SetupActivityEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/setup/SetupActivityInitTest.kt
- app/src/test/java/org/simple/clinic/setup/SetupActivityUpdateTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
- gradle.properties
https://www.pivotaltracker.com/story/show/169418103
> Add Select Country screen to the app navigation graph

- app/src/main/java/org/simple/clinic/appconfig/AppConfigRepository.kt
- app/src/main/java/org/simple/clinic/appconfig/Manifest.kt
- app/src/main/java/org/simple/clinic/appconfig/api/ManifestFetchApi.kt
- app/src/test/java/org/simple/clinic/appconfig/AppConfigRepositoryTest.kt
Response: https://api-qa.simple.org/api/manifest.json
> Update the manifest fetch api result as per API spec

- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenController.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/main/java/org/simple/clinic/user/finduser/FindUserResult.kt
- app/src/main/java/org/simple/clinic/user/finduser/FindUserWithPhoneNumber.kt
- app/src/main/java/org/simple/clinic/user/refreshuser/RefreshCurrentUser.kt
- app/src/sharedTest/java/org/simple/clinic/util/RxTestUtils.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/login/LoginUserWithOtpTest.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
- app/src/test/java/org/simple/clinic/user/finduser/FindUserWithPhoneNumberTest.kt
- app/src/test/java/org/simple/clinic/user/refreshuser/RefreshCurrentUserTest.kt
https://www.pivotaltracker.com/story/show/168980786
> Refactor registration flows out of user session

- app/src/main/java/org/simple/clinic/newentry/form/AgeField.kt
- app/src/main/java/org/simple/clinic/newentry/form/DateOfBirthField.kt
- app/src/main/java/org/simple/clinic/newentry/form/DistrictField.kt
- app/src/main/java/org/simple/clinic/newentry/form/GenderField.kt
- app/src/main/java/org/simple/clinic/newentry/form/InputField.kt
- app/src/main/java/org/simple/clinic/newentry/form/PatientNameField.kt
- app/src/main/java/org/simple/clinic/newentry/form/StateField.kt
- app/src/main/java/org/simple/clinic/newentry/form/StreetAddressField.kt
- app/src/main/java/org/simple/clinic/newentry/form/ValidationError.kt
- app/src/main/java/org/simple/clinic/newentry/form/VillageOrColonyField.kt
- app/src/main/java/org/simple/clinic/newentry/form/ZoneField.kt
- app/src/test/java/org/simple/clinic/newentry/form/AgeFieldTest.kt
- app/src/test/java/org/simple/clinic/newentry/form/DateOfBirthFieldTest.kt
- app/src/test/java/org/simple/clinic/newentry/form/DistrictFieldTest.kt
- app/src/test/java/org/simple/clinic/newentry/form/GenderFieldTest.kt
- app/src/test/java/org/simple/clinic/newentry/form/PatientNameFieldTest.kt
- app/src/test/java/org/simple/clinic/newentry/form/StateFieldTest.kt
- app/src/test/java/org/simple/clinic/newentry/form/StreetAddressFieldTest.kt
- app/src/test/java/org/simple/clinic/newentry/form/VillageOrColonyFieldTest.kt
- app/src/test/java/org/simple/clinic/newentry/form/ZoneFieldTest.kt
This is an evolving design at the moment and contains duplication that will be addressed in the future PRs.
> Begin adding configurable fields for new patient entry screen

- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenController.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/main/java/org/simple/clinic/user/resetpin/ForgotPinResult.kt
- app/src/main/java/org/simple/clinic/user/resetpin/ResetPinResult.kt
- app/src/main/java/org/simple/clinic/user/resetpin/ResetUserPin.kt
- app/src/sharedTest/java/org/simple/clinic/util/TestExtensions.kt
- app/src/test/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
- app/src/test/java/org/simple/clinic/user/resetpin/JavaHashPasswordHasher.kt
- app/src/test/java/org/simple/clinic/user/resetpin/ResetUserPinTest.kt
https://www.pivotaltracker.com/story/show/168980786
> Refactor reset PIN flow out of UserSession

- README.md
- quality/code-style.xml
This commit also renames the code style from "Uncmn" to "Simple".
> Add README instructions for importing the current code style

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentConfig.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentModule.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetControllerTest.kt
https://www.pivotaltracker.com/story/show/169913323
> Change overdue appointments list

- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenController.kt
- app/src/main/java/org/simple/clinic/login/LoginUserWithOtp.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/main/java/org/simple/clinic/user/clearpatientdata/ClearPatientDataModule.kt
- app/src/main/java/org/simple/clinic/user/clearpatientdata/SyncAndClearPatientData.kt
- app/src/test/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/login/LoginUserWithOtpTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
- app/src/test/java/org/simple/clinic/user/clearpatientdata/SyncAndClearPatientDataTest.kt
https://www.pivotaltracker.com/story/show/168980786
> Refactor syncing and clearing of patient data out of UserSession

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/businessid/BusinessIdMetaDataAdapterAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/PatientModule.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessIdMetaData.kt
- app/src/main/java/org/simple/clinic/patient/businessid/Identifier.kt
- app/src/main/java/org/simple/clinic/util/identifierdisplay/BangladeshNationalIdDisplayFormatter.kt
- app/src/main/java/org/simple/clinic/util/identifierdisplay/IdentifierDisplayAdapterModule.kt
- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/168980840
> Add Bangladesh National Id Metadata

- app/src/main/java/org/simple/clinic/settings/SettingsModule.kt
- app/src/main/res/values-bn-rBD/strings.xml
- app/src/main/res/values-bn-rIN/strings.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-pa/strings.xml
- Hindi
- Punjabi
- Bengali (India)
- Bengali (Bangladesh)
> Pull translations from Transifex

- app/src/androidTest/java/org/simple/clinic/DateOfBirthHintUnfocusedAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/main/res/values-ti-rET/strings.xml
https://www.pivotaltracker.com/story/show/170094485
> Hint in patient register/edit screen should not be smaller than mask

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/phonemask/PhoneMaskBottomSheet.kt
- app/src/main/java/org/simple/clinic/home/overdue/phonemask/PhoneMaskBottomSheetController.kt
- app/src/main/java/org/simple/clinic/home/overdue/phonemask/PhoneMaskBottomSheetUi.kt
- app/src/main/java/org/simple/clinic/patient/PatientModule.kt
- app/src/main/java/org/simple/clinic/phone/PhoneCaller.kt
- app/src/main/java/org/simple/clinic/phone/PhoneNumberMaskerConfig.kt
- app/src/main/res/layout/sheet_phone_mask.xml
- app/src/test/java/org/simple/clinic/home/overdue/phonemask/PhoneMaskBottomSheetControllerTest.kt
- app/src/test/java/org/simple/clinic/phone/PhoneDialerTest.kt
https://www.pivotaltracker.com/story/show/169860653
> Fix broken UI in phone masking sheet

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/bloodsugar/selection/type/BloodSugarTypeAdapter.kt
- app/src/main/java/org/simple/clinic/bloodsugar/selection/type/BloodSugarTypePickerSheet.kt
- app/src/main/res/layout/blood_sugar_type_list_item.xml
- app/src/main/res/layout/list_blood_sugar_type.xml
- app/src/main/res/layout/sheet_blood_sugar_type_picker.xml
- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/170099068
> User must be able to select a type of Blood Sugar to add

- .github/workflows/android.yml
Steps performed in GitHub Actions
- lintQaDebug [Runs on Ubuntu machine]
- testQaDebugUnitTest [Runs on Ubuntu machine]
- connectedQaDebugAndroidTest [Runs on Mac machine]
- assembleQaDebug [Runs on Ubuntu machine]
All of the above steps are run in parallel.
> Add GitHub Actions

- app/src/main/java/org/simple/clinic/overdue/AppointmentSyncApi.kt
https://www.pivotaltracker.com/story/show/170357654
We also need to resync the Appointments from start after users update to the new API.
> Resync appointments to fetch creation_facility_id

- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffect.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEvent.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientInit.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientModel.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientUi.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientUpdate.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt
- app/src/main/res/layout/screen_edit_patient.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenCreatedTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenFormTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenSaveTest.kt
https://www.pivotaltracker.com/story/show/168980840
> Add Business ID in Patient Edit Screen

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/bloodsugar/BloodSugarRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarRepository.kt
- app/src/main/java/org/simple/clinic/bloodsugar/di/BloodSugarModule.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
https://www.pivotaltracker.com/story/show/169675670
> Add BloodSugarRepository

- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEffect.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEvent.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewInit.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewModel.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewUpdate.kt
- app/src/test/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewInitTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewUpdateTest.kt
- mobius-base/src/main/java/org/simple/clinic/mobius/MobiusFoo.kt
Pivotol story-> https://www.pivotaltracker.com/story/show/169675670
> Add BloodSugarSummaryViewUpdate class

- app/build.gradle
- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- build.gradle
Links:
- https://square.github.io/leakcanary/
- https://square.github.io/leakcanary/upgrading-to-leakcanary-2.0/
> Bump LeakCanary version -> 2.1

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEvent.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientModel.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientUi.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientUpdate.kt
- app/src/main/java/org/simple/clinic/editpatient/EditablePatientEntry.kt
- app/src/main/java/org/simple/clinic/newentry/Field.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryEvent.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryModel.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryUpdate.kt
- app/src/main/java/org/simple/clinic/newentry/country/InputFieldsFactory.kt
- app/src/main/java/org/simple/clinic/patient/OngoingNewPatientEntry.kt
- app/src/main/java/org/simple/clinic/patient/PatientAddress.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/test/java/org/simple/clinic/newentry/PatientEntryScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/patient/OngoingNewPatientEntryTest.kt
https://www.pivotaltracker.com/story/show/168980965
> Change address model to have 5 fields

- app/src/androidTest/java/org/simple/clinic/bloodsugar/BloodSugarRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarRepository.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffect.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntrySheet.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
https://www.pivotaltracker.com/story/show/169676359
Completed `BloodSugarEntryEffectHandler` implementation
> User must be able to enter a blood sugar reading - Part 3

- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEffect.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEvent.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewInit.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewModel.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewUpdate.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/UiActions.kt
- app/src/test/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewInitTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewUpdateTest.kt
https://www.pivotaltracker.com/story/show/169675670
We are not implementing `Edit` for now.
> Implement Blood sugar Summary EffectHandler

- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewModel.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewUi.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewUiRenderer.kt
- app/src/test/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewUiRendererTest.kt
https://www.pivotaltracker.com/story/show/169675670
> Add BloodSugarSummaryViewUiRenderer

- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenEvents.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
> Migrate patient summary screen to Mobius #1: Inject runtime dependencies into `PatientSummaryScreenController`

- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurementType.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryModel.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntrySheet.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUpdate.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/OpenAs.kt
https://www.pivotaltracker.com/story/show/169676359
Wire UI and Mobius loop
> User must be able to enter a blood sugar reading - Part 4

- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/summary/ActivityRequestCodes.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryItems.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenEvents.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenUi.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryUi.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryView.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewController.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewInjector.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryLogicTest.kt
> Migrate patient summary screen to Mobius #2: Extract blood pressure summary view controller

- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientValidationError.kt
- app/src/main/java/org/simple/clinic/editpatient/EditablePatientEntry.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryValidationActions.kt
- app/src/main/java/org/simple/clinic/patient/OngoingNewPatientEntry.kt
- app/src/main/java/org/simple/clinic/patient/PatientEntryValidationError.kt
- app/src/main/java/org/simple/clinic/widgets/ageanddateofbirth/UserInputAgeValidator.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/newentry/UserInputAgeValidatorTest.kt
https://www.pivotaltracker.com/story/show/170501005
> Add validation for age for age equal to 0

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/patient/RecentPatient.kt
https://www.pivotaltracker.com/story/show/170485623
> Use creation facility ID instead of facility ID for recent patients

- app/src/androidTest/java/org/simple/clinic/medicalhistory/MedicalHistoryRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryItems.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenEvents.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenUi.kt
- app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUi.kt
- app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUiController.kt
- app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryView.kt
- app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryViewInjector.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUiControllerTest.kt
> Migrate patient summary screen to Mobius #3: Extract medical history summary view controller

- .github/scripts/commit_and_push.sh
- .github/workflows/code_formatting_checks.yml
- Runs daily at 5 AM IST / 11:30 PM UTC
- Automatically fixes code formatting issues using `./gradlew spotlessApply`
- Commit the changes to a new branch with format `bot/MMM-dd-yyyy/code-formatting`
- Raise a PR with `master` with title `[BOT] Code formatting fixes MMM-dd-yyyy`
**REQUIRED**:
- `USER_NAME` and `USER_EMAIL` have to be set in GitHub secrets
> Automate code formatting

- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryItems.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenEvents.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenUi.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryUi.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryUiController.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryView.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryViewInjector.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryUiControllerTest.kt
> Migrate patient summary screen to Mobius #4: Extract prescribed drugs summary view controller

- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryInit.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryViewRenderer.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
> Migrate patient summary screen to Mobius #5: Prepare patient summary screen controller

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bloodsugar/selection/type/BloodSugarTypePickerSheet.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/summary/ActivityRequestCodes.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryConfig.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarSummaryView.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarSummaryViewInjector.kt
- app/src/main/res/layout/list_patientsummary_bloodsugar_measurement.xml
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/test/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryLogicTest.kt
This is the last PR in the story -> https://www.pivotaltracker.com/story/show/169675670
> Add Diabetes widget to PatientSummaryScreen

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
https://www.pivotaltracker.com/story/show/170641087
> Add check to verify Bangladesh National ID is not empty

- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryInit.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryProfile.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryViewRenderer.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- mobius-base/src/main/java/org/simple/clinic/mobius/MobiusDelegate.kt
> Migrate patient summary to Mobius #6: move populatePatientProfile() and showEditButton()

- app/src/test/java/org/simple/clinic/newentry/PatientEntryUpdateTest.kt
https://www.pivotaltracker.com/story/show/169030605
> Add Mobius update tests for showing validation errors

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration56AndroidTest.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentSyncApi.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_55_56.kt
- Fix incorrect migration for appointments
- Force a resync of appointments on app update
> Fixes to recent appointment changes

- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffect.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffectHandler.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEvent.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenInit.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenModel.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUi.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUiActions.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUiRenderer.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUpdate.kt
- app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenInitTest.kt
- app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUiRendererTest.kt
- app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUpdateTest.kt
https://www.pivotaltracker.com/story/show/169677099
- Added `BloodPressureHistoryScreenInit`
- Added `BloodPressureHistoryScreenUpdate`
- Added `BloodPressureHistoryScreenEffectHandler`
- Added `BloodPressureHistoryScreenUiRenderer`
> `BloodPressureHistoryScreen` - Part 1

- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreen.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenInjector.kt
- app/src/main/java/org/simple/clinic/bp/history/adapter/BloodPressureHistoryListItem.kt
- app/src/main/java/org/simple/clinic/bp/history/adapter/BloodPressureHistoryListItemDiffCallback.kt
- app/src/main/java/org/simple/clinic/bp/history/adapter/Event.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/res/drawable/bp_reading_high.xml
- app/src/main/res/drawable/bp_reading_normal.xml
- app/src/main/res/layout/list_bp_history_item.xml
- app/src/main/res/layout/screen_bp_history.xml
- app/src/main/res/values/styles_v2.xml
- app/src/test/java/org/simple/clinic/bp/history/adapter/BloodPressureHistoryListItemTest.kt
- quality/lint.xml
https://www.pivotaltracker.com/story/show/169677099
- Initial implementation of `BloodPressureHistoryScreen`
> `BloodPressureHistoryScreen` - Part 2

- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreen.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffect.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffectHandler.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEvent.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenInit.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenKey.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenModel.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUi.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUiActions.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUiRenderer.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUpdate.kt
- app/src/main/java/org/simple/clinic/bp/history/adapter/BloodPressureHistoryListItem.kt
- app/src/main/java/org/simple/clinic/bp/history/adapter/BloodPressureHistoryListItemDiffCallback.kt
- app/src/main/java/org/simple/clinic/bp/history/adapter/Event.kt
- app/src/main/res/drawable/ic_add_circle_blue1_24dp.xml
- app/src/main/res/layout/list_bp_history_item.xml
- app/src/main/res/layout/list_new_bp_button.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenInitTest.kt
- app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUiRendererTest.kt
- app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUpdateTest.kt
- app/src/test/java/org/simple/clinic/bp/history/adapter/BloodPressureHistoryListItemTest.kt
https://www.pivotaltracker.com/story/show/169677099
- Wire Mobius Loop with UI
> `BloodPressureHistoryScreen` - Part 3

- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenEvents.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenUi.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
> Migrate patient summary to Mobius #7: move showScheduleAppointmentSheet()

- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreen.kt
- app/src/main/java/org/simple/clinic/bp/history/adapter/BloodPressureHistoryListItem.kt
- app/src/main/java/org/simple/clinic/di/DateFormatterModule.kt
- app/src/main/java/org/simple/clinic/widgets/DividerItemDecorator.kt
- app/src/main/java/org/simple/clinic/widgets/Views.kt
- app/src/main/res/drawable/divider.xml
- app/src/main/res/layout/list_bp_history_item.xml
- app/src/main/res/layout/list_new_bp_button.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/bp/history/adapter/BloodPressureHistoryListItemTest.kt
- quality/lint.xml
https://www.pivotaltracker.com/story/show/169677099
- Show bp history date & time
- Use `DividerItemDecorator`
> `BloodPressureHistoryScreen` - Part 4

- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewConfig.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewEffect.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewEvent.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewInit.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewModel.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewUiActions.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewUpdate.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewInitTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewUpdateTest.kt
https://www.pivotaltracker.com/story/show/170816330
- `NewBloodPressureSummaryViewUpdate `
- `NewBloodPressureSummaryEffectHandler`
> New blood pressure summary view - Part 1

- app/schemas/org.simple.clinic.AppDatabase/58.json
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration58AndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/facility/Facility.kt
- app/src/main/java/org/simple/clinic/facility/FacilityConfig.kt
- app/src/main/java/org/simple/clinic/facility/FacilityPayload.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_57_58.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
https://www.pivotaltracker.com/story/show/169676334
> Add support for the diabetes management flag to the Facility model

- app/src/main/java/org/simple/clinic/bp/history/adapter/BloodPressureHistoryListItem.kt
- app/src/main/res/values-bn-rBD/strings.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-mr-rIN/strings.xml
- app/src/main/res/values/strings.xml
- Design updated to be similar as the summary view
> Change `timeDateTextView` string format in `list_bp_history_item`

- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewUi.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewUiRenderer.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/newbpsummary/view/NewBloodPressureItemView.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/newbpsummary/view/NewBloodPressureSummaryView.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/newbpsummary/view/NewBloodPressureSummaryViewInjector.kt
- app/src/main/res/drawable/ic_chevron_right_blue1_24dp.xml
- app/src/main/res/layout/list_patientsummary_newbp_measurement.xml
- app/src/main/res/layout/patientsummary_newbpitem_content.xml
- app/src/main/res/layout/patientsummary_newbpsummary_content.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/summary/bloodpressures/newbpsummary/NewBloodPressureSummaryViewUiRendererTest.kt
- quality/lint.xml
https://www.pivotaltracker.com/story/show/170816330
- `NewBloodPressureSummaryViewUiRenderer`
- Initial implementation of `NewBloodPressureSummaryView`
- `NewBloodPressureItemView`
> New blood pressure summary view - Part 2

- app/schemas/org.simple.clinic.AppDatabase/59.json
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration57AndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration59AndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/storage/migrations/MigrationHelper.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_58_59.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
https://www.pivotaltracker.com/story/show/170696612
> Fix Patient SQL query to include house address and zone

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/bloodsugar/BloodSugarRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarRepository.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenEffect.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenEffectHandler.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenEvent.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenInit.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenModel.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenUi.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenUiActions.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenUiRenderer.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenUpdate.kt
- app/src/test/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenInitTest.kt
- app/src/test/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenUiRendererTest.kt
- app/src/test/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenUpdateTest.kt
https://www.pivotaltracker.com/story/show/169677139
> `BloodSugarHistoryScreen` - Part 1

- app/src/main/java/org/simple/clinic/medicalhistory/Answer.kt
- app/src/main/java/org/simple/clinic/medicalhistory/OngoingMedicalHistoryEntry.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffect.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandler.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEvent.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryModel.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenController.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenEvents.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUi.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiActions.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdate.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/169674952
This moves the feature of registering a patient and opening the summary screen to the Mobius loop.
> New Medical History screen - cleanup #3

- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreen.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenEvent.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenInjector.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenKey.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenModel.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/adapter/BloodSugarHistoryListItem.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/adapter/BloodSugarHistoryListItemDiffCallback.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/adapter/Event.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreen.kt
- app/src/main/java/org/simple/clinic/di/DateFormatterModule.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureSummaryView.kt
- app/src/main/res/drawable/ic_blood_sugar_filled.xml
- app/src/main/res/layout/list_blood_sugar_history_item.xml
- app/src/main/res/layout/list_new_blood_sugar_button.xml
- app/src/main/res/layout/screen_blood_sugar_history.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/bloodsugar/history/adapter/BloodSugarHistoryListItemTest.kt
- quality/lint.xml
https://www.pivotaltracker.com/story/show/169677139
> `BloodSugarHistoryScreen` - Part 2

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/bloodsugar/sync/BloodSugarSyncAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurementType.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarRepository.kt
- app/src/main/java/org/simple/clinic/bloodsugar/di/BloodSugarModule.kt
- app/src/main/java/org/simple/clinic/bloodsugar/sync/BloodSugarMeasurementPayload.kt
- app/src/main/java/org/simple/clinic/bloodsugar/sync/BloodSugarPullResponse.kt
- app/src/main/java/org/simple/clinic/bloodsugar/sync/BloodSugarPushRequest.kt
- app/src/main/java/org/simple/clinic/bloodsugar/sync/BloodSugarSync.kt
- app/src/main/java/org/simple/clinic/bloodsugar/sync/BloodSugarSyncApi.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
https://www.pivotaltracker.com/story/show/169674850
> Add Blood sugar sync

- app/src/main/java/org/simple/clinic/facility/Facility.kt
- app/src/main/java/org/simple/clinic/facility/FacilityConfig.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryQuestionView.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffect.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandler.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEvent.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryInit.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryModel.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUi.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiActions.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRenderer.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdate.kt
- app/src/main/res/layout/screen_new_medical_history.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryInitTest.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRendererTest.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdateTest.kt
https://www.pivotaltracker.com/story/show/169674952
Sorry about the large-ish PR, but most of this is test code which tests a bunch of similar cases and involves some repetition. Let me know if you need help pairing on the review at any point.
> Implement the Diagnosis view in the new medical history screen

- app/src/main/java/org/simple/clinic/home/overdue/appointmentreminder/AppointmentReminder.kt
- app/src/main/java/org/simple/clinic/home/overdue/appointmentreminder/AppointmentReminderSheet.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/home/overdue/appointmentreminder/AppointmentReminderSheetControllerTest.kt
https://www.pivotaltracker.com/story/show/170310730
> Unit for period is not translated in any language when you set appointment reminder for overdue patients

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt
- app/src/main/java/org/simple/clinic/user/clearpatientdata/SyncAndClearPatientData.kt
- app/src/test/java/org/simple/clinic/user/clearpatientdata/SyncAndClearPatientDataTest.kt
https://www.pivotaltracker.com/story/show/171020273
> Clear blood sugars data when user gets logged out

- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreen.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/adapter/BloodSugarHistoryListItem.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreen.kt
- app/src/main/java/org/simple/clinic/bp/history/adapter/BloodPressureHistoryListItem.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentRow.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientScreenItemTypes.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientItem.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt
- app/src/main/java/org/simple/clinic/security/pin/PinEntryCardView.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureItemView.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/java/org/simple/clinic/util/RelativeTimestampGenerator.kt
- app/src/main/java/org/simple/clinic/widgets/PatientSearchResultItemView.kt
- app/src/main/res/values-bn-rBD/strings.xml
- app/src/main/res/values-bn-rIN/strings.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-kn-rIN/strings.xml
- app/src/main/res/values-mr-rIN/strings.xml
- app/src/main/res/values-pa-rIN/strings.xml
- app/src/main/res/values-te-rIN/strings.xml
- app/src/main/res/values-ti-rET/strings.xml
- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/170946758
> Fix translation issue in numerals

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistorySyncApi.kt
https://www.pivotaltracker.com/story/show/170991191
> Bump resync token for CV history

- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryView.kt
https://www.pivotaltracker.com/story/show/170669591
> Alphabetically sort medicines in patient summary screen

- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewConfig.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewEffect.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewEvent.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewInit.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewModel.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewUiRenderer.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewUpdate.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureSummaryView.kt
- app/src/test/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewInitTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewUiRendererTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewUpdateTest.kt
https://www.pivotaltracker.com/story/show/171014778
> Show a different number of BPs if diabetes management is disabled in Patient Summary

- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryProfile.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/main/res/values-bn-rBD/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryInitTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryViewRendererTest.kt
https://www.pivotaltracker.com/story/show/170924934
> Show Bangladesh National ID on Patient Summary screen

- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- mobius-base/src/main/java/org/simple/clinic/mobius/MobiusDelegate.kt
https://www.pivotaltracker.com/story/show/171126418
> Fix edit patient issue

- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryView.kt
- app/src/main/res/layout/drugs_summary_view.xml
- app/src/main/res/values-bn-rBD/strings.xml
- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/171145401
> Add empty view for Medicine summary view

- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/main/java/org/simple/clinic/widgets/PatientSearchResultItemView.kt
- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/171107159
> Display complete address in patient search results

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffect.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEvent.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientInit.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientModel.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreenKey.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientUpdate.kt
- app/src/main/java/org/simple/clinic/editpatient/EditablePatientEntry.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenCreatedTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenFormTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenSaveTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditablePatientEntryTest.kt
https://www.pivotaltracker.com/story/show/170717757
> Clearing Bangladesh Id should delete it

- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt
- app/src/main/java/org/simple/clinic/summary/AppointmentSheetOpenedFrom.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenEvents.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenUi.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryInitTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryViewRendererTest.kt
> Migrate patient summary to Mobius #8: Move `goToPreviousScreen()` to `PatientSummaryUiActions`

- app/src/debug/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryConfigModule.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarRepository.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffect.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEvent.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryInit.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUpdate.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/OpenAs.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryConfig.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModule.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryConfig.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEffect.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEvent.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewUiRenderer.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewUpdate.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/UiActions.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarItemView.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarSummaryView.kt
- app/src/main/res/layout/patientsummary_bloodsugar_item_content.xml
- app/src/main/res/layout/sheet_blood_sugar_entry.xml
- app/src/main/res/values/strings.xml
- app/src/release/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryConfigModule.kt
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryInitTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewUiRendererTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewUpdateTest.kt
https://www.pivotaltracker.com/story/show/169676402
> Allow user to edit a Blood Sugar within 60 minutes of it being added - Part 1

- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffect.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryInit.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntrySheet.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUi.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUiRenderer.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUpdate.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/OpenAs.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/UiActions.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarSummaryView.kt
- app/src/main/res/layout/sheet_blood_sugar_entry.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryInitTest.kt
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUiRendererTest.kt
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUpdateTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEffectHandlerTest.kt
https://www.pivotaltracker.com/story/show/169676402
> Allow user to edit a Blood Sugar within 60 minutes of it being added - Part 2

- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenUi.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
> Migrate patient summary to Mobius #9: Move `goToHomeScreen` to Mobius

- app/build.gradle
- build.gradle
- gradle.properties
> Use R8 instead of Proguard

- app/src/main/java/org/simple/clinic/deniedaccess/AccessDeniedScreen.kt
- app/src/main/java/org/simple/clinic/deniedaccess/AccessDeniedScreenInjector.kt
- app/src/main/java/org/simple/clinic/deniedaccess/AccessDeniedScreenKey.kt
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/main/TheActivityController.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenController.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/main/res/layout/screen_access_denied.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/activity/TheActivityControllerTest.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/170594720
> Show Denied access screen to users

- app/src/release/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryConfigModule.kt
Forgot to enable blood sugar edit feature flag in release mode.
> Enable blood sugar edit feature flag

- doc/arch/001-screen-controllers.md
- doc/arch/007-screen-architecture-v2.md
- doc/arch/008-screen-architecture-v3.md
- doc/mobius/implementing-a-new-screen.md
- doc/mobius/migrating-to-mobius.md
https://www.pivotaltracker.com/story/show/170146761
> Add ADR for Mobius

- app/src/androidTest/java/org/simple/clinic/bloodsugar/BloodSugarRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarRepository.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/171435609
> Show schedule appointment sheet when only blood sugar is added

- app/src/androidTest/java/org/simple/clinic/di/TestRetrofitModule.kt
- app/src/main/java/org/simple/clinic/bloodsugar/sync/BloodSugarSyncApi.kt
- app/src/main/java/org/simple/clinic/bp/sync/BloodPressureSyncApi.kt
- app/src/main/java/org/simple/clinic/di/network/RetrofitModule.kt
- app/src/main/java/org/simple/clinic/drugs/sync/PrescriptionSyncApi.kt
- app/src/main/java/org/simple/clinic/facility/FacilitySyncApi.kt
- app/src/main/java/org/simple/clinic/help/HelpApi.kt
- app/src/main/java/org/simple/clinic/login/LoginApi.kt
- app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistorySyncApi.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentSyncApi.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientSyncApi.kt
- app/src/main/java/org/simple/clinic/protocol/ProtocolSyncApi.kt
- app/src/main/java/org/simple/clinic/registration/RegistrationApi.kt
- app/src/main/java/org/simple/clinic/reports/ReportsApi.kt
https://www.pivotaltracker.com/story/show/171716382
> Add support for new API version bump structure

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientPhoneNumber.kt
- app/src/main/java/org/simple/clinic/patient/PatientProfile.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryInit.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryInitTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
This PR attempts to clean up the `PatientSummaryEffectHandler` in order to make it more "Mobius idiomatic". I managed to get a good bit of the module, but there are other parts left over which I haven't gotten around to yet. I'll leave for later.
> Migrate patient summary to Mobius: epilogue

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreen.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreen.kt
- app/src/main/java/org/simple/clinic/di/DateFormatterModule.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentRow.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureSummaryView.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarSummaryView.kt
- app/src/main/java/org/simple/clinic/widgets/PatientSearchResultItemView.kt
- app/src/main/res/layout/item_overdue_list_patient.xml
- app/src/main/res/values-bn-rBD/strings.xml
- app/src/main/res/values-bn-rIN/strings.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-kn-rIN/strings.xml
- app/src/main/res/values-mr-rIN/strings.xml
- app/src/main/res/values-om-rET/strings.xml
- app/src/main/res/values-pa-rIN/strings.xml
- app/src/main/res/values-te-rIN/strings.xml
- app/src/main/res/values-ti-rET/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/home/overdue/OverdueAppointmentRowTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
https://www.pivotaltracker.com/story/show/170068607
> Change "Last BP" to "Last seen" in the overdue list

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
Since it's possible to have blood sugar only patient in a facility, we should start considering those patients when showing in `AllPatientsInFacilityView`
https://www.pivotaltracker.com/story/show/171720538
> Show patients with blood sugar only in `AllPatientsInFacilityView`

- doc/mobius/migrating-to-mobius.md
https://www.pivotaltracker.com/story/show/170146771
> Document the Mobius migration process

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/RecentPatient.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientScreenItemTypes.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreenController.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientItem.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsViewController.kt
- app/src/test/java/org/simple/clinic/recentpatient/RecentPatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/recentpatientsview/RecentPatientsViewControllerTest.kt
https://www.pivotaltracker.com/story/show/170068604
- Showing last seen for both BP and Blood sugars in `RecentPatientsView` and `RecentPatientsScreen`
> Change "Last BP" to "Last Seen" in Recent Patient List

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
https://www.pivotaltracker.com/story/show/170067831
> Support blood sugars for overdue high risk measurement

- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffect.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandler.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEvent.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdate.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/main/java/org/simple/clinic/sync/DataSync.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewController.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdateTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
- app/src/test/java/org/simple/clinic/sync/DataSyncTest.kt
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorViewControllerTest.kt
https://www.pivotaltracker.com/story/show/171718198
> Add alternate triggers for syncing the frequent syncs

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityListItem.kt
- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityModel.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsItemType.kt
- app/src/main/java/org/simple/clinic/widgets/PatientSearchResultItemView.kt
- app/src/main/res/layout/view_patient_search_result.xml
- app/src/main/res/values-bn-rBD/strings.xml
- app/src/main/res/values-bn-rIN/strings.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-kn-rIN/strings.xml
- app/src/main/res/values-mr-rIN/strings.xml
- app/src/main/res/values-om-rET/strings.xml
- app/src/main/res/values-pa-rIN/strings.xml
- app/src/main/res/values-te-rIN/strings.xml
- app/src/main/res/values-ti-rET/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/searchresultsview/SearchResultsItemTypeTest.kt
https://www.pivotaltracker.com/story/show/170068604
> Change "Last BP" to "Last Seen" in Search Results

- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://www.pivotaltracker.com/story/show/171762828
> Unify the conditions for checking blood pressure and blood sugar on "Back" and "Done" events in patient summary screen

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
https://www.pivotaltracker.com/story/show/170068992
> Revisit logic for scheduling an automatic appointment when the user has not scheduled one

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentRow.kt
- app/src/main/res/layout/item_overdue_list_patient.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/home/overdue/OverdueAppointmentRowTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
https://www.pivotaltracker.com/story/show/170068614
> Show diagnosis label in overdue list

- app/src/main/res/layout/item_overdue_list_patient.xml
- app/src/main/res/values/styles_v2.xml
The text styles that are used previously used are different from the new one in mockups. So I have created the new text style and updated it in overdue list item.
> Change text style to `Body2Bold` for labels in overdue

- app/src/androidTest/java/org/simple/clinic/medicalhistory/MedicalHistoryRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUi.kt
- app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUiController.kt
- app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryView.kt
- app/src/main/java/org/simple/clinic/widgets/Views.kt
- app/src/main/res/layout/medicalhistory_summary_view.xml
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/main/res/values-bn-rBD/strings.xml
- app/src/main/res/values-om-rET/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/medicalhistory/MedicalHistoryTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
- app/src/test/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUiControllerTest.kt
https://www.pivotaltracker.com/story/show/169676456
> User must select a diagnosis for a patient from the patient summary screen

- app/src/main/res/drawable/background_overdue_high_risk_label.xml
- app/src/main/res/layout/item_overdue_list_patient.xml
- app/src/main/res/values/colors_v2.xml
- app/src/main/res/values/styles_v2.xml
Updated the spacing and text styles for the overdue item to make it close to the newer design on Figma.
> Update `item_overdue_list_patient` design

- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarReading.kt
- app/src/main/java/org/simple/clinic/bloodsugar/di/BloodSugarModule.kt
- app/src/main/java/org/simple/clinic/bloodsugar/sync/BloodSugarMeasurementPayload.kt
- app/src/main/java/org/simple/clinic/bloodsugar/sync/BloodSugarSyncApi.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://www.pivotaltracker.com/story/show/169676371
> Sync HbA1c Blood Sugar

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/summary/addphone/MissingPhoneReminderRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryProfile.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/main/java/org/simple/clinic/summary/addphone/MissingPhoneReminder.kt
- app/src/main/java/org/simple/clinic/summary/addphone/MissingPhoneReminderRepository.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://www.pivotaltracker.com/story/show/171689706
> Fix: Add phone dialog gets shown when the patient has a phone number

- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageEffect.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageEffectHandler.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageScreen.kt
- app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageUpdate.kt
- app/src/test/java/org/simple/clinic/settings/changelanguage/ChangeLanguageEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/settings/changelanguage/ChangeLanguageUpdateTest.kt
https://www.pivotaltracker.com/story/show/170311998
> Pull help and progress reports again on language change

- app/src/main/java/org/simple/clinic/overdue/AppointmentModule.kt
https://www.pivotaltracker.com/story/show/171859132
> While scheduling the next visit for the patient - change the default next visit date to 28 days. 

- app/src/test/java/org/simple/clinic/security/pin/JavaHashPasswordHasher.kt
- app/src/test/java/org/simple/clinic/security/pin/PinEntryCardControllerTest.kt
- app/src/test/java/org/simple/clinic/user/resetpin/ResetUserPinTest.kt
https://www.pivotaltracker.com/story/show/171951596
> Migrate `PinEntryCardView` to Mobius #1: Stabilise the tests

- app/src/main/res/layout/screen_home.xml
https://www.pivotaltracker.com/story/show/171859083
> Truncate facility name

- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryView.kt
- app/src/main/res/drawable/ic_edit_medicine.xml
- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/171856890
> After at least one medicine is added to patient summary screen, the title of the card changes to 'Edit medicine' with an edit icon

- app/src/main/java/org/simple/clinic/addidtopatient/searchforpatient/AddIdToPatientSearchScreen.kt
- app/src/main/res/layout/screen_addidtopatientsearch.xml
- app/src/main/res/values-bn-rBD/strings.xml
- app/src/main/res/values-bn-rIN/strings.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-kn-rIN/strings.xml
- app/src/main/res/values-mr-rIN/strings.xml
- app/src/main/res/values-om-rET/strings.xml
- app/src/main/res/values-pa-rIN/strings.xml
- app/src/main/res/values-te-rIN/strings.xml
- app/src/main/res/values-ti-rET/strings.xml
- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/171856756
> Change text when - Assigning new passport to an existing patient

- app/build.gradle
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessIdMetaData.kt
- build.gradle
We had two libraries that were not supporting annotation processing.
- Room
- Moshi
I bumped them up to their latest versions and enabled it.
> Enable incremental annotation processing

- app/src/main/res/values/strings.xml
Pragati asked for this change along with facility name truncate.
> Rename "Recent Patients" string to "Recent"

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/registration/confirmfacility/ConfirmFacilitySheet.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenController.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenEvents.kt
- app/src/main/res/layout/sheet_registration_confirm_facility.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/171858938
> Alert to confirm facility selection during sign-up flow 

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/di/AppComponent.kt
- app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeComponent.kt
- app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeSheet.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityChangeActivity.kt
- app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeSheet.kt
- app/src/main/res/layout/sheet_alert_facility_change.xml
- app/src/main/res/values/strings.xml
- router/src/main/java/org/simple/clinic/router/screen/ActivityResult.kt
https://www.pivotaltracker.com/story/show/171623970
This PR adds the `AlertFacilityChangeSheet` and takes care of the navigation based on the flow. The next PR will have the implementation to show this sheet when the user switches facility.
> Alert users for facility change in patient registration

- app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeSheet.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityChangeModule.kt
- app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeEffectHandler.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsController.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
- app/src/test/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/search/results/PatientSearchResultsControllerTest.kt
https://www.pivotaltracker.com/story/show/171623970
> Show alert facility change at patient registration

- app/src/main/java/org/simple/clinic/login/LoginApi.kt
- app/src/main/java/org/simple/clinic/login/activateuser/ActivateUser.kt
- app/src/main/java/org/simple/clinic/login/activateuser/ActivateUserContract.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreen.kt
- app/src/main/java/org/simple/clinic/security/di/PinVerificationModule.kt
- app/src/main/java/org/simple/clinic/security/di/VerificationMethodKey.kt
- app/src/main/java/org/simple/clinic/security/pin/PinEntryCardView.kt
- app/src/main/java/org/simple/clinic/security/pin/PinEntryEffect.kt
- app/src/main/java/org/simple/clinic/security/pin/PinEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/security/pin/PinEntryEvent.kt
- app/src/main/java/org/simple/clinic/security/pin/PinEntryUpdate.kt
- app/src/main/java/org/simple/clinic/security/pin/UiActions.kt
- app/src/main/java/org/simple/clinic/security/pin/verification/LoginPinServerVerificationMethod.kt
- app/src/main/java/org/simple/clinic/security/pin/verification/PinVerificationMethod.kt
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/FakeCall.kt
- app/src/test/java/org/simple/clinic/login/activateuser/ActivateUserTest.kt
- app/src/test/java/org/simple/clinic/security/pin/PinEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/security/pin/PinEntryUpdateTest.kt
https://www.pivotaltracker.com/story/show/171874779
> Implement a remote PIN verification in the PIN entry component

- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreenController.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenController.kt
- app/src/test/java/org/simple/clinic/login/pin/LoginPinScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/171874779
This is required because of an upcoming change to the user login flows with respect to the ICMR security audit.
> Pull facilities earlier in the login flow

- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/java/org/simple/clinic/newentry/country/InputFieldsFactory.kt
- app/src/main/java/org/simple/clinic/newentry/form/GenderField.kt
- app/src/test/java/org/simple/clinic/newentry/form/GenderFieldTest.kt
https://www.pivotaltracker.com/story/show/169392408
> Do not show Transgender option in gender for Ethiopia

- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreen.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreenController.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreenEvents.kt
- app/src/main/java/org/simple/clinic/login/pin/UpdateLoginEntryWithEnteredPin.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/security/pin/verification/LoginPinServerVerificationMethod.kt
- app/src/main/res/layout/screen_login_pin.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/login/pin/LoginPinScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/171874779
> Change LoginPinScreen to use the remote PIN verification method

- app/src/main/java/org/simple/clinic/home/overdue/phonemask/PhoneMaskBottomSheet.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/res/layout/screen_manual_patient_entry.xml
- app/src/main/res/layout/sheet_phone_mask.xml
- app/src/main/res/values/strings.xml
Confirmed with Pragati that this feature has to be changed to accept 4 digits. So I'll skip this commit and make this change in another PR.
~https://www.pivotaltracker.com/story/show/171296031~
https://www.pivotaltracker.com/story/show/171854372
https://www.pivotaltracker.com/story/show/170942753
> Design changes and fixes

- app/src/main/java/org/simple/clinic/registration/FindUserContract.kt
- app/src/main/java/org/simple/clinic/registration/RegistrationApi.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenController.kt
- app/src/main/java/org/simple/clinic/user/finduser/FindUserResult.kt
- app/src/main/java/org/simple/clinic/user/finduser/UserLookup.kt
- app/src/main/java/org/simple/clinic/user/refreshuser/RefreshCurrentUser.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/user/finduser/UserLookupTest.kt
- app/src/test/java/org/simple/clinic/user/refreshuser/RefreshCurrentUserTest.kt
https://www.pivotaltracker.com/story/show/171874779
> Switch to the new Find User v4 api

- app/build.gradle
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/debug/AndroidManifest.xml
- app/src/debug/java/org/simple/clinic/FakeDataGenerationReceiver.kt
- app/src/debug/java/org/simple/clinic/di/DebugAppComponent.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreen.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/patient/PatientConfig.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsViewController.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- app/src/test/java/org/simple/clinic/recentpatientsview/RecentPatientsViewControllerTest.kt
- build.gradle
https://www.pivotaltracker.com/story/show/172119635
This PR also adds a way for us to generate fake data on the local device for testing.
> Fix crash when searching for a phone number with few digits

- app/src/main/java/org/simple/clinic/newentry/country/InputFieldsFactory.kt
- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/169392487
> Address model for Ethiopia

- gradle.properties
- settings.gradle
https://www.pivotaltracker.com/story/show/171592160
> Remove hardcoded Gradle build cache

- app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeSheet.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsController.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
- app/src/test/java/org/simple/clinic/search/results/PatientSearchResultsControllerTest.kt
https://www.pivotaltracker.com/story/show/169808600
> Simplify alerting users for facility change 

- app/schemas/org.simple.clinic.AppDatabase/63.json
- app/src/androidTest/java/org/simple/clinic/SqliteHelperFunctions.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration63AndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_63.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
https://www.pivotaltracker.com/story/show/172194221
> Add method to check if patient is overdue

- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEvent.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntrySheet.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUi.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUpdate.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEvent.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryModel.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheet.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryUi.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryUpdate.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryLogicTest.kt
https://www.pivotaltracker.com/story/show/171296031
> Change date and message to be DD/MM/YYYY everywhere

- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryModel.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUpdate.kt
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUpdateTest.kt
https://www.pivotaltracker.com/story/show/171296031
> Fix blood sugar entry error with 4 digit years

- app/src/main/java/org/simple/clinic/reports/ReportsSync.kt
https://www.pivotaltracker.com/story/show/171687005
> Sync Progress tab every 15 minutes (instead of daily)

- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt
- app/src/main/java/org/simple/clinic/widgets/ThreeTenBpDatePickerDialog.kt
https://www.pivotaltracker.com/story/show/172194296
> Add custom `DatePickerDialog` subclass that works with threetenbp

- app/src/main/java/org/simple/clinic/patientcontact/PatientContactEffect.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactEffectHandler.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactEvent.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactInit.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactModel.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactUi.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactUiRenderer.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactUpdate.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
- app/src/test/java/org/simple/clinic/patientcontact/PatientContactEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/patientcontact/PatientContactInitTest.kt
- app/src/test/java/org/simple/clinic/patientcontact/PatientContactUiRendererTest.kt
- app/src/test/java/org/simple/clinic/patientcontact/PatientContactUpdateTest.kt
https://www.pivotaltracker.com/story/show/172194270
This PR does not include the UI. This sets up the Mobius classes and adds some of the business logic and presentation logic.
> Implement initial logic for the call patient view

- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentRow.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreenController.kt
- app/src/main/res/layout/item_overdue_list_patient.xml
- app/src/test/java/org/simple/clinic/home/overdue/OverdueAppointmentRowTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/172258478
> Show diagnosis label only if diabetes management is enabled

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentScreenController.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/test/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentScreenControllerTest.kt
This was done as part of https://www.pivotaltracker.com/story/show/172194352
Breaking it out to parallelize reviews.
> Change calls in appointment repository and patient repository to be blocking calls

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/di/AppComponent.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentCancelReason.kt
- app/src/main/java/org/simple/clinic/patient/PatientProfile.kt
- app/src/main/java/org/simple/clinic/patientcontact/CallPatientView.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactBottomSheet.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactEffect.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactEffectHandler.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactEvent.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactModel.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactUiActions.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactUiRenderer.kt
- app/src/main/java/org/simple/clinic/patientcontact/PatientContactUpdate.kt
- app/src/main/java/org/simple/clinic/patientcontact/di/PatientContactBottomSheetComponent.kt
- app/src/main/res/drawable/ic_radio_button_unchecked_red1_24dp.xml
- app/src/main/res/layout/patientcontact_view_callpatient.xml
- app/src/main/res/layout/sheet_patientcontact.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_v2.xml
- app/src/test/java/org/simple/clinic/patientcontact/PatientContactEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/patientcontact/PatientContactUpdateTest.kt
https://www.pivotaltracker.com/story/show/172194270
This PR still doesn't trigger the UI, this will be in the next PR.
> Implement the Call patient UI

- app/src/test/java/org/simple/clinic/drugs/selection/PrescribedDrugsScreenControllerTest.kt
Pivotal story -> https://www.pivotaltracker.com/story/show/172145024
This PR covers Step 1 (Stabilize) of Mobius migration for `PrescribedDrugsScreenController`.
> `PrescribedDrugsScreenController` test refactor

- app/src/main/java/org/simple/clinic/appupdate/AppUpdateState.kt
- app/src/main/java/org/simple/clinic/appupdate/CheckAppUpdateAvailability.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/settings/AppVersionFetcher.kt
- app/src/main/java/org/simple/clinic/settings/SettingsEffect.kt
- app/src/main/java/org/simple/clinic/settings/SettingsEffectHandler.kt
- app/src/main/java/org/simple/clinic/settings/SettingsEvent.kt
- app/src/main/java/org/simple/clinic/settings/SettingsInit.kt
- app/src/main/java/org/simple/clinic/settings/SettingsModel.kt
- app/src/main/java/org/simple/clinic/settings/SettingsScreen.kt
- app/src/main/java/org/simple/clinic/settings/SettingsUi.kt
- app/src/main/java/org/simple/clinic/settings/SettingsUiRenderer.kt
- app/src/main/java/org/simple/clinic/settings/SettingsUpdate.kt
- app/src/main/res/drawable/ic_app_update_24dp.xml
- app/src/main/res/layout/screen_settings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/settings/SettingsEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/settings/SettingsInitTest.kt
- app/src/test/java/org/simple/clinic/settings/SettingsUiRendererTest.kt
- app/src/test/java/org/simple/clinic/settings/SettingsUpdateTest.kt
https://www.pivotaltracker.com/story/show/168804289
> Display the current app version in the settings screen

- .github/workflows/ci_checks.yml
https://www.pivotaltracker.com/story/show/172448351
> Verify PR description contains pivotal story

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreenController.kt
- app/src/main/java/org/simple/clinic/home/overdue/appointmentreminder/AppointmentReminderSheetController.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/appointmentreminder/AppointmentReminderSheetControllerTest.kt
This was done as a part of https://www.pivotaltracker.com/story/show/172194296
Breaking it out to parallelize reviews.
> Change Rx calls to blocking calls in Appointment repository

- .github/scripts/compare_directory_contents.sh
- .github/scripts/verify_file_was_changed.sh
- .github/workflows/ci_checks.yml
- CHANGELOG.md
https://www.pivotaltracker.com/story/show/172448348
> Add CI check for verifying that the CHANGELOG was updated

- .github/workflows/ci_checks.yml
This will fix the check fails if we use back ticks in the PR description
https://www.pivotaltracker.com/story/show/172448351
> Fix PR description CI check

- app/src/main/java/org/simple/clinic/drugs/EditMedicinesEffect.kt
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesEffectHandler.kt
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesEvent.kt
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesInit.kt
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesModel.kt
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesUiRenderer.kt
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesUpdate.kt
- app/src/main/java/org/simple/clinic/drugs/selection/AddNewPrescriptionListItem.kt
- app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesUiActions.kt
- app/src/main/java/org/simple/clinic/drugs/selection/PrescribedDrugEvents.kt
- app/src/main/java/org/simple/clinic/drugs/selection/PrescribedDrugScreen.kt
- app/src/main/java/org/simple/clinic/drugs/selection/PrescribedDrugUi.kt
- app/src/main/java/org/simple/clinic/drugs/selection/PrescribedDrugsScreenController.kt
- app/src/test/java/org/simple/clinic/drugs/selection/PrescribedDrugsScreenControllerTest.kt
- doc/mobius/migrating-to-mobius.md
https://www.pivotaltracker.com/story/show/172145024
Strangulate controller to move `showNewPrescriptionEntrySheet`.
> Prescribed drugs controller strangulate

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/64.json
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration64AndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_64.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
https://www.pivotaltracker.com/story/show/172448343
> Use database view for `PatientSearchResult`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/search/PatientSearchScreen.kt
https://www.pivotaltracker.com/story/show/172092404
> Error when you search without providing any input

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientModel.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentConfig.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentModule.kt
- app/src/main/java/org/simple/clinic/overdue/PotentialAppointmentDate.kt
- app/src/main/java/org/simple/clinic/overdue/TimeToAppointment.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetController.kt
- app/src/main/java/org/simple/clinic/util/TimeFunctions.kt
- app/src/test/java/org/simple/clinic/contactpatient/ContactPatientInitTest.kt
- app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUiRendererTest.kt
- app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUpdateTest.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetControllerTest.kt
This is part of https://www.pivotaltracker.com/story/show/172194296
It adds the list of potential appointment reminder dates to the `ContactPatientModel`.
> Add potential appointment reminder dates to the contact patient model

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/contactpatient/CallPatientView.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffect.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffectHandler.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEvent.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientModel.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUi.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiActions.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiRenderer.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUpdate.kt
- app/src/main/java/org/simple/clinic/util/TimeFunctions.kt
- app/src/test/java/org/simple/clinic/contactpatient/ContactPatientEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUiRendererTest.kt
- app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUpdateTest.kt
https://www.pivotaltracker.com/story/show/172194296
> Implement the mobius loop for the set appointment reminder view

- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryController.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryEvents.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntrySheet.kt
- app/src/test/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryControllerTest.kt
https://www.pivotaltracker.com/story/show/172531165
> Stabilize tests for `CustomPrescriptionEntryController`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffect.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEvent.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientInit.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientUi.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientUpdate.kt
- app/src/main/res/layout/patient_edit_bp_passport_view.xml
- app/src/main/res/layout/screen_edit_patient.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/editpatient/EditPatientEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenCreatedTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenFormTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenSaveTest.kt
https://www.pivotaltracker.com/story/show/171292061
This PR is only showing the list of all BP passports in patient edit screen without the add BP passport button.
> Show all BP passports in patient edit screen

- .github/scripts/strings_reader.py
- .github/workflows/ci_checks.yml
- CHANGELOG.md
https://www.pivotaltracker.com/story/show/172579029
> CI check to fix android ellipsis

- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryController.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryEffect.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryEvent.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryInit.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryModel.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntrySheet.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryUi.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryUiActions.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryUiRenderer.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryUpdate.kt
- app/src/test/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryControllerTest.kt
https://www.pivotaltracker.com/story/show/172531165
> Strangulate custom prescription sheet

- .github/scripts/amend_and_push.sh
- .github/scripts/strings_reader.py
- .github/workflows/ci_checks.yml
https://www.pivotaltracker.com/story/show/172579029
> Fix `fix_strings_ellipsise` CI check

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffect.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffectHandler.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEvent.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientModel.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUi.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiRenderer.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUpdate.kt
- app/src/main/java/org/simple/clinic/contactpatient/RemoveAppointmentReason.kt
- app/src/main/java/org/simple/clinic/contactpatient/UiMode.kt
- app/src/test/java/org/simple/clinic/contactpatient/ContactPatientEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/contactpatient/ContactPatientRemoveAppointmentUiRendererTest.kt
- app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUpdateTest.kt
- app/src/test/java/org/simple/clinic/contactpatient/SetAppointmentReminderUiRendererTest.kt
https://www.pivotaltracker.com/story/show/172194352
> Business logic for remove appointment view from the contact patient screen

- CHANGELOG.md
- app/src/main/res/values-hi-rIN/strings.xml
translation completed for the source file '/app/src/main/res/values/strings.xml'
on the 'hi_IN' language.
> Apply translations in hi_IN

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEvent.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUpdate.kt
- app/src/main/java/org/simple/clinic/contactpatient/RemoveAppointmentReason.kt
- app/src/main/java/org/simple/clinic/contactpatient/views/RemoveAppointmentReasonItem.kt
- app/src/main/java/org/simple/clinic/contactpatient/views/RemoveAppointmentView.kt
- app/src/main/java/org/simple/clinic/contactpatient/views/SetAppointmentReminderView.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryConfig.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/res/drawable/ic_call_9dp.xml
- app/src/main/res/drawable/ic_summary_call_icon.xml
- app/src/main/res/layout/contactpatient_removeappointment.xml
- app/src/main/res/layout/contactpatient_removeappointment_reasonitem.xml
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/main/res/layout/sheet_contact_patient.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUpdateTest.kt
- quality/lint.xml
https://www.pivotaltracker.com/story/show/172194352
This PR completes the feature to contact the patient from the summary screen.
> UI implementation for the "Remove from overdue list" part of the contact patient sheet

- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/169392487
> Change string `patiententry_kebele` value to Kebele

- CHANGELOG.md
- app/build.gradle
- app/src/main/java/org/simple/clinic/navigation/BackStackEntry.kt
- app/src/main/java/org/simple/clinic/navigation/ScreenHostView.kt
- app/src/main/java/org/simple/clinic/navigation/ScreenNavigator.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingScreen.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryScreen.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivity.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityComponent.kt
- app/src/main/res/layout/activity_setup.xml
- app/src/main/res/layout/fragment_screen_host.xml
- app/src/main/res/navigation/setup_activity_nav_graph.xml
- app/src/main/res/values/attrs.xml
- build.gradle
https://www.pivotaltracker.com/story/show/172448374
This PR will replace screen router usage with navigation component in `SetupActivity`
> Replace flow with navigation component

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/65.json
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration65AndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/facility/FacilityConfig.kt
- app/src/main/java/org/simple/clinic/facility/FacilityPayload.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_65.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/main/java/org/simple/clinic/user/User.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://www.pivotaltracker.com/story/show/172667342
> Add teleconsultation fields to the facility model

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/drugs/selection/dosage/DosageListItem.kt
- app/src/main/java/org/simple/clinic/drugs/selection/dosage/DosageOption.kt
- app/src/main/java/org/simple/clinic/drugs/selection/dosage/DosagePickerEffectHandler.kt
- app/src/main/java/org/simple/clinic/drugs/selection/dosage/DosagePickerEvents.kt
- app/src/main/java/org/simple/clinic/drugs/selection/dosage/DosagePickerSheet.kt
- app/src/main/java/org/simple/clinic/drugs/selection/dosage/DosagePickerUiRenderer.kt
- app/src/test/java/org/simple/clinic/drugs/selection/DosagePickerSheetLogicTest.kt
https://www.pivotaltracker.com/story/show/172669407
> Clean up `DosagePickerSheet`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescribedDrugListItem.kt
https://www.pivotaltracker.com/story/show/172784091
> Fix clicks on custom prescription when editing medicines

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesEffectHandler.kt
- app/src/main/java/org/simple/clinic/user/SessionModule.kt
- app/src/test/java/org/simple/clinic/drugs/selection/EditMedicinesScreenLogicTest.kt
https://www.pivotaltracker.com/story/show/172668123
> Lazy inject current user and facility

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetControllerTest.kt
> Migrate `ScheduleAppointmentSheet` to Mobius - Stabilize tests

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryConfig.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/main/java/org/simple/clinic/summary/PatientTeleconsultationInfo.kt
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://www.pivotaltracker.com/story/show/172667700
I have re-ordered couple of commits, so please check out the branch when reviewing.
> User should be able to consult a doctor remotely from the patient summary screen #1

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffect.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffectHandler.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEvent.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEvents.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentInit.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentModel.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetController.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUi.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUiRenderer.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUpdate.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetControllerTest.kt
> Migrate schedule appointment sheet to Mobius: Prepare controller

- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/drugs/selection/dosage/DosagePickerEffectHandler.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeEffectHandler.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandler.kt
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/DosagePickerSheetLogicTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryLogicTest.kt
- app/src/test/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenLogicTest.kt
https://www.pivotaltracker.com/story/show/172668123
> Inject user and facility in `EffectHandler`s

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetController.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetControllerTest.kt
> Migrate schedule appointment sheet to Mobius: Strangulate controller #1

- CHANGELOG.md
- app/src/debug/java/org/simple/clinic/FakeDataGenerationReceiver.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryEffectHandler.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryLogicTest.kt
https://www.pivotaltracker.com/story/show/172668123
Final PR to inject `user` and `facility` in already migrated(to Mobius) screens.
> Inject `facility` and `user` in `EffectHandler` - Part 2

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetController.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetControllerTest.kt
https://www.pivotaltracker.com/story/show/172909030
> Fix crash when loading the facility in `ScheduleAppointmentSheet`

- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryInit.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryInitTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://www.pivotaltracker.com/story/show/172667700
Addressing feedback that's left from this [PR](https://github.com/simpledotorg/simple-android/pull/1321).
> User should be able to consult a doctor remotely from the patient summary screen #3

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/protocol/ProtocolRepository.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffect.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffectHandler.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEvent.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEvents.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentInit.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentModel.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetController.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUiRenderer.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUpdate.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetControllerTest.kt
- mobius-base/src/main/java/org/simple/clinic/mobius/MobiusDelegate.kt
> Migrate schedule appointment sheet to Mobius: Strangulate controller #2

- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewController.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewEvents.kt
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorViewControllerTest.kt
> Stabilize tests in `SyncIndicatorViewController`

- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEffect.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEffectHandler.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEvent.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorInit.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorModel.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorUi.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorUiActions.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorUiRenderer.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorUpdate.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewController.kt
- app/src/main/res/layout/sync_indicator.xml
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorViewControllerTest.kt
> Prepare `SyncIndicatorController` for migration

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/widgets/qrcodescanner/QrCodeScannerView.kt
- app/src/main/java/org/simple/clinic/widgets/qrcodescanner/ZxingQrCodeAnalyzer.kt
https://www.pivotaltracker.com/story/show/172667903
> Shutdown camera executor when screen is detached

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/66.json
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration66AndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentRow.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverduePatientAddress.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_66.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/main/res/layout/item_overdue_list_patient.xml
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueAppointmentRowTest.kt
https://www.pivotaltracker.com/story/show/172931419
> Show patient address in overdue list

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffect.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffectHandler.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUpdate.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentLogicTest.kt
> Migrate schedule appointment sheet to Mobius: Final cleanup

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/67.json
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration67AndroidTest.kt
- app/src/debug/java/org/simple/clinic/FakeDataGenerationReceiver.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt
- app/src/main/java/org/simple/clinic/patient/DeletedReason.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientSync.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_67.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
- app/src/sharedTest/java/org/simple/clinic/util/TestFunctions.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
https://www.pivotaltracker.com/story/show/172955500
> Add `DeletedReason` for `Patient`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/user/User.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/sharedTest/java/org/simple/clinic/util/TestClocks.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/172953157
> Migrate Patients Screen to Mobius: Stabilise tests

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/patients/PatientsEffect.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsEvent.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsInit.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsModel.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreen.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsUi.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsUiRenderer.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsUpdate.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
- doc/mobius/migrating-to-mobius.md
https://www.pivotaltracker.com/story/show/172953157
> Migrate Patients screen to Mobius: prepare controller for strangulation

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/editpatient/deletepatient/DeletePatientEffect.kt
- app/src/main/java/org/simple/clinic/editpatient/deletepatient/DeletePatientEffectHandler.kt
- app/src/main/java/org/simple/clinic/editpatient/deletepatient/DeletePatientEvent.kt
- app/src/main/java/org/simple/clinic/editpatient/deletepatient/DeletePatientModel.kt
- app/src/main/java/org/simple/clinic/editpatient/deletepatient/DeletePatientUpdate.kt
- app/src/main/java/org/simple/clinic/editpatient/deletepatient/PatientDeleteReason.kt
- app/src/main/java/org/simple/clinic/editpatient/deletepatient/UiActions.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
- app/src/test/java/org/simple/clinic/editpatient/deletepatient/DeletePatientEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/editpatient/deletepatient/DeletePatientUpdateTest.kt
https://www.pivotaltracker.com/story/show/172955460
> Users can soft delete patients #1

- .codeclimate.yml
- CHANGELOG.md
- Enabled checks for max arguments to a function
- Reduced threshold for method complexity to 5 from 15
- Reduced max allowed nested control flow to 1
> Tighten Code Climate checks

- .codeclimate.yml
Complexity of 5 seemed to be too much for now.
Assigning to @sanchita since your PR is blocked on this.
> Change max allowed method complexity to 10

- app/src/main/java/org/simple/clinic/sync/LastSyncedState.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEffect.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEffectHandler.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEvent.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorInit.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorModel.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorState.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorUiRenderer.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorUpdate.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewController.kt
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorViewControllerTest.kt
> Migrate `SyncIndicatorController.updateState` to Mobius

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/patients/PatientsEffect.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsEvent.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsInit.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsModel.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreen.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenEvents.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsUi.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsUiActions.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsUpdate.kt
- app/src/main/java/org/simple/clinic/user/User.kt
- app/src/main/java/org/simple/clinic/user/UserStatus.kt
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/172953157
> Migrate Patients screen to Mobius: strangulate controller #1

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarRepository.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/facility/Facility.kt
- app/src/main/java/org/simple/clinic/facility/FacilityRepository.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/protocol/Protocol.kt
- app/src/main/java/org/simple/clinic/protocol/ProtocolRepository.kt
- app/src/main/java/org/simple/clinic/sync/SynceableRepository.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEffect.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEffectHandler.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEvent.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorInit.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorUiRenderer.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorUpdate.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewController.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewEvents.kt
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorViewControllerTest.kt
This PR completes the controller migration. There will be one more PR that will cover clean-up.
> Migrate Sync indicator controller to Mobius #2

- app/src/main/java/org/simple/clinic/editpatient/deletepatient/DeletePatientScreen.kt
https://www.pivotaltracker.com/story/show/172955460
> Users can soft delete patients - Final

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarRepository.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/facility/Facility.kt
- app/src/main/java/org/simple/clinic/facility/FacilityRepository.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/protocol/Protocol.kt
- app/src/main/java/org/simple/clinic/protocol/ProtocolRepository.kt
- app/src/main/java/org/simple/clinic/sync/SynceableRepository.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEffect.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEffectHandler.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEvent.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorInit.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorUpdate.kt
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorViewControllerTest.kt
> Fix showing pending sync in indicator

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientConfig.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
https://www.pivotaltracker.com/story/show/172955460
Tested on `QA` build and sync is working correctly. This feature should be deployed `SBX` server by the end of today or tomorrow morning.
> Fix delete patient sync

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarReading.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/adapter/BloodSugarHistoryListItem.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarItemView.kt
https://www.pivotaltracker.com/story/show/173163349
> Add "Low" label for Blood Sugars

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureHistoryListItemDataSourceTest.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureHistoryListItemDataSource.kt
- app/src/main/java/org/simple/clinic/bp/history/adapter/BloodPressureHistoryListItem.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureItemView.kt
https://www.pivotaltracker.com/story/show/173168583
> Add "Low" label for Blood Pressures

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureHistoryListItemDataSourceTest.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureHistoryListItemDataSource.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureLevel.kt
- app/src/main/java/org/simple/clinic/bp/history/adapter/BloodPressureHistoryListItem.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureItemView.kt
https://www.pivotaltracker.com/story/show/173188293
> Fix blood pressure "High" label displaying when blood pressure is low.

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/teleconsultation/api/TeleconsultPhoneNumber.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/api/TeleconsultationsResponse.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://www.pivotaltracker.com/story/show/173188639
> Support receiving multiple teleconsultation phone numbers

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandler.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewController.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenCreatedTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenFormTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenSaveTest.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewControllerTest.kt
https://www.pivotaltracker.com/story/show/173100992
> Extract generation of UUIDs to a separate class #2

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/173144564
**Note:** The commits show up in the wrong order in the GitHub UI because of re-ordering. Please view them locally to see the actual order.
> Migrate registration phone screen to Mobius: Stabilize controller tests

- CHANGELOG.md
- app/build.gradle
- build.gradle
This is in preparation for #1381.
> Add support for Java 8 desugaring

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffect.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEvent.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneInit.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneModel.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenController.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUi.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUiActions.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUpdate.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/173144564
> Migrate registration phone entry to Mobius: prepare controller

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffect.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEvent.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneInit.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneModel.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenController.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenEvents.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUi.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUiActions.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUpdate.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneValidationResult.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationResult.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationUiMode.kt
- app/src/main/java/org/simple/clinic/user/OngoingRegistrationEntry.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/173144564
> Migrate registration phone entry screen to Mobius - strangulate controller #1

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffect.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEvent.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneInit.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneModel.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenController.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUi.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUiActions.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUpdate.kt
- app/src/main/java/org/simple/clinic/util/ValueChangedCallback.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/173144564
The last commit in this PR is pretty large. There was no way for me to migrate atomically without significant work. I am open to pairing on the review if the reviewer has trouble following what is happening.
> Migrate Registration phone entry to Mobius: strangulate #2

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreen.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureSummaryView.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarSummaryView.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryView.kt
- app/src/main/java/org/simple/clinic/util/AndroidExtensions.kt
https://www.pivotaltracker.com/story/show/173282881
> Create extension for extracting intent data from `ActivityResult`

- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarReading.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/adapter/BloodSugarHistoryListItem.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarItemView.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/TeleconsultationMessageBuilder.kt
- app/src/main/res/values-am-rET/strings.xml
- app/src/main/res/values-bn-rBD/strings.xml
- app/src/main/res/values-bn-rIN/strings.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-kn-rIN/strings.xml
- app/src/main/res/values-mr-rIN/strings.xml
- app/src/main/res/values-om-rET/strings.xml
- app/src/main/res/values-pa-rIN/strings.xml
- app/src/main/res/values-te-rIN/strings.xml
- app/src/main/res/values-ti-rET/strings.xml
- app/src/main/res/values/strings.xml
https://www.pivotaltracker.com/story/show/173242299
> Move blood sugar reading type and unit string to `BloodSugarReading`

- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt
https://www.pivotaltracker.com/story/show/173326632
> Fix bug where country ISD code would not be displayed when signing in

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/registration/name/RegistrationFullNameScreenController.kt
- app/src/main/java/org/simple/clinic/user/OngoingRegistrationEntry.kt
- app/src/test/java/org/simple/clinic/registration/name/RegistrationFullNameScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/173216658
> Migrate registration name entry screen to Mobius: Stabilize tests

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/registration/name/RegistrationFullNameScreen.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationFullNameScreenController.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameEffect.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameEvent.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameInit.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameModel.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameScreenKey.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameUi.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameUiActions.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameUpdate.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffect.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUiActions.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUpdate.kt
- app/src/test/java/org/simple/clinic/registration/name/RegistrationFullNameScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenLogicTest.kt
https://www.pivotaltracker.com/story/show/173216658
> Migrate registration name entry screen to Mobius: Prepare controller for migration

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/registration/name/RegistrationFullNameScreenController.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameEffect.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameEvent.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameInit.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameModel.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameScreenEvents.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameUi.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameUiActions.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameUpdate.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameValidationResult.kt
- app/src/test/java/org/simple/clinic/registration/name/RegistrationFullNameScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/173216658
> Migrate registration name screen to Mobius: Strangulate controller

- app/src/main/res/layout/screen_onboarding.xml
https://www.pivotaltracker.com/n/projects/2358313/stories/173030066
> Update background colour in `OnboardingScreen` to white

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/HomeScreen.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenController.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/res/layout/screen_home.xml
- app/src/main/res/values/styles_v2.xml
- app/src/test/java/org/simple/clinic/home/HomeScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/172931754
> Show total overdue patients count in tabs

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/user/OngoingRegistrationEntry.kt
- app/src/test/java/org/simple/clinic/registration/pin/RegistrationPinScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/173283121
> Migrate registration PIN entry to Mobius: Sterilize tests

- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinEffect.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinEvent.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinInit.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinModel.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreen.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreenController.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinUi.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinUiActions.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinUpdate.kt
- app/src/test/java/org/simple/clinic/registration/pin/RegistrationPinScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/173283121
> Migrate registration PIN screen to Mobius: Prepare controller for migration

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesScreen.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryEffect.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntrySheet.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryUpdate.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/OpenAs.kt
- app/src/test/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryInitTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryLogicTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryUpdateTest.kt
https://www.pivotaltracker.com/story/show/173464722
> Make non-protocol drugs immutable

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityChangeActivity.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityChangeActivityController.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt
- app/src/main/java/org/simple/clinic/location/LocationUpdate.kt
- app/src/main/java/org/simple/clinic/location/ScreenLocationUpdates.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenController.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenEvents.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreen.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/facilityselection/FacilitySelectionActivity.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/facilityselection/FacilitySelectionActivityController.kt
- app/src/main/java/org/simple/clinic/util/RuntimePermissions.kt
- app/src/main/java/org/simple/clinic/util/RxFoo.kt
- app/src/test/java/org/simple/clinic/facility/change/FacilityChangeActivityControllerTest.kt
- app/src/test/java/org/simple/clinic/location/ScreenLocationUpdatesTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/facilityselection/FacilitySelectionActivityControllerTest.kt
- app/src/test/java/org/simple/clinic/util/RequestPermissionsTest.kt
- app/src/test/java/org/simple/clinic/util/scheduler/TestSchedulersProvider.kt
- app/src/test/java/org/simple/clinic/util/scheduler/TrampolineSchedulersProvider.kt
This is being done in preparation for https://www.pivotaltracker.com/story/show/173443647
> Clean up location updates in facility selection screens

- CHANGELOG.md
- app/src/main/res/drawable/ic_summary_call_icon.xml
- app/src/main/res/drawable/overdue_call_button_background.xml
- app/src/main/res/layout/contactpatient_callpatient.xml
- app/src/main/res/values/styles_v2.xml
https://www.pivotaltracker.com/story/show/173443143
> Change all 'normal call' buttons in the app from green to blue

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesModel.kt
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesUiRenderer.kt
- app/src/main/java/org/simple/clinic/protocol/ProtocolDrugAndDosages.kt
- app/src/test/java/org/simple/clinic/drugs/EditMedicinesUiRendererTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/EditMedicinesScreenLogicTest.kt
https://www.pivotaltracker.com/story/show/172974575
> Prescription created from a protocol drug is not shown in the "Edit Medicines" screen if the drug is no longer in the protocol

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/Globals.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreen.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreenController.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationFullNameScreen.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameEffect.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameUiActions.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameUpdate.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinEffect.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinEvent.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinModel.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreen.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreenController.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreenEvents.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreenKey.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinUi.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinUiActions.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinUpdate.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinValidationResult.kt
- app/src/test/java/org/simple/clinic/registration/name/RegistrationNameScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/registration/pin/RegistrationPinScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/173283121
> Migrate Registration PIN screen to Mobius: Strangulate the controller

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemovePrescriptionDialogEvents.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/confirmremovedialog/ConfirmRemovePrescriptionDialog.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/confirmremovedialog/ConfirmRemovePrescriptionDialogController.kt
- app/src/test/java/org/simple/clinic/drugs/selection/entry/confirmremovedialog/ConfirmRemovePrescriptionDialogControllerTest.kt
https://www.pivotaltracker.com/story/show/173527048
> Migrate confirm remove prescription dialog to Mobius : Stabilize tests

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreen.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreenController.kt
- app/src/test/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/173391366
> Migrate registration PIN entry screen to Mobius: Stabilize tests

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinEffect.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinEvent.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinInit.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinModel.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreen.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreenController.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreenKey.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinUi.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinUiActions.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinUpdate.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinEffect.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreen.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinUiActions.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinUpdate.kt
- app/src/test/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/registration/pin/RegistrationPinScreenLogicTest.kt
https://www.pivotaltracker.com/story/show/173391366
> Migrate registration confirm PIN screen to Mobius: Prepare the controller

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/drugs/selection/entry/confirmremovedialog/ConfirmRemovePrescriptionDialog.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/confirmremovedialog/ConfirmRemovePrescriptionDialogController.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/confirmremovedialog/ConfirmRemovePrescriptionDialogEffect.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/confirmremovedialog/ConfirmRemovePrescriptionDialogEffectHandler.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/confirmremovedialog/ConfirmRemovePrescriptionDialogEvent.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/confirmremovedialog/ConfirmRemovePrescriptionDialogModel.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/confirmremovedialog/ConfirmRemovePrescriptionDialogUpdate.kt
- app/src/main/java/org/simple/clinic/drugs/selection/entry/confirmremovedialog/UiActions.kt
- app/src/test/java/org/simple/clinic/drugs/selection/entry/confirmremovedialog/ConfirmRemovePrescriptionDialogControllerTest.kt
https://www.pivotaltracker.com/story/show/173527048
> Migrate confirm remove prescription dialog to Mobius : Prepare controller

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/settings/SettingsModule.kt
https://www.pivotaltracker.com/story/show/173219253
> Add Amharic translation

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinEffect.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinEvent.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinModel.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreen.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreenController.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreenEvents.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinUi.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinUiActions.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinUpdate.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinValidationResult.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreen.kt
- app/src/main/java/org/simple/clinic/user/OngoingRegistrationEntry.kt
- app/src/test/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreenControllerTest.kt
- router/src/main/java/org/simple/clinic/router/screen/ScreenRouter.kt
https://www.pivotaltracker.com/story/show/173391366
> Migrate registration confirm PIN to Mobius: Strangulate controller

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/173654521
> Migrate registration location permission screen to Mobius - Stabilise Tests

- app/src/main/java/org/simple/clinic/setup/SetupActivity.kt
- build.gradle
- Added checks to verify if the current screen is `placeHolderScreen` in `SetupActivity`
> Bump navigation component

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionEffect.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionEvent.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionInit.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionModel.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreen.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreenController.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionUi.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionUiActions.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionUpdate.kt
- app/src/test/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/231/migrate-registration-location-permission-screen-to-mobius
> Migrate registration location permission screen to Mobius: Prepare controller for migration

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/69.json
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration69AndroidTest.kt
- app/src/debug/java/org/simple/clinic/FakeDataGenerationReceiver.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientSync.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_69.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
https://app.clubhouse.io/simpledotorg/story/210/add-registration-facility-id-and-assigned-facility-id-to-the-patient-model
> Add `registration_facility_id` and `assigned_facility_id`

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/home/report/ReportsScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/342/migrate-reports-screen-to-mobius
> Migrate reports screen to Mobius - Stablize tests

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/recentpatientsview/RecentPatientsViewControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/311/migrate-recent-patients-view-to-mobius
> Migrate recent patients view to Mobius: Stabilise tests

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialog.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialogController.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialogEvents.kt
- app/src/test/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialogControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/347/migrate-add-phone-number-dialog-to-mobius
> Migrate add phone number dialog to Mobius - Stabilize

- CHANGELOG.md
- app/build.gradle
https://app.clubhouse.io/simpledotorg/story/364/fix-vectordrawable-native-crash
> Enable vector drawable support library flag in gradle

- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsEffect.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsEffectHandler.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsEvent.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsInit.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsModel.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsUi.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsUiActions.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsUiRenderer.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsUpdate.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsView.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsViewController.kt
- app/src/test/java/org/simple/clinic/recentpatientsview/RecentPatientsViewControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/311/migrate-recent-patients-view-to-mobius
> Migrate recent patients view to Mobius: Prepare controller for migration

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionEffect.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionEvent.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionInit.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionModel.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenController.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionUi.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionUiActions.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionUpdate.kt
- app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/237/migrate-registration-facility-selection-screen-to-mobius
> Migrate registration facility selection screen to Mobius: Prepare controller

- app/src/main/java/org/simple/clinic/home/report/ReportsEffect.kt
- app/src/main/java/org/simple/clinic/home/report/ReportsEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/report/ReportsEvent.kt
- app/src/main/java/org/simple/clinic/home/report/ReportsInit.kt
- app/src/main/java/org/simple/clinic/home/report/ReportsModel.kt
- app/src/main/java/org/simple/clinic/home/report/ReportsScreen.kt
- app/src/main/java/org/simple/clinic/home/report/ReportsScreenController.kt
- app/src/main/java/org/simple/clinic/home/report/ReportsUi.kt
- app/src/main/java/org/simple/clinic/home/report/ReportsUiRenderer.kt
- app/src/main/java/org/simple/clinic/home/report/ReportsUpdate.kt
- app/src/test/java/org/simple/clinic/home/report/ReportsScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/342/migrate-reports-screen-to-mobius
> Migrate reports screen to Mobius - Prepare controller

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/registration/phone/PhoneNumberValidator.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialog.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialogController.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialogEvents.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberEffect.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberEvent.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberModel.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberUi.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberUiRender.kt
- app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberUpdate.kt
- app/src/main/java/org/simple/clinic/summary/addphone/UiActions.kt
- app/src/test/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialogControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/347/migrate-add-phone-number-dialog-to-mobius
> Migrate add phone number dialog to Mobius - Strangulate

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/patient/RecentPatient.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsEffect.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsEffectHandler.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsEvent.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsInit.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsModel.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsUi.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsUiActions.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsUiRenderer.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsUpdate.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientEvents.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsView.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsViewController.kt
- app/src/test/java/org/simple/clinic/recentpatientsview/RecentPatientsViewControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/311/migrate-recent-patients-view-to-mobius
> Migrate recent patients view to Mobius: Strangulate controller

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/login/pin/LoginPinScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/407/migrate-login-pin-screen-to-mobius
> Migrate login pin screen to Mobius - Stabilise tests

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/recentpatient/RecentPatientsScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/331/migrate-all-recent-patients-screen-to-mobius
> Migrate recent patients screen to Mobius: Stabilize tests

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/registration/register/RegistrationLoadingScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/246/migrate-complete-registration-screen-to-mobius
> Migrate registration loading screen to Mobius: Stabilize tests

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffect.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffectHandler.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEvent.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentInit.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUpdate.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/217/appointment-should-be-scheduled-by-default-at-the-patient-s-assigned-facility
> Appointment should be scheduled by default at the patient's assigned facility

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingEffect.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingEvent.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingInit.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingModel.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingScreen.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingScreenController.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingUi.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingUiActions.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingUpdate.kt
- app/src/test/java/org/simple/clinic/registration/register/RegistrationLoadingScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/246/migrate-complete-registration-screen-to-mobius
> Migrate registration loading screen to Mobius: prepare screen for migration

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsEffect.kt
- app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsEffectHandler.kt
- app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsEvent.kt
- app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsInit.kt
- app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsModel.kt
- app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsUi.kt
- app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsUiActions.kt
- app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsUiRenderer.kt
- app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsUpdate.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreen.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreenController.kt
- app/src/main/res/layout/recent_patients_screen.xml
- app/src/test/java/org/simple/clinic/recentpatient/RecentPatientsScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/331/migrate-all-recent-patients-screen-to-mobius
> Migrate recent patients screen to Mobius: Prepare screen for migration

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/facility/Facility.kt
https://app.clubhouse.io/simpledotorg/story/475/exclude-deleted-facilities-from-facility-selection-sheets
> Exclude deleted facilities from facility selection sheets

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/registration/register/RegisterUserResult.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingEffect.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingEvent.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingInit.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingModel.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingScreenController.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingScreenEvents.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingUi.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingUiActions.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingUpdate.kt
- app/src/test/java/org/simple/clinic/registration/register/RegistrationLoadingScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/246/migrate-complete-registration-screen-to-mobius
> Migrate registration loading screen to Mobius: Strangulate controller

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/patient/sync/PatientSyncApi.kt
https://app.clubhouse.io/simpledotorg/story/221/bump-resync-token-to-populate-facility-info
> Bump resync token to populate facility info

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/login/pin/LoginPinEffect.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinEffectHandler.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinEvent.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinInit.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinModel.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreen.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreenController.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreenUi.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinUiRenderer.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinUpdate.kt
- app/src/main/java/org/simple/clinic/login/pin/UiActions.kt
- app/src/test/java/org/simple/clinic/login/pin/LoginPinScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/407/migrate-login-pin-screen-to-mobius
> Migrate login pin screen to Mobius - Prepare

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/home/overdue/OverdueScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/373/migrate-overdue-screen-to-mobius
> Migrate overdue screen to Mobius: Stabilise tests

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/561/migrate-forgot-pin-scree-to-mobius
> Migrate forgot pin scree to Mobius - Stablize tests

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewEffect.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewEffectHandler.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewEvent.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewInit.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewModel.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinScreen.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinScreenController.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinUi.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewUiRenderer.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewUpdate.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/UiActions.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/res/layout/screen_forgotpin_createpin.xml
- app/src/test/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/561/migrate-forgot-pin-scree-to-mobius
> Migrate forgot pin screen to Mobius - Prepare

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueInit.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreenController.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUi.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUiActions.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUiRenderer.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/373/migrate-overdue-screen-to-mobius
> Migrate overdue screen to Mobius: Prepare screen for migration

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreen.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenController.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenEvents.kt
- app/src/test/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/608/migrate-forgot-confirm-pin-screen-to-mobius
> Migrate forgot confirm pin screen to Mobius - Stabilise

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/newentry/ButtonState.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryModel.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryUi.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryUiRenderer.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryUpdate.kt
- app/src/main/res/layout/screen_manual_patient_entry.xml
https://app.clubhouse.io/simpledotorg/story/498/add-progress-ui-for-registering-a-patient
> Update `materialButton` to `ProgressMaterialButton` in `PatientEntryScreen`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueInit.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreenController.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreenEvents.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUi.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUiActions.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUiRenderer.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/373/migrate-overdue-screen-to-mobius
> Migrate overdue screen to Mobius: Strangulate controller

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentModel.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUi.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUiRenderer.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUpdate.kt
- app/src/main/res/layout/sheet_schedule_appointment.xml
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentLogicTest.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/554/add-progress-ui-when-scheduling-an-appointment
> Update to `ProgressMaterialButton` in `ScheduleAppointmentSheet`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinEffect.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinEffectHandler.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinEvent.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinInit.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinModel.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreen.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenController.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinUi.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinUiRenderer.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinUpdate.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/UiActions.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/res/layout/screen_forgotpin_confirmpin.xml
- app/src/test/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/608/migrate-forgot-confirm-pin-screen-to-mobius
> Migrate forgot confirm pin screen to Mobius - Prepare

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/editpatient/EditPatientModel.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientState.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientUi.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientUpdate.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientViewRenderer.kt
- app/src/main/java/org/simple/clinic/editpatient/EditablePatientEntry.kt
- app/src/main/res/layout/screen_edit_patient.xml
- app/src/test/java/org/simple/clinic/editpatient/EditPatientEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenCreatedTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenFormTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenSaveTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditablePatientEntryTest.kt
https://app.clubhouse.io/simpledotorg/story/499/add-progress-ui-for-editing-a-patient
> Update `ProgressMaterialButton` in `EditPatientScreen`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinEffect.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinEffectHandler.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinEvent.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinInit.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinModel.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreen.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenController.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenEvents.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinUi.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinUiRenderer.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinUpdate.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/UiActions.kt
- app/src/test/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/608/migrate-forgot-confirm-pin-screen-to-mobius
> Migrate forgot confirm pin screen to Mobius - Migrate

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/search/PatientSearchEffect.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchEffectHandler.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchEvent.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchInit.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchModel.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchScreen.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchScreenController.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchUi.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchUiActions.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchUiRenderer.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchUpdate.kt
- app/src/test/java/org/simple/clinic/search/PatientSearchScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/639/migrate-patient-search-screen-to-mobius
> Migrate patient search screen to Mobius: Stabilize tests and strangulate controller

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/688/migrate-scan-simple-id-screen-to-mobius
> Migrate scan Simple ID screen to Mobius - Stabilise

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/502/migrate-enter-otp-screen-to-mobius
> Migrate Enter OTP screen to Mobius: Stabilize the tests

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/help/HelpScreen.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreenController.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreenEffect.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreenEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreenEvent.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreenInit.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreenModel.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreenUi.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreenUiActions.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreenUiRenderer.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreenUpdate.kt
- app/src/test/java/org/simple/clinic/home/help/HelpScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/700/migrate-help-screen-to-mobius
> Migrate help screen to Mobius - Stabilise & Prepare

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffect.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandler.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEvent.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdModel.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreenController.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUi.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUiActions.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUiRenderer.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt
- app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/688/migrate-scan-simple-id-screen-to-mobius
> Migrate scan Simple ID screen to Mobius - Prepare

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryModel.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheet.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryUi.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryUiRenderer.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryUpdate.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureSaveState.kt
- app/src/main/res/layout/sheet_blood_pressure_entry.xml
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryLogicTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryUiRendererTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/496/add-progress-ui-for-saving-blood-pressure-measurements
> Add progress UI when saving blood pressure

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/HomeScreen.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenController.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenEffect.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenEvent.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenInit.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenModel.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenUi.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenUiActions.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenUiRenderer.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenUpdate.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/test/java/org/simple/clinic/home/HomeScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/726/migrate-home-screen-to-mobius
> Migrate home screen to Mobius - Stabilise & Prepare

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryModel.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntrySheet.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUi.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUiRenderer.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUpdate.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarSaveState.kt
- app/src/main/res/layout/sheet_blood_sugar_entry.xml
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUiRendererTest.kt
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/497/add-progress-ui-for-saving-blood-sugar-measurements
> Add progress UI for saving Blood Sugar

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/Globals.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpEffect.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpEffectHandler.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpEvent.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpInit.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpModel.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreen.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreenController.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreenEvents.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUi.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUiActions.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUiRenderer.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUpdate.kt
- app/src/main/java/org/simple/clinic/login/OtpSmsReceiver.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/502/migrate-enter-otp-screen-to-mobius
> Migrate Enter OTP screen to Mobius: Prepare screen

- doc/arch/010-dagger-qualifier-migration.md
> Add Dagger `Qualifier` migration ADR

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffect.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandler.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEvent.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdModel.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreenController.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreenEvents.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUi.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUiActions.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt
- app/src/main/java/org/simple/clinic/scanid/ShortCodeInput.kt
- app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/688/migrate-scan-simple-id-screen-to-mobius
> Migrate scan Simple ID screen to Mobius - Migrate

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/enterotp/AsyncOpError.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpEffect.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpEffectHandler.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpEvent.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpInit.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpModel.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreen.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreenController.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreenEvents.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUi.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUiActions.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUiRenderer.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUpdate.kt
- app/src/main/java/org/simple/clinic/enterotp/LoginError.kt
- app/src/main/java/org/simple/clinic/enterotp/ValidationResult.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/502/migrate-enter-otp-screen-to-mobius
> Migrate Enter OTP screen to Mobius: Strangulate controller

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/HomeScreen.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenController.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenEffect.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenEvent.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenEvents.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenInit.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenModel.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenUi.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenUiActions.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenUiRenderer.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenUpdate.kt
- app/src/test/java/org/simple/clinic/home/HomeScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/726/migrate-home-screen-to-mobius
> Migrate home screen to Mobius - Migrate

- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheet.kt
- app/src/main/res/layout/sheet_blood_pressure_entry.xml
https://app.clubhouse.io/simpledotorg/story/496/add-progress-ui-for-saving-blood-pressure-measurements
> UI updates when creating blood pressure

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsController.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsEffect.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsEffectHandler.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsEvent.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsInit.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsModel.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreenEvents.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsUi.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsUiActions.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsUiRenderer.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsUpdate.kt
- app/src/test/java/org/simple/clinic/search/results/PatientSearchResultsControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/676/migrate-patient-search-results-screen-to-mobius
> Migrate patient search results screen to Mobius: Stabilize tests and prepare screen for migration

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialog.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialogController.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialogEvents.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialogUi.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialogUiActions.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureEffect.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureEffectHandler.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureEvent.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureModel.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureUpdate.kt
- app/src/test/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialogControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/767/migrate-confirm-remove-blood-pressure-dialog-to-mobius
> Migrate confirm remove blood pressure dialog to Mobius - Stabilise & Prepare

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceDialog.kt
- app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceDialogController.kt
- app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceDialogUi.kt
- app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceEffect.kt
- app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceEvent.kt
- app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceInit.kt
- app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceModel.kt
- app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceUiRenderer.kt
- app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceUpdate.kt
- app/src/test/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceDialogControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/784/migrate-logged-out-of-device-dialog-to-mobius
> Migrate logged out of device dialog to Mobius - Stabilise & Prepare

- CHANGELOG.md
- app/src/debug/java/org/simple/clinic/login/AppLockConfigModule.kt
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
- app/src/main/java/org/simple/clinic/main/TheActivityController.kt
- app/src/release/java/org/simple/clinic/login/AppLockConfigModule.kt
- app/src/test/java/org/simple/clinic/activity/TheActivityControllerTest.kt
- app/src/test/java/org/simple/clinic/activity/TheActivityInitialScreenKeyTest.kt
https://app.clubhouse.io/simpledotorg/story/744/migrate-theactivity-to-mobius
> Migrate the activity to Mobius: Stabilize tests

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberDialog.kt
- app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberDialogController.kt
- app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberDialogEvents.kt
- app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberDialogUi.kt
- app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberEffect.kt
- app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberEvent.kt
- app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberInit.kt
- app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberModel.kt
- app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberUiActions.kt
- app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberUiRenderer.kt
- app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberUpdate.kt
- app/src/main/res/layout/dialog_patientsummary_updatephone.xml
- app/src/test/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberDialogControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/793/migrate-update-phone-number-dialog-to-mobius
> Migrate update phone number dialog to Mobius - Stabilise & Prepare

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsController.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsEffect.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsEffectHandler.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsEvent.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsModel.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreenEvents.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsUi.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsUiActions.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsUpdate.kt
- app/src/test/java/org/simple/clinic/search/results/PatientSearchResultsControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/708/migrate-search-results-view-to-mobius
> Migrate patient search results screen to Mobius: Strangulate controller

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
- app/src/main/java/org/simple/clinic/main/TheActivityController.kt
- app/src/main/java/org/simple/clinic/main/TheActivityEffect.kt
- app/src/main/java/org/simple/clinic/main/TheActivityEffectHandler.kt
- app/src/main/java/org/simple/clinic/main/TheActivityEvent.kt
- app/src/main/java/org/simple/clinic/main/TheActivityInit.kt
- app/src/main/java/org/simple/clinic/main/TheActivityModel.kt
- app/src/main/java/org/simple/clinic/main/TheActivityUi.kt
- app/src/main/java/org/simple/clinic/main/TheActivityUiActions.kt
- app/src/main/java/org/simple/clinic/main/TheActivityUiRenderer.kt
- app/src/main/java/org/simple/clinic/main/TheActivityUpdate.kt
- app/src/test/java/org/simple/clinic/activity/TheActivityControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/744/migrate-theactivity-to-mobius
> Migrate the main activity to Mobius: Prepare screen for migration

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientEffect.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientEvent.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientModel.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientUiActions.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientUpdate.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientView.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewController.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewUi.kt
- app/src/main/res/layout/link_id_with_patient_view.xml
- app/src/test/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/836/migrate-link-id-with-patient-view-to-mobius
> Migrate link id with patient view to Mobius - Stabilise & Prepare

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/login/applock/AppLockScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/856/migrate-app-lock-screen-to-mobius
> Migrate app lock screen to Mobius - Stabilise

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffect.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEvent.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientInit.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientUi.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientUpdate.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryInit.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryModule.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenCreatedTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenFormTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenSaveTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/766/add-different-address-fields-for-specific-facility-group-ids
> Load input fields via an effect in edit patient screen

- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientEffect.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientEvent.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientEvents.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientModel.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientUiActions.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientUpdate.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewController.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewUi.kt
- app/src/test/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/836/migrate-link-id-with-patient-view-to-mobius
> Migrate link id with patient view to Mobius - Migrate

- CHANGELOG.md
- app/src/main/res/layout/screen_edit_patient.xml
- app/src/main/res/layout/screen_manual_patient_entry.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/styles_v2.xml
https://app.clubhouse.io/simpledotorg/story/882/change-error-messages-text-size-to-14sp
> Change error messages text size to 14sp

- app/src/main/java/org/simple/clinic/login/applock/AppLockEffect.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockEffectHandler.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockEvent.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockInit.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockModel.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockScreen.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockScreenController.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockScreenUi.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockUiActions.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockUiRenderer.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockUpdate.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/res/layout/screen_app_lock.xml
- app/src/test/java/org/simple/clinic/login/applock/AppLockScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/856/migrate-app-lock-screen-to-mobius
> Migrate app lock screen to Mobius - Prepare

- app/src/main/java/org/simple/clinic/login/applock/AppLockEffect.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockEffectHandler.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockEvent.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockInit.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockModel.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockScreen.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockScreenController.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockScreenEvents.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockScreenUi.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockUiActions.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockUiRenderer.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockUpdate.kt
- app/src/test/java/org/simple/clinic/login/applock/AppLockScreenControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/856/migrate-app-lock-screen-to-mobius
> Migrate app lock screen to Mobius - Migrate

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsUi.kt
- app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsUiRenderer.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientItem.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreen.kt
- app/src/test/java/org/simple/clinic/recentpatient/AllRecentPatientsLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/960/can-t-get-to-patient-summary-from-recent-patient-list
> Fix cannot open patient summary from recent patient's screen

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/searchresultsview/PatientSearchViewControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/708/migrate-search-results-view-to-mobius
> Migrate patient search view to Mobius: Stabilize tests

- app/src/main/java/org/simple/clinic/signature/SignatureActivity.kt
- app/src/main/java/org/simple/clinic/signature/SignatureEffectHandler.kt
- app/src/main/java/org/simple/clinic/signature/SignatureUiActions.kt
- app/src/test/java/org/simple/clinic/signature/SignatureEffectHandlerTest.kt
https://app.clubhouse.io/simpledotorg/story/735/implement-a-screen-to-accept-and-save-the-user-signature
> Update naming convention in `SignatureActivity`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
- app/src/main/java/org/simple/clinic/main/TheActivityController.kt
- app/src/main/java/org/simple/clinic/main/TheActivityEffect.kt
- app/src/main/java/org/simple/clinic/main/TheActivityEffectHandler.kt
- app/src/main/java/org/simple/clinic/main/TheActivityEvent.kt
- app/src/main/java/org/simple/clinic/main/TheActivityInit.kt
- app/src/main/java/org/simple/clinic/main/TheActivityUi.kt
- app/src/main/java/org/simple/clinic/main/TheActivityUiActions.kt
- app/src/main/java/org/simple/clinic/main/TheActivityUpdate.kt
- app/src/main/java/org/simple/clinic/user/User.kt
- app/src/test/java/org/simple/clinic/activity/TheActivityControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/744/migrate-theactivity-to-mobius
> Migrate `TheActivity` to Mobius: Strangulate controller

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchUi.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchView.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchViewController.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsEffect.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsEffectHandler.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsEvent.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsInit.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsItemType.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsModel.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsUi.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsUiRenderer.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsUpdate.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsViewEvents.kt
- app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultScreen.kt
- app/src/test/java/org/simple/clinic/searchresultsview/PatientSearchViewControllerTest.kt
https://app.clubhouse.io/simpledotorg/story/708/migrate-search-results-view-to-mobius
> Migrate patient search view to Mobius: prepare screen for migration

- build.gradle
https://blog.jetbrains.com/kotlin/2020/08/kotlin-1-4-released-with-a-focus-on-quality-and-performance/
> Bump Kotlin Gradle plugin to v1.4.0

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/di/AppComponent.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationEffect.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationEffectHandler.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationEvent.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationInit.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationModel.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationSheet.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationUi.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationUiActions.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationUiRenderer.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationUpdate.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationValidationResult.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/di/DrugDurationComponent.kt
- app/src/main/res/layout/sheet_drug_duration.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationInitTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationUiRendererTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/891/add-screen-for-adjusting-medicine-duration
> Add screen for adjusting medicine duration

- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDuration.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationSheet.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationValidationResult.kt
Addressing feedback from #1640
> Drug duration screen cleanup

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessEffect.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessEffectHandler.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessEvent.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessInit.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessModel.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessScreen.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessScreenKey.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessScreenUiActions.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessUi.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessUiRenderer.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessUpdate.kt
- app/src/main/res/drawable/ic_check_circle.xml
- app/src/main/res/layout/screen_teleconsult_success.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessInitTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/887/add-screen-for-notifying-a-successful-teleconsultation
> Add screen to notify a successful Teleconsultation 

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/71.json
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration71AndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/login/LoginUserWithOtp.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinEffectHandler.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreen.kt
- app/src/main/java/org/simple/clinic/security/pin/verification/LoginPinServerVerificationMethod.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_71.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/main/java/org/simple/clinic/user/LoggedInUserPayload.kt
- app/src/main/java/org/simple/clinic/user/OngoingLoginEntry.kt
- app/src/main/java/org/simple/clinic/user/User.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/main/java/org/simple/clinic/user/refreshuser/RefreshCurrentUser.kt
- app/src/main/java/org/simple/clinic/user/registeruser/RegisterUser.kt
- app/src/main/java/org/simple/clinic/user/resetpin/ResetUserPin.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
- app/src/sharedTest/java/org/simple/clinic/util/TestFunctions.kt
- app/src/test/java/org/simple/clinic/login/pin/LoginPinScreenLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/877/update-the-user-model-to-include-the-teleconsultation-number
> Update the `User` model to include the teleconsultation number

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/PatientSummaryChildModel.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryChildView.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityModel.kt
- app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityView.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewModel.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureSummaryView.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/BloodSugarSummaryViewModel.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarSummaryView.kt
- app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryModel.kt
- app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryView.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryModel.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryView.kt
- app/src/main/res/layout/screen_patient_summary.xml
https://app.clubhouse.io/simpledotorg/story/1033/hide-patient-summary-widgets-until-all-are-ready-to-display
> Improve UX while loading the patient summary screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/TeleconsultationMessageBuilder.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/messagebuilder/LongTeleconsultMessageBuilder.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/messagebuilder/ShortTeleconsultMessageBuilder.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/messagebuilder/TeleconsultationMessageBuilder.kt
- app/src/main/java/org/simple/clinic/util/messagesender/MessageSender.kt
- app/src/main/java/org/simple/clinic/util/messagesender/SmsMessageSender.kt
- app/src/main/java/org/simple/clinic/util/messagesender/WhatsAppMessageSender.kt
https://app.clubhouse.io/simpledotorg/story/885/add-support-for-sending-teleconsult-request-via-sms
> Add support for sending teleconsult request via SMS #1

- CHANGELOG.md
- app/src/main/res/values/strings.xml
https://app.clubhouse.io/simpledotorg/story/806/update-error-message-for-address-fields-in-patient-entry-screen
> Update error messages in `PatientEntryScreen`

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/72.json
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration72AndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultationFacilityRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultationFacilityWithMedicalOfficersTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/main/TypedPreference.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_72.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModule.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/MedicalOfficer.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/MedicalOfficerPayload.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultFacilityInfoApi.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultFacilityInfoPullResponse.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultationFacilityInfo.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultationFacilityInfoPayload.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultationFacilityRepository.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultationFacilityWithMedicalOfficers.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultationSync.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://app.clubhouse.io/simpledotorg/story/878/add-support-for-facility-teleconsultation-info-sync-resource
> Add support for facility teleconsultation info sync resource

- CHANGELOG.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/deeplink/DeepLinkActivity.kt
- app/src/main/java/org/simple/clinic/deeplink/DeepLinkEffect.kt
- app/src/main/java/org/simple/clinic/deeplink/DeepLinkEffectHandler.kt
- app/src/main/java/org/simple/clinic/deeplink/DeepLinkModel.kt
- app/src/main/java/org/simple/clinic/deeplink/DeepLinkResult.kt
- app/src/main/java/org/simple/clinic/deeplink/DeepLinkUiActions.kt
- app/src/main/java/org/simple/clinic/deeplink/DeepLinkUpdate.kt
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
- app/src/main/java/org/simple/clinic/summary/OpenIntention.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryInit.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/main/java/org/simple/clinic/util/Strings.kt
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/deeplink/DeepLinkEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/deeplink/DeepLinkInitTest.kt
- app/src/test/java/org/simple/clinic/deeplink/DeepLinkUpdateTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryInitTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/884/add-support-for-the-teleconsultation-record-deeplink
> Add support for the teleconsultation record deeplink

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/73.json
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration73AndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/drugs/sync/PrescribedDrugPayload.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_73.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/medicinefrequency/MedicineFrequency.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/medicinefrequency/MedicineFrequencySheet.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://app.clubhouse.io/simpledotorg/story/1086/update-the-prescribeddrug-to-include-drug-duration-and-frequency
> Update the `PrescribedDrug` to include drug duration and frequency

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityModel.kt
https://app.clubhouse.io/simpledotorg/story/1127/patient-details-screen-does-not-load-for-patients-who-don-t-have-an-assigned-facility
> Fix issue where patient details would not load for patients without an assigned facility

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/74.json
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/di/TestStorageModule.kt
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration74AndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_74.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/Answer.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecord.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordInfo.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordInfoPayload.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordModule.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordPayload.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordPrescribedDrug.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordWithPrescribedDrugs.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRequestInfo.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRequestInfoPayload.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultationType.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://app.clubhouse.io/simpledotorg/story/907/add-support-for-teleconsult-record-sync-resource
> Add `TeleconsultRecord` and `TeleconsultRecordPayload`

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/75.json
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration75AndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/user/OngoingLoginEntryRepositoryTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt
- app/src/main/java/org/simple/clinic/login/LoginUserWithOtp.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinEffectHandler.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreen.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffectHandler.kt
- app/src/main/java/org/simple/clinic/security/pin/verification/LoginPinServerVerificationMethod.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_75.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/main/java/org/simple/clinic/user/LoggedInUserPayload.kt
- app/src/main/java/org/simple/clinic/user/OngoingLoginEntry.kt
- app/src/main/java/org/simple/clinic/user/User.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/main/java/org/simple/clinic/user/refreshuser/RefreshCurrentUser.kt
- app/src/main/java/org/simple/clinic/user/registeruser/RegisterUser.kt
- app/src/main/java/org/simple/clinic/user/resetpin/ResetUserPin.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
- app/src/sharedTest/java/org/simple/clinic/util/TestFunctions.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpLogicTest.kt
- app/src/test/java/org/simple/clinic/login/pin/LoginPinScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/880/add-a-check-if-the-current-mo-is-allowed-to-log-a-teleconsult-record-at-the-current-facility
> Add Capabilties to user

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/user/LoggedInUserHttpInterceptor.kt
https://app.clubhouse.io/simpledotorg/story/1197/stop-querying-additional-facility-in-headers-for-making-network-calls
> Stop querying redundant facility for HTTP request headers

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/HomeScreenUpdate.kt
- app/src/test/java/org/simple/clinic/home/HomeScreenLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/1199/disable-loading-overdue-count-in-the-home-screen
> Remove loading of overdue item count on the home screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultFacilityInfoApi.kt
the [conversation](https://simpledotorg.slack.com/archives/CFK2PHJ1L/p1599211058076600) regarding this change.
> Change `TeleconsultFacilityInfoApi` endpoint

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureEffectHandler.kt
https://app.clubhouse.io/simpledotorg/story/1211/fix-remove-bloodpressure
> Fix Remove BloodPressure

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/storage/PurgeDatabaseAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt
https://app.clubhouse.io/simpledotorg/story/1201/prune-the-local-database-at-regular-intervals
> Add methods to purge unnecessary patient records

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/storage/PurgeDatabaseAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
https://app.clubhouse.io/simpledotorg/story/1201/prune-the-local-database-at-regular-intervals
> Add method to purge deleted resources

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/storage/PurgeDatabaseAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
https://app.clubhouse.io/simpledotorg/story/1201/prune-the-local-database-at-regular-intervals
> Add method to purge unncessary appointments from the database

- CHANGELOG.md
- app/src/main/res/layout/item_overdue_list_patient.xml
Daniel requested for this [here](https://simpledotorg.slack.com/archives/CFKMFQCKB/p1600093368001700?thread_ts=1599558365.001800&cid=CFKMFQCKB).
> Add ripple on touch for overdue patient name

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/teleconsultlog/medicinefrequency/MedicineFrequencySheet.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/medicinefrequency/MedicineFrequencySheetExtra.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEffect.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEffectHandler.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEvent.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesModel.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUiActions.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUpdate.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/889/add-screen-for-updating-the-patient-s-prescription
> Add screen for updating the patient's prescription #3

- CHANGELOG.md
- app/src/debug/java/org/simple/clinic/setup/SetupActivityConfigModule.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/main/TypedPreference.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingEffectHandler.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingModule.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivity.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityConfig.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityEffect.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityEffectHandler.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityEvent.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityModel.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityModule.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityUpdate.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/release/java/org/simple/clinic/setup/SetupActivityConfigModule.kt
- app/src/test/java/org/simple/clinic/setup/SetupActivityEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/setup/SetupActivityInitTest.kt
- app/src/test/java/org/simple/clinic/setup/SetupActivityUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/1201/prune-the-local-database-at-regular-intervals
> Add recurring task to prune the database

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/appconfig/AppConfigModule.kt
- app/src/main/java/org/simple/clinic/bloodsugar/di/BloodSugarModule.kt
- app/src/main/java/org/simple/clinic/bp/di/BloodPressureModule.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionModule.kt
- app/src/main/java/org/simple/clinic/facility/FacilityModule.kt
- app/src/main/java/org/simple/clinic/login/LoginModule.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryModule.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentModule.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientSyncModule.kt
- app/src/main/java/org/simple/clinic/protocol/ProtocolModule.kt
- app/src/main/java/org/simple/clinic/settings/SettingsModule.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityModule.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/TeleconsultPrescriptionModule.kt
- app/src/main/java/org/simple/clinic/util/preference/OptionalRxPreferencesConverter.kt
- app/src/main/java/org/simple/clinic/util/preference/RxPreferencesFoo.kt
https://app.clubhouse.io/simpledotorg/story/1271/create-kotlin-extension-for-saving-optional-preferences
> Create Kotlin extension for saving Optional preferences

- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/bp/BloodPressureRepositoryTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryLogicTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureValidationMockDateValidatorTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureValidationTest.kt
https://app.clubhouse.io/simpledotorg/story/1275/add-performance-instrumentation-for-bp-entry-flow
> Partially change the BP entry flows to be synchronous

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/77.json
- app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration77AndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/sync/PrescriptionSyncIntegrationTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/drugs/sync/PrescribedDrugPayload.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_77.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://app.clubhouse.io/simpledotorg/story/1253/modify-prescribeddrug-to-include-teleconsult-record-id
> Modify `PrescribedDrug` to include `teleconsultation_id`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationConfig.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationEffect.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationEffectHandler.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationInit.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationModel.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationSheet.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationUi.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationUiActions.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationUiRenderer.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationUpdate.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationValidationResult.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationValidator.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/di/DrugDurationComponent.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/di/DrugDurationModule.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationInitTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationUiRendererTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationUpdateTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationValidatorTest.kt
https://app.clubhouse.io/simpledotorg/story/1252/set-max-drug-duration-limit-to-1000-days
> Set max drug duration limit to 1000 days

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryLogicTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureValidationMockDateValidatorTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureValidationTest.kt
https://app.clubhouse.io/simpledotorg/story/1275/add-performance-instrumentation-for-bp-entry-flow
> Change Blood Pressure create and update flows to be fully synchronous

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/TeleconsultPrescriptionEffect.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/TeleconsultPrescriptionEffectHandler.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/TeleconsultPrescriptionEvent.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/TeleconsultPrescriptionScreen.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/TeleconsultPrescriptionUiActions.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/TeleconsultPrescriptionUpdate.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/prescription/TeleconsultPrescriptionEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/prescription/TeleconsultPrescriptionUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/889/add-screen-for-updating-the-patient-s-prescription
> Add screen for updating the patient's prescription - Final

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandler.kt
https://app.clubhouse.io/simpledotorg/story/1275/add-performance-instrumentation-for-bp-entry-flow
> Add custom performance traces for blood pressure measurement flows

- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientTeleconsultationInfo.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/messagebuilder/LongTeleconsultMessageBuilder.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/messagebuilder/LongTeleconsultMessageBuilder_Old.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
Once this is merged in, will open a different PR that will use the new `LongTeleconsultMessageBuilder` in the `ContactDoctorSheet`
> Implement new teleconsultation message builder

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/79.json
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration79AndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordRepositoryTest.kt
- app/src/androidTest/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordSyncIntegrationTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_79.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultPushRequest.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecord.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordApi.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordModule.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordRepository.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordSync.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://app.clubhouse.io/simpledotorg/story/907/add-support-for-teleconsult-record-sync-resource
> Add teleconsult record sync resource

- app/src/androidTest/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordRepositoryTest.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecord.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordRepository.kt
https://app.clubhouse.io/simpledotorg/story/1278/set-sync-status-to-pending-when-updating-teleconsultrecord﻿
> Set sync status to pending when updating `TeleconsultRecord`

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordRepositoryTest.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/contactdoctor/ContactDoctorEffect.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/contactdoctor/ContactDoctorEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/contactdoctor/ContactDoctorEvent.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/contactdoctor/ContactDoctorModel.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/contactdoctor/ContactDoctorSheet.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/contactdoctor/ContactDoctorUiActions.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/contactdoctor/ContactDoctorUpdate.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/contactdoctor/DoctorListItem.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/contactdoctor/MessageTarget.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/messagebuilder/LongTeleconsultMessageBuilder.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/messagebuilder/ShortTeleconsultMessageBuilder.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordRepository.kt
- app/src/test/java/org/simple/clinic/summary/teleconsultation/contactdoctor/ContactDoctorEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/teleconsultation/contactdoctor/ContactDoctorInitTest.kt
- app/src/test/java/org/simple/clinic/summary/teleconsultation/contactdoctor/ContactDoctorUiRendererTest.kt
- app/src/test/java/org/simple/clinic/summary/teleconsultation/contactdoctor/ContactDoctorUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/885/add-support-for-sending-teleconsult-request-via-sms
> Add support for sending teleconsult request via SMS - Final

- app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordCreateState.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordEffect.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordEffectHandler.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordEvent.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordModel.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordScreen.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordUi.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordUiRenderer.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordUpdate.kt
- app/src/main/res/layout/screen_teleconsult_record.xml
- app/src/test/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordUiRendererTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/1257/save-teleconsult-record-id-to-prescribed-drugs-when-creating-teleconsultrecord
> Save teleconsult record id to prescribed drugs when creating TeleconsultRecord

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
- app/src/main/java/org/simple/clinic/sync/DataSync.kt
- app/src/main/java/org/simple/clinic/sync/SyncSetup.kt
- app/src/main/java/org/simple/clinic/sync/SyncWorker.kt
- app/src/main/java/org/simple/clinic/user/clearpatientdata/SyncAndClearPatientData.kt
- app/src/test/java/org/simple/clinic/sync/DataSyncTest.kt
- app/src/test/java/org/simple/clinic/sync/SyncDataOnApprovalTest.kt
- app/src/test/java/org/simple/clinic/user/clearpatientdata/SyncAndClearPatientDataTest.kt
This will be important for block level sync since we will need to trigger certain events when the sync of an entire group completes.
> Fix issues with sync where sync events were being triggered at the sync level instead of the group level

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/80.json
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration80AndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/facility/Facility.kt
- app/src/main/java/org/simple/clinic/facility/FacilityPayload.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_80.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://app.clubhouse.io/simpledotorg/story/1457/add-syncgroup-property-to-the-facilityresource
> Add `syncGroup` property to the `Facility` resource

- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/storage/DeleteSyncGroupDatabaseAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/facility/Facility.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
https://app.clubhouse.io/simpledotorg/story/1413/regularly-purge-data-outside-the-current-sync-group
> Add method to delete patients not in the current sync group

- CHANGELOG.md
- build.gradle
Please update Android Studio to v4.0.2
> Bump AGP to v4.0.2

- app/src/androidTest/java/org/simple/clinic/storage/DeleteSyncGroupDatabaseAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
https://app.clubhouse.io/simpledotorg/story/1413/regularly-purge-data-outside-the-current-sync-group
> Delete blood pressure measurements without a patient when deleting data from other sync groups

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/storage/DeleteSyncGroupDatabaseAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
https://app.clubhouse.io/simpledotorg/story/1413/regularly-purge-data-outside-the-current-sync-group
> Complete method to delete resources for missing patients

- CHANGELOG.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/teleconsultlog/shareprescription/TeleconsultSharePrescriptionEvent.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/shareprescription/TeleconsultSharePrescriptionScreen.kt
https://app.clubhouse.io/simpledotorg/story/1559/request-storage-permission-when-downloading-or-sharing-prescription
> Request storage permission when downloading or sharing prescription

- CHANGELOG.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/fileprovider/SimpleFileProvider.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/shareprescription/TeleconsultSharePrescriptionRepository.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/shareprescription/TeleconsultSharePrescriptionScreen.kt
- app/src/main/res/xml/provider_paths.xml
https://app.clubhouse.io/simpledotorg/story/1569/add-file-provider-for-sharing-prescription-image-below-android-10
> Add file provider for sharing prescription image below Android 10

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/security/pin/PinEntryCardView.kt
- app/src/main/java/org/simple/clinic/security/pin/PinEntryEvent.kt
- app/src/main/java/org/simple/clinic/security/pin/PinEntryUpdate.kt
- app/src/main/res/layout/pin_entry_card.xml
- app/src/test/java/org/simple/clinic/security/pin/PinEntryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/589/app-freezes-when-we-press-enter-with-empty-pin-in-lock-screen
> App freezes when we press enter with empty pin in lock screen

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/login/LoginUserWithOtpServerIntegrationTest.kt
- app/src/androidTest/java/org/simple/clinic/rules/ServerAuthenticationRule.kt
- app/src/androidTest/java/org/simple/clinic/user/UserSessionAndroidTest.kt
- app/src/main/java/org/simple/clinic/sync/DataSync.kt
- app/src/main/java/org/simple/clinic/sync/PurgeOnSync.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
- app/src/main/java/org/simple/clinic/sync/SyncScheduler.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEffectHandler.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/test/java/org/simple/clinic/sync/DataSyncTest.kt
https://app.clubhouse.io/simpledotorg/story/1413/regularly-purge-data-outside-the-current-sync-group
> Purge data from a different sync group whenever all syncs complete

- app/src/main/java/org/simple/clinic/AppDatabase.kt
- simple-platform/src/main/java/org/simple/clinic/platform/analytics/DatabaseOptimizationEvent.kt
https://app.clubhouse.io/simpledotorg/story/1614/add-analytics-for-database-size-optimization-metrics
> Add analytics for database optimization metrics (Part 1)

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/test/java/org/simple/clinic/analytics/AnalyticsTest.kt
- simple-platform/src/main/java/org/simple/clinic/platform/analytics/Analytics.kt
https://app.clubhouse.io/simpledotorg/story/1614/add-analytics-for-database-size-optimization-metrics
> Add analytics for database optimization metrics (Part 2)

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordSyncIntegrationTest.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordSync.kt
https://app.clubhouse.io/simpledotorg/story/1634/sync-teleconsultrecord-frequently
> Update `TeleconsultRecord` to sync frequently

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/82.json
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration82AndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordSyncIntegrationTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_82.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/contactdoctor/ContactDoctorEffectHandler.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordSync.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRequestInfo.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRequestInfoPayload.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultStatus.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://app.clubhouse.io/simpledotorg/story/1619/add-teleconsultstatus-to-teleconsultrecord
> Add `TeleconsultStatus` to `TeleconsultRecord`

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/user/UserSessionAndroidTest.kt
- app/src/main/java/org/simple/clinic/facility/FacilityPayload.kt
- app/src/main/java/org/simple/clinic/facility/FacilitySyncApi.kt
- app/src/main/java/org/simple/clinic/user/LoggedInUserHttpInterceptor.kt
- app/src/main/java/org/simple/clinic/user/User.kt
- app/src/main/java/org/simple/clinic/user/UserFacilityDetails.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
https://app.clubhouse.io/simpledotorg/story/1582/add-sync-region-id-header-to-http-requests
> Add support for server controlled resync on switching sync regions

- app/src/main/res/values/strings.xml
https://app.clubhouse.io/simpledotorg/story/1781/convert-header-to-sentence-case-in-selectcountryscreen
[Suggested by Pragati here](https://obvious-hq.slack.com/archives/CE0F1TLTC/p1603449420037400)
> Convert header to sentence case in `SelectCountryScreen`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/drugs/OpenIntention.kt
- app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesScreen.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryModel.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryUpdate.kt
- app/src/main/res/layout/screen_patient_prescribed_drugs_entry.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/drugs/DrugSummaryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/1712/refill-prescriptions-in-edit-medicines-screen
In this PR 
- Adds Refill button layout
- Adds `OpenIntention` sealed class
- Adds update logic to implement refill medicine or add new medicine logic
> Refill prescriptions in edit medicines screen - 1

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarUnitPreference.kt
- app/src/main/java/org/simple/clinic/bloodsugar/di/BloodSugarModule.kt
https://app.clubhouse.io/simpledotorg/story/1843/create-blood-sugar-unit-preference
> Add blood sugar unit preference

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesEffect.kt
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesEffectHandler.kt
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesEvent.kt
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesModel.kt
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesUiRenderer.kt
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesUpdate.kt
- app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesScreen.kt
- app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesUi.kt
- app/src/main/java/org/simple/clinic/drugs/selection/PrescribedDrugsScreenKey.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryUiActions.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryView.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEffect.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEffectHandler.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesModel.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUiActions.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUpdate.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesView.kt
- app/src/main/res/layout/screen_patient_prescribed_drugs_entry.xml
- app/src/test/java/org/simple/clinic/drugs/DrugSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/drugs/EditMedicineEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/drugs/EditMedicineUpdateTest.kt
- app/src/test/java/org/simple/clinic/drugs/EditMedicinesUiRendererTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/EditMedicinesScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryUiLogicTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/1712/refill-prescriptions-in-edit-medicines-screen
> Refill prescriptions in edit medicines screen - 2

- app/src/main/java/org/simple/clinic/drugs/EditMedicinesEffectHandler.kt
- app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesScreen.kt
- app/src/main/res/layout/screen_patient_prescribed_drugs_entry.xml
- app/src/test/java/org/simple/clinic/drugs/EditMedicinesUiRendererTest.kt
https://app.clubhouse.io/simpledotorg/story/1712/refill-prescriptions-in-edit-medicines-screen
> Refill prescriptions in edit medicines screen - Final
