- app/build.gradle
- gradle.properties
- Read endpoints from `gradle.properties` instead of system environment variables
- QA endpoint is hardcoded so that local development is a lot faster
- Staging and Production endpoints have placeholder values, that are meant to be overriden on the build server
> Gradle build cleanup

- app/build.gradle
- app/src/main/java/org/simple/clinic/activity/TheActivity.kt
- app/src/main/java/org/simple/clinic/widgets/BottomSheetActivity.kt
- It has been disabled only in the `release` build type
- Android doesn't let you set individual `View` instances as `SECURE`, (only exception is `SurfaceView`), so we have to set it for `TheActivity`, which disables screenshots for the entire production application
> Disable capturing screenshots and screen recording

- app/src/androidTest/java/org/simple/clinic/bp/sync/BloodPressureSyncAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/drugs/sync/PrescriptionSyncAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- Adds a new field `searchableName` to the `Patient` table that saves a stripped down version of the Patient name without whitespaces and punctuation
- Changed `PatientRepository` to strip search queries of white spaces and punctuation when searching for names
- Changed `PatientRepository` to updated the `searchableName` when merging remote patient records as well as adding new patients
- Changed `PatientSearchResult.RoomDao` to use the `searchableName` instead of the `fullName` when doing search queries
> 25 July 2018 - Fuzzy Lookup v1

- app/src/main/java/org/simple/clinic/user/LoggedInUser.kt
This is done to avoid breaking the login API.
> Temporarily default LoggedInUser.status to APPROVED

- app/build.gradle
- app/schemas/org.simple.clinic.AppDatabase/5.json
- app/src/main/java/org/simple/clinic/AppDatabase.kt
We may not do the DB migration testing right now, but since we are actively writing migrations, we should be exporting schemas so that we don't have to retro-actively generate too many schemas in the future.
- Export schemas from `AppDatabase`. 
- Add schemas to the `androidTest` source set
See https://developer.android.com/training/data-storage/room/migrating-db-versions
> Export Room schemas from AppDatabase

- app/src/main/java/org/simple/clinic/registration/facility/FacilitiesAdapter.kt
Facility selection screen was becoming unresponsive because updating CheckBox's checked state was triggering an infinite loop of data-set updates.
> Suppress CheckBox's listener when updating it in FacilitiesAdapter

- app/src/androidTest/java/org/simple/clinic/user/UserSessionAndroidTest.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
RegistrationPhoneScreen wasn't recreating the ongoing registration entry once it was cleared. This was happening because UserSession#clearOngoingRegistrationEntry() and isOngoingRegistrationEntryPresent() were not in sync. 
Steps for reproducing the crash:
1. Open registration screen and enter the phone number of an existing user
2. The login-pin screen should open. Go back to the registration-phone screen
3. Proceed to facility selection and press done to complete registration
> Fix a crash when completing registration after selecting facilities 

- app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryController.kt
- app/src/test/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryControllerTest.kt
Bug fix for https://www.pivotaltracker.com/story/show/160350133
The placeholder was previously shown everytime the dosage field is empty, making it impossible to clear the field.
> Add 'mg' to dosage field only when it's focused for the first time

- app/src/main/java/org/simple/clinic/activity/TheActivity.kt
- app/src/main/java/org/simple/clinic/activity/TheActivityController.kt
- app/src/main/java/org/simple/clinic/analytics/UpdateAnalyticsUserId.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinScreen.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/login/applock/ConfirmResetPinDialog.kt
- app/src/main/java/org/simple/clinic/user/User.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/main/res/layout/screen_app_lock.xml
- app/src/main/res/layout/screen_forgotpin_createpin.xml
- app/src/test/java/org/simple/clinic/activity/TheActivityControllerTest.kt
- app/src/test/java/org/simple/clinic/analytics/UpdateAnalyticsUserIdTest.kt
- app/src/test/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
1. Removes the `VERIFYING_OTP` logged in status since it was not being used anywhere, and added two more, `RESETTING_PIN` and `RESET_PIN_REQUESTED`.
2. Updated initial screen key in `TheActivity` to load the Create PIN screen if the logged in status is `RESETTING_PIN`.
3. Change the user logged in status to `RESETTING_PIN` once the patient data is cleared.
> Open create new PIN screen if user has not completed raising a PIN request

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- build.gradle
Plugin 3.2.0 creates an empty mapping.txt file even though we have the '-dontobfuscate' option set. This caused problems with the CI setup since deploying to the Play Store automatically failed because it doesn't handle empty mapping files.
This downgrades the plugin to 3.1.4.
The plan to fix this is to add a gradle task that automatically deletes the mapping files after builds when upgradling to 3.2.0.
> Downgrade to gradle plugin 3.1.4

- app/src/main/java/org/simple/clinic/search/results/PhoneNumberObfuscator.kt
- app/src/main/java/org/simple/clinic/util/Unicode.kt
- app/src/test/java/org/simple/clinic/search/results/IndianPhoneNumberObfuscatorTest.kt
1. Last three digits are always visible.
2. Five digits before the last three are masked.
3. All preceding digits are also visible.
> Update Indian PhoneNumberObfuscator with new specs.

- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheet.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
Steps to reproduce:
1. Open a patient's summary
2. Tap on 'New BP'
3. Enter empty value for systolic
4. Hit IME-done in keyboard
The same steps will also work for the diastolic field.
> Fix: entering an empty systolic or diastolic value crashes BP entry

- app/src/androidTest/java/org/simple/clinic/medicalhistory/MedicalHistoryRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
Steps to reproduce:
1. Send patients to the server without any medical history. This can be done by using an HTTP client or running Android tests for syncing patients.
2. Open the patient's summary screen on two phones
3. Answer different medical history questions
4. Exit summary screen
5. Trigger a sync on both phones
6. Open summary screen again for the same patient
7. The app will crash.
> Fix: summary screen crashes if multiple histories are present for the patient

- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/summary/RelativeTimestampGeneratorAndroidTest.kt
- app/src/main/java/org/simple/clinic/summary/RelativeTimestampGenerator.kt
Reason: DateTimeFormatter cannot format patterns with date strings from an Instant.
> Convert Instant to LocalDateTime before formatting

- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/crash/CrashReporter.kt
- app/src/main/java/org/simple/clinic/crash/SentryCrashReporter.kt
- app/src/main/java/org/simple/clinic/sync/SyncWorker.kt
We swallow errors if data syncing fails, but it'll be nice to see them reported on Sentry along with breadcrumbs (if any).
> Report to Sentry if data syncing fails

- app/src/androidTest/java/org/simple/clinic/TestClinicApp.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/fuzzy/AbsoluteFuzzer.kt
- app/src/main/java/org/simple/clinic/patient/fuzzy/AgeFuzzer.kt
- app/src/main/java/org/simple/clinic/patient/fuzzy/AgeFuzzerModule.kt
- app/src/main/java/org/simple/clinic/patient/fuzzy/BoundedAge.kt
- app/src/main/java/org/simple/clinic/patient/fuzzy/PercentageFuzzer.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- app/src/test/java/org/simple/clinic/patient/fuzzy/AbsoluteFuzzerTest.kt
- app/src/test/java/org/simple/clinic/patient/fuzzy/BoundedAgeTest.kt
- app/src/test/java/org/simple/clinic/patient/fuzzy/PercentageFuzzerTest.kt
The percentage based fuzzer was ignoring the precision lost when rounding down the fuzziness factor. However, since this is multiplied by years instead of days, our fuzziness search could be inaccurate by months.
This commit fixes the problem by changing Age fuzziness to compute the dates internally, and to convert the fuzziness into a factor of days instead of years.
This is a little tricky to test since the calculation is done taking the current date into account.
Create patients with the following DOBs:
1. 26/11/1998
2. 26/08/1994
On master, only the 26th november patient will be visible but on the current branch, both will be (as is expected.)
> Avoid ignoring months when calculating fuzzy age bounds

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/PatientFuzzySearch.kt
SQLite has a hard limit of 999 for the number of parameters in a parameterized query. Since it is unlikely the nurse will scroll through 999 patients, this fixes the problem by limiting the number of results from fuzzy search to 100.
> Fix: Crash on 1000+ results in patient search

- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/facility/FacilityRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/storage/DaoWithUpsertAndroidTest.kt
- app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt
- app/src/main/java/org/simple/clinic/facility/Facility.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientAddress.kt
- app/src/main/java/org/simple/clinic/patient/PatientPhoneNumber.kt
- app/src/main/java/org/simple/clinic/storage/DaoWithUpsert.kt
When records are inserted with `replace` as the conflict strategy, sqlite internally performs a delete+insert. Although they are performed inside the same transaction, sqlite seems to trigger onCascade behavior on foreign keys midway during the transaction. Sqlite recently added support for an `upsert` clause that instead performs insert/update, avoiding any deletion of records. Unfortunately it's only available on newer versions Android and so Room doesn't support it either.
This commit mimics upsert clause by attempting to always insert records and then updating them if insertions fail with conflicts.
> Upsert records when saving Patient and PatientAddress

- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
We manually change the thread to IO for refreshing user status which was causing the test to be flaky.
> Override IO scheduler to Trampoline in PatientsScreenControllerTest

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/di/NetworkModule.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreen.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenController.kt
- app/src/main/java/org/simple/clinic/home/patients/PatientsScreenEvents.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/patient/PatientSummaryResult.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModule.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenEvents.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/main/res/layout/patients_summary_appointment_saved.xml
- app/src/main/res/layout/patients_summary_saved.xml
- app/src/test/java/org/simple/clinic/home/patients/PatientsScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- app/src/test/java/org/simple/clinic/patient/PatientSummaryResultTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
- router/src/main/java/org/simple/clinic/router/screen/ScreenRouter.kt
There is one issue for which a separate PR has been opened.
If a prescription is deleted from Patient Summary, we are not detecting that as a change. This happens because the query in the controller fetches only prescribed drugs and not deleted drugs, hence we cannot check that row.
> Show transient snackbar in patient screen 

- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentSheetController.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/test/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentSheetControllerTest.kt
This commit is another reminder why we need Database triggers to automatically set rows as "dirty" when they are updated on device. We were seeing a bug where canceled/dismissed appointments were coming back to the overdue list after a sync with the server. This was happening because updates to appointments were not getting synced with the server. They were instead getting replaced by server copies.
> Fix: Update updated-at timestamp when updating appointments

- app/schemas/org.simple.clinic.AppDatabase/21.json
- app/src/androidTest/java/org/simple/clinic/MigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/di/NetworkModule.kt
- app/src/main/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentEvents.kt
- app/src/main/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentSheet.kt
- app/src/main/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentSheetController.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentCancelReason.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentPayload.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/storage/Migration_20_21.kt
- app/src/test/java/org/simple/clinic/home/overdue/removepatient/RemoveAppointmentSheetControllerTest.kt
- app/src/test/java/org/simple/clinic/overdue/AppointmentCancelReasonTypeAdapterTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
Enums are great for representing constants as they offer a type-safe API for usage, but blow-up when unknown strings are received from the server. Our JSON library, Moshi, provides a way to use a default enum as a fallback for unknown strings, but that results in the original string getting lost. When the enum has to be sent back to the server during our two way sync, there's no way to retrieve the actual value.
This commit replaces enums with sealed classes for storing Appointment cancellation reasons. The conversion of cancellation reason strings <-> sealed classes happen only when they're being read, allowing us to store the strings received from the server as-is. The usages also get to keep their type-safe API. Kotlin FTW!
> Store appointment cancel reason enums as raw strings

- app/src/androidTest/java/org/simple/clinic/DatabaseMigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/MigrationAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/MigrationTestHelperWithForeignConstraints.kt
- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
We've made mistakes in the past where we would write tests for a migration but forget to include it in the list of migrations for creating AppDatabase. This PR should reduce this problem by unifying how migrations are provided to both the tests and to creation of AppDatabase.
I spent some time with [AutoService](https://github.com/google/auto/tree/master/service) for dynamically finding all migrations instead of manually maintaining a list, but using it seems to be a pain right now until [this commit](https://github.com/google/auto/commit/af1e5daff849b4762062018b9e8bce1716bfc8b0) gets released.
>  Provide list of migrations separately in DI module

- app/src/main/java/org/simple/clinic/sync/DataSync.kt
- app/src/main/java/org/simple/clinic/util/ErrorResolver.kt
I tested this by adding a bunch of `doOnError()` blocks in the Rx chain and manually throwing `TraceurExceptions`:
```kotlin
private fun sync(): Completable {
return patientSync.sync()
.andThen(Completable.mergeArrayDelayError(
bloodPressureSync.sync(),
prescriptionSync.sync(),
appointmentSync.sync(),
communicationSync.sync(),
medicalHistorySync.sync(),
facilitySync.sync(),
protocolSync.sync()
))
.doOnError { e ->
TraceurException.create().appendTo(e)
}
.doOnError { e ->
TraceurException.create().appendTo(e)
}
.doOnError { e ->
TraceurException.create().appendTo(e)
}
.doOnError(logError())
.onErrorComplete()
}
```
> Improve filtering of network related errors before reporting to Sentry

- app/src/androidTest/java/org/simple/clinic/TestClinicApp.kt
- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetEvents.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialogController.kt
- app/src/main/java/org/simple/clinic/patient/PatientConfig.kt
- app/src/main/java/org/simple/clinic/patient/PatientFuzzySearch.kt
- app/src/main/java/org/simple/clinic/patient/PatientModule.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/main/res/layout/sheet_blood_pressure_entry.xml
- app/src/test/java/org/simple/clinic/bp/BloodPressureRepositoryTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialogControllerTest.kt
- app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
- Exclude deleted blood pressures from Patient Summary.
- Exclude deleted blood pressures from Search Results.
- Remove search v1 related feature flag and unused methods.
> Exclude deleted Blood Pressures from UI (Part 1)

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureConfig.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureModule.kt
- app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerV2.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTestV2.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/163046626
- Excluded deleted blood pressures from overdue appointments.
- Removed feature flag for toggling the "Remove Blood Pressure" feature.
> Exclude deleted blood pressures (Part 2)

- app/src/androidTest/java/org/simple/clinic/TestClinicApp.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityListItem.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityListItemBuilder.kt
- app/src/main/java/org/simple/clinic/location/LocationRepository.kt
- app/src/main/java/org/simple/clinic/location/LocationUpdate.kt
- app/src/main/java/org/simple/clinic/registration/RegistrationConfig.kt
- app/src/main/java/org/simple/clinic/registration/RegistrationModule.kt
- app/src/main/java/org/simple/clinic/registration/facility/FacilitiesAdapter.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenController.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenEvents.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreen.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreenController.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreenEvents.kt
- app/src/main/java/org/simple/clinic/util/Clocks.kt
- app/src/main/java/org/simple/clinic/util/RuntimePermissions.kt
- app/src/main/res/layout/list_facility_selection_option.xml
- app/src/main/res/layout/list_facility_selection_progress.xml
- app/src/main/res/values/styles.xml
- app/src/sharedTest/java/org/simple/clinic/util/TestClocks.kt
- app/src/test/java/org/simple/clinic/facility/change/FacilityListItemBuilderTest.kt
- app/src/test/java/org/simple/clinic/location/LocationUpdateTest.kt
- app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreenControllerTest.kt
This PR brings brings a portion of changes towards this feature:
https://www.pivotaltracker.com/story/show/158963954
Major changes:
- Discard stale location updates that are older than 10m
- Hide suggested facilities once the user starts searching facilities
- Read user location only when permission is granted
> Facility selection: discard stale location updates

- doc/arch/001-screen-controllers.md
- doc/arch/002-bottom-sheets.md
https://www.pivotaltracker.com/n/projects/2184102/stories/159982880
The image URLs are broken because they're pointing to `master`. They'll start working once this branch gets merged. I considered uploading them on Imgur instead, but I think it's better to contain the images inside the project. This ADR has already been reviewed by @pratul so I guess it's fine to have broken image links for this PR. 
If you still want to see the images, here's the same ADR hosted on dropbox paper: https://paper.dropbox.com/doc/ADR-Using-Activity-for-bottom-sheets-instead-of-Fragment--AZLLknf6gBx5fQOnxopRsvVbAg-tL4ox6oqIkHo3xTtBr5vc
>  Add an ADR for documenting why we use a custom bottom sheet widget

- app/src/main/java/org/simple/clinic/home/HomePagerAdapter.kt
- app/src/main/java/org/simple/clinic/home/HomeScreen.kt
The WebView in "Progress" tab is expensive to load and freezes the app for a good 1-2s when the tab is clicked. Instantiating it when the ViewPager is starting solves it at the expense of theoretically slightly delaying the app startup. The delay seems to be unnoticeable in my limited testing so this looks harmless to me.
**Note for reviewer**: please profile the app startup and let me know if you notice a difference before and after applying this commit. We could try delaying the inflation of WebView to potentially improve this further.
> Speed up showing of Progress tab by instantiating it on app start

- app/build.gradle
- app/src/debug/google-services.json
- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/main/java/org/simple/clinic/di/NetworkModule.kt
- app/src/main/java/org/simple/clinic/patient/PatientModule.kt
- app/src/main/java/org/simple/clinic/phone/OfflineMaskedPhoneCaller.kt
- app/src/main/java/org/simple/clinic/phone/PhoneNumberMaskerConfig.kt
- app/src/main/java/org/simple/clinic/remoteconfig/FirebaseRemoteConfigCacheExpiration.kt
- app/src/main/java/org/simple/clinic/remoteconfig/RemoteConfigSync.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
- app/src/production/google-services.json
- app/src/sandbox/google-services.json
- app/src/staging/google-services.json
- app/src/test/java/org/simple/clinic/home/overdue/OverdueScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/phone/OfflineMaskedPhoneCallerTest.kt
- app/src/test/java/org/simple/clinic/remoteconfig/RemoteConfigSyncTest.kt
- build.gradle
https://www.pivotaltracker.com/story/show/164954589
This PR introduces Firebase remote config and wires it for our phone number masking feature. Rest of the feature configs are still hardcoded in the app.
Wiring a config object with `FirebaseRemoteConfig` is very verbose right now. It feels like working with JSON where we're forced to hand-write type adapters. I'm going to write a reflection based parser so backing configs with firebase won't require a lot of extra effort.
We've four Firebase projects, one each for debug, sandbox, demo and production. The debug project should be available to everyone in the project. 
The [debug project](https://console.firebase.google.com/u/2/project/simple-org/config) already has config values for phone number masking so you can try playing with them. …
> Remotely configure phone number masking

- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsController.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsItemType.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
Whenever we scroll, the data in the patient results RecyclerView
seems to update to incorrect values. This was happening because of the
usage of lazy to instantiate the views and those views not updating
everytime the ViewHolder updated. To fix this: we have used custom
ViewHolder for patient search result row.
Story: https://www.pivotaltracker.com/story/show/165308633
> Fix: Wrong data being shown in patient search results.

- README.md
The "Running the app" section isn't required because anyone who is building an Android app from the source, will either know how to run it on an emulator/device, or figure it out elsewhere.
> Cleanup README a bit more

- doc/QUIRKS.md
When the document was moved to the `doc/` folder, the image reference was broken. This fixes the reference.
> Fix image reference in docs

- app/src/main/java/org/simple/clinic/drugs/selection/dosage/DosageAdapter.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityListItem.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueListAdapter.kt
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Changes:
- Bump gradle plugin to 3.4.0
- Bump Kotlin version to 1.3.31
- Bump gradle version to 5.4.1
I also ended up having to suppress a new lint check that was added in AGP 3.4.0 in DIffUtils because it doesn't seem to realize that we are using sealed classes.
> Update build tooling to latest versions

- app/src/main/res/layout/screen_app_lock.xml
Pivotal Story Link: https://www.pivotaltracker.com/story/show/165815696
> Hide "Not You?" button on app lock screen

- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/main/java/org/simple/clinic/patient/Patient.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/util/TimeFunctions.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
- app/src/test/java/org/simple/clinic/util/TimeFunctionsTest.kt
Pivotol story -> https://www.pivotaltracker.com/story/show/166119194
One part of this story is remaining where we need to consider deleted BPs and update `recordedAt` accordingly.
> Update patient recordedAt based on oldest BP

- app/src/main/java/org/simple/clinic/ReleaseClinicApp.kt
Earlier, we were initializing them as soon as the clas was instantiated
but this caused a crash when we tried to access them in ClinicApp. This
changes the creation to a getter so that they are initialized after
onCreate() is called
> Fix crash when starting the Release build

- app/src/main/res/layout/sheet_phone_mask.xml
https://www.pivotaltracker.com/story/show/166231978
> Fix: Buttons should not be cut off in the phone mask bottom sheet

- app/src/main/java/org/simple/clinic/ClinicApp.kt
- app/src/main/java/org/simple/clinic/ReleaseClinicApp.kt
Since they are accessed from the Application's onCreate method only,
we can safely skip synchronized initilization.
> Remove synchronization when initiailizing analytics reporters

- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreenController.kt
Bug Tracker Link: https://www.pivotaltracker.com/story/show/166494209
Post-mortem:
We refactored the AppointmentRepository to accept the current facility
externally instead of looking it up itself in a past commit. As part of
that change, we updated OverdueScreenController to load the facility
and query the method like so -
val facilityStream = userSession
.requireLoggedInUser()
.switchMap { facilityRepository.currentFacility(it) }
events.ofType<ScreenCreated>()
.withLatestFrom(facilityStream)
.flatMap { (_, facility) ->
appointmentRepository.overdue(facility)
}
The failure happened because the ScreenCreated event was getting
emitted *BEFORE* the facility was queried, so when the
wlf(facilityStream) is called, there is no facility yet as part of that
stream to combine, so the overdue …
> Fix: Overdue Appointments not loading

- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsView.kt
- app/src/main/res/layout/recent_patients.xml
I thought I had added the code to disable nestedscrolling in the recyclerview. I must have been mistaken. This seems to have fixed the issue.
https://www.pivotaltracker.com/story/show/165815684
> Fix: Taps sometimes don't work in recent patients list

- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchResults.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchView.kt
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchViewController.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsItemType.kt
- app/src/test/java/org/simple/clinic/searchresultsview/PatientSearchViewControllerTest.kt
- app/src/test/java/org/simple/clinic/searchresultsview/SearchResultsItemTypeTest.kt
https://www.pivotaltracker.com/story/show/166784013
https://www.pivotaltracker.com/story/show/166783916
This is needed to ease the transition to the local view model for the `PatientSearchResultView` widget. I didn't want to do this as part of another extremely large PR.
> Move generation of list items in search results screen to the view from controller

- app/src/debug/res/values/strings.xml
- app/src/sandbox/res/values/strings.xml
In the launcher the simple app icons are scattered across because the variant names are placed before the app name. This PR ensure all the app variants are grouped together in the launcher by moving the variant names as suffixes.
> Group simple launcher icons

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
https://www.pivotaltracker.com/story/show/167870079
This PR handles excluding patients when searching by name, short code and phone number. The rest of the tasks in the story will be handled in another PR.
> Exclude deleted patients when searching

- app/src/main/java/org/simple/clinic/patient/filter/WeightedLevenshteinSearch.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- spellfix/.gitignore
This PR bumps the Gradle plugin to 3.5.0. In addition, it updates libraries which use KAPT (Dagger, Room) to the latest versions and enabled KAPT incremental annotation processing.
> Update to Android Studio 3.5

- .codeclimate.yml
This adds a CodeClimate quality config file (https://docs.codeclimate.com/docs/advanced-configuration)
to the repository. Currently, it is set to the same defaults that are
configured on the web app, but it serves as a starting point for us to
tweak in the future.
> Add CodeClimate configuration to the repository

- mobius-migration/src/main/java/org/simple/mobius/migration/MobiusTestFixture.kt
- mobius-migration/src/test/java/org/simple/mobius/migration/EventsOnlyTest.kt
- mobius-migration/src/test/java/org/simple/mobius/migration/MobiusTestFixtureTest.kt
- mobius-migration/src/test/java/org/simple/mobius/migration/fix/Counter.kt
- mobius-migration/src/test/java/org/simple/mobius/migration/fix/EventsViaEffects.kt
Previously the fixture was able to test only states that were produced in response to external events dispatched through an event source. This implementation also works with state machines that are driven by events generated by the effect handler.
> Enable testing state machines just driven by effects

- build.gradle
In Heap 1.1.1, they switched to a new version of the Protobuf library
(https://docs.heap.io/docs/android-changelog#section--1-1-1-2019-08-16).
However, we started seeing crash reports that Heap was crashing on lower
API versions because it was accessing methods that did not exist (tested
on API 21; see https://sentry.io/share/issue/6c4a9e19d17e4d2081798ee208a0a652/).
Downgrading to Heap 1.1.0 fixes this problem.
> Downgrade Heap -> 1.1.0

- mobius-migration/src/test/java/org/simple/mobius/migration/EventsOnlyTest.kt
- mobius-migration/src/test/java/org/simple/mobius/migration/MobiusTestFixtureTest.kt
This also means,
1. Our pre-push hook should run `./gradlew test` so that we can run tests present in all modules.
2. Our CI didn't fail, so we should revisit our CI setup as well.
> Fix failing tests due to introduction of the start function

- app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityView.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/java/org/simple/clinic/mobius/MobiusDelegate.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingScreen.kt
- Manage event subscription on its own
- Remove temporal coupling from `onRestoreInstanceState`
> Mobius delegate improvements

- app/src/main/java/org/simple/clinic/mobius/MobiusDelegate.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryEffect.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryLogic.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryModel.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreenController.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreenEvents.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryViewRenderer.kt
- app/src/main/java/org/simple/clinic/patient/OngoingNewPatientEntry.kt
- app/src/test/java/org/simple/clinic/newentry/PatientEntryScreenControllerTest.kt
- mobius-migration/src/main/java/org/simple/mobius/migration/ImmediateEventSource.kt
The following logic was moved from `PatientEntryScreenController` to Mobius
- Screen created
- Date of birth & age updates
- Toggle identifier section
- Scrolling to the bottom of the screen when gender is selected for the first time
> Strangulate logic from screen controller to Mobius

- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEffect.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryInit.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryModel.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryUpdate.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryViewRenderer.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
The `SheetCreated` events are instrumental in bringing in Mobius. I have extracted these event dispatches as a function so that we can create and call the `fixture.start()` function in either `New` or `Update` mode.
> Prepare tests to introduce Mobius fixture

- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEffect.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryInit.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheet.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetController.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryUpdate.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntrySheetControllerTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureValidationTest.kt
- Prefill date when updating a BP entry
- Move BP validation when date button / save button is clicked
- Remove auto-dismiss BP entry sheet when synced BP was removed
- Go to date entry screen
> Migrate more functionality to Mobius

- app/src/main/java/org/simple/clinic/activity/TheActivity.kt
- app/src/main/java/org/simple/clinic/activity/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/di/InjectorProviderContextWrapper.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingScreen.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingScreenInjector.kt
- app/src/main/java/org/simple/clinic/util/KotlinFoo.kt
https://www.pivotaltracker.com/story/show/169253555
The current injection method for screens does not allow us to use alternate injectors for a given Screen and couples it tightly to a specific activity. This PR is meant to give us a way to abstract the injector from the screen so we can move a Screen to a different activity in stages.
> Provide alternate injection method for screens

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/debug/java/org/simple/clinic/widgets/ProxySystemKeyboardEnterToImeOption.kt
- app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheet.kt
- app/src/main/java/org/simple/clinic/home/overdue/appointmentreminder/AppointmentReminderSheet.kt
- app/src/main/java/org/simple/clinic/home/patients/LoggedOutOnOtherDeviceDialog.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt
- app/src/test/java/org/simple/clinic/patient/PatientMocker.kt
- build.gradle
- Bump target SDK to 29
- This version added a bunch of nullability and type parameters to the platform, so had to fix compilation errors related to those
- Bumped version of the ViewPump library to the latest version since the version we were using did not support API level 29 and would crash.
Tested on the following API levels:
- Lollipop (21)
- Android 10 (29)
> Add support for targeting API level 29

- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenController.kt
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenControllerTest.kt
This fixes these crashes (i.e. Kotlin NPE when **Edit** button is clicked before the profile is populated).
https://sentry.io/organizations/resolve-to-save-lives/issues/searches/2487760/?project=1212614&statsPeriod=14d
> Hide the Edit button in patient summary until the profile is populated

- app/src/main/java/org/simple/clinic/remoteconfig/RemoteConfigSync.kt
- app/src/main/java/org/simple/clinic/sync/DataSync.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt
- app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorViewController.kt
- app/src/main/java/org/simple/clinic/user/UnauthorizeUser.kt
- app/src/main/java/org/simple/clinic/util/ErrorResolver.kt
- app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorViewControllerTest.kt
- app/src/test/java/org/simple/clinic/user/UnauthorizeUserTest.kt
- app/src/test/java/org/simple/clinic/util/ErrorResolverTest.kt
This is needed to show appropriate errors when the app manifest fails to be fetched.
> Add more comprehensive types to the http error resolver

- router/src/main/java/org/simple/clinic/router/screen/BaseViewGroupKeyChanger.kt
Earlier, we were logging the entire key in the screen key changer as
breadcrumbs to the crash reporter. However, the key might end up
having references to sensitive information and might accidentally log
this data to the crash reporting service.
This commit changes this to only log the type of the key instead of the
entire key.
> Stop logging the entire key in the screen key changer

- app/build.gradle
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/widgets/ageanddateofbirth/UserInputDateValidator.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryLogicTest.kt
- app/src/test/java/org/simple/clinic/bp/entry/BloodPressureValidationTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenCreatedTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenFormTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenSaveTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditablePatientEntryTest.kt
- app/src/test/java/org/simple/clinic/newentry/PatientEntryScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/newentry/PatientEntryUpdateTest.kt
- app/src/test/java/org/simple/clinic/newentry/UserInputDateValidatorTest.kt
- app/src/test/java/org/simple/clinic/patient/OngoingNewPatientEntryTest.kt
https://www.pivotaltracker.com/story/show/168775283
While this might be an IDE bug, it's still a problem that's slowing us down when we write tests. I fixed it by changing the `UserInputDateValidator` to accept the clock instead of the timezone. I could remove the extra threetenbp import in the tests after that.
> Fix broken threentenbp imports in tests

- app/build.gradle
- app/src/main/java/org/simple/clinic/di/AssistedInjectModule.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivity.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityEffectHandler.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityModule.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenCreatedTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenFormTest.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenSaveTest.kt
- app/src/test/java/org/simple/clinic/setup/SetupActivityEffectHandlerTest.kt
- build.gradle
Until now, we were manually creating effect handlers in the screen when connecting the Mobius loop. This is cumbersome since it requires us to inject the dependencies which the effect handler requires into the screen first and then construct the effect handler.
We should inject the effect handlers directly, but in most cases, the effect handler also needs dynamic dependencies at runtime (for example, a reference to the view to perform UI actions), which prevents us from doing constructor injection.
This PR uses [AssistedInject](https://github.com/square/AssistedInject) as a way to reduce this boilerplate around constructing effect handlers. This PR does not convert all the effect handlers at the moment, only one for an `Activity` and another for a `Screen` to show how this integration …
> Introduce Assisted Injection for effect handlers

- .github/workflows/android.yml
This would decrease the actions run time by 2~3 minutes and also the cache is not doing anything significant
> Remove GitHub Actions gradle cache

- app/build.gradle
- app/proguard-rules.pro
- app/src/debug/AndroidManifest.xml
- app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
- app/src/debug/java/org/simple/clinic/ReadOnlySqliteDatabaseDriver.kt
- app/src/debug/java/org/simple/clinic/di/FlipperModule.kt
- app/src/debug/java/org/simple/clinic/di/network/HttpInterceptorsModule.kt
- app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialog.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/home/patients/LoggedOutOnOtherDeviceDialog.kt
- app/src/release/java/org/simple/clinic/di/FlipperModule.kt
- build.gradle
We had integrated [Stetho](http://facebook.github.io/stetho/) for debugging the app during development. Stetho is not being actively developed, and they have an alternate tool called [Flipper](https://fbflipper.com/), which they recommend instead.
This PR replaces the usage of Stetho in the app with Flipper, along with integration for the following plugins:
> Replace Stetho with Flipper

- app/src/androidTest/java/org/simple/clinic/TestData.kt
- app/src/main/java/org/simple/clinic/Globals.kt
- app/src/main/java/org/simple/clinic/widgets/ageanddateofbirth/UserInputAgeValidator.kt
The test generator would use a random number in the range [0, 100] for the age when creating a patient. However, we changed the age limit to have a minimum value of 1. This
ended up causing flakiness in some test runs where the random age
generator would create a patient with an age = 0.
This commit fixes the issue by extracting the minimum and maximum age
limits to global constants and using that in the test data generation.
> Fix flaky test when recording a patient

- .github/scripts/commit_and_push.sh
- .github/workflows/code_formatting_checks.yml
Instead of creating the branch name in `Create PR` step. Get the already created branch name from `Commit and Push` step and set it as env variable for `Create PR` step.
> Get branch name from `Commit and Push` step

- .github/workflows/code_formatting_checks.yml
- Run code formatting action only on weekdays
- Use `GITHUB_ACCESS_TOKEN` instead of `GITHUB_TOKEN`
**Required**
- Create `GITHUB_ACCESS_TOKEN` secret with a personal access token with repo scope.
> Change code formatting action run timings

- app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientEffectHandlerTest.kt
This is a temporary fix to stop an existing Bangladesh national ID from getting set to a blank identifier when editing a patient.
The real solution is to soft-delete the `BusinessId` when clearing the field and saving. This is captured in another story here: https://www.pivotaltracker.com/story/show/170717757
> Fix blank Bangladesh national ID getting saved while editing a patient

- README.md
Story: https://www.pivotaltracker.com/story/show/170764753
This PR adds more instructions to the repo's README, describing how to go from cloning the repo to running the app on an emulator locally. Notable additions are:
* Installation of the NDK package (for now. I understand this is soon to be no longer required)
* Creating a run/debug configuration
* Setting up an AVD
* Setting the right `qaDebug` build
> Documentation - More Run Instructions

- README.md
The `README` was missing setup instructions for the JDK. Added this in.
> Add instructions for setting up the JDK

- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffect.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandler.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEvent.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryInit.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryModel.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenController.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRenderer.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdate.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenControllerTest.kt
https://www.pivotaltracker.com/story/show/169674952
This sets up the Mobius loop in the `NewMedicalHistoryScreen`. In the next PR, the screen events will be migrated to Mobius.
> New Medical History cleanup #2

- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenModel.kt
- If we check for both null and empty list, edge case of removing all the BPs is not being handled. In order to fix that only null check is being made and the empty list is being rendered on the UI.
> Fix empty blood pressures state in BP history screen

- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/res/layout/screen_patient_summary.xml
After merging in the new BP summary view, the UI tests in the screen
started breaking because there were two views on the screen with the
same ID: the patient edit button and the button on the BP item to
edit it.
This commit renames the button used to open the Edit patient screen so
that the clashes of the IDs will no longer happen.
> Rename `editButton` -> `editPatientButton` in patient summary screen

- app/src/main/res/layout/screen_patient_summary.xml
https://github.com/simpledotorg/simple-android/pull/1127 introduced a bug where `contactTextView` overlaps with `bpPassportTextView` or `bangladeshNationalIdTextView` depending on the visibility. 
In order to fix this I have moved the `bpPassportTextView` & `bangladeshNationalIdTextView` into a container `identifiersContainer` and use that as anchor for `contactTextView`.
> Fix `contactTextView` overlapping 

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/facility/FacilitySyncApi.kt
This is so that the `diabetesManagementEnabled` flag can get synced.
> Bump facility resync token to 2

- app/build.gradle
- app/ndk-versions.gradle
- app/proguard-rules.pro
- app/src/main/java/org/simple/clinic/security/pin/PinEntryCardView.kt
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Bump gradle wrapper to 5.6.4
- Fix lint issues in `PinEntryCardView`
- Add new proguard rules
> Bump AGP to 3.6.0

- build.gradle
https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-3-70-released/
> Bump Kotlin version to `1.3.70`

- app/src/androidTest/java/org/simple/clinic/bloodsugar/sync/BloodSugarSyncAndroidTest.kt
Since `HbA1c` support is not added on the server side yet, the sync test will fail if we use `HbA1c`. To avoid that, for now, we are setting the blood sugar type to `RBS`
> Fix `BloodSugarSyncAndroidTest`

- app/src/main/res/values/styles_v2.xml
The `letterSpacing` and `lineSpaceExtra` for style `Body2Bold` were incorrect.
Fixing these to match Zeplin.
> Fix `Body2Bold` style

- app/src/androidTest/java/org/simple/clinic/medicalhistory/MedicalHistoryRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
This is mainly to avoid cases where medical history may not be synced which may cause app to crash when user back clicks or clicks on the done button.
> Return `MedicalHistory` or default value for patient immediately

- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientView.kt
- app/src/main/java/org/simple/clinic/widgets/Views.kt
Back press when showing `linkIdWithPatientView` should cancel the link id with the patient, this will take back the user to search results instead of the home screen.
https://www.pivotaltracker.com/story/show/171308016
Since `LinkIdWithPatientView` is a subview of `PatientSummaryScreen` I am not sure if we can handle the back clicks separately for that view, so instead I just went this approach. But maybe once we move towards the navigation component we can migrate `LinkIdWithPatientView` to a proper bottom sheet?
> Cancel patient link ID on back press

- app/src/androidTest/java/org/simple/clinic/login/LoginUserWithOtpServerIntegrationTest.kt
Previously, the server would accept a login call for an OTP any number
of times. Now, that has changed to only allow verifying an OTP once.
This caused a test to fail because the test was not generating a new
OTP before verifying the login call. This commit fixes the issue by
generating an OTP.
> Fix failing test that verifies login to the server

- app/build.gradle
- build.gradle
We were using a transitive zxing dependency from the QR scanner library. Once we remove the old QR scanner the new one will be broken, adding the zxing dependency to the app gradle.
The zxing android-core dependency we added didn't internally contain the zxing core dependency.
> Add zxing core dependency

- app/src/main/res/values/colors_v2.xml
- app/src/main/res/values/styles_v2.xml
- app/src/main/res/values/theme_material.xml
- build.gradle
We are migrating to bridge theme first so that the existing widget themes don't break. In future, we will remove the bridge theme and use full material components theme and fix broken widget themes.
We can now start using Material components in our app, you can find the necessary style attrs and components [here](https://material.io/components/).
> Migrate to MaterialComponents bridge theme

- app/src/main/java/org/simple/clinic/overdue/AppointmentModule.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetController.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheetControllerTest.kt
This was done as a part of https://www.pivotaltracker.com/story/show/172194296 in order to simplify the injection of `AppointmentConfig`.
Breaking this out into a separate story since it's technically unrelated to the feature so we can review and merge this in sooner.
> Simplify schedule appointment screen controller

- .github/workflows/ci_checks.yml
Currently, we only verify that the **SANDBOX** environment builds on CI checks. The problems with this are:
- The only thing this verifies is the R8 configuration files.
- Things like build specific Dagger setup, etc are not verified.
This PR changes the CI checks to run verifications on ALL our release variants. It does this using a [build matrix](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix), which allows all the different builds to happen in parallel.
> Define a build matrix to verify all release builds on CI

- app/src/androidTest/java/org/simple/clinic/bp/BloodPressureHistoryListItemDataSourceTest.kt
`BloodPressureRepositoryAndroidTest#getting_the_blood_pressure_count_immediate_for_a_patient_should_work_correctly`
was detected as 10% flaky over the last few days. I investigated this
and found out the cause:
- `BloodPressureHistoryListItemDataSourceTest` was added which creates
some data in the `BloodPressureMeasurement` table, but does not clean
up after itself.
- The flaky test in question asserts the total count of BPs present
in the database before running its assertions.
- When the test was run by itself, it would work fine.
- When the test was run *after* `BloodPressureHistoryListItemDataSourceTest`,
it would first fail because the BP count was not what it expected, then
the test rule would clear the databases, then the flaky test rule would
execute it again and it would pass. …
> Fix flaky test in `BloodPressureRepositoryAndroidTest`

- app/src/main/java/org/simple/clinic/util/ParcelableOptional.kt
This is required for https://www.pivotaltracker.com/story/show/172194270.
The reason this class has been added is because the model *requires* the notion of an `Optional`, but it also has to be `Parcelable`, which our current `Optional` class cannot be.
> Add separate `ParcelableOptional` to use in Parcelable classes

- app/src/main/java/org/simple/clinic/home/overdue/phonemask/PhoneMaskBottomSheetController.kt
- app/src/main/java/org/simple/clinic/phone/PhoneCaller.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueScreenControllerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/phonemask/PhoneMaskBottomSheetControllerTest.kt
- app/src/test/java/org/simple/clinic/phone/PhoneDialerTest.kt
This was done to support https://www.pivotaltracker.com/story/show/172194270, to make the task of calling numbers easier.
> Change phone caller methods to synchronous calls

- app/build.gradle
- build.gradle
https://www.pivotaltracker.com/story/show/170332759
I had to bump the appcompat version to `1.2.0-beta01` to get it to work. Since beta releases are more or less stable, and what is expected to change would only be API contracts, I think this is a safe tradeoff.
> Exclude appcompat 1.1.0 from the dependency tree

- .github/workflows/ci_checks.yml
When running checkout in `fix_strings_ellipsise` use `GITHUB_ACCESS_TOKEN` to be able to push back as a user to the repo.
https://www.pivotaltracker.com/story/show/172579029
> Checkout using `GITHUB_ACCESS_TOKEN`

- .github/workflows/ci_checks.yml
- gradle.properties
- Pin the current NDK version to the latest available.
- Remove the switching of NDK version for the android tests since the version of the NDK installed on the macOS runner is [updated](https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#android-utils).
> Update NDK version

- .github/workflows/ci_checks.yml
- CHANGELOG.md
https://www.pivotaltracker.com/story/show/172909087
Because we were using a single quote when converting the PR body to a string, it started considering the markdown syntax as "commands". In order to fix that, I have changed it to convert the received PR description to a proper double-quoted string so that it will ignore the "command" blocks inside the string.
A sample **markdown** [link](https://github.com/simpledotorg/simple-android) to test it.
> Fix PR description CI check when using markdown syntax

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/PatientSummaryInit.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryInitTest.kt
We are now checking if teleconsultation is enabled for the facility and user is logged in before making this call.
https://www.pivotaltracker.com/story/show/172935677
> Fix fetching teleconsultation info on patient summary screen restore

- .github/workflows/ci_checks.yml
- CHANGELOG.md
- app/build.gradle
https://www.pivotaltracker.com/story/show/164202222
This was blocked on Heap Analytics earlier since their plugin was not supporting Android App Bundles. But we no longer use Heap, so we should be able to switch.
> Add support for Android App Bundles

- app/src/main/AndroidManifest.xml
I have accidentally removed the `DosagePickerSheet` activity entry from the `AndroidManifest`, that caused the app to crash when we are starting the `DosagePickerSheet`
> Fix `DosagePickerSheet` crash

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
https://www.pivotaltracker.com/story/show/172910991
This was happening because of a race condition of dismissing and showing snackbar again when in airplane mode.
> Retrying on a failed teleconsultation fetch only works once

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/widgets/Views.kt
This might be occurring because some other view might be requesting focus when laying down the layout. So adding a slight delay when posting should resolve this issue. I have done this for the extension itself to avoid any issues related to this in other screens.
> Fix keyboard not opening in app lock screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt
- mobius-base/src/main/java/org/simple/clinic/mobius/DeferredEventSource.kt
- mobius-base/src/main/java/org/simple/clinic/mobius/MobiusDelegate.kt
- mobius-base/src/main/java/org/simple/clinic/mobius/MobiusFoo.kt
- mobius-migration/src/main/java/org/simple/mobius/migration/MobiusTestFixture.kt
- mobius-migration/src/test/java/org/simple/mobius/migration/MobiusTestFixtureTest.kt
This PR fixes https://www.pivotaltracker.com/story/show/173509335.
The reason this was happening is because of the following reasons:
- Mobius subscribes to the events in `onStart()` since `ScheduleAppointmentSheet` is an activity.
- The event that forwards the facility change to the loop is emitted in `onActivityResult()`.
- `onActivityResult` gets invoked *before* `onStart()` and the event is lost because the loop has not yet been setup at this point.
According to an issue ([LINK](https://github.com/spotify/mobius/issues/42)) on the Mobius repository, they solve this case using an alternate event source that caches these events until the source gets subscribed to. This PR implements the fix by adding support for these sources.
> Fix appointment facility selection change does not work anymore

- app/src/main/res/values/strings.xml
We need to escape percent symbols in string resources by using the double percent sequence (`%%`). However, it seems like the Android toolchain only throws an error if the percent symbol is present in the middle of the string and not at the end.
So we can have situations where a source string in English ("Value cannot be less than 3%") works fine, but when it gets translated to another language, the "3%" part moves to a different location and starts throwing errors.
In order to fix this, we will use the unicode symbol for the percent character whenever it is meant to be displayed on screen and translated.
> Use unicode characters for percent symbol in string resources

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
Ticket: https://app.clubhouse.io/simpledotorg/story/414/starting-a-teleconsultation-session-crashes-in-some-scenarios
The current facility was being lazily queried and stored in the `PatientSummaryEffectHandler`
via a `dagger.Lazy` class. When the screen is created, we query this as
part of the screen setup which runs on a background thread. However, on
screen restoration we do not query it if it was already fetched.
This means that a database query would be made the next time the lazy
property is invoked, which would happen when there are multiple doctors
available for teleconsultation and we show the picker sheet. This runs
on the UI thread and caused a crash.
This commit fixes the issue by passing in the facility via the effect
since the model already has it.
> Fix occasional crash when starting a teleconsultation session

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/res/values/strings.xml
https://app.clubhouse.io/simpledotorg/story/366/app-crashing-when-phone-number-is-empty-while-editing-patient
> Show phone number empty error in `EditPatientScreen`

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/user/UserSessionAndroidTest.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinEffect.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinEvent.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinUpdate.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameEffect.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameEvent.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationNameUpdate.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffect.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEvent.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUpdate.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinEffect.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinEvent.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinUpdate.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingEffect.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingEvent.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingUpdate.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/test/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinLogicTest.kt
- app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionLogicTest.kt
- app/src/test/java/org/simple/clinic/registration/name/RegistrationNameScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/registration/pin/RegistrationPinScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/registration/register/RegistrationLoadingLogicTest.kt
This instance has been changed so that it is passed from screen to screen and managed by the Android state saving mechanism.
> Stop tracking ongoing registration entry in `UserSession`

- app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityEvent.kt
- app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityUpdate.kt
- app/src/test/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/323/display-patient-s-assigned-facility-in-the-patient-summary-screen
Since this is still part of the assigned facility PR feedback, haven't updated the CHANGELOG.
[*original feedback*](https://github.com/simpledotorg/simple-android/pull/1514#pullrequestreview-451485895)
> Remove `FacilityChanged` event in `AssignedFacilityView`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueInit.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsEffectHandler.kt
- app/src/main/java/org/simple/clinic/user/SessionModule.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueLogicTest.kt
- app/src/test/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/742/home-screen-does-not-update-when-changing-facilities
Both `HomeScreen` and `OverdueScreen` are in the screen where the changing of current facility happens. Since `FacilityChangeActivity` is a new activity and not a new screen in `TheActivity`, returning to `HomeScreen` after switching the current facility does not cause the screen to be reinitialized and thus, does not notify a change in the current facility.
This PR fixes the issue by changing the two screen to observe the current facility for changes instead of just loading it once.
> Fix issue where recent and overdue patients on home screen would not update after changing facilities

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/HomeScreen.kt
- app/src/main/res/layout/screen_home.xml
https://app.clubhouse.io/simpledotorg/story/791/the-app-crashes-when-navigating-back-to-the-home-screen-from-any-other-screen
This was caused due to a state restoration issue because the home screen
root layout ID was the same as the ID of the sync indicator view on
the patients tab, which cause the wrong state to be returned during
view inflation.
This commit fixes the issue by changing the layout ID of the home screen.
> Fix crash on returning to the home screen from any other screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/facilitypicker/FacilityPickerView.kt
https://app.clubhouse.io/simpledotorg/story/1030/app-crashes-during-registration-when-it-is-backgrounded
> Fix crash on saving the state during registration facility selection

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
Disabled the sync since the APIs are not yet available.
See [this Slack discussion](https://simpledotorg.slack.com/archives/CV9V1DWLV/p1598425138008400) for further info.
> Disable Telemedicine Facility Info sync

- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenUi.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryViewRenderer.kt
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/test/java/org/simple/clinic/summary/PatientSummaryViewRendererTest.kt
A small change to #1659, I forgot to move the rendering of the teleconsult log button to view renderer. I have also added `logTeleconsultButton` instead of trying to reuse existing `doctorButton`.
> Move showing teleconsult log button to view renderer

- app/src/androidTest/java/org/simple/clinic/sync/TeleconsultationSyncIntegrationTest.kt
- app/src/main/java/org/simple/clinic/main/TypedPreference.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModule.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultFacilityInfoApi.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultationSync.kt
You can find the reference to the conversation where we decided to remove this [here](https://simpledotorg.slack.com/archives/CV9V1DWLV/p1598945680015200)
> Remove `process_token` usage from `TeleconsultationSync`

- lint/src/main/java/org/simple/clinic/lint/ImageSrcDetector.kt
- lint/src/test/java/org/simple/clinic/lint/ImageSrcDetectorTest.kt
Added an option to provide lint fix option that can be used in Android Studio options to replace the existing usages with `app:srcCompat` usage.
In order to try this, please run `app:lintQaDebug` once and then replace any `app:srcCompat` usage with `android:src` and Android Studio should show the error and option to replace the usage.
> Add lint fix option to replace `ImageView#src` usage

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/ClinicApp.kt
Since we were using Retrofit observable calls earlier, certain exceptions were being swallowed by them internally when the stream was disposed and a request was ongoing.
However, since we have moved to synchronous calls, it is up to us to manage disposal of the streams ourselves. I've elected to use the method prescribed by the RxJava error handling docs (See [HERE](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling)) and swallow these exceptions globally.
> Add global error handler to catch RxJava errors that can be ignored

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentRow.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUiActions.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/1144/open-patientsummaryscreen-when-patient-name-is-clicked-in-overdue-list
> Open `PatientSummaryScreen` when patient name is clicked in overdue list

- CHANGELOG.md
- app/src/debug/java/org/simple/clinic/login/AppLockConfigModule.kt
- app/src/main/java/org/simple/clinic/appconfig/AppLockModule.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/login/LoginModule.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockEffectHandler.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockScreenKey.kt
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/main/TheActivityEffect.kt
- app/src/main/java/org/simple/clinic/main/TheActivityEffectHandler.kt
- app/src/main/java/org/simple/clinic/main/TheActivityEvent.kt
- app/src/main/java/org/simple/clinic/main/TheActivityUpdate.kt
- app/src/main/java/org/simple/clinic/main/TypedPreference.kt
- app/src/main/java/org/simple/clinic/storage/MemoryValue.kt
- app/src/test/java/org/simple/clinic/activity/TheActivityControllerTest.kt
- app/src/test/java/org/simple/clinic/login/applock/AppLockScreenLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/1148/stop-storing-app-lock-timestamp-in-shared-preferences
> Change storage of app lock timestamps to be in-memory instead of in shared preferences

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchView.kt
This is temporarily done to stop crashes from persisting lists of
search results in the saved state bundle until paging library v3 is ready.
> Disable state saving and restoration for the search results screen

- app/src/main/res/layout/screen_teleconsult_success.xml
- app/src/main/res/values/shape.xml
The existing `TeleconsultSuccessScreen` UI doesn't match with Figma mockups. So made changes to fix that.
> Refactor `screen_teleconsult_success`

- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordEvent.kt
We would like to know which `TeleconsultationType` is selected when creating the teleconsultation record.
> Pass `TeleconsultationType` to `DoneClicked.analyticsName`

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/78.json
- app/src/androidTest/java/org/simple/clinic/rules/LocalAuthenticationRule.kt
- app/src/androidTest/java/org/simple/clinic/rules/ServerAuthenticationRule.kt
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration78AndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/facility/FacilitySync.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinEffectHandler.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffectHandler.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_78.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/main/java/org/simple/clinic/user/User.kt
- app/src/main/java/org/simple/clinic/user/UserSession.kt
- app/src/test/java/org/simple/clinic/login/pin/LoginPinScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
`FacilitySync` currently uses 'Insert or Replace' when we save facilities into the local database during sync. However, the implementation of this in SQLite ends up triggering a DELETE on conflict and then an insertion.
A consequence of this is that any other table that has a foreign key reference to the facility table will end up getting deleted if a row in the facility table is replaced that has a reference to this row.
This commit removes the foreign key reference on the facility table from the user table and we will rely on the flow in the application logic to ensure that facilities are present.
> Remove foreign keys on facility table from User table

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
https://app.clubhouse.io/simpledotorg/story/1406/fix-deeplink-screens-warning-dialogs-are-displayed-again-when-activity-is-restarted
> Fix deeplink screens & warning dialogs are displayed again when activity is restarted

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/login/applock/ConfirmResetPinDialog.kt
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
- router/src/main/java/org/simple/clinic/router/screen/ScreenRouter.kt
We introduced a bug in a previous commit where the app lock screen could be bypassed by hitting back on the app lock screen and then opening it again before the app lock timer runs out.
This was happening because `TheActivity` would update the app lock timer in `onStop` regardless of whether the app lock was successfully completed or not and the lock at time would be advanced to some point in the future.
> Check the current screen before updating the app lock time

- app/src/androidTest/java/org/simple/clinic/di/TestRetrofitModule.kt
We have less than five users who are current on a build before the country selection screen was added. This means that the fallback country mechanism is mostly unnecessary and we can think of removing it.
The first step in this would be to use the manifest endpoint in tests instead of the fallback. We will remove the fallback mechanism after reaching out to the users who are on older app versions in person and asking them to update.
> Use manifest API endpoint in tests instead of the fallback API endpoint

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/appconfig/Country.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
https://app.clubhouse.io/simpledotorg/story/1535/remove-whatsapp-legal-text-for-ethiopia
> Remove WhatsApp as a channel from the reminder consent in the patient entry screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/widgets/ProgressMaterialButton.kt
https://app.clubhouse.io/simpledotorg/story/590/fix-progressmaterialbutton-avd-not-animating-when-initial-state-is-not-in-progress
> Fix `ProgressMaterialButton` AVD not animating when initial state is not `in-progress`

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/facility/FacilityRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/facility/FacilityRepository.kt
- app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeEffect.kt
- app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeEffectHandler.kt
- app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeEvent.kt
- app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeInit.kt
- app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeModel.kt
- app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeSheet.kt
- app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeUpdate.kt
- app/src/main/java/org/simple/clinic/main/TypedPreference.kt
- app/src/main/java/org/simple/clinic/sync/PurgeOnSync.kt
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
- app/src/test/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeInitTest.kt
- app/src/test/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeUpdateTest.kt
- app/src/test/java/org/simple/clinic/sync/PurgeOnSyncTest.kt
https://app.clubhouse.io/simpledotorg/story/1491/delay-purging-of-data-from-an-older-sync-group-if-the-blocks-have-been-switched-within-a-certain-time-window
> Delay purging of sync group data for a specified time after switching

- CHANGELOG.md
- app/src/main/res/layout/screen_patient_summary.xml
https://app.clubhouse.io/simpledotorg/story/1707/bottom-button-bar-layout-is-broken-on-the-patient-summary-screen-on-some-devices
> Bottom button bar layout is broken on the patient summary screen on some devices

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandler.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsEffectHandler.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/newentry/PatientEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/newentry/PatientEntryScreenLogicTest.kt
- app/src/test/java/org/simple/clinic/search/results/PatientSearchResultsLogicTest.kt
This is being done in preparation for some future refactoring work before we get to the "Faster patient registration" feature.
- Extract patient registration to a use case outside the `PatientRepository` scoped to the patient entry screens
- Unify the patient entry and edit forms in some fashion so we don't need to duplicate most of the code
> Clean up patient repository

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/introvideoscreen/IntroVideoScreen.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingScreen.kt
- app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreen.kt
- app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt
- app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreen.kt
- app/src/main/java/org/simple/clinic/registration/name/RegistrationFullNameScreen.kt
- app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt
- app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreen.kt
- app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingScreen.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryScreen.kt
> Migration app screens to use ViewBinding #1

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/activity/placeholder/PlaceholderScreen.kt
- app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreen.kt
- app/src/main/java/org/simple/clinic/deniedaccess/AccessDeniedScreen.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/java/org/simple/clinic/editpatient/deletepatient/DeletePatientScreen.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreen.kt
- app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreen.kt
> Migrate app screens to use ViewBinding #2

- .github/workflows/ci_checks.yml
- .github/workflows/code_formatting_checks.yml
- CHANGELOG.md
The next version of the Android Development toolchain is going to drop support for JDK 1.8. Making this change now in order to be ready for the release in advance.
https://android-developers.googleblog.com/2020/12/announcing-android-gradle-plugin.html
> Bump JDK version in CI to 11

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/facilitypicker/FacilityPickerView.kt
- app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinScreen.kt
- app/src/main/java/org/simple/clinic/home/HomeScreen.kt
- app/src/main/java/org/simple/clinic/home/help/HelpScreen.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockScreen.kt
- app/src/main/java/org/simple/clinic/login/pin/LoginPinScreen.kt
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreen.kt
- app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsView.kt
- app/src/main/java/org/simple/clinic/registration/confirmfacility/ConfirmFacilitySheet.kt
- app/src/main/java/org/simple/clinic/scanid/ScanBpPassportActivity.kt
- app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/facilityselection/FacilitySelectionActivity.kt
- app/src/main/java/org/simple/clinic/search/PatientSearchScreen.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/security/pin/PinEntryCardView.kt
- app/src/main/res/layout/view_allpatientsinfacility.xml
https://app.clubhouse.io/simpledotorg/story/1828/migrate-app-to-use-view-binding-instead-of-kotlin-synthetic-view-accessors﻿
> Migrate app to use View Binding instead of Kotlin synthetic view accessors - 4

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesScreen.kt
https://app.clubhouse.io/simpledotorg/story/2047/dequeue-runnable-when-editmedicinesscreen-is-detached
- On `master`, change the delay to execute the recycler view scroll operation in `EditMedicinesScreen#populateDrugsList` to a larger value.
- Run the app and add a custom drug. Once the drug is added and before the earlier specified duration completes, press back and exit the `EditMedicinesScreen`.
- Once the delay is complete, the app will crash.
- Repeat the same task on the current branch
> Fix crash on edit medicines screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityView.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureSummaryView.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarSummaryView.kt
- app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientView.kt
- app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryView.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryView.kt
> Migrate app to use View Binding instead of Kotlin synthetic view accessors - 8

- CHANGELOG.md
- quality/pre-push
Without the shell env in the `pre-push` hook, Windows Git clients cannot identify the `pre-push` hook and fails to push the code.
> Add shell env comment to `pre-push` hook 

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/teleconsultation/contactdoctor/ContactDoctorSheet.kt
- app/src/main/java/org/simple/clinic/summary/teleconsultation/status/TeleconsultStatusSheet.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/TeleconsultPrescriptionScreen.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/shareprescription/TeleconsultSharePrescriptionScreen.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessScreen.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordScreen.kt
- app/src/main/java/org/simple/clinic/widgets/qrcodescanner/QrCodeScannerView.kt
> Migrate app to use View Binding instead of Kotlin synthetic view accessors - 10

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/navigation/v2/ScreenKey.kt
- app/src/main/java/org/simple/clinic/navigation/v2/compat/ScreenFragmentCompat.kt
- app/src/main/java/org/simple/clinic/navigation/v2/compat/ScreenKeyCompat.kt
https://app.clubhouse.io/simpledotorg/story/2131/add-support-for-the-new-navigation-framework
This is a follow up PR to #2241.
> Add a compatibility layer that lets us use the older screens in the new navigation framework

- .github/workflows/ci_checks.yml
- CHANGELOG.md
Since we use static patient IDs in tests, but the facility is randomly selected, it was possible to get into a situation where instrumented tests would continuously fail until the server was manually purged. This resolves the issue by running the purge task before triggering the instrumented tests.
More details here: https://simpledotorg.slack.com/archives/CFK2PHJ1L/p1609913473022000
> Purge the QA environment before running the instrumented tests in CI

- CHANGELOG.md
- quality/pre-push
Git Bash is printing garbled logs because it cannot figure out how to print the rich content from Gradle logs (ex: progress) when running the pre-push hook. In order to resolve that and make the logs readable, we set the console type for the pre-push hook.
**Reproduction steps**:
- Open Git Bash
- Run pre-push hook without these changes
> Prints garbled logs
- Run pre-push hook with these changes
> Prints plain logs
> Fix garbled gradle logs when running pre-push hook in Git Bash

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/teleconsultlog/drugduration/DrugDurationSheet.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/medicinefrequency/MedicineFrequencySheet.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesView.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/patientinfo/TeleconsultPatientInfoView.kt
> Migrate app to use View Binding instead of Kotlin synthetic view accessors - 11

- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchInit.kt
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchModel.kt
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt
- app/src/test/java/org/simple/clinic/instantsearch/InstantSearchInitTest.kt
- app/src/test/java/org/simple/clinic/util/matchers/IterableNotContaining.kt
https://app.clubhouse.io/simpledotorg/story/2421/the-bp-passport-scan-sheet-is-continuously-being-shown
> Fix BP Passport sheet reopens after it is dismissed

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
https://app.clubhouse.io/simpledotorg/story/1274/app-crashes-when-returning-to-the-register-patient-screen-before-completing-registration-when-patient-date-of-birth-is-entered
> Fix app crash when returning to `PatientEntryScreen` from `MedicalHistoryScreen`

- CHANGELOG.md
- app/build.gradle
- app/src/main/java/org/simple/clinic/util/ParcelableOptional.kt
- build.gradle
- Bump Kotlin to v1.4.30
- Add parcelable implementation to `ParcelableOptional`
- Use new JVM IR backend
Kotlin 1.4.30 changes: https://blog.jetbrains.com/kotlin/2021/02/kotlin-1-4-30-released/
New JVM IR Backend: https://blog.jetbrains.com/kotlin/2021/02/the-jvm-backend-is-in-beta-let-s-make-it-stable-together/
`@Parcelize` annotation issue: https://youtrack.jetbrains.com/issue/KT-42652
> Bump Kotlin version

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
https://app.clubhouse.io/simpledotorg/story/2805/fix-cannot-exit-patient-summary-screen-after-scheduling-an-appointment
> Fix cannot exit patient summary screen after scheduling an appointment

- .github/workflows/ci_checks.yml
- .github/workflows/code_formatting_checks.yml
- CHANGELOG.md
Just a quality of life change, for manually running GH Actions for a given branch from the Actions tab on GitHub.
> Enable running GH actions manually for ci_checks & code_formatting_checks

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/report/ReportsEvent.kt
- app/src/main/java/org/simple/clinic/home/report/ReportsScreen.kt
- app/src/main/java/org/simple/clinic/home/report/ReportsUpdate.kt
- app/src/main/java/org/simple/clinic/home/report/ReportsWebViewClient.kt
- app/src/test/java/org/simple/clinic/home/report/ReportsUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2224/add-drug-stock-form-to-progress-tab-behind-a-feature-flag
https://app.clubhouse.io/simpledotorg/story/2929/handle-navigation-and-from-drug-stock-success-page-in-the-android-app
> Add drug stock option in progress screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/patient/PatientAddress.kt
- app/src/test/java/org/simple/clinic/editpatient/EditPatientInitTest.kt
- app/src/test/java/org/simple/clinic/newentry/PatientEntryInitTest.kt
https://app.clubhouse.io/simpledotorg/story/3038/patient-entry-edit-crashes-when-entering-village-name
> Fix village type ahead crash when creating/editing patient

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/drugs/EditMedicinesUiRenderer.kt
- app/src/main/java/org/simple/clinic/drugs/selection/DrugListItem.kt
- app/src/test/java/org/simple/clinic/drugs/EditMedicinesUiRendererTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/EditMedicinesScreenLogicTest.kt
Without this we are getting a weird UI glitch where the top corner radius are being preserved if a new item is pushed to top.
*Reproducing steps*
- Add a dosage to protocol/custom drug to move it to top of the list
- The item that is pushed down now has top corner radius even though it's not longer the first item
> Fix prescribed drugs item corner radius not being updated when order is changed

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/86.json
- app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration86AndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/feature/Feature.kt
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchCriteria.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsEvent.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt
- app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsUpdate.kt
- app/src/main/java/org/simple/clinic/searchresultsview/SearchResultsEvent.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_86.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
- app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2225/search-by-patient-identifiers-bangladesh-national-id-etc
When user searches from a numeric criteria and wants to register a new patient/update an existing entry then they add it as a phone number. Currently this is how I've implemented this flow. Lmk if you think this is not how it should work. @vinaysshenoy
> Implement Search by patient identifiers in Instant Search 

- CHANGELOG.md
- app/build.gradle
- app/src/debug/AndroidManifest.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/simple/clinic/crash/SentryCrashReporter.kt
- build.gradle
- gradle.properties
https://app.clubhouse.io/simpledotorg/story/3251/migrate-sentry-android-to-v4-3-0
> Migrate Sentry Android to v4.3.0

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/facility/change/FacilityListItem.kt
- app/src/main/java/org/simple/clinic/widgets/PatientSearchResultItemView.kt
- app/src/main/res/values/colors.xml
https://app.clubhouse.io/simpledotorg/story/3360/if-you-do-an-instant-search-by-name-the-highlight-colour-is-yellow-but-it-s-blue-when-you-search-by-phone-number
> Fix highlight color for instant search using phone number  

- .github/workflows/auto_request_review.yml
- CHANGELOG.md
In certain scenarios, it's possible the auto-request review action will assign a reviewer even if one already is present. For example, when we mark a PR as a draft without removing the reviewer and mark it ready for review, the auto-request review action will run and tries to add another reviewer.
> Don't assign a reviewer if a reviewer already exist

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUpdate.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpLogicTest.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/1012/progress-view-for-manual-otp-entry-screen-is-not-hidden-when-login-fails
> Fix progress view for manual OTP entry screen is not hidden when login fails

- CHANGELOG.md
- app/build.gradle.kts
- app/src/main/java/org/simple/clinic/util/BitmapUtils.kt
- buildSrc/src/main/kotlin/Versions.kt
- Bump AndroidX annotation library to v1.2.0
- Add AndroidX annotation dependency
- Add AndroidX annotation experimental dependency
- Use `OptIn` annotation for `ExperimentalGetImage` usage in `BitmapUtils`
> Bump annotation dependency

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffect.kt
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffectHandler.kt
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchInit.kt
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchModel.kt
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUiActions.kt
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt
- app/src/main/res/layout/screen_instant_search.xml
- app/src/test/java/org/simple/clinic/instantsearch/InstantSearchEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/instantsearch/InstantSearchInitTest.kt
- app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUiRendererTest.kt
- app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
- Pass initial search query when creating `InstantSearchModel`
- Add effect to prefill search query
- When current facility is loaded and search query is present then prefill search query
- Return current model from the `BaseScreen`
- Disable implicit state of search query edit text
- When screen is restored and facility is loaded, then prefill search query
> Prefill search query in `InstantSearchScreen`

- CHANGELOG.md
- app/src/main/res/layout/screen_forgotpin_confirmpin.xml
https://app.clubhouse.io/simpledotorg/story/3863/confirm-reset-pin-error-text-is-not-hidden-by-default
> Fix confirm reset pin error text visibility

- .github/workflows/ci_checks.yml
- CHANGELOG.md
- Use macos version 11.0 to run instrumentation tests
> Use macos version 11.0 to run instrumentation tests on CI

- .github/workflows/ci_checks.yml
- CHANGELOG.md
- Pin Android emulator build version to resolve emulator timeout error
> Pin Android emulator build version to resolve emulator timeout error

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt
- app/src/main/java/org/simple/clinic/patient/onlinelookup/api/DurationFromSecondsMoshiAdapter.kt
- app/src/main/java/org/simple/clinic/patient/onlinelookup/api/PatientOnlineLookupRequest.kt
- app/src/main/java/org/simple/clinic/patient/onlinelookup/api/PatientOnlineLookupResponsePayload.kt
- app/src/main/java/org/simple/clinic/patient/onlinelookup/api/RecordRetention.kt
- app/src/main/java/org/simple/clinic/patient/onlinelookup/api/RetentionType.kt
- app/src/main/java/org/simple/clinic/patient/onlinelookup/api/SecondsDuration.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientSyncApi.kt
- app/src/test/java/org/simple/clinic/patient/onlinelookup/RetentionMoshiAdapterTest.kt
There is a deviation between the _current_ API documentation and the one defined in the code. The relevant discussions are in these Slack threads.
- https://simpledotorg.slack.com/archives/C01P71BD3NY/p1624525771010100
- https://simpledotorg.slack.com/archives/C01P71BD3NY/p1624533709024400
https://app.clubhouse.io/simpledotorg/story/3807/add-support-for-online-patient-lookup-api
> Add Lookup API service definition

- CHANGELOG.md
- buildSrc/src/main/kotlin/Versions.kt
> Bump Kotlin to v1.5.20

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt
- app/src/main/java/org/simple/clinic/datepicker/calendar/CalendarDatePicker.kt
- app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseBottomSheet.kt
- app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseDialog.kt
- app/src/main/java/org/simple/clinic/util/AndroidExtensions.kt
- Remove `overrideCancellation` usage in `BaseBottomSheet`
- Trigger backpress to remove bottom sheet from navigation router when `onCancel` is called
- When bottom sheet is swiped down, then trigger backpress on navigation router
- Remove `overrideCancellation` usage in `ContactPatientBottomSheet`
- Remove `overrideCancellation` usage in `BaseDialog`
- Trigger router backpress when `onCancel` is called
- Remove `overrideCancellation` usage in `CalendarDatePicker`
- Trigger router backpress when `onCancel` is called
- Remove `overrideCancellation` extension
> Remove dialog from history when dialog is cancelled

- app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
- app/src/androidTest/java/org/simple/clinic/rules/ServerRegistrationAtFacilityRule.kt
Currently, the `ServerAuthenticationRule` in the instrumented tests registers a user at the first stored facility. This worked for us until recently, but for the patient online lookup feature requires specific conditions to verify that it's working as expect. See https://simpledotorg.slack.com/archives/C01P71BD3NY/p1625037760002300 for more details.
This PR is to add a rule that we can then use in integration tests where specific conditions are required for registering a patient.
https://app.clubhouse.io/simpledotorg/story/3948/create-use-case-to-query-the-online-lookup-api-and-save-the-patient-profile
> Add support for registering a patient in tests at a specific facility

- CHANGELOG.md
- buildSrc/src/main/kotlin/Versions.kt
**Release notes**: https://androidstudio.googleblog.com/2021/06/android-studio-422-available.html
> Bump AGP to v4.2.2

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreen.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenInjector.kt
- app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureSummaryView.kt
- app/src/main/res/layout/screen_bp_history.xml
- Use `ConstraintLayout` as parent in `screen_bp_history`
- Add `ScreenKey` in `BloodPressureHistoryScreen`
- Use new `BloodPressureHistoryScreen.Key` for opening blood pressure history screen
- Extend `BaseScreen` in `BloodPressureHistoryScreen`
- Override lifecycle methods of the fragment
- Use `requireContext` instead of `context
- Remove unused code
- Replace `detaches` usage with `viewLifecycleOwnerLiveData`
> Migrate `BloodPressureHistoryScreen` to a fragment

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt
- app/src/main/java/org/simple/clinic/util/AndroidExtensions.kt
**Testing steps**:
- Go to overdue list
- Open contact patient bottom sheet
- Select "Remind to call later..."
- Click Android back button
- It should go back to call patient view
> Fix `ContactPatientBottomSheet` not going back to call patient view on back click in call later mode

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueLogicTest.kt
- Inject current facility stream in `OverdueEffectHandler`
- Subscribe to `currentFacilityStream` for getting current facility
- Rename `isLoading` to `isLoadingInitialData` in `overdueListAdapterLoadStateListener`
- Update `overdueListAdapterLoadStateListener` to display progress when loading data after switching facility
**Story:** https://app.clubhouse.io/simpledotorg/story/4108/overdue-list-not-changing-when-switching-facility-from-the-overdue-screen
> Fix overdue list not changing when switching facility from overdue screen

- CHANGELOG.md
- buildSrc/src/main/kotlin/Versions.kt
https://github.com/JetBrains/kotlin/releases/tag/v1.5.21
> Bump Kotlin to v1.5.21

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/drugs/search/DrugRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/di/PagingModule.kt
- app/src/main/java/org/simple/clinic/di/PagingSize.kt
- app/src/main/java/org/simple/clinic/drugs/search/Drug.kt
- app/src/main/java/org/simple/clinic/drugs/search/DrugRepository.kt
- app/src/main/java/org/simple/clinic/drugs/search/DrugSearchEffect.kt
- app/src/main/java/org/simple/clinic/drugs/search/DrugSearchEffectHandler.kt
- app/src/main/java/org/simple/clinic/drugs/search/DrugSearchEvent.kt
- app/src/main/java/org/simple/clinic/drugs/search/DrugSearchModel.kt
- app/src/main/java/org/simple/clinic/drugs/search/DrugSearchUi.kt
- app/src/main/java/org/simple/clinic/drugs/search/DrugSearchUiRenderer.kt
- app/src/main/java/org/simple/clinic/drugs/search/DrugSearchUpdate.kt
- app/src/main/java/org/simple/clinic/drugs/search/UiActions.kt
- app/src/test/java/org/simple/clinic/drugs/search/DrugSearchEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/drugs/search/DrugSearchUiRendererTest.kt
- app/src/test/java/org/simple/clinic/drugs/search/DrugSearchUpdateTest.kt
**Story**: https://app.clubhouse.io/simpledotorg/story/2899/implement-drugssearchscreen
- Add query to search for drugs
- Add page size for drug search results
- Add effect to search drugs
- Handle `SetDrugsSearchResults` effect
- When drug search results are loaded then show search results
- When search query is changed, then update model and search drugs
- When search query is empty, then update model
- When search query is empty, then hide search results
- When search query is not empty, then show search results
> Implement `DrugsSearchScreen`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- Don't show progress if overdue adapter already has items
> Don't show progress if overdue list already has items

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt
- app/src/main/res/layout/contactpatient_callpatient.xml
- app/src/main/res/layout/contactpatient_callpatient_old.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/theme_overlay.xml
- Rename `Widget.Simple.PatientContactCallResultItem` to `Widget.Simple.PatientContactCallResultItem_Old`
- Add `Widget.Simple.PatientContactCallResultItem`
- Set `colorBackground` in `ThemeOverlay.Simple.BottomSheetDialog`
- Fix `contactpatient_callpatient` UI spacing and styling
> Fix `ContactPatientBottomSheet` UI spacing and styling

- CHANGELOG.md
- buildSrc/src/main/kotlin/Versions.kt
- Bump CameraX dependency to v1.0.0
**Should be tested on all the test devices**
> Bump CameraX dependencies

- CHANGELOG.md
- app/src/main/res/layout/contactpatient_appointmentreminder.xml
- app/src/main/res/layout/item_overdue_list_patient_old.xml
- app/src/main/res/layout/screen_edit_patient.xml
- app/src/main/res/layout/screen_manual_patient_entry.xml
- app/src/main/res/layout/screen_patient_summary.xml
- app/src/main/res/layout/sheet_schedule_appointment.xml
- app/src/main/res/layout/sheet_text_input_date_picker.xml
- buildSrc/src/main/kotlin/Versions.kt
- router/build.gradle.kts
- Bump AppCompat version to v1.3.0
- Use `app:tint` instead of platform tint
> Bump AppCompat to v1.3.0

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/ClinicApp.kt
- buildSrc/src/main/kotlin/Versions.kt
- Bump Fragment to v1.3.6
- Disable new `FragmentStateManager`
> Bump Fragment to v1.3.6

- app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseDialog.kt
- Remove `ViewRenderer` generic property from `BaseDialog`
- Set `NoopViewRenderer` as default UI renderer in `BaseDialog`
- Add view effects generic type to `BaseDialog`
- Add `MobiusLoopViewModel` in `BaseDialog`
- Remove Mobius controller usage from `BaseDialog`
- When viewmodel model updates, then render UI
- Change `BaseDialog#createEffectHandler` signature to accept view effects consumer
- Handle view effects in `BaseDialog`
- Forward UI events to viewmodel in `BaseDialog`
> Add `MobiusLoopViewModel` to `BaseDialog`

- CHANGELOG.md
- buildSrc/src/main/kotlin/Versions.kt
> Bump Flipper to v0.98.0

- CHANGELOG.md
- buildSrc/src/main/kotlin/Versions.kt
- Bump UUID generator to v4.0.1
> Bump UUID generator to v4.0.1

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/navigation/v2/History.kt
- app/src/main/java/org/simple/clinic/navigation/v2/Router.kt
- Don't push to new screen if the top screen is same as the new screen
Fixes [issue](https://simpledotorg.slack.com/archives/CFK2PHJ1L/p1627448041022400)
> Don't push to new screen if the top screen is same as the new screen

- CHANGELOG.md
- buildSrc/src/main/kotlin/Versions.kt
- Bump ML Kit Barcode to v16.2.0
> Bump ML Kit Barcode to v16.2.0

- CHANGELOG.md
- app/build.gradle.kts
- buildSrc/src/main/kotlin/Versions.kt
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- lint/build.gradle.kts
- lint/src/main/java/org/simple/clinic/lint/SimpleIssueRegistry.kt
- mobius-base/build.gradle.kts
- router/build.gradle.kts
- router/src/main/res/values/strings.xml
- simple-platform/build.gradle.kts
- simple-visuals/build.gradle.kts
- Bump AGP to v7.0.0
- Bump Gradle wrapper to v7.0.2
- Replace deprecated Gradle usages
- Disable Lint partial analysis
- Enable checking dependencies when running lint
- Enable core library desugaring in platform module
- Remove unused resources in router module
- Bump Lint to v30.0.0
- Add `Vendor` in `SimpleIssueRegistry`
**Story**: https://app.clubhouse.io/simpledotorg/story/4326/bump-agp-to-v7-0-0
**Release notes**: https://developer.android.com/studio/releases/gradle-plugin#7-0-0
> Bump AGP to v7.0.0

- .gitignore
The latest version of Android Studio/AGP has started adding this as an empty file during the build. Ignoring this.
> Add `.idea/gradle.properties` to `.gitignore`

- CHANGELOG.md
- app/src/test/java/org/simple/clinic/activity/TheActivityControllerTest.kt
There was a test where the setup was being done incorrectly (using the current timestamp instead of the test stub). However, the test was always passing because we were not setting up a mock for the logged in user, so the code path that works with the timestamp was never getting triggered.
> Fix incorrect test in `TheActivityControllerTest`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt
- app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4404/don-t-load-search-results-if-search-query-is-not-changed-from-previous-search-query
> Don't load search results if search query is not changed from previous search query

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt
- app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeSheet.kt
- app/src/main/java/org/simple/clinic/facility/change/FacilityChangeScreen.kt
- app/src/main/java/org/simple/clinic/home/HomeScreen.kt
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt
- app/src/main/java/org/simple/clinic/navigation/v2/ExpectsResult.kt
- app/src/main/java/org/simple/clinic/navigation/v2/Router.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/util/FragmentExt.kt
- Add fragment extensions for fragment results
- Set fragment result when dispatching screen results in `Router`
- Migrate `AlertFacilityChangeSheet` to use fragment results listener
- Migrate `ContactPatientBottomSheet` to use fragment results listener
- Migrate `FacilityChangeScreen` to use fragment results listener
- Migrate `InstantSearchScreen` to use fragment results listener
- Migrate `PatientSummaryScreen` to use fragment results listener
- Migrate `ScheduleAppointmentSheet` to use fragment results listener
- Removed unused code
> Migrate to Fragment results API

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt
- app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
- app/src/main/res/layout/screen_manual_patient_entry.xml
- Use `RelativeLayout` as parent in `screen_manual_patient_entry`
- Add `ScreenKey` in `PatientEntryScreen`
- Use `PatientEntryScreen.Key` to open `PatientEntryScreen`
- Extend `BaseScreen` in `PatientEntryScreen`
- Replace `context` with `requireContext`
- Override lifecycle method of the fragment
- Remove unused code
**Story**: https://app.clubhouse.io/simpledotorg/story/4460/migrate-patiententryscreen-to-a-fragment
> Migrate `PatientEntryScreen` to a fragment

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt
- app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4583/searching-by-short-code-from-the-scan-bp-passport-screen-does-not-load-results-initially
> Fix searching by short code from the scan BP Passport screen does not load results initially

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUi.kt
- app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiRenderer.kt
- app/src/main/java/org/simple/clinic/contactpatient/views/CallPatientView.kt
- app/src/main/res/layout/contactpatient_callpatient.xml
- app/src/test/java/org/simple/clinic/contactpatient/CallPatientUiRendererTest.kt
Slack message: https://simpledotorg.slack.com/archives/CFK2PHJ1L/p1629447233229600
Since this UI doesn't have to be reactive, we don't have to worry about hiding the results section. Basically we are not adjusting UI based on some reactive stream, we just render the UI when creating the sheet.
This results UI is hidden by default, and only get's shown if the patient doesn't have no phone number and has appointment.
> Show appointment results in contact patient sheet for patient with no phone number

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/di/TestRetrofitModule.kt
- app/src/main/java/org/simple/clinic/appconfig/AppConfigModule.kt
- app/src/main/java/org/simple/clinic/appconfig/AppConfigRepository.kt
- app/src/main/java/org/simple/clinic/appconfig/CountryModule.kt
- app/src/main/java/org/simple/clinic/appconfig/CountryV2.kt
- app/src/main/java/org/simple/clinic/appconfig/Deployment.kt
- app/src/main/java/org/simple/clinic/bloodsugar/di/BloodSugarModule.kt
- app/src/main/java/org/simple/clinic/bp/di/BloodPressureModule.kt
- app/src/main/java/org/simple/clinic/di/network/RetrofitModule.kt
- app/src/main/java/org/simple/clinic/drugs/PrescriptionModule.kt
- app/src/main/java/org/simple/clinic/drugs/search/DrugModule.kt
- app/src/main/java/org/simple/clinic/facility/FacilityModule.kt
- app/src/main/java/org/simple/clinic/help/HelpModule.kt
- app/src/main/java/org/simple/clinic/login/LoginModule.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryModule.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentModule.kt
- app/src/main/java/org/simple/clinic/patient/sync/PatientSyncModule.kt
- app/src/main/java/org/simple/clinic/protocol/ProtocolModule.kt
- app/src/main/java/org/simple/clinic/reports/ReportsModule.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModule.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordModule.kt
- app/src/sharedTest/java/org/simple/clinic/TestData.kt
- app/src/test/java/org/simple/clinic/appconfig/AppConfigRepositoryTest.kt
https://app.clubhouse.io/simpledotorg/story/4753/migrate-v1-country-usages-to-v2-country
In later PRs we will migrate all the `Country` usages with `CountryV2`. In this PR, we migrated the `Country#endPoint` usage with `Deployment` usage.
**Testing steps**:
- Before running this PR, sign in into the `master` branch app
- Run the app from this branch
- You should see updated preferences in Flipper
- Verify sync is working as expected. You can look at the network panel of Flipper to make sure all calls are successful.
> Migrate v1 `Country` usages to v2 `Country` - 1

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtection.kt
- app/src/main/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtectionConfig.kt
- app/src/main/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtectionConfigModule.kt
- app/src/main/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtectionModule.kt
- app/src/main/java/org/simple/clinic/enterotp/BruteForceOtpProtectionState.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpEffect.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpEffectHandler.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUpdate.kt
- app/src/test/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtectionTest.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpLogicTest.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4514/limit-incorrect-otp-entries
> Restricting login OTP entries to 5 attempts #1

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryModel.kt
- app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUiRendererTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4813/refactor-logic-around-providing-drug-frequencies-label-depending-on-the-country
I will change the `labelResId` references in the individual tests to getting it from the `drugFrequencyToFrequencyChoiceItemMap` value in the next PR
> Refactor logic around providing drug frequencies label depending on the country - 1

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpEffect.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpEffectHandler.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpModel.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUi.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUiActions.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUiRenderer.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUpdate.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpLogicTest.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4844/add-effects-for-network-error-unexpected-error-to-have-consistent-behaviour-for-login-otp-entry
> Remove login failed errors from UiRenderer, and add via effect handler when logging in

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityEffect.kt
- app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityEvent.kt
- app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityUpdate.kt
- app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityView.kt
- app/src/main/java/org/simple/clinic/summary/assignedfacility/UiActions.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
- app/src/test/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4822/changing-the-assigned-facility-for-a-patient-goes-to-home-screen-instead-of-staying-on-summary-screen
In order to fix this, we need to migrate the facility selection screen to extend the `BaseScreen` and be a part of the navigation graph. However, there is an issue in the current setup where `AssignedFacilityView` is one of the components which starts this screen. This makes migration hard because we cannot handle results in a child view.
This PR moves opening of the facility selection screen to `PatientSummaryScreen`, which will then make it easier for us to migrate `FacilitySelectionScreen`
> Move opening of facility selection screen to patient summary screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/appconfig/AppConfigModule.kt
- app/src/main/java/org/simple/clinic/appconfig/AppConfigRepository.kt
- app/src/main/java/org/simple/clinic/appconfig/StatePayload.kt
- app/src/main/java/org/simple/clinic/appconfig/StatesFetcher.kt
- app/src/main/java/org/simple/clinic/appconfig/StatesPayload.kt
- app/src/main/java/org/simple/clinic/appconfig/api/StatesApi.kt
- app/src/main/java/org/simple/clinic/registerorlogin/AuthenticationActiivtyComponent.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryEffect.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryEffectHandler.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryScreen.kt
- app/src/main/java/org/simple/clinic/selectcountry/SelectCountryUpdate.kt
- app/src/main/java/org/simple/clinic/selectcountry/UiActions.kt
- app/src/main/java/org/simple/clinic/selectstate/SelectStateEffectHandler.kt
- app/src/main/java/org/simple/clinic/selectstate/SelectStateEvent.kt
- app/src/main/java/org/simple/clinic/selectstate/SelectStateScreen.kt
- app/src/main/java/org/simple/clinic/selectstate/SelectableStateItem.kt
- app/src/main/res/layout/list_selectstate_state_view.xml
- app/src/main/res/layout/screen_select_state.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/appconfig/AppConfigRepositoryTest.kt
- app/src/test/java/org/simple/clinic/selectcountry/SelectCountryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/selectcountry/SelectCountryUpdateTest.kt
- app/src/test/java/org/simple/clinic/selectstate/SelectStateEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/selectstate/SelectableStateItemTest.kt
https://app.clubhouse.io/simpledotorg/story/4035/allow-state-selection-during-app-onboarding
**Testing steps**
- Enable clear text traffic in debug `AndroidManifest` using `android:usesCleartextTraffic="true"` (This is temporary since some deployments have `http` instead of `https`, so we don't need it in prod)
- Replace manifest and fallback endpoints in `gradle.properties` with this: `https://simple-review-pr-2870.herokuapp.com/api/`
- Clear app data and run the app
> Allow state selection during app onboarding

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/HomeScreen.kt
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
- app/src/main/java/org/simple/clinic/util/IntentExt.kt
https://app.shortcut.com/simpledotorg/story/5073/fix-patient-summary-going-back-to-the-home-screen-when-opening-teleconsult-links
> Fix patient summary going back to the home screen when opening teleconsult links

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreen.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUi.kt
- app/src/main/java/org/simple/clinic/enterotp/EnterOtpUiRenderer.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpLogicTest.kt
- app/src/test/java/org/simple/clinic/enterotp/EnterOtpUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/5079/when-the-timer-has-blocked-otp-attempts-hide-the-resend-sms-button
> Hide resend sms button when OTP attempts are blocked

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffect.kt
- app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheetUiActions.kt
- app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUi.kt
- app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUiRenderer.kt
- app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdate.kt
- app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUiRendererTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdateTest.kt
This change is made because show keyboard method was getting invoked every time there was a model change. 
From [this](https://github.com/simpledotorg/simple-android/pull/3131#discussion_r708772528) PR comment
> Handle `ShowKeyboard` as a Ui Action instead of rendering it in the `UiRenderer`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5098/go-back-to-the-previous-screen-when-done-back-is-clicked-in-the-patient-summary-screen-when-the-patient-is-marked-as-dead
> Don't show appointment sheet when patient is dead

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/contactpatient/views/CallPatientView.kt
- app/src/main/res/layout/contactpatient_callpatient.xml
https://app.shortcut.com/simpledotorg/story/5156/fix-contactpatientbottomsheet-not-behaving-as-expected-when-navigated-back-from-remove-from-overdue-list-sheet
> Fix contact patient bottom sheet not showing correct results

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/drugs/selection/DrugListItem.kt
- app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffect.kt
- app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandler.kt
- app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheet.kt
- app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheetUiActions.kt
- app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUi.kt
- app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdate.kt
- app/src/main/res/layout/sheet_custom_drug_entry.xml
- app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5046/custom-drug-entry-sheet-ui-improvements
This PR:
- Removes the focus from dosage when user clicks on frequency
- Saves `null` in the repository if dosage edit text value is equal to "mg"
- Changes from numeric keyboard to the default keyboard for drug dosage edit text
- Uses `joinToString` to correctly display dosage and frequency values in `EditMedicineScreen`
Next PR:
- Make the cursor appear right before 'mg' whenever the sheet is opened
> Custom Drug Entry Sheet UI Improvements

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
- app/src/main/java/org/simple/clinic/main/TheActivityEffect.kt
- app/src/main/java/org/simple/clinic/main/TheActivityEffectHandler.kt
- app/src/main/java/org/simple/clinic/main/TheActivityUiActions.kt
- app/src/main/java/org/simple/clinic/main/TheActivityUpdate.kt
- app/src/main/java/org/simple/clinic/navigation/v2/Router.kt
- app/src/test/java/org/simple/clinic/activity/TheActivityControllerTest.kt
- app/src/test/java/org/simple/clinic/activity/TheActivityUpdateTest.kt
- app/src/test/java/org/simple/clinic/main/TheActivityEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/5181/restore-correct-navigation-state-after-app-is-resumed-from-background
> Replace the entire screen history in `TheActivityUpdate` instead of loading a single screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesScreen.kt
- Scroll to top when drugs list content is changed in edit medicines screen
> Scroll to top when drugs list content is changed in edit medicines screen

- CHANGELOG.md
- app/src/debug/AndroidManifest.xml
- app/src/debug/java/org/simple/clinic/DebugNotification.kt
- app/src/main/AndroidManifest.xml
- build.gradle.kts
- gradle/libs.versions.toml
**Testing steps**
- Run the app on an Android 12 device or emulator to make sure the app is installing and running correctly.
> Add support for Android 12

- CHANGELOG.md
- app/src/main/res/layout/screen_select_state.xml
https://app.shortcut.com/simpledotorg/story/5357/fix-state-selection-list-content-hidden-behind-android-navigation-bar
**Testing steps**
- Change the manifest endpoint to `https://api.simple.org/api/` in `gradle.properties`
- Run the app and verify entire state list is visible when scrolling
> Fix state selection list content hidden behind Android navigation bar

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/login/applock/AppLockScreen.kt
- app/src/main/java/org/simple/clinic/login/applock/AppLockScreenKey.kt
- app/src/main/java/org/simple/clinic/main/TheActivity.kt
- app/src/main/java/org/simple/clinic/main/TheActivityEffectHandler.kt
- app/src/main/java/org/simple/clinic/main/TheActivityEvent.kt
- app/src/main/java/org/simple/clinic/main/TheActivityUpdate.kt
- app/src/main/java/org/simple/clinic/navigation/v2/History.kt
- app/src/main/java/org/simple/clinic/navigation/v2/Router.kt
- app/src/test/java/org/simple/clinic/activity/TheActivityControllerTest.kt
- app/src/test/java/org/simple/clinic/activity/TheActivityUpdateTest.kt
- app/src/test/java/org/simple/clinic/main/TheActivityEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/5181/restore-correct-navigation-state-after-app-is-resumed-from-background
> Fix screen backstack not getting maintained when app is restored from background

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryModel.kt
- app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5822/fix-diabetes-treatment-input-required-dialog-showing-when-diabetes-management-is-disabled
> Fix diabetes treatment input required dialog showing when diabetes management is disabled

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/sync/SyncScheduler.kt
Enough users are on the latest version of the app, so we can remove this code now
https://mixpanel.com/s/3wOyJ4
> Remove canceling previously scheduled periodic work in `SyncScheduler`

- CHANGELOG.md
- gradle/libs.versions.toml
**Release notes**: https://github.com/spotify/mobius/releases/tag/v1.5.6
> Bump Mobius to v1.5.6

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
https://app.shortcut.com/simpledotorg/story/5454/enable-overdue-list-download-and-share-feature-in-india-only
> Enable overdue list download and share feature in India only

- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt
- app/src/main/java/org/simple/clinic/util/RuntimeNetworkStatus.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueLogicTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
- app/src/test/java/org/simple/clinic/util/RuntimeNetworkStatusTest.kt
https://app.shortcut.com/simpledotorg/story/6092/add-an-observabletransform-to-check-the-network-status
**Testing steps**:
- Enable overdue download & share feature in `Feature.kt`
- Disable network connection on your device
- Click on download or share button to see the no active connection error dialog
> Add an `ObservableTransform` to check the network status

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/analytics/MixpanelAnalyticsReporter.kt
https://app.shortcut.com/simpledotorg/story/6106/set-user-id-as-user-property-in-mixpanelanalyticsreporter
> Set user ID as user property in `MixpanelAnalyticsReporter`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/ClinicApp.kt
- app/src/main/java/org/simple/clinic/analytics/MixpanelAnalyticsReporter.kt
- app/src/main/java/org/simple/clinic/appconfig/AppConfigRepository.kt
- app/src/main/java/org/simple/clinic/crash/SentryCrashReporterSink.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/plumbing/infrastructure/DatadogInfrastructure.kt
- app/src/main/java/org/simple/clinic/plumbing/infrastructure/Infrastructure.kt
- app/src/main/java/org/simple/clinic/plumbing/infrastructure/InfrastructureModule.kt
- app/src/main/java/org/simple/clinic/plumbing/infrastructure/MixpanelInfrastructure.kt
- app/src/main/java/org/simple/clinic/plumbing/infrastructure/SentryInfrastructure.kt
- app/src/main/java/org/simple/clinic/plumbing/infrastructure/UpdateInfrastructureUserDetails.kt
- app/src/test/java/org/simple/clinic/plumbing/infrastructure/UpdateInfrastructureUserDetailsTest.kt
https://app.shortcut.com/simpledotorg/story/6107/clean-up-assigning-user-meta-data-to-apm-and-crash-reporting-tools
> Provide standardized mechanism for keeping user details updated in third party tooling

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/overdue/download/OverdueListDownloaderIntegrationTest.kt
- app/src/main/java/org/simple/clinic/overdue/download/OverdueListDownloader.kt
- app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffectHandler.kt
- app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/6120/sharing-downloaded-overdue-list-through-whatsapp-is-not-working
> Fix sharing downloaded overdue list through Whatsapp is not working

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/feature/Feature.kt
Waiting for [Sharing downloaded overdue list through Whatsapp is not working](https://app.shortcut.com/simpledotorg/story/6120/sharing-downloaded-overdue-list-through-whatsapp-is-not-working) bug's fix to get merged in.
> Enable `OverdueListDownloadAndShare` feature flag

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/appconfig/AppConfigModule.kt
https://app.shortcut.com/simpledotorg/story/5508/investigate-need-for-moshi-preference-converter-when-injecting-the-current-selected-state-in-appconfigmodule
> Use `StringPreferenceConverter` for getting selected state from preferences

- .github/workflows/cleanup_heroku_review_apps.yml
- CHANGELOG.md
Currently, if we need to reset a Heroku instance for a PR, the only way is to login to the Heroku console and manually delete the instance. This allows us to  trigger it via GitHub Actions by taking the following steps:
- Close the PR
- Manually the Heroku cleanup workflow
- Reopen the PR
> Add support for manually running Heroku cleanup workflow

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueViewEffectHandler.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueLogicTest.kt
https://app.shortcut.com/simpledotorg/story/6264/migrate-overduescreen-to-use-view-effects
> Migrate `OverdueScreen` to use view effects

- .github/workflows/benchmark_suite.yml
This is being done because the first time we try to lock the clocks, the task always fails with the device being offline but it works the second time. This commit restarts ADB as root in order to make the test pass.
> Restart ADB as root before running the performance regression test suite

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/di/network/TimeoutCallAdapterFactory.kt
If the required conditions are not satisfied, we are returning early to avoid checking annotations or creating a new call adapter.
> Return early if the required `Timeout` conditions are not satisfied in `TimeoutCallAdapterFactory`

- .github/workflows/auto_request_review.yml
- CHANGELOG.md
Right now we have to manually enable auto merge when creating PR, this CI step will automatically do that when assigning the reviewer.
> Enable auto merge of PR when assigning reviewer

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt
https://app.shortcut.com/simpledotorg/story/6611/debounce-overdue-updates-to-prevent-running-out-of-effect-queue-size
> Debounce overdue updates to prevent running out of view effect queue size

- .github/scripts/setup_heroku_instance.sh
The `heroku buildpacks:add` commands don't work, created a custom buildpack that combines
- `https://github.com/weibeld/heroku-buildpack-run`
- `https://github.com/heroku/heroku-buildpack-ruby`
This is a workaround for the moment, we'll need to get the buildpacks command working to do this correctly
> Use a custom buildpack to get CI working

- CHANGELOG.md
- renovate.json5
With the previous configuration we would have received 5 PR's every 2 months and have to manually trigger the PR generation if we want from the dashboard. But we are gonna run this job daily to generate max of 5 concurrent PR's to avoid too much noise.
> Run renovate bot daily after 12 am

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/res/layout/screen_edit_patient.xml
https://app.shortcut.com/simpledotorg/story/6797/refactor-addbppassport-and-addnhidbutton-to-use-materialbutton
Depended on [#3402](https://github.com/simpledotorg/simple-android/pull/3402) to be merged in 
This PR also resolves [this](https://app.shortcut.com/simpledotorg/story/6783/bug-two-duplicate-nhids-end-up-rendering-in-edit-patient-screen) bug. Added it in this PR as it was a small fix.
> Refactor `addBPPassport` and `addNHIDButton` to use `MaterialButton`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientUi.kt
- app/src/main/java/org/simple/clinic/editpatient/EditPatientViewRenderer.kt
- app/src/main/res/layout/screen_edit_patient.xml
- app/src/test/java/org/simple/clinic/editpatient/EditPatientViewRendererTest.kt
https://app.shortcut.com/simpledotorg/story/6763/show-bp-passport-text-when-bp-passport-is-null-as-well
> Handle visibility of Bp Passport label and button when scan health id from edit patient is enabled

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt
- app/src/main/res/layout/screen_edit_patient.xml
https://app.shortcut.com/simpledotorg/story/7110/ui-improvement-the-spacing-between-health-id-labels-and-add-button-is-uneven
> Fix uneven spacing between health ID labels and `ADD` button

- CHANGELOG.md
- mobius-migration/build.gradle.kts
- mobius-migration/src/main/java/org/simple/mobius/migration/MobiusTestFixture.kt
Currently we are using Google Guava dependency for getting a [executor service](https://guava.dev/releases/19.0/api/docs/com/google/common/util/concurrent/MoreExecutors.html#newDirectExecutorService()) in `MobiusTestFixture`, for running tasks in the same thread they are invoked from. The usage can be replaced by [`ImmediateWorker`](https://github.com/spotify/mobius/blob/master/mobius-core/src/main/java/com/spotify/mobius/runners/ImmediateWorkRunner.java) from `mobius` package, which does the same.
> Remove Google Guava dependency

- CHANGELOG.md
- gradle/libs.versions.toml
When removing Google Guava dependency in [this](https://github.com/simpledotorg/simple-android/pull/3515) PR, I forgot to remove it from the `libs.versions` file. This PR will remove it from the file.
> Remove Google Guava from `libs.versions` file

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/appupdate/CheckAppUpdateAvailability.kt
- app/src/main/java/org/simple/clinic/appupdate/UpdateInfo.kt
- app/src/main/java/org/simple/clinic/appupdate/UpdateManager.kt
- app/src/test/java/org/simple/clinic/appupdate/CheckAppUpdateAvailabilityTest.kt
Since we are not using the `AppUpdateManager` to start a update flow, it doesn't matter if a update is flexible or immediate, we are not listening to update status in the app. We just open the Google Play page for Simple and let user update from there.
> Remove `isFlexibleUpdateType` as parameter from `UpdateInfo`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
- app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
I initially used the wildcard formatting in the repository layer while testing it out. Moved it to query itself to avoid any confusion/issues when using the dao query somewhere else outside of repository layer.
> Move wildcard formatting to search query

- .github/workflows/benchmark_suite.yml
- .github/workflows/ci_checks.yml
- .github/workflows/trigger_demo_release.yml
- CHANGELOG.md
I have noticed couple of Android tests failed with no space error. So, set the disk size to 8 GB for AVD
> Update AVD disk size to 8GB in GH Actions

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
- app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffectHandler.kt
- app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/7763/remove-marking-older-appointments-for-a-patient-as-a-side-effect-when-scheduling-an-appointment
> Remove marking older appointments for a patient as a side effect when scheduling an appointment

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryInit.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryInitTest.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/7768/load-clinical-decision-support-info-when-the-patient-summary-screen-is-created
To be merged in after #3666
> Load clinical decision support info when the patient summary screen is created

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenUi.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryViewRenderer.kt
- app/src/main/res/values/ids.xml
- app/src/test/java/org/simple/clinic/summary/PatientSummaryViewRendererTest.kt
https://app.shortcut.com/simpledotorg/story/7770/hide-clinical-decision-support-alert-banner-when-edit-medicines-are-clicked
> Hide clinical decision support alert banner when edit medicines are clicked

- .github/workflows/cut_release_branch.yml
- CHANGELOG.md
Since we want the release branch creation to run a different workflow (triggering demo release). We need to use PAT (Personal Access Token) instead of GITHUB_TOKEN in GH Actions to do that.
> Use personal access token when checking out repo in `cut_release_branch` workflow

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt
https://app.shortcut.com/simpledotorg/story/8030/handle-calling-drugstocknotifcationscheduler-when-drug-stock-reminder-is-enabled
> Handle calling `DrugStockNotifcationScheduler` when drug stock reminder is enabled

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreen.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffect.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffectHandler.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryViewEffectHandler.kt
- app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/7985/migrate-bloodpressurehistoryscreeneffecthandler-to-use-view-effects
In order for us to finish this migration, we need to migrate `ShowBloodPressures` effect, which requires us to change the BP history data source to paging source. I will do this in a different PR and then migrate this part later.
> Migrate `BloodPressureHistoryScreenEffectHandler` to use view effects - 1

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/appupdate/AppUpdateModule.kt
- app/src/main/java/org/simple/clinic/appupdate/CheckAppUpdateAvailability.kt
- app/src/main/java/org/simple/clinic/appupdate/UpdateInfo.kt
- app/src/main/java/org/simple/clinic/appupdate/UpdateManager.kt
- app/src/main/java/org/simple/clinic/main/TypedMap.kt
- app/src/test/java/org/simple/clinic/appupdate/CheckAppUpdateAvailabilityTest.kt
https://app.shortcut.com/simpledotorg/story/8037/add-updatepriority-for-security-app-update-reminders-as-a-firebase-remote-config
> Add `updatePriorities` for security app update reminders as a Firebase remote config

- .github/workflows/ci_checks.yml
Instead of running CI on pull requests that are opened onto `master`, this will enable us to run it on all the PRs within branches as well
> Run CI on every pull request

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/widgets/Views.kt
https://app.shortcut.com/simpledotorg/story/8291/text-cursor-jumping-to-end-in-edit-patient-screen-when-making-changes-in-the-middle-of-text
> Fix text cursor jumping to end when editing patient details

- CHANGELOG.md
- app/src/main/res/layout/screen_instant_search.xml
- app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/8260/handle-special-characters-when-searching-for-patient
Another potential option we can take is replacing the special characters with a "safe" character. But that would require 
us to 
1. Either change the characters saved in DB or
2. Replace them while fetching and do transformations
Both of them felt like a complex solutions for the use case. So, we can go ahead with the alphanumeric search for now and 
based on user feedback take the call
> Limit instant search to alphanumeric characters

- CHANGELOG.md
- README.md
Pull reminders has shut down, so the status link in our README is broken. So, removing it.
> Remove pull reminders status from `README.md`

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
- app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
Since we want the overdue screen to be reactive based on the actions. We are changing the return type to be a reactive 
stream.
> Change return type of `AppointmentRepository#overdueAppointmentsInFacilityNew` to `Observable<List<OverdueAppointment>>`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8327/load-overdue-appointments-and-break-down-into-different-sections-based-on-states
> Update `OverdueModel` once overdue appointments are loaded

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/feature/Feature.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUi.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUiRenderer.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8346/render-ui-for-all-overdue-sections-when-feature-flag-is-enabled
> Render overdue appointments when appointments are loaded and overdue sections feature is enabled

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueLogicTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8346/render-ui-for-all-overdue-sections-when-feature-flag-is-enabled
> Load overdue appointments when current facility is loaded and overdue sections feature is enabled

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUi.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUiRenderer.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8401/show-all-overdue-patients-count-instead-of-just-pending-patients-in-overdue-tab
> Show all overdue patients count instead of just pending patients in overdue tab

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/patient/onlinelookup/api/RetentionType.kt
Moshi requires us to annotate the enums with `@JsonClass(generateAdapter  = false)` to prevent obfuscation by R8/ProGuard
https://github.com/square/moshi#enums
This fixes a crash
https://sentry.io/organizations/resolve-to-save-lives/issues/2579117871/?project=1212614&referrer=slack
> Fix `RetentionType` getting obfuscated by R8/Proguard

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
https://app.shortcut.com/simpledotorg/story/8437/fetch-the-last-created-appointment-for-the-patient-when-fetching-the-latest-overdue-appointment
> Fetch the last created appointment for the patient when fetching the latest overdue appointment

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt
https://app.shortcut.com/simpledotorg/story/8337/show-no-pending-patients-error-card-when-there-are-no-overdue-pending-patients
> Show no pending patients card when there are no pending overdue patients

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt
- app/src/main/java/org/simple/clinic/home/overdue/PendingListState.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8336/handle-see-all-and-see-less-button-state-for-pending-overdue-lists
> Handle pending list footer clicks

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt
https://app.shortcut.com/simpledotorg/story/8453/fix-app-crashing-after-coming-back-to-app-from-the-background-after-the-overdue-list-is-loaded
> Fix app crashing after coming back to app from the background after the overdue list is loaded

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUi.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUiRenderer.kt
- app/src/main/res/layout/list_item_overdue_pending_list_footer.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/home/overdue/OverdueUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8336/handle-see-all-and-see-less-button-state-for-pending-overdue-lists
> Handle see all/see less button clicks for pending overdue list section

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt
https://app.shortcut.com/simpledotorg/story/8465/fix-see-all-button-being-shown-when-there-are-no-overdue-patients
> Don't show pending overdue list footer if there are no pending overdue appointments

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment_Old.kt
https://app.shortcut.com/simpledotorg/story/7644/overdue-list-is-loading-patients-with-older-appointments-even-though-there-are-recent-visits
> Fix overdue list showing older scheduled appointments

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentSectionTitle.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentSections.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8343/handle-collapse-expand-states-of-overdue-appointment-sections
> Handle collapse/expand states of overdue appointment sections - #1

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt
https://app.shortcut.com/simpledotorg/story/8343/handle-collapse-expand-states-of-overdue-appointment-sections
> Handle collapse/expand states of overdue appointment sections - #final

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt
https://app.shortcut.com/simpledotorg/story/8487/fix-no-pending-patients-illustration-is-not-collapsing
> Fix no pending patients illustration is not collapsing

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt
https://app.shortcut.com/simpledotorg/story/8526/hide-footer-when-the-pending-section-is-collapsed
> Hide footer when the pending section is collapsed

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchInit.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchInitTest.kt
https://app.shortcut.com/simpledotorg/story/8520/display-search-history-in-overdue-search-screen
> Load overdue search history when overdue search screen is opened

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModule.kt
- app/src/main/java/org/simple/clinic/main/TypedPreference.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt
Unfortunately, the string set preference type doesn't seem to maintain the order in which the items were inserted/added. This becomes a problem when we have to drop older searches as we save newer ones based on the search history limit. To avoid this we will save the search history as a `String` with delimiter and split it. Another potential option is to save it as a JSON array and use Moshi to parse it. Either way, we have to transform the data into a string. 
This is in preparation to extract this into a separate `OverdueSearchHistory` class that takes care of fetching, transforming and updating the overdue search history.
> Save overdue search history as `String` type in preferences

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUiActions.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt
- app/src/main/java/org/simple/clinic/home/overdue/OverdueViewEffectHandler.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8560/open-overdue-search-screen-when-search-button-is-clicked-in-overdue-screen
> Open overdue search screen when search button is clicked in overdue screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8529/handle-user-interactions-for-overdue-search-results
> Handle user interactions for overdue search results (Final)

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt
https://app.shortcut.com/simpledotorg/story/8528/show-no-patients-found-view-when-there-are-no-search-results-in-the-overdue-search-screen
> Handle overdue search load states

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8588/search-overdue-patients-when-the-search-history-item-is-clicked
> Search overdue patients, when the search history item is clicked

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt
https://app.shortcut.com/simpledotorg/story/8600/handle-keyboard-visibility-in-the-overdue-search-screen
> Handle keyboard visibility in overdue search screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchHistory.kt
https://app.shortcut.com/simpledotorg/story/8604/don-t-show-empty-search-history-items-in-overdue-search-screen
> Don't show empty search history items in overdue search screen

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/storage/PurgeDatabaseAndroidTest.kt
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
https://app.shortcut.com/simpledotorg/story/8613/fix-old-synced-appointments-not-getting-deleted-on-purge
> Fix old synced appointments not getting deleted on purge

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/home/overdue/search/OverdueSearchHistoryTest.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchHistory.kt
https://app.shortcut.com/simpledotorg/story/8616/move-existing-search-history-item-to-the-top-when-clicked
> Move existing search history item to the top when clicked

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/report/ReportsModel.kt
Since `ReportsModel#reportsContent` is a HTML string, the size can vary significantly depending on how much data it has. Since the parcel limit is shared across transactions in a process. It's not ideal to save huge data into parcel. Instead of saving and restoring the data in reports screen, we can fetch it from DB on restore to avoid this issue. 
You can use [this](git@github.com:guardian/toolargetool.git) tool to check how much space each transaction operation is taking.
> Ignore `ReportsModel#reportsContent` on parcel

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueAppointmentSearchListItem.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModel.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8664/handle-selected-state-in-overdue-search-screen
> Handle selected overdue appointments state in overdue search screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt
- app/src/main/res/layout/screen_overdue_search.xml
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8672/show-download-and-share-button-in-overdue-search-screen-when-search-results-are-loaded
> Show download and share button in overdue search screen when search results are loaded

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/overdue/download/OverdueDownloadWorker.kt
https://app.shortcut.com/simpledotorg/story/8682/fix-app-crashing-when-scheduling-overdue-download-worker
> Fix app crashing when scheduling overdue download worker

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/overdue/Appointment.kt
https://app.shortcut.com/simpledotorg/story/8680/ignore-deleted-and-old-phone-numbers-when-generating-overdue-csv-from-database
> Ignore deleted and old phone numbers when generating overdue CSV from database

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchInit.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchInitTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8715/use-overdue-appointment-selector-in-overdue-search-screen
> Use overdue appointment selector in overdue search screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
- app/src/main/java/org/simple/clinic/overdue/download/formatdialog/OpenAs.kt
- app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffect.kt
- app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffectHandler.kt
- app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEvent.kt
- app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatInit.kt
- app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUpdate.kt
- app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatInitTest.kt
- app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUiRendererTest.kt
- app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8717/use-overdue-appointment-selector-to-fetch-selected-ids-in-overdue-download-format-selection-dialog
> Use overdue appointment selector to fetch selected ids in overdue download format selection dialog

- CHANGELOG.md
- gradle/libs.versions.toml
- renovate.json5
Previously we didn't update the Material library as Material 3 spec was just introduced and there were some backward compatability issues for us. With recent version it seems much more stable and those issues were addressed. So we are updating Material library again.
But we are not switching to using Material3 or Material You. We will continue using `Theme.MaterialComponents.*` and as such all the components are themed to Material 2 specs.
> Bump Material Design Components to v1.6.1

- CHANGELOG.md
- app/src/main/res/layout/contactpatient_callpatient.xml
https://app.shortcut.com/simpledotorg/story/8484/fix-secure-call-button-showing-when-securing-calling-is-disabled-for-the-facility
> Fix secure call button showing when securing calling is disabled for the facility

- CHANGELOG.md
- app/lint.xml
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt
- app/src/main/res/drawable/ic_chevron_down_24.xml
- app/src/main/res/drawable/ic_chevron_up_24px.xml
https://app.shortcut.com/simpledotorg/story/8792/when-a-list-is-expanded-the-accordion-should-point-downwards
> Point accordion downwards when overdue list is expanded

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseBottomSheet.kt
https://app.shortcut.com/simpledotorg/story/8793/call-button-in-bottom-sheet-is-half-hidden
> Fix bottom sheet not opening completely

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchInit.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchInitTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8829/don-t-show-search-history-when-overdue-search-v2-is-enabled
> Don't show search history when overdue search v2 is enabled

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/feature/Feature.kt
Since it's possible we might not finish the overdue search v2 work before next release. Having this key is not backward compatible safe when turning on. So, for now changed it into a developer flag. We add the key back once this entire feature is dev complete.
> Remove overdue search v2 feature flag key

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModel.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8837/add-support-for-searching-with-multiple-village-or-patient-names-in-overdue-search-screen
> Add multiple search inputs support in overdue search screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModel.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiActions.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt
- app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchViewEffectHandler.kt
- app/src/main/java/org/simple/clinic/util/PagerFactory.kt
- app/src/test/java/org/simple/clinic/drugs/search/DrugSearchEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/OverdueLogicTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt
- app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
- app/src/test/java/org/simple/clinic/instantsearch/InstantSearchEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/recentpatient/AllRecentPatientsEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/8853/fix-select-all-not-updating-checkbox-state-in-the-overdue-search-screen
> Fix select all not updating checkbox state in the overdue search screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/widgets/ChipInputAutoCompleteTextView.kt
https://app.shortcut.com/simpledotorg/story/8924/fix-app-crashing-when-overdue-search-screen-is-opened
> Fix app crashing when overdue search screen is opened

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseDialog.kt
https://app.shortcut.com/simpledotorg/story/8943/fix-app-is-crashing-when-clicking-on-download-or-share
> Fix app crashing when clicking on Overdue download or share buttons

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/analytics/MixpanelAnalyticsReporter.kt
We need this to track `AppSession` and `AppUpdated` events that are required for some of the reports we have
> Enable tracking automatic events from Mixpanel

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/ReleaseClinicApp.kt
https://app.shortcut.com/simpledotorg/story/9175/fix-app-crashing-when-injecting-config-reader-in-release-builds
> Remove `ConfigReader` injection from `ReleaseClinicApp`

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/patient/download/PatientLineListCsvGeneratorTest.kt
- app/src/androidTest/java/org/simple/clinic/patient/download/PatientLineListDownloaderTest.kt
- app/src/main/java/org/simple/clinic/patient/PatientConfig.kt
- app/src/main/java/org/simple/clinic/patient/download/PatientLineListCsvGenerator.kt
- app/src/main/java/org/simple/clinic/patient/download/PatientLineListDownloader.kt
- app/src/main/java/org/simple/clinic/patient/download/PatientLineListScheduler.kt
- app/src/main/java/org/simple/clinic/patient/download/PatientLinetListDownloadWorker.kt
- app/src/test/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsLogicTest.kt
Since the HTN control status are not changeable by user from UI and the period is fixed. There is no point exposing the values to be configurable until effect handler. Instead we are creating the start and end date for calculating HTN control status in the `PatientLineListCsvGenerator`
> Move `bpCreatedAfter` and `bpCreatedBefore` date calculation to `PatientLineListCsvGenerator#generate`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
Since we are using observable streams of data on a query that relies on table joins. Without transaction it can cause crashes when the table that are joined has changes.
> Run overdue appointment queries in a transaction

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/9286/fix-diabetes-warning-dialog-showing-in-patient-screen-for-facilities-with-diabetes-management-disabled
> Fix diabetes warning dialog showing in patient screen for facilities with diabetes management disabled

- CHANGELOG.md
- renovate.json5
Flipper updates much more frequently and causes a lot of noise in our PRs. That's why scheduled it to only check for update only once a month instead.
> Add renovate package rule for Flipper updates

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/splash/SplashScreen.kt
- app/src/main/res/layout/screen_splash.xml
- app/src/main/res/values/integers.xml
This will allow us to safely replace the layout for states without having to worry much about the `SplashScreen` class as we are only accessing the next button reference
> Move splash screen lottie config to XML

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/HomeScreen.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenEffect.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenUiActions.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenUpdate.kt
- app/src/main/java/org/simple/clinic/home/HomeScreenViewEffectHandler.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/home/HomeScreenEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/home/HomeScreenUpdateTest.kt
- app/src/test/java/org/simple/clinic/home/HomeScreenViewEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/9424/show-notification-permission-rationale-dialog-when-user-doesn-t-allow-notification-permission
> Show notification permission rationale dialog when user doesn’t allow notification permission

- CHANGELOG.md
- app/src/main/AndroidManifest.xml
Reverting change from #4309, since it's effecting storage permissions in tests
> Remove max SDK for storage permissions

- renovate.json5
We only use this library to turn off logs from `ControllerStateBase` from Mobius. That's why we are not actively looking to update the dependency.
> Ignore logback dependency updates

- .github/workflows/maestro_tests.yml
- CHANGELOG.md
- maestroUiFlows/login_flow.yaml
We are already providing this information publicly as part of test data in `TestDataModule`. So, I don't see any point in keep these as secrets. This will also allow us to eventually have a Gradle task to run the maestro tests without having to pass command params.
> Move test login details into Maestro login flow

- .github/scripts/setup_heroku_instance.sh
- .github/workflows/ci_checks.yml
- CHANGELOG.md
**Story card:** [sc-9029](https://app.shortcut.com/simpledotorg/story/9029/investigate-heroku-ending-free-tier-services-and-potential-non-profit-benefits)
Heroku has stopped supporting hobby (free) dynos. 
This bumps up our heroku review app configuration to use the basic paid tier to unblock android review apps while we figure out alternatives.
> Test heroku android review apps

- .github/scripts/compute_node_dependency_hash.sh
- .github/scripts/generate_heroku_app_name.sh
- CHANGELOG.md
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Replace deprecated `set-output` command in GH Actions

- CHANGELOG.md
- app/schemas/org.simple.clinic.AppDatabase/107.json
- app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration107AndroidTest.kt
- app/src/main/java/org/simple/clinic/AppDatabase.kt
- app/src/main/java/org/simple/clinic/monthlyReports/Questionnaire.kt
- app/src/main/java/org/simple/clinic/storage/migrations/Migration_107.kt
- app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
1. Story Link: https://app.shortcut.com/simpledotorg/story/9557/add-sync-resource-for-questionnaire-layout-api
2. Questionnaire table modified by adding deleted_at column (type: String, nullable: true)
3. App database version updated to 107.
> Add column deleted_at to the questionnaire table

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/sync/SyncModule.kt
Questionnaire sync resource removed from the sync list as the feature is still in development mode.
https://app.shortcut.com/simpledotorg/story/9558/add-sync-resource-for-questionnaire-responseapi
> Questionnaire sync resource removed from sync list

- .github/workflows/trigger_release.yml
[sc-9976](https://app.shortcut.com/simpledotorg/story/9976/user-enumeration-through-api-endpoints)
The `trigger_release` action was broken due to changes introduced in https://github.com/simpledotorg/simple-android/pull/4645.
This fixes usage of the `setup_heroku_instance` script, which takes a branch name that needs to be explicitly passed in.
> Fix trigger_release GH action

- CHANGELOG.md
- app/proguard-rules.pro
https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md#r8-full-mode
> Add rules to prevent Retrofit & GSON types being stripped in R8 full mode

- .github/scripts/setup_heroku_instance.sh
- .github/workflows/ci_checks.yml
- .github/workflows/trigger_release.yml
- CHANGELOG.md
This will fix the failing integration tests on CI
> Use heroku generated app url for manifest endpoint in CI

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
https://app.shortcut.com/simpledotorg/story/10839/hide-overdue-download-share-actions-when-there-are-no-overdue-patients
> Hide overdue download/share actions when there are no overdue patients

- README.md
This build status is for CI runs, but we don't run CI runs on push on main branch, so the indicator is showing it for the last finished PR CI run. It doesn't make sense to include that in the README. So, removing it.
PS: Since it doesn't impact project in anyway, haven't update the CHANGELOG
> Remove build status from the README

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/teleconsultlog/shareprescription/TeleconsultSharePrescriptionRepository.kt
- build.gradle.kts
- gradle/libs.versions.toml
Since Jetpack Compose BOM doesn't support using alpha/beta version BOM, we are switching to using a different maven path for that.
https://app.shortcut.com/simpledotorg/story/10889/add-date-picker-component-to-questionnaire-forms
> Bump Compose BOM to latest alpha versions

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/contactpatient/views/CallPatientView.kt
- app/src/main/java/org/simple/clinic/contactpatient/views/SetAppointmentReminderView.kt
- app/src/main/java/org/simple/clinic/facilitypicker/FacilityPickerView.kt
- app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryQuestionView.kt
- app/src/main/java/org/simple/clinic/security/pin/PinEntryCardView.kt
- app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityView.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureItemView.kt
- app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureSummaryView.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarItemView.kt
- app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarSummaryView.kt
- app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryView.kt
- app/src/main/java/org/simple/clinic/summary/nextappointment/NextAppointmentCardView.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryItemView.kt
- app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryView.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/doctorinfo/TeleconsultDoctorInfoView.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesView.kt
- app/src/main/java/org/simple/clinic/teleconsultlog/prescription/patientinfo/TeleconsultPatientInfoView.kt
- app/src/main/java/org/simple/clinic/widgets/ChipInputAutoCompleteTextView.kt
- app/src/main/java/org/simple/clinic/widgets/PatientStatusView.kt
We initially did this because in documentation it was done for Fragments, but fragments outlive there views, so we were clearing it. Since that's not the case with views, it's not necessary.
In fact this can cause issues in scenarios where a view is detached because it's being recycled or in background, and once the view is attached again the binding is null and causes crashes
> Stop clearing view binding reference when a custom view is detached

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/util/MinimumMemoryChecker.kt
Based on conversation with Jon and Daniel, we increased the minimum required memory for encryption to 5.5 GB (essentially devices that are advertised as having 6 GB or more memory)
> Increase minimum required memory for encryption to 5.5GB

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/navigation/v2/History.kt
We are getting quite a few errors when trying to remove the last key. Adding the key name to help debug this issue further.
> Report last key name when removing last key fails in `History`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeSheet.kt
- app/src/main/java/org/simple/clinic/navigation/v2/History.kt
- app/src/main/java/org/simple/clinic/navigation/v2/Router.kt
https://app.shortcut.com/simpledotorg/story/11505/fix-app-crashing-when-trying-to-replacing-the-last-screen-during-navigation
> Fix app crashing when trying to replacing the last screen during navigation

- .gitignore
- .idea/inspectionProfiles/Project_Default.xml
- CHANGELOG.md
- app/src/main/java/org/simple/clinic/consent/onboarding/OnboardingConsentEffect.kt
- app/src/main/java/org/simple/clinic/consent/onboarding/OnboardingConsentEffectHandler.kt
- app/src/main/java/org/simple/clinic/consent/onboarding/OnboardingConsentEvent.kt
- app/src/main/java/org/simple/clinic/consent/onboarding/OnboardingConsentModel.kt
- app/src/main/java/org/simple/clinic/consent/onboarding/OnboardingConsentScreenFragment.kt
- app/src/main/java/org/simple/clinic/consent/onboarding/OnboardingConsentUpdate.kt
- app/src/main/java/org/simple/clinic/consent/onboarding/OnboardingConsentViewEffectHandler.kt
- app/src/main/java/org/simple/clinic/consent/onboarding/UiActions.kt
- app/src/main/java/org/simple/clinic/di/AppModule.kt
- app/src/main/java/org/simple/clinic/main/TypedPreference.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingEffect.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingEffectHandler.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingEvent.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingScreen.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingUi.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingUpdate.kt
- app/src/main/java/org/simple/clinic/onboarding/OnboardingViewEffectHandler.kt
- app/src/main/java/org/simple/clinic/setup/SetupActivityComponent.kt
- app/src/main/java/org/simple/clinic/util/ViewModelExt.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/simple/clinic/consent/onboarding/OnboardingConsentEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/consent/onboarding/OnboardingConsentUpdateTest.kt
- app/src/test/java/org/simple/clinic/onboarding/OnboardingEffectHandlerTest.kt
- app/src/test/java/org/simple/clinic/onboarding/OnboardingUpdateTest.kt
- common-ui/src/main/java/org/simple/clinic/common/ui/components/Button.kt
- maestroUiFlows/login_flow.yaml
https://app.shortcut.com/simpledotorg/story/11557/show-data-protection-consent-screen-during-onboarding
> Show data protection consent screen during onboarding

- CHANGELOG.md
- renovate.json5
Schedule ended up creating a backlog of dependency updates, and ideally, we would want to review any updates before merging in. So, removed these 2 options.
> Remove schedule and auto merge from renovate

- .github/scripts/setup_heroku_instance.sh
We fix a bug in the setup script that always causes the exit code of the rails db setup and seeding to be successful because it used the exit code of `heroku run` itself. We add a flag that will instead pass through the exit code of the underlying run, in this case, the `rails` command.
> heroku setup: pass through seed exit status

- CHANGELOG.md
- gradle/libs.versions.toml
Paging 3.3.0 release is causing occasional crashes in the app. Probably due to KMP migration, so reverting this update, so that we can resolve those issue for the time being.
Tracking issue here: https://issuetracker.google.com/issues/343124454
> Revert AndroidX Paging to v3.2.1

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreen.kt
- app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffectHandler.kt
- app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/13418/app-crashing-when-displaying-blood-pressure-history-list
> Fix app crashing when viewing BP history

- CHANGELOG.md
- common-ui/src/main/res/values-v35/theme.xml
- common-ui/src/main/res/values/theme.xml
**Story:** https://app.shortcut.com/simpledotorg/story/14491/handle-edge-to-edge-enforcement-in-android-15
Stop-gap until we handle window insets properly in all screens and components
> Opt-out of edge to edge enforcement on Android 15

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskLevel.kt
- app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskRange.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt
- app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt
- app/src/main/java/org/simple/clinic/summary/compose/StatinNudgeView.kt
- app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/14643/show-smoking-dialog-if-risk-is-low-high-or-medium-high?team_id=1&iteration_ids=14465&iteration_ids=14489
> Show smoking status dialog when cvd risk is `LOW-HIGH` or `MEDIUM-HIGH`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/settings/Language.kt
- app/src/main/java/org/simple/clinic/settings/PreferencesSettingsRepository.kt
- app/src/main/java/org/simple/clinic/settings/SettingsModule.kt
- app/src/test/java/org/simple/clinic/settings/PreferencesSettingsRepositoryTest.kt
https://app.shortcut.com/simpledotorg/story/15301/display-only-languages-supported-by-the-selected-country-in-the-settings-screen
> Display only languages supported by the selected country in the settings screen

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/settings/SettingsModule.kt
**Story:** https://app.shortcut.com/simpledotorg/story/15317/show-spanish-language-option-in-non-production-builds
> Show spanish language option in non-production builds only

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/compose/StatinNudgeView.kt
https://app.shortcut.com/simpledotorg/story/15517/fix-crash-when-displaying-large-statin-risk-percentage-text
>  Fix crash when displaying large statin risk percentage text 

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/widgets/ChipInputAutoCompleteTextView.kt
**Story:** https://app.shortcut.com/simpledotorg/story/15703/handle-nullable-inputs-when-removing-last-chip-in-the-chipinputautocompletetextview
> Handle nullable inputs when removing last chip in the `ChipInputAutoCompleteTextView`

- CHANGELOG.md
- app/src/androidTest/java/org/simple/clinic/storage/DatabaseEncryptorTest.kt
- app/src/main/java/org/simple/clinic/storage/DatabaseEncryptor.kt
- app/src/main/java/org/simple/clinic/storage/StorageModule.kt
- gradle/libs.versions.toml
https://app.shortcut.com/simpledotorg/story/16100/migrate-deprecated-sqlcipher-library?team_id=1&iteration_ids=15786&iteration_ids=16015
> Replace `android-database-sqlcipher` library with `sqlcipher-android`

- CHANGELOG.md
- app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
https://app.shortcut.com/simpledotorg/story/16485/update-tobacco-use-dialog-to-single-option-select-in-ethiopia
> Update tobacco use dialog to single option select in Ethiopia
