simpledotorg/simple-android

CHANGELOG.md, app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityView.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntrySheet.kt, app/src/main/java/org/simple/clinic/bloodsugar/selection/type/BloodSugarTypePickerSheet.kt, app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheet.kt, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreen.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt, app/src/main/java/org/simple/clinic/contactpatient/views/CallPatientView.kt, app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesScreen.kt, app/src/main/java/org/simple/clinic/drugs/selection/dosage/DosagePickerSheet.kt, app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntrySheet.kt, app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeSheet.kt, app/src/main/java/org/simple/clinic/facility/change/FacilityChangeActivity.kt, app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeSheet.kt
=> Migrate app to use View Binding instead of Kotlin synthetic view accessors - 3

CHANGELOG.md, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffect.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEvent.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntrySheet.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUi.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUpdate.kt, app/src/main/java/org/simple/clinic/bloodsugar/unitselection/BloodSugarUnitSelectionDialog.kt, app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/1789/add-blood-sugar-unit-switching-button-in-bloodsugarentrysheet
=> Open `BloodSugarUnitSelectionDialog`

CHANGELOG.md, app/src/main/java/org/simple/clinic/widgets/qrcodescanner/QrCodeScannerView.kt
https://app.clubhouse.io/simpledotorg/story/1565/bp-passport-scan-failing
=> Fix BP passport scanning not working

app/src/test/java/org/simple/clinic/home/HomeScreenEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/HomeScreenUpdateTest.kt
=> BP Passport scanning cleanup

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/HomeScreenEffect.kt, app/src/main/java/org/simple/clinic/home/HomeScreenEffectHandler.kt, app/src/main/java/org/simple/clinic/home/HomeScreenEvent.kt, app/src/main/java/org/simple/clinic/home/HomeScreenUpdate.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEvent.kt, app/src/main/java/org/simple/clinic/scanid/ScanResult.kt, app/src/main/java/org/simple/clinic/scanid/ScanSearchState.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffect.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandler.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEvent.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdModel.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUi.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUiRenderer.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt, app/src/main/res/layout/screen_scan_simple.xml, app/src/test/java/org/simple/clinic/home/HomeScreenEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/HomeScreenUpdateTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdScreenLogicTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdUiRendererTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2063/app-shows-home-screen-after-scanning-a-bp-passport
=> Fix app going back to home screen after scanning BP passport

CHANGELOG.md, app/src/main/java/org/simple/clinic/ViewControllerBinding.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultEffect.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultEffectHandler.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultInit.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultScreen.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultState.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultStateProducer.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultUi.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultUpdate.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/UiActions.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/UiRenderer.kt, app/src/test/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/1955/migrate-short-code-search-results-screen-to-mobius
=> Prepare the short code search results screen for mobius migration

CHANGELOG.md, app/src/main/java/org/simple/clinic/searchresultsview/PatientSearchView.kt, app/src/main/java/org/simple/clinic/settings/SettingsScreen.kt, app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageScreen.kt, app/src/main/java/org/simple/clinic/setup/SetupActivity.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultScreen.kt, app/src/main/java/org/simple/clinic/signature/SignatureActivity.kt, app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialog.kt, app/src/main/res/layout/activity_setup.xml, app/src/main/res/layout/screen_shortcode_search_result.xml
=> Migrate app to use View Binding instead of Kotlin synthetic view accessors - 5

CHANGELOG.md, app/src/main/java/org/simple/clinic/widgets/qrcodescanner/BitmapUtils.kt, app/src/main/java/org/simple/clinic/widgets/qrcodescanner/FrameMetadata.kt, app/src/main/java/org/simple/clinic/widgets/qrcodescanner/MLKitQrCodeAnalyzer.kt, app/src/main/java/org/simple/clinic/widgets/qrcodescanner/QrCodeScannerView.kt
https://app.clubhouse.io/simpledotorg/story/2000/unable-to-scan-passports-or-find-patients
=> Fix BP passport scanning using ML Kit

CHANGELOG.md, app/src/main/java/org/simple/clinic/navigation/v2/Direction.kt, app/src/main/java/org/simple/clinic/navigation/v2/ExpectsResult.kt, app/src/main/java/org/simple/clinic/navigation/v2/HandlesBack.kt, app/src/main/java/org/simple/clinic/navigation/v2/History.kt, app/src/main/java/org/simple/clinic/navigation/v2/NavRequest.kt, app/src/main/java/org/simple/clinic/navigation/v2/Router.kt, app/src/main/java/org/simple/clinic/navigation/v2/ScreenKey.kt, app/src/main/java/org/simple/clinic/navigation/v2/ScreenResult.kt
https://app.clubhouse.io/simpledotorg/story/2131/add-support-for-the-new-navigation-framework
=> Implement a Router that allows routing screens via fragments

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/views/RemoveAppointmentView.kt, app/src/main/java/org/simple/clinic/contactpatient/views/SetAppointmentReminderView.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryQuestionView.kt, app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureItemView.kt, app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarItemView.kt, app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryItemView.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/doctorinfo/TeleconsultDoctorInfoView.kt
=> Migrate app to use View Binding instead of Kotlin synthetic view accessors - 9

.gitignore, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/inspectionProfiles/Project_Default.xml, CHANGELOG.md
One way we can check if it works is by checking out this branch and checking the AS settings to see if the lint rule is enabled and if the code style is selected at the project level with correct values.
=> Track code style and lint rules for project in VCS

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
https://app.clubhouse.io/simpledotorg/story/1967/implement-instant-search-query
=> Implement Instant Search Query

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/85.json, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration85AndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityEffectHandler.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_85.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt, app/src/test/java/org/simple/clinic/allpatientsinfacility/AllPatientsInFacilityLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/2029/implement-instant-search-screen
=> Implement instant search screen - 1

CHANGELOG.md, app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseBottomSheet.kt, app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseDialog.kt, app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseScreen.kt, app/src/main/java/org/simple/clinic/util/AndroidExtensions.kt, app/src/main/res/values/styles_v2.xml
https://app.clubhouse.io/simpledotorg/story/2131/add-support-for-the-new-navigation-framework
=> Add convenience screens for working with the new navigation framework

CHANGELOG.md, app/src/main/java/org/simple/clinic/bp/assignbppassport/BpPassportSheet.kt
https://app.clubhouse.io/simpledotorg/story/1977/show-bp-passport-sheet-in-instant-search-screen
=> Update BpPassport prefill value to displayValue

CHANGELOG.md, app/src/main/java/org/simple/clinic/di/AppModule.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchConfig.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchConfigModule.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffect.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEvent.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchInit.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchModel.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUiActions.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchValidator.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchInitTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2029/implement-instant-search-screen
=> Implement instant search screen - 3

CHANGELOG.md, app/build.gradle, app/src/main/java/org/simple/clinic/activity/BindsScreenResultBus.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/confirmremovebloodsugar/ConfirmRemoveBloodSugarDialog.kt, app/src/main/java/org/simple/clinic/bloodsugar/unitselection/BloodSugarUnitSelectionDialog.kt, app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialog.kt, app/src/main/java/org/simple/clinic/deniedaccess/AccessDeniedScreen.kt, app/src/main/java/org/simple/clinic/introvideoscreen/IntroVideoScreen.kt, app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt, app/src/main/java/org/simple/clinic/navigation/di/FlowScreenKeyModule.kt, app/src/main/java/org/simple/clinic/navigation/v2/keyprovider/FlowBasedScreenKeyProvider.kt, app/src/main/java/org/simple/clinic/navigation/v2/keyprovider/FragmentBasedScreenKeyProvider.kt, app/src/main/java/org/simple/clinic/navigation/v2/keyprovider/ScreenKeyProvider.kt, app/src/main/java/org/simple/clinic/registerorlogin/AuthenticationActiivtyComponent.kt, app/src/main/java/org/simple/clinic/registerorlogin/AuthenticationActivity.kt, app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreen.kt, app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt, app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreen.kt, app/src/main/java/org/simple/clinic/registration/name/RegistrationFullNameScreen.kt, app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreen.kt, app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingScreen.kt, app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberDialog.kt, app/src/main/java/org/simple/clinic/sync/indicator/dialog/SyncIndicatorFailureDialog.kt, app/src/main/res/layout/activity_setup.xml, build.gradle
https://app.clubhouse.io/simpledotorg/story/2183/migrate-authenticationactivity-to-the-new-navigation-framework
=> Prepare `AuthenticationActivity` to use the new navigation framework

CHANGELOG.md, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffect.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEvent.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchInit.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchModel.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUiActions.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchInitTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2029/implement-instant-search-screen
=> Implement instant search screen - 4

CHANGELOG.md, app/src/main/java/org/simple/clinic/bp/assignbppassport/BlankBpPassportResult.kt, app/src/main/java/org/simple/clinic/bp/assignbppassport/BpPassportEffect.kt, app/src/main/java/org/simple/clinic/bp/assignbppassport/BpPassportEffectHandler.kt, app/src/main/java/org/simple/clinic/bp/assignbppassport/BpPassportEvent.kt, app/src/main/java/org/simple/clinic/bp/assignbppassport/BpPassportSheet.kt, app/src/main/java/org/simple/clinic/bp/assignbppassport/BpPassportUiActions.kt, app/src/main/java/org/simple/clinic/bp/assignbppassport/BpPassportUpdate.kt, app/src/test/java/org/simple/clinic/bp/assignbppassport/BpPassportEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/bp/assignbppassport/BpPassportUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/1977/show-bp-passport-sheet-in-instant-search-screen
Resolved previous https://github.com/simpledotorg/simple-android/pull/2223#discussion_r544956740
=> Send BpPassport result

CHANGELOG.md, quality/pre-push
=> Revert "Fix garbled gradle logs when running pre-push hook in Git Bash"

CHANGELOG.md, app/src/main/java/org/simple/clinic/bp/assignbppassport/BpPassportSheet.kt, app/src/main/java/org/simple/clinic/bp/assignbppassport/BpPassportUiActions.kt, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEvent.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2029/implement-instant-search-screen
=> Implement instant search screen - Final

CHANGELOG.md, app/src/main/java/org/simple/clinic/activity/BindsRouter.kt, app/src/main/java/org/simple/clinic/introvideoscreen/IntroVideoScreen.kt, app/src/main/java/org/simple/clinic/login/pin/LoginPinScreen.kt, app/src/main/java/org/simple/clinic/login/pin/LoginPinScreenKey.kt, app/src/main/java/org/simple/clinic/navigation/di/FragmentScreenKeyModule.kt, app/src/main/java/org/simple/clinic/navigation/v2/History.kt, app/src/main/java/org/simple/clinic/navigation/v2/Router.kt, app/src/main/java/org/simple/clinic/navigation/v2/ScreenKey.kt, app/src/main/java/org/simple/clinic/navigation/v2/compat/ScreenKeyCompat.kt, app/src/main/java/org/simple/clinic/registerorlogin/AuthenticationActiivtyComponent.kt, app/src/main/java/org/simple/clinic/registerorlogin/AuthenticationActivity.kt, app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreen.kt, app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreenKey.kt, app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt, app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreen.kt, app/src/main/java/org/simple/clinic/registration/name/RegistrationFullNameScreen.kt, app/src/main/java/org/simple/clinic/registration/name/RegistrationNameScreenKey.kt, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenKey.kt, app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreen.kt, app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreenKey.kt, app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingScreen.kt, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryScreen.kt, app/src/main/res/layout/screen_login_pin.xml, app/src/main/res/layout/screen_registration_confirm_pin.xml, app/src/main/res/layout/screen_registration_name.xml, app/src/main/res/layout/screen_registration_phone.xml, app/src/main/res/layout/screen_registration_pin.xml
https://app.clubhouse.io/simpledotorg/story/2183/migrate-authenticationactivity-to-the-new-navigation-framework
=> Migrate `AuthenticationActivity` to use the new navigation framework

CHANGELOG.md, doc/arch/002-bottom-sheets.md, doc/arch/005-single-activity-view-based-navigation.md, doc/arch/011-screen-navigation-v2.md
https://app.clubhouse.io/simpledotorg/story/1998/create-an-adr-for-the-mobile-navigation-refactor
=> Add ADR for the new navigation framework

CHANGELOG.md, app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreen.kt, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreen.kt, app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesScreen.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/editpatient/deletepatient/DeletePatientScreen.kt, app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/search/PatientSearchScreen.kt, app/src/main/java/org/simple/clinic/search/results/PatientSearchResultsScreen.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityView.kt, app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureSummaryView.kt, app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarSummaryView.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryView.kt, app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryView.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/TeleconsultPrescriptionScreen.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesView.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/patientinfo/TeleconsultPatientInfoView.kt, app/src/main/java/org/simple/clinic/teleconsultlog/shareprescription/TeleconsultSharePrescriptionScreen.kt, app/src/main/java/org/simple/clinic/teleconsultlog/success/TeleConsultSuccessScreen.kt, app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordScreen.kt, router/src/main/java/org/simple/clinic/router/screen/ScreenRouter.kt
https://app.clubhouse.io/simpledotorg/story/2270/migrate-theactivity-to-the-new-navigation-framework
=> Prepare `TheActivity` for migration to the new navigation framework

app/src/main/res/color/color_high_emphasis.xml, app/src/main/res/color/color_low_emphasis.xml, app/src/main/res/color/color_medium_emphasis.xml, app/src/main/res/color/mtrl_btn_stroke_color_selector.xml, app/src/main/res/values/colors_v3.xml, app/src/main/res/values/shape.xml, app/src/main/res/values/styles_v3.xml, app/src/main/res/values/theme_attr.xml, app/src/main/res/values/theme_overlay.xml, app/src/main/res/values/theme_v2.xml, app/src/main/res/values/type.xml, quality/lint.xml
https://app.clubhouse.io/simpledotorg/story/1780/material-theming-migration
=> Material Theming Migration - 1

CHANGELOG.md, app/src/debug/java/org/simple/clinic/DebugClinicApp.kt
https://app.clubhouse.io/simpledotorg/story/2057/strict-mode-violation
=> Strict mode violation

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientEffect.kt, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientEvent.kt, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientModel.kt, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientUiRenderer.kt, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientUpdate.kt, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientView.kt, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewUi.kt, app/src/main/res/layout/link_id_with_patient_view.xml, app/src/main/res/values-am-rET/strings.xml, app/src/main/res/values-bn-rBD/strings.xml, app/src/main/res/values-bn-rIN/strings.xml, app/src/main/res/values-hi-rIN/strings.xml, app/src/main/res/values-kn-rIN/strings.xml, app/src/main/res/values-mr-rIN/strings.xml, app/src/main/res/values-om-rET/strings.xml, app/src/main/res/values-pa-rIN/strings.xml, app/src/main/res/values-ta-rIN/strings.xml, app/src/main/res/values-te-rIN/strings.xml, app/src/main/res/values-ti-rET/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles_v2.xml, app/src/test/java/org/simple/clinic/summary/linkId/LinkIdWithPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/linkId/LinkIdWithPatientUiRendererTest.kt, app/src/test/java/org/simple/clinic/summary/linkId/LinkIdWithPatientUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/1982/change-linkidwithpatientview-design
=> Change `LinkIdWithPatientView` design

CHANGELOG.md, app/src/main/java/org/simple/clinic/appupdate/dialog/AppUpdateDialog.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/confirmremovebloodsugar/ConfirmRemoveBloodSugarDialog.kt, app/src/main/java/org/simple/clinic/bloodsugar/unitselection/BloodSugarUnitSelectionDialog.kt, app/src/main/java/org/simple/clinic/bp/entry/confirmremovebloodpressure/ConfirmRemoveBloodPressureDialog.kt, app/src/main/java/org/simple/clinic/drugs/selection/entry/confirmremovedialog/ConfirmRemovePrescriptionDialog.kt, app/src/main/java/org/simple/clinic/editpatient/ConfirmDiscardChangesDialog.kt, app/src/main/java/org/simple/clinic/editpatient/deletepatient/DeletePatientScreen.kt, app/src/main/java/org/simple/clinic/home/patients/LoggedOutOnOtherDeviceDialog.kt, app/src/main/java/org/simple/clinic/login/applock/ConfirmResetPinDialog.kt, app/src/main/java/org/simple/clinic/main/TheActivity.kt, app/src/main/java/org/simple/clinic/medicalhistory/SelectDiagnosisErrorDialog.kt, app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceDialog.kt, app/src/main/java/org/simple/clinic/setup/SetupActivity.kt, app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialog.kt, app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberDialog.kt, app/src/main/java/org/simple/clinic/sync/indicator/dialog/SyncIndicatorFailureDialog.kt, app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultNotRecordedDialog.kt, app/src/main/res/values/styles_v3.xml, app/src/main/res/values/theme_overlay.xml, app/src/main/res/values/theme_v2.xml
https://app.clubhouse.io/simpledotorg/story/1780/material-theming-migration
=> Material Theming Migration - 3

CHANGELOG.md, lint/src/main/java/org/simple/clinic/lint/CardViewDetector.kt, lint/src/main/java/org/simple/clinic/lint/SimpleIssueRegistry.kt, lint/src/main/java/org/simple/clinic/lint/TextViewTextSizeDetector.kt, lint/src/test/java/org/simple/clinic/lint/CardViewDetectorTest.kt, lint/src/test/java/org/simple/clinic/lint/TextViewTextSizeDetectorTest.kt
https://app.clubhouse.io/simpledotorg/story/2364/add-lint-rules-when-using-platform-appcompat-components-that-are-available-in-mdc
=> Add lint rules

CHANGELOG.md, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffect.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchResultsItemType.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUiActions.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/main/java/org/simple/clinic/widgets/PatientSearchResultItemView.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchResultsItemTypeTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2035/highlight-patient-name-and-phone-number-based-on-search-query
=> Highlight instant search results

CHANGELOG.md, app/src/debug/java/org/simple/clinic/playground/AwaitActivity.kt, app/src/main/java/org/simple/clinic/bloodsugar/selection/type/BloodSugarTypeAdapter.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberDialog.kt, app/src/main/java/org/simple/clinic/widgets/PatientSearchResultItemView.kt
=> Migrate app to use View Binding instead of Kotlin synthetic view accessors - 12

CHANGELOG.md, app/src/main/java/org/simple/clinic/appconfig/AppConfigRepository.kt, app/src/main/java/org/simple/clinic/crash/SentryCrashReporter.kt
https://app.clubhouse.io/simpledotorg/story/322/track-the-user-country-in-sentry
=> Track the user country in Sentry

CHANGELOG.md, app/build.gradle, app/src/main/java/org/simple/clinic/drugs/selection/AddNewPrescriptionListItem.kt, app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesScreen.kt, app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesUi.kt, app/src/main/java/org/simple/clinic/drugs/selection/ProtocolDrugListItem.kt, app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescribedDrugListItem.kt, app/src/main/java/org/simple/clinic/summary/GroupieItemWithUiEvents.kt, app/src/main/java/org/simple/clinic/widgets/BottomSheetActivity.kt, build.gradle
=> Migrate app to use View Binding instead of Kotlin synthetic view accessors - 13

CHANGELOG.md, app/src/main/res/values/styles.xml, app/src/main/res/values/theme_overlay.xml, quality/lint.xml
**Usage**
```xml
<com.google.android.material.textfield.TextInputLayout
android:id="@+id/textInputLayout"
style="@style/Widget.Simple.TextField.Layout.PatientEntry.AutoComplete"
android:layout_width="match_parent"
android:layout_height="wrap_content">
<com.google.android.material.textfield.MaterialAutoCompleteTextView
android:id="@+id/autoCompleteTextView"
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:hint="@string/hint"/>
</com.google.android.material.textfield.TextInputLayout>
```
=> Add `Widget.Simple.TextField.Layout.PatientEntry.AutoComplete` style

CHANGELOG.md, build.gradle
Context: https://jeroenmols.com/blog/2021/02/04/migratingjcenter/
=> Limit JCenter to specific dependencies only

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffect.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEvent.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUpdate.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2359/update-patient-migrated-status-from-call-result
=> Update `PatientStatus` to migrated

CHANGELOG.md, app/src/main/res/layout/sheet_custom_prescription_entry.xml
https://app.clubhouse.io/simpledotorg/story/2594/fix-prescription-entry-sheet-ui
=> Fix prescription entry sheet UI

CHANGELOG.md, app/src/main/java/org/simple/clinic/teleconsultlog/shareprescription/TeleconsultSharePrescriptionScreen.kt
https://app.clubhouse.io/simpledotorg/story/2570/add-white-background-color-to-downloaded-prescription
=> Add white background color to downloaded prescription

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/2517/slow-patient-screen-load
=> Stop overdue query from being triggered twice in the overdue screen

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/patient/PatientAddress.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
https://app.clubhouse.io/simpledotorg/story/2572/load-list-of-colonyorvillage-from-the-patientaddress-table
=> Load list of `colonyOrVillage` from `PatientAddress`

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/linkId/ButtonState.kt, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientModel.kt, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientUiRenderer.kt, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientUpdate.kt, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientView.kt, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewUi.kt, app/src/main/res/layout/link_id_with_patient_view.xml, app/src/test/java/org/simple/clinic/summary/linkId/LinkIdWithPatientUiRendererTest.kt, app/src/test/java/org/simple/clinic/summary/linkId/LinkIdWithPatientUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/linkId/LinkIdWithPatientViewLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/2655/convert-add-button-from-linkidwithpatientview-to-progress-button
=> Convert add button from `LinkIdWithPatientView` to progress button

CHANGELOG.md, app/src/main/java/org/simple/clinic/medicalhistory/newentry/ButtonState.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryModel.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUi.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRenderer.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdate.kt, app/src/main/res/layout/screen_new_medical_history.xml, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRendererTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2656/convert-next-button-from-newmedicalhistoryscreen-to-progress-button
=> Convert next button from `NewMedicalHistoryScreen` to progress button

CHANGELOG.md, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://simpledotorg.slack.com/archives/CFHKJ5WJY/p1613968075000100?thread_ts=1613709946.216200&cid=CFHKJ5WJY
=> Stop loading all patients after current facility is loaded in `InstantSearchScreen`

CHANGELOG.md, app/src/main/res/layout/screen_patient_summary.xml
https://app.clubhouse.io/simpledotorg/story/2601/convert-patient-summary-screen-to-use-constraintlayout
=> Convert `screen_patient_summary` to use `ConstraintLayout`

CHANGELOG.md, app/src/main/java/org/simple/clinic/appupdate/AppUpdateModule.kt, app/src/main/java/org/simple/clinic/appupdate/CheckAppUpdateAvailability.kt, app/src/main/java/org/simple/clinic/appupdate/UpdateInfo.kt, app/src/main/java/org/simple/clinic/appupdate/UpdateManager.kt, app/src/test/java/org/simple/clinic/appupdate/CheckAppUpdateAvailabilityTest.kt, build.gradle
https://app.clubhouse.io/simpledotorg/story/2600/update-play-core-library-version
=> Update play core library version

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryInit.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryProfile.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
Bug explanation: https://simpledotorg.slack.com/archives/CFK2PHJ1L/p1615270894171400
=> Show link id sheet after patient summary profile is loaded and link id is present

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/home/HomeScreen.kt, app/src/main/java/org/simple/clinic/home/HomeScreenUpdate.kt, app/src/test/java/org/simple/clinic/home/HomeScreenLogicTest.kt, app/src/test/java/org/simple/clinic/home/HomeScreenUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2816/add-overdue-badge-to-the-home-screen-tabs
=> Add overdue badge to the home screen tabs

.github/workflows/ci_check_pr_comment.yml, CHANGELOG.md
Reference: https://github.com/cirrus-actions/rebase/pull/70
=> Use personal access token for GitHub rebase command

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientUi.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientViewRenderer.kt, app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt, app/src/main/java/org/simple/clinic/newentry/PatientEntryUi.kt, app/src/main/java/org/simple/clinic/newentry/PatientEntryUiRenderer.kt, app/src/main/res/layout/village_typeahead_list_item.xml, app/src/test/java/org/simple/clinic/editpatient/EditPatientViewRendererTest.kt, app/src/test/java/org/simple/clinic/newentry/PatientEntryUiRendererTest.kt
https://app.clubhouse.io/simpledotorg/story/2574/implement-auto-complete-text-view-in-patient-entry-edit-screens#activity-2824
=> Implement auto complete text view in patient entry/edit screens - 2

CHANGELOG.md, app/src/main/res/layout/screen_edit_patient.xml, app/src/main/res/layout/screen_manual_patient_entry.xml
https://app.clubhouse.io/simpledotorg/story/2932/show-or-between-age-and-dob-fields-in-patient-entry-and-edit
=> Show 'Or' between Age and DOB fields in Patient entry and edit

CHANGELOG.md, app/src/main/assets/drug_stock_no_connection.html, app/src/main/java/org/simple/clinic/home/report/ReportsWebViewClient.kt
https://app.clubhouse.io/simpledotorg/story/2980/show-custom-error-screen-for-drug-stock-web-view-when-there-is-no-internet-connection
=> Show custom error screen for drug stock web view when there is no internet connection

CHANGELOG.md, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffect.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUiActions.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2891/improvements-to-instant-search
=> Improvements to instant search

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffect.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEvent.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchInit.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchModel.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUiActions.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/main/res/drawable/ic_qr_code_scanner.xml, app/src/main/res/layout/screen_instant_search.xml, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchInitTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2974/add-qr-code-scanner-button-in-instantsearchscreen
=> Add QR code scanner button in InstantSearchScreen

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandler.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/patient/PatientRepositoryTest.kt
https://app.clubhouse.io/simpledotorg/story/3010/remove-datetimeformatter-from-patientrepository
=> Remove `DateTimeFormatter` from `PatientRepository`

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/selection/DrugListItem.kt, app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesScreen.kt, app/src/main/res/layout/list_prescribeddrugs_custom_drug.xml, app/src/main/res/layout/list_prescribeddrugs_new_custom_drug.xml, app/src/main/res/layout/list_prescribeddrugs_protocol_drug.xml, app/src/main/res/layout/screen_patient_prescribed_drugs_entry.xml, app/src/main/res/values/shape.xml
https://app.clubhouse.io/simpledotorg/story/2934/make-entire-prescribed-drugs-list-scrollable-instead-of-list-scrolling-inside-a-fixed-card-view
=> Make entire prescribed drugs list scrollable

CHANGELOG.md, app/build.gradle, app/src/androidTest/java/org/simple/clinic/di/TestAppModule.kt, app/src/main/java/org/simple/clinic/appconfig/AppConfigModule.kt, app/src/main/java/org/simple/clinic/appconfig/Country.kt, app/src/main/java/org/simple/clinic/appconfig/CountryModule.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntrySheet.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUi.kt, app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheet.kt, app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryUi.kt, app/src/main/java/org/simple/clinic/di/AppModule.kt, app/src/main/java/org/simple/clinic/di/DateFormatter.kt, app/src/main/java/org/simple/clinic/di/DateFormatterModule.kt, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryLogicTest.kt, build.gradle
https://app.clubhouse.io/simpledotorg/story/3023/render-ethiopian-dates-in-the-app
=> Render Ethiopian dates in the app

CHANGELOG.md, app/src/main/java/org/simple/clinic/widgets/PatientSearchResultItemView.kt, app/src/main/res/values/colors.xml
https://app.clubhouse.io/simpledotorg/story/3062/change-facility-picker-highlight-background-color
https://app.clubhouse.io/simpledotorg/story/2993/change-instant-search-highlight-background-color
=> Change facility picker and instant search highlight background color to yellow

CHANGELOG.md, app/src/main/java/org/simple/clinic/appconfig/Country.kt
https://app.clubhouse.io/simpledotorg/story/3063/update-ethiopian-date-separator-pattern
=> Update Ethiopian date separator pattern

CHANGELOG.md, app/src/main/java/org/simple/clinic/storage/monitoring/DelegateableSQLiteDatabase.kt, app/src/main/java/org/simple/clinic/storage/monitoring/DelegateableSQLiteOpenHelper.kt, app/src/main/java/org/simple/clinic/storage/monitoring/SQLiteDatabaseSqlDelegate.kt
https://app.clubhouse.io/simpledotorg/story/3011/automatically-report-sql-query-performance-to-firebase
=> Support delegating SQL query operations

CHANGELOG.md, app/src/main/java/org/simple/clinic/di/AppModule.kt, app/src/main/java/org/simple/clinic/storage/monitoring/DaoInformationExtractor.kt, app/src/main/java/org/simple/clinic/storage/monitoring/DbMethodLookup.kt, app/src/main/java/org/simple/clinic/storage/monitoring/DelegateableSQLiteOpenHelper.kt, app/src/main/java/org/simple/clinic/storage/monitoring/FirebasePerfReportingSqlDelegate.kt, app/src/test/java/org/simple/clinic/storage/monitoring/DbMethodLookupTest.kt
https://app.clubhouse.io/simpledotorg/story/3011/automatically-report-sql-query-performance-to-firebase
=> Add a SQLite DB delegate that can report to Firebase performance monitoring

CHANGELOG.md, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffect.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEvent.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUiActions.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/3129/request-camera-permissions-when-opening-qr-code-scanner-from-instant-search-screen
=> Request camera permissions when opening QR code scanner from instant search screen

CHANGELOG.md, app/build.gradle, app/src/debug/resources/sentry.properties, app/src/main/AndroidManifest.xml, app/src/main/java/org/simple/clinic/crash/SentryCrashReporter.kt, build.gradle, gradle.properties
https://app.clubhouse.io/simpledotorg/story/3251/migrate-sentry-android-to-v4-3-0
=> Migrate Sentry Android to v4.3.0

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/home/HomeScreenEvent.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEvent.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/scanid/ScanResult.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandler.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEvent.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/3284/show-patient-results-if-they-have-same-bp-passport-assigned
=> Show patient results if they have same BP passport assigned

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/87.json, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration87AndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_87.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
Source: https://simpledotorg.slack.com/archives/CFK2PHJ1L/p1619405180375500
=> Fix dead patients showing in overdue list

CHANGELOG.md, app/proguard-rules.pro, app/src/debug/java/org/simple/clinic/storage/SqliteModule.kt, app/src/main/java/org/simple/clinic/storage/StorageModule.kt, app/src/main/java/org/simple/clinic/storage/monitoring/FirebasePerfReportingSqlDelegate.kt, app/src/main/java/org/simple/clinic/storage/monitoring/Sampler.kt, app/src/release/java/org/simple/clinic/storage/SqliteModule.kt
https://app.clubhouse.io/simpledotorg/story/3011/automatically-report-sql-query-performance-to-firebase
=> Enable Room performance profiling

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientUi.kt, app/src/main/res/layout/patient_edit_alternate_id_view.xml, app/src/main/res/layout/screen_edit_patient.xml
https://app.clubhouse.io/simpledotorg/story/3335/show-national-health-id-in-patient-edit-screen
=> Show national health id in patient edit screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/sync/DataSync.kt, app/src/test/java/org/simple/clinic/analytics/AnalyticsTest.kt, simple-platform/src/main/java/org/simple/clinic/platform/analytics/Analytics.kt, simple-platform/src/main/java/org/simple/clinic/platform/analytics/SyncAnalyticsEvent.kt
https://app.clubhouse.io/simpledotorg/story/3356/remove-syncevent-reporting-from-analytics
=> Stop reporting `SyncEvent` to analytics

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/HomeScreen.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchModel.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreenKey.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultScreen.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchInitTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUiRendererTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/3218/show-patients-with-national-health-id-when-searching-with-from-scan-screen
More information about the NHID search behaviour: https://simpledotorg.slack.com/archives/CFK2PHJ1L/p1620159883025500
=> Show patients with national health id when searching with from scan screen - 1

CHANGELOG.md, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchModel.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/main/java/org/simple/clinic/scanid/EnteredCodeInput.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffect.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandler.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUiActions.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchInitTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUiRendererTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/3218/show-patients-with-national-health-id-when-searching-with-from-scan-screen
=> Show patients with national health id when searching with from scan screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/scanid/IndiaNHIDInfoPayload.kt, app/src/main/java/org/simple/clinic/scanid/PatientPrefillInfo.kt
https://app.clubhouse.io/simpledotorg/story/3509/remove-state-and-district-from-patientprefillinfo
=> Remove unwanted fields from `PatientPrefillInfo`

CHANGELOG.md, app/src/main/res/layout/screen_scan_simple.xml, app/src/main/res/values/strings.xml
https://app.clubhouse.io/simpledotorg/story/3511/add-labels-in-the-scan-screen-to-match-the-design
=> Add label in `ScanSimpleIdScreen`

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/88.json, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration88AndroidTest.kt, app/src/androidTest/java/org/simple/clinic/sync/PatientSyncIntegrationTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/main/java/org/simple/clinic/patient/OngoingNewPatientEntry.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt, app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt, app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_88.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://app.clubhouse.io/simpledotorg/story/3157/implement-instant-search-using-bp-passport-number
=> Implement Instant Search using BP Passport Number

CHANGELOG.md, app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchModel.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreenKey.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/main/java/org/simple/clinic/newentry/PatientEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/newentry/PatientEntryUpdate.kt, app/src/main/java/org/simple/clinic/patient/Gender.kt, app/src/main/java/org/simple/clinic/patient/OngoingNewPatientEntry.kt, app/src/main/java/org/simple/clinic/scanid/IndiaNHIDDateOfBirth.kt, app/src/main/java/org/simple/clinic/scanid/IndiaNHIDDateOfBirthMoshiAdapter.kt, app/src/main/java/org/simple/clinic/scanid/IndiaNHIDGender.kt, app/src/main/java/org/simple/clinic/scanid/IndiaNHIDInfoPayload.kt, app/src/main/java/org/simple/clinic/scanid/PatientPrefillInfo.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffect.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandler.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdModel.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUiActions.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt, app/src/main/java/org/simple/clinic/shortcodesearchresult/ShortCodeSearchResultScreen.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchInitTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUiRendererTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt, app/src/test/java/org/simple/clinic/newentry/PatientEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/3215/use-indianhidinfo-for-prefilling-patient-entry-information\
Currently you will see that the nhid number is being shown where the bp passport number is shown. The handling of this is being done in [another story](https://app.clubhouse.io/simpledotorg/story/3535/add-support-for-nhid-in-patiententryscreen)
=> Use `PatientPrefillInfo` for prefilling patient entry information

CHANGELOG.md, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchModel.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreenKey.kt, app/src/main/java/org/simple/clinic/patient/OngoingNewPatientEntry.kt, app/src/main/java/org/simple/clinic/patient/PatientPrefillInfo.kt, app/src/main/java/org/simple/clinic/scanid/IndiaNHIDInfoPayload.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffect.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEvent.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdModel.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUiActions.kt
https://app.clubhouse.io/simpledotorg/story/3639/resolve-coupling-between-scanid-and-instantsearch-packages
=> Resolve Coupling between `scanid` and `instantsearch` packages

CHANGELOG.md, app/src/main/res/layout/sheet_text_input_date_picker.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/theme_overlay.xml
https://app.clubhouse.io/simpledotorg/story/3084/add-a-new-style-and-a-theme-overlay-for-textinputdatepicker-textfields
=> Update style in `TextInputDatePicker` textfields

CHANGELOG.md, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchResultsItemType.kt, app/src/main/java/org/simple/clinic/widgets/PatientSearchResultItemView.kt, app/src/main/res/layout/view_patient_search_result.xml, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchResultsItemTypeTest.kt
https://app.clubhouse.io/simpledotorg/story/3154/instant-search-ui-changes
=> Highlight patient identifiers in search

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/patients/PatientsEffectHandler.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEffect.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUi.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUiActions.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUiRenderer.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUpdate.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/3293/user-cannot-see-sync-button
=> Fix user cannot see sync button bug

CHANGELOG.md, app/src/main/java/org/simple/clinic/scanid/qrcodeanalyzer/MLKitQrCodeAnalyzer.kt, app/src/main/java/org/simple/clinic/util/BitmapUtils.kt
- Allow `BitmapUtils#getBitmap` to use the experiment get image
=> Use `ExperimentalGetImage` for `BitmapUtils#getBitmap`

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/bloodsugar/BloodSugarHistoryListItemDataSourceTest.kt, app/src/androidTest/java/org/simple/clinic/bp/BloodPressureHistoryListItemDataSourceTest.kt, app/src/androidTest/java/org/simple/clinic/home/overdue/OverdueAppointmentRowDataSourceTest.kt, app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarHistoryListItemDataSource.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureHistoryListItemDataSource.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentRowDataSource.kt, buildSrc/src/main/kotlin/Versions.kt
- Bump Room to v2.3.0
- Bump Paging to v3.0.0
- Override `List` instead of `MutableList` in data sources
=> Bump paging dependency

CHANGELOG.md, app/src/main/java/org/simple/clinic/patient/RecentPatient.kt
- Redact logs with `RecentPatient`
=> Redact logs with `RecentPatient`

CHANGELOG.md, app/src/main/java/org/simple/clinic/scanid/QRCodeJsonParser.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandler.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdScreenLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/3561/implement-qr-code-json-parser-and-extract-direct-moshi-usage-in-scansimpleideffecthandler
=> Implement `QRCodeJsonParser` in `ScanSimpleIdEffectHandler`

app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEvent.kt
https://app.clubhouse.io/simpledotorg/story/3813/adding-invalid-code-event
=> Adding analytics name to InvalidQrCode

CHANGELOG.md, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt
https://app.clubhouse.io/simpledotorg/story/3831/fix-instant-search-error-views-overlapping-each-other
=> Fix instant search error views overlapping each other

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/89.json, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration89AndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_89.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueLogicTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/3735/migrate-overdueappointment-to-add-patients-without-phone-number?vc_group_by=day&ct_workflow=all
=> Migrate `OverdueAppointment` to add patients without phone number

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItem.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/main/res/layout/item_overdue_list_patient_old.xml, app/src/main/res/layout/list_item_overdue_patient.xml, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/3871/make-overdue-patient-card-item-clickable-to-open-patient-summary
=> Make overdue patient card item clickable to open patient summary

CHANGELOG.md, app/src/main/java/org/simple/clinic/Globals.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/3870/stringindexoutofboundsexception-while-trying-to-display-nhid-number
=> Fix `StringIndexOutOfBoundsException` while trying to display NHID number

CHANGELOG.md, app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt, app/src/main/java/org/simple/clinic/patient/onlinelookup/DurationFromSecondsMoshiAdapter.kt, app/src/main/java/org/simple/clinic/patient/onlinelookup/PatientOnlineLookupResponsePayload.kt, app/src/main/java/org/simple/clinic/patient/onlinelookup/RecordRetention.kt, app/src/main/java/org/simple/clinic/patient/onlinelookup/RetentionType.kt, app/src/main/java/org/simple/clinic/patient/onlinelookup/SecondsDuration.kt, app/src/test/java/org/simple/clinic/patient/onlinelookup/RetentionMoshiAdapterTest.kt
https://app.clubhouse.io/simpledotorg/story/3807/add-support-for-online-patient-lookup-api
=> Add the network models for the patient identifier lookup API

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/patients/PatientsEffectHandler.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt, app/src/main/java/org/simple/clinic/introvideoscreen/IntroVideoScreen.kt, app/src/main/java/org/simple/clinic/newentry/PatientEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/patient/Languages.kt, app/src/main/java/org/simple/clinic/patient/SimpleVideo.kt, app/src/main/java/org/simple/clinic/patient/SimpleVideoModule.kt
https://app.clubhouse.io/simpledotorg/story/3194/change-training-videos-depending-on-country-language
=> Add training videos depending on language

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItem.kt, app/src/main/res/layout/list_item_overdue_patient.xml
- Extract patient gender icon to separate view from name text view
- Fix village, risk and overdue text view indentation
=> Fix overdue list item UI indentation

CHANGELOG.md, app/src/main/java/org/simple/clinic/patient/onlinelookup/api/RecordRetention.kt, app/src/test/java/org/simple/clinic/patient/onlinelookup/api/RecordRetentionTest.kt
https://app.clubhouse.io/simpledotorg/story/3807/add-support-for-online-patient-lookup-api
=> Add support for computing a retain until timestamp from the record retention period

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItem.kt
- Add extension to increase tappable area of a view
- Increase tappable area of the overdue call button
=> Increase tappable area of overdue call button

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/91.json, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration91AndroidTest.kt, app/src/debug/java/org/simple/clinic/FakeDataGenerationReceiver.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_91.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://app.clubhouse.io/simpledotorg/story/3836/add-room-migration-for-retain-until
=> Add `retainUntil` column to `PatientTable`

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/patient/CompleteMedicalRecord.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://app.clubhouse.io/simpledotorg/story/3948/create-use-case-to-query-the-online-lookup-api-and-save-the-patient-profile
=> Add method to save the complete medical record for a single patient

CHANGELOG.md, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEvent.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchModel.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchProgressState.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUi.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUiRenderer.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUiRendererTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/3832/use-single-list-adapter-in-instantsearchscreen
=> Use single list adapter in `InstantSearchScreen`

.github/workflows/auto_request_review.yml, .github/workflows/ci_check_pr_comment.yml, .github/workflows/ci_checks.yml, .github/workflows/code_formatting_checks.yml, CHANGELOG.md
- Replace `GITHUB_ACCESS_TOKEN` usage with `SERVICES_ACCESS_TOKEN`
=> Replace GITHUB_ACCESS_TOKEN usage with SERVICES_ACCESS_TOKEN

CHANGELOG.md, app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt, app/src/main/java/org/simple/clinic/patient/onlinelookup/api/RecordRetention.kt, app/src/main/java/org/simple/clinic/patient/onlinelookup/api/RetentionType.kt, app/src/main/java/org/simple/clinic/patient/sync/ForPatientSync.kt, app/src/main/java/org/simple/clinic/patient/sync/PatientSyncModule.kt, app/src/test/java/org/simple/clinic/patient/onlinelookup/api/RecordRetentionTest.kt
https://app.clubhouse.io/simpledotorg/story/3927/add-a-fallback-behaviour-if-the-retention-type-enum-is-not-known-to-the-app
=> Add fallback behaviour for unknown record retention

CHANGELOG.md, app/build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt
- Bump Sentry gradle plugin to v2.0.1
=> Bump Sentry Gradle plugin version

CHANGELOG.md, app/build.gradle.kts, gradle.properties
- Add `mixpanelToken` to `gradle.properties`
- Add `manifestEndpoint` in `gradle.properties`
- Add `fallbackApiEndpoint` in `gradle.properties`
- Remove unused code
=> Clean up `gradle.properties`

app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/patient/onlinelookup/api/LookupPatientOnlineApiIntegrationTest.kt, app/src/main/java/org/simple/clinic/patient/CompleteMedicalRecord.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/patient/onlinelookup/api/CompleteMedicalRecordPayload.kt, app/src/main/java/org/simple/clinic/patient/onlinelookup/api/LookupPatientOnline.kt, app/src/main/java/org/simple/clinic/patient/onlinelookup/api/OnlineLookupResponsePayload.kt, app/src/main/java/org/simple/clinic/patient/sync/PatientSyncApi.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt, app/src/test/java/org/simple/clinic/patient/onlinelookup/api/LookupPatientOnlineTest.kt
https://app.clubhouse.io/simpledotorg/story/3948/create-use-case-to-query-the-online-lookup-api-and-fetch-the-medical-record
=> Add `OnlineLookupClass` to abstract the network calls for online lookup

CHANGELOG.md, buildSrc/src/main/kotlin/Versions.kt
**Changelog**: https://github.com/material-components/material-components-android/compare/1.3.0...1.4.0
=> Bump Material Design Components to v1.4.0

CHANGELOG.md, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandler.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandlerTest.kt
https://app.clubhouse.io/simpledotorg/story/4041/fix-indian-nhid-scan-showing-invalid-qr-code
=> Fix Indian NHID scan showing invalid QR code

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/92.json, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration92AndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/drugs/Answer.kt, app/src/main/java/org/simple/clinic/drugs/Drug.kt, app/src/main/java/org/simple/clinic/drugs/DrugCategory.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_92.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
- Add `Drug` Room table
- Add migration for adding `Drug`s table
**Story:** https://app.clubhouse.io/simpledotorg/story/2892/add-drug-database-model
=> Add `Drug` database model

CHANGELOG.md, app/src/main/java/org/simple/clinic/settings/SettingsModule.kt
- Add Sri Lankan Tamil language option
- Add Sinhala language option
=> Add Sri Lanka languages (Sinhala & Tamil) in language selection

CHANGELOG.md, app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreen.kt, app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenInjector.kt, app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt, app/src/main/java/org/simple/clinic/summary/bloodsugar/view/BloodSugarSummaryView.kt, app/src/main/res/layout/screen_blood_sugar_history.xml
https://app.clubhouse.io/simpledotorg/story/4051/migrate-bloodsugarhistoryscreen-to-a-fragment
=> Migrate `BloodSugarHistoryScreen` to a fragment

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/storage/PurgeDatabaseAndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt, app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt
https://app.clubhouse.io/simpledotorg/story/3804/delete-patient-data-if-it-does-not-comply-to-the-regular-sync-rules
=> Delete patients when the retention time has passed

CHANGELOG.md, app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt, app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarRepository.kt, app/src/main/java/org/simple/clinic/bloodsugar/sync/BloodSugarSync.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt, app/src/main/java/org/simple/clinic/bp/sync/BloodPressureSync.kt, app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt, app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt, app/src/main/java/org/simple/clinic/drugs/sync/PrescriptionSync.kt, app/src/main/java/org/simple/clinic/facility/FacilityRepository.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt, app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistorySync.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentSync.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/patient/sync/PatientSync.kt, app/src/main/java/org/simple/clinic/protocol/ProtocolRepository.kt, app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultationFacilityRepository.kt, app/src/main/java/org/simple/clinic/sync/SyncCoordinator.kt, app/src/main/java/org/simple/clinic/sync/SynceableRepository.kt, app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecord.kt, app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordRepository.kt, app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordSync.kt, app/src/test/java/org/simple/clinic/sync/SyncCoordinatorTest.kt
https://app.clubhouse.io/simpledotorg/story/4085/support-batching-of-sync-push-requests
=> Support batching sync push requests

app/src/androidTest/java/org/simple/clinic/storage/PurgeDatabaseAndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt, app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityEffectHandler.kt, app/src/test/java/org/simple/clinic/setup/SetupActivityEffectHandlerTest.kt
Refer : https://github.com/simpledotorg/simple-android/pull/2797#discussion_r667745078
Refer : https://github.com/simpledotorg/simple-android/pull/2797#issuecomment-878143897
=> Update `Instant` to be passed from prune()

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/drugs/search/DrugRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/drugs/search/sync/DrugSyncIntegrationTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt, app/src/main/java/org/simple/clinic/drugs/search/Answer.kt, app/src/main/java/org/simple/clinic/drugs/search/Drug.kt, app/src/main/java/org/simple/clinic/drugs/search/DrugCategory.kt, app/src/main/java/org/simple/clinic/drugs/search/DrugModule.kt, app/src/main/java/org/simple/clinic/drugs/search/DrugRepository.kt, app/src/main/java/org/simple/clinic/drugs/search/sync/DrugPayload.kt, app/src/main/java/org/simple/clinic/drugs/search/sync/DrugPullResponse.kt, app/src/main/java/org/simple/clinic/drugs/search/sync/DrugSync.kt, app/src/main/java/org/simple/clinic/drugs/search/sync/DrugSyncApi.kt, app/src/main/java/org/simple/clinic/main/TypedPreference.kt, app/src/main/java/org/simple/clinic/sync/SyncConfigModule.kt, app/src/main/java/org/simple/clinic/sync/SyncConfigType.kt, app/src/main/java/org/simple/clinic/sync/SyncModule.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://app.clubhouse.io/simpledotorg/story/2895/implement-drug-sync
=> Implement `Drug` sync

CHANGELOG.md, app/src/main/java/org/simple/clinic/protocol/ProtocolRepository.kt
- Add rx norm codes to default protocols
**Story:** https://app.clubhouse.io/simpledotorg/story/2925/add-rxnorm-code-for-hardcoded-protocol-drugs-list
=> Update default protocol drugs

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestSyncConfigModule.kt, app/src/androidTest/java/org/simple/clinic/drugs/search/sync/DrugSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/AppointmentSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/BloodPressureSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/BloodSugarSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/MedicalHistorySyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/PatientSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/PrescriptionSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/ProtocolSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/TeleconsultationSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordSyncIntegrationTest.kt, app/src/main/java/org/simple/clinic/bloodsugar/sync/BloodSugarSync.kt, app/src/main/java/org/simple/clinic/bp/sync/BloodPressureSync.kt, app/src/main/java/org/simple/clinic/drugs/search/sync/DrugSync.kt, app/src/main/java/org/simple/clinic/drugs/sync/PrescriptionSync.kt, app/src/main/java/org/simple/clinic/facility/FacilitySync.kt, app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistorySync.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentSync.kt, app/src/main/java/org/simple/clinic/patient/sync/PatientSync.kt, app/src/main/java/org/simple/clinic/protocol/sync/ProtocolSync.kt, app/src/main/java/org/simple/clinic/remoteconfig/RemoteConfigSync.kt, app/src/main/java/org/simple/clinic/sync/SyncConfig.kt, app/src/main/java/org/simple/clinic/sync/SyncConfigModule.kt, app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordSync.kt, app/src/test/java/org/simple/clinic/sync/DataSyncTest.kt
https://app.clubhouse.io/simpledotorg/story/4130/separate-batch-sizes-for-sync-uploads-and-downloads
=> Separate push and pull batch sizes when syncing resources

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestSyncConfigModule.kt, app/src/main/java/org/simple/clinic/bloodsugar/sync/BloodSugarSync.kt, app/src/main/java/org/simple/clinic/bp/sync/BloodPressureSync.kt, app/src/main/java/org/simple/clinic/drugs/sync/PrescriptionSync.kt, app/src/main/java/org/simple/clinic/facility/FacilitySync.kt, app/src/main/java/org/simple/clinic/help/HelpSync.kt, app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistorySync.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentSync.kt, app/src/main/java/org/simple/clinic/patient/sync/PatientSync.kt, app/src/main/java/org/simple/clinic/protocol/sync/ProtocolSync.kt, app/src/main/java/org/simple/clinic/reports/ReportsSync.kt, app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultationSync.kt, app/src/main/java/org/simple/clinic/sync/SyncConfigModule.kt, app/src/main/java/org/simple/clinic/sync/SyncConfigType.kt, app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordSync.kt
- Add `Daily` & `Frequent` sync config types
- Replace `@Named("sync_config_frequent")` with `@SyncConfigType(Frequent)`
- Replace `@Named("sync_config_daily")` with `@SyncConfigType(Daily)`
**Story:** https://app.clubhouse.io/simpledotorg/story/4146/use-syncconfigtype-qualifier-for-daily-and-frequent-sync-configs
=> Use `SyncConfigType` qualifier for daily and frequent sync configs

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientModel.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUi.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiRenderer.kt, app/src/main/java/org/simple/clinic/contactpatient/views/CallPatientView.kt, app/src/main/res/layout/contactpatient_callpatient.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/contactpatient/CallPatientUiRendererTest.kt
https://app.clubhouse.io/simpledotorg/story/3714/update-contactpatientbottomsheet-behaviour
Merge after #2810
=> Update `ContactPatientBottomSheet` Behaviour to use the new `CallPatientView` 

CHANGELOG.md, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffect.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandler.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEvent.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdScreenLogicTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/3794/load-online-lookup-api-if-patient-not-found-locally
=> Load online lookup API if patient not found locally #1

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestSyncConfigModule.kt, app/src/main/java/org/simple/clinic/facility/FacilitySync.kt, app/src/main/java/org/simple/clinic/help/HelpSync.kt, app/src/main/java/org/simple/clinic/protocol/sync/ProtocolSync.kt, app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultationSync.kt, app/src/main/java/org/simple/clinic/sync/SyncConfigModule.kt
https://app.clubhouse.io/simpledotorg/story/4148/remove-separation-between-daily-and-frequent-syncs
=> Move all daily syncs to the frequent syncs group

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestSyncConfigModule.kt, app/src/androidTest/java/org/simple/clinic/drugs/search/sync/DrugSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/AppointmentSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/BloodPressureSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/BloodSugarSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/MedicalHistorySyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/PatientSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/PrescriptionSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/ProtocolSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/TeleconsultationSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordSyncIntegrationTest.kt, app/src/main/java/org/simple/clinic/sync/SyncConfigModule.kt, app/src/main/java/org/simple/clinic/sync/SyncInterval.kt, app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorUpdate.kt, app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorView.kt, app/src/test/java/org/simple/clinic/sync/DataSyncTest.kt, app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/4148/remove-separation-between-daily-and-frequent-syncs
=> Change `SyncInterval` to a data class

.github/workflows/ci_checks.yml, CHANGELOG.md
- Timeout instrumented tests after 30 minutes
=> Timeout instrumented tests after 30 minutes

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/HomeScreen.kt, app/src/main/java/org/simple/clinic/home/HomeScreenTabPagerAdapter.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
https://app.clubhouse.io/simpledotorg/story/4181/fix-memory-leaks-in-homescreen
=> Fix memory leaks in `HomeScreen`

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffect.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandler.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEvent.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/3794/load-online-lookup-api-if-patient-not-found-locally
=> Load online lookup API if patient not found locally #2

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/93.json, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration93AndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffect.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEvent.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientInit.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientModel.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUi.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiRenderer.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUpdate.kt, app/src/main/java/org/simple/clinic/contactpatient/views/CallPatientView.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_93.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt, app/src/main/res/values/strings.xml, app/src/sharedTest/java/org/simple/clinic/TestData.kt, app/src/test/java/org/simple/clinic/contactpatient/CallPatientUiRendererTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientInitTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4185/implement-transferred-to-and-registered-at-patient-facility-in-contactpatientbottomsheet
=> Implement `transferred to` and `registered at` patient facility in `ContactPatientBottomSheet`

CHANGELOG.md, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientProfile.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
https://app.clubhouse.io/simpledotorg/story/4195/use-room-s-relation-annotation-for-patientprofile
=> Use the `Room` @Relation` annotation for representing `PatientProfile`

CHANGELOG.md, build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt
- Add Gradle versions plugin
- Reject any non stable dependency updates in dependency update task
- Configure output format of dependency updates report
=> Add gradle-versions-plugin for checking dependency updates

CHANGELOG.md, buildSrc/src/main/kotlin/Versions.kt
=> Bump AndroidX Core Testing to v2.1.0

CHANGELOG.md, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandler.kt, app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/sync/DataSync.kt, app/src/main/java/org/simple/clinic/sync/SyncGroup.kt, app/src/main/java/org/simple/clinic/sync/SyncWorker.kt, app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorEffectHandler.kt, app/src/main/java/org/simple/clinic/sync/indicator/SyncIndicatorStatusCalculator.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/settings/changelanguage/ChangeLanguageEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/sync/DataSyncTest.kt, app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorLogicTest.kt, app/src/test/java/org/simple/clinic/sync/indicator/SyncIndicatorStatusCalculatorTest.kt
https://app.clubhouse.io/simpledotorg/story/4148/remove-separation-between-daily-and-frequent-syncs
=> Remove the `DAILY` enum value from `SyncGroup`

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt
- Use full date formatter in contact patient sheet
=> Use full date formatter when rendering last visited date in contact patient sheet

CHANGELOG.md, app/src/main/res/layout/contactpatient_callpatient.xml, app/src/main/res/layout/list_item_overdue_patient.xml
- Change village label color to `color_on_surface_67`
- Adjust margin between result label and results items
=> Fix UI inconsistencies in overdue list and contact patient sheet

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdScreenLogicTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4213/add-feature-flag-for-online-patient-lookup
=> Add online patient lookup behind a feature flag

.github/workflows/ci_checks.yml, CHANGELOG.md
https://app.clubhouse.io/simpledotorg/story/4223/cache-maven-dependencies-and-build-intermediates-for-android-instrumented-tests
=> Cache dependencies in CI

CHANGELOG.md, app/src/main/res/layout/screen_patients.xml, app/src/main/res/values/styles.xml
- Add big button styles for `Button` and `OutlinedButton`
- Set big button style for search patients button in patients screen
- Set big button style for scan id button in patients screen
=> Increase the search and scan button height in patients screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt, app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeSheet.kt, app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeSheet.kt, app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseBottomSheet.kt, app/src/main/java/org/simple/clinic/scanid/scannedqrcode/ScannedQrCodeSheet.kt, app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt, app/src/main/java/org/simple/clinic/summary/linkId/LinkIdWithPatientSheet.kt, app/src/main/java/org/simple/clinic/textInputdatepicker/TextInputDatePickerSheet.kt
https://app.clubhouse.io/simpledotorg/story/4074/use-mobiusloopviewmodel-for-sending-view-effects-that-are-lifecycle-aware
=> Add `MobiusLoopViewModel` to `BaseBottomSheet`

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/search/sync/DrugSync.kt, app/src/main/java/org/simple/clinic/sync/SyncConfigModule.kt, app/src/main/java/org/simple/clinic/sync/SyncConfigType.kt, app/src/main/java/org/simple/clinic/sync/SyncScheduler.kt, app/src/main/java/org/simple/clinic/sync/SyncWorker.kt
https://app.clubhouse.io/simpledotorg/story/4148/remove-separation-between-daily-and-frequent-syncs
=> Unify sync jobs in `SyncScheduler`

CHANGELOG.md, buildSrc/src/main/kotlin/Versions.kt
=> Bump Logback to v1.2.4

CHANGELOG.md, buildSrc/src/main/kotlin/Versions.kt
=> Bump Core KTX to v1.6.0

CHANGELOG.md, buildSrc/src/main/kotlin/Versions.kt
- Bump AndroidX test to v1.4.0
- Bump AndroidX test extension to v1.1.3
=> Bump AndroidX Test dependencies

CHANGELOG.md, buildSrc/src/main/kotlin/Versions.kt
- Bump RxPreferences to v2.0.1
=> Bump Rx preferences to v2.0.1

CHANGELOG.md, buildSrc/src/main/kotlin/Versions.kt
=> Bump Lottie to v3.7.2

CHANGELOG.md, buildSrc/src/main/kotlin/Versions.kt
=> Bump Lint to v27.2.2

CHANGELOG.md, app/src/debug/java/org/simple/clinic/di/network/HttpInterceptorsModule.kt, app/src/main/java/org/simple/clinic/di/network/CompressRequestInterceptor.kt, app/src/main/java/org/simple/clinic/di/network/RequestCompression.kt, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/release/java/org/simple/clinic/di/network/HttpInterceptorsModule.kt, app/src/test/java/org/simple/clinic/di/network/RequestCompressionTest.kt
https://app.clubhouse.io/simpledotorg/story/4078/support-gzip-for-http-request-bodies
=> Support GZIP compression for HTTP request bodies

CHANGELOG.md, app/src/main/java/org/simple/clinic/ClinicApp.kt, app/src/main/java/org/simple/clinic/navigation/v2/History.kt, app/src/main/java/org/simple/clinic/navigation/v2/Router.kt, app/src/main/java/org/simple/clinic/navigation/v2/ScreenKey.kt
https://app.clubhouse.io/simpledotorg/story/4308/fix-navigation-issues-in-router
=> Fix navigation issues in `Router`

CHANGELOG.md, buildSrc/src/main/kotlin/Versions.kt
=> Bump Jackson to v2.12.4

CHANGELOG.md, app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageScreen.kt
https://app.clubhouse.io/simpledotorg/story/4286/restart-theactivity-after-changing-language
=> Restart `TheActivity` after changing language

CHANGELOG.md, buildSrc/src/main/kotlin/Versions.kt
- Bump Play Services Location to v18.0.0
=> Bump Play Services Location to v18.0.0

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffect.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEvent.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientInit.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientModel.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientProfile.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiRenderer.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUpdate.kt, app/src/main/java/org/simple/clinic/contactpatient/PatientDetails.kt, app/src/main/java/org/simple/clinic/contactpatient/views/CallPatientView.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt, app/src/test/java/org/simple/clinic/contactpatient/CallPatientUiRendererTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientInitTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4298/support-contact-patient-sheet-with-no-appointment
=> Add support for `ContactPatientSheet` without appointment #1

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://app.clubhouse.io/simpledotorg/story/4388/fix-duplicate-patients-in-search-results
=> Fix showing duplicate patients in search results

CHANGELOG.md, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEvent.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchInit.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchUpdate.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchInitTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4401/show-keyboard-and-prefill-search-query-when-instant-search-screen-is-shown
=> Show keyboard and prefill search query when instant search screen is shown

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientInit.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientModel.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUi.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiRenderer.kt, app/src/main/java/org/simple/clinic/contactpatient/views/CallPatientView.kt, app/src/main/res/layout/contactpatient_callpatient.xml, app/src/main/res/layout/sheet_contact_patient.xml, app/src/test/java/org/simple/clinic/contactpatient/CallPatientUiRendererTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientInitTest.kt
https://app.clubhouse.io/simpledotorg/story/4298/support-contact-patient-sheet-with-no-appointment
=> Support contact patient sheet with no appointment- #2

app/src/main/java/org/simple/clinic/appconfig/Country.kt, app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt, app/src/main/java/org/simple/clinic/patient/businessid/Identifier.kt, app/src/main/java/org/simple/clinic/widgets/PatientSearchResultItemView.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/patient/IdentifierDisplayTest.kt
- Add Sri Lanka identifier type
- Add Sri Lanka national ID meta data version in `BusinessId`
=> Add Sri Lanka national id business identifier

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt
https://app.clubhouse.io/simpledotorg/story/4296/change-feature-flag-key-for-overdue-list-ui-changes-when-releasing
=> Update OverdueListChanges feature flag to support `ContactPatientSheet` changes

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientProfile.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiRenderer.kt, app/src/main/java/org/simple/clinic/contactpatient/PatientDetails.kt, app/src/main/java/org/simple/clinic/contactpatient/views/CallPatientView.kt, app/src/test/java/org/simple/clinic/contactpatient/CallPatientUiRendererTest.kt
- Make registered facility nullable in `ContactPatientProfile`
- Hide registered facility text view, when registered facility is not present
=> Change registered facility as nullable in `ContactPatientProfile`

CHANGELOG.md, app/src/main/java/org/simple/clinic/appconfig/Country.kt
- Change Sri Lanka iso country code to `LK`
=> Change Sri Lanka iso country code to `LK`

CHANGELOG.md, gradle/libs.versions.toml
=> Bump asm to v9.2

CHANGELOG.md, app/src/main/res/values-sid-rET/strings.xml
https://app.clubhouse.io/simpledotorg/story/4450/update-sidama-translations
=> Update sidama translations

CHANGELOG.md, app/src/main/java/org/simple/clinic/appconfig/displayname/PlatformCountryDisplayNameFetcher.kt, app/src/main/res/values/strings.xml
=> Set Sri Lanka display name in country selection screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/patient/DateOfBirth.kt, app/src/test/java/org/simple/clinic/patient/DateOfBirthTest.kt
https://app.clubhouse.io/simpledotorg/story/4426/change-dateofbirth-to-an-embedded-room-model
=> Add the patient age and date of birth properties to the `DateOfBirth` model

CHANGELOG.md, gradle/libs.versions.toml
- Bump threeten-extra to v1.7.0
=> Bump threeten-extra to v1.7.0

CHANGELOG.md, gradle/libs.versions.toml
=> Bump AppCompat to v1.3.1

CHANGELOG.md, gradle/libs.versions.toml
=> Bump RecyclerView to v1.2.1

CHANGELOG.md, app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseBottomSheet.kt, app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseDialog.kt, app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseScreen.kt
- Check if `viewModel` is initialised when saving state in `BaseScreen`
- Check if `viewModel` is initialised when saving state in `BaseBottomSheet`
- Check if `viewModel` is initialised when saving state in `BaseDialog`
Should resolve this issue: https://simpledotorg.slack.com/archives/C01Q7S69AGL/p1628561816007800
=> Check if ViewModel is initialised when saving state in base screens

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffect.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEvent.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryInit.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryModel.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheetUiActions.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUi.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUiRenderer.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdate.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/OpenAs.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryInitTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUiRendererTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2905/implement-customdrugentrysheet
=> Implement mobius loop logic of `CustomDrugEntrySheet` - 1

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientModel.kt, app/src/main/java/org/simple/clinic/editpatient/EditablePatientEntry.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientAgeDetails.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditablePatientEntryTest.kt
https://app.clubhouse.io/simpledotorg/story/4484/remove-the-age-class
=> Replace usages of `Age` in `EditPatientEffectHandler` with `PatientAgeDetails`

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt, app/src/main/java/org/simple/clinic/drugs/search/DrugFrequency.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffect.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEvent.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryInit.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryModel.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheetUiActions.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdate.kt, app/src/main/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/teleconsultlog/medicinefrequency/MedicineFrequency.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryInitTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdateTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/entry/CustomPrescriptionEntryLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/2905/implement-customdrugentrysheet
Mobius loop logic for doing the following things from `CustomDrugEntrySheet`- 
1. Adding a new custom prescription to the repository
2. Updating an existing custom prescription in the repository 
3. Closing the bottom sheet
4. Fetching prescription from prescription id and setting up the ui accordingly 
4. Removing an existing custom prescription from the repository
=> Implement mobius loop logic of `CustomDrugEntrySheet` - 2

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4387/nudge-users-to-add-bp-or-blood-sugar-after-creating-patient
=> Nudge users to add BP or Blood Sugar after creating patient - 1

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4387/nudge-users-to-add-bp-or-blood-sugar-after-creating-patient
=> Nudge users to add BP or Blood Sugar after creating patient - final

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/94.json, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration94AndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_94.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt, app/src/main/res/layout/sheet_custom_prescription_entry.xml
https://app.clubhouse.io/simpledotorg/story/4527/disable-save-button-when-creating-new-custom-drug-and-drug-name-is-not-present
=> Fix app syncing prescription drugs with empty name

CHANGELOG.md, app/src/main/res/layout/simple_video_layout.xml, app/src/main/res/values/dimens.xml
https://app.clubhouse.io/simpledotorg/story/4546/fix-text-overflowing-in-video-illustration-in-some-languages
=> Fix text overflowing in video illustration in some languages

CHANGELOG.md, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffect.kt, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneEffectHandler.kt, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUi.kt, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUpdate.kt, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneViewEffectHandler.kt, app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/4570/change-registrationphonescreen-to-use-view-effects
=> Change `RegistrationPhoneScreen` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffect.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandler.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdViewEffectHandler.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdScreenLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/4559/change-scansimpleidscreen-to-use-view-effects
=> Change `ScanSimpleIdScreen` to use Mobius view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt
https://app.clubhouse.io/simpledotorg/story/4553/remove-reporting-scanning-logs-to-sentry
=> Remove reporting scanned logs to Sentry

CHANGELOG.md, app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeEffectHandler.kt, app/src/main/java/org/simple/clinic/reports/ReportsSync.kt
https://app.clubhouse.io/simpledotorg/story/4604/handle-exception-when-syncing-reports-in-confirmfacilitychangeeffecthandler
=> Handle exception when syncing reports in `ConfirmFacilityChangeEffectHandler`

.github/scripts/compute_node_dependency_hash.sh, .github/scripts/generate_heroku_app_name.sh, .github/scripts/server_heroku_env_setup.py, .github/scripts/setup_heroku_instance.sh, .github/scripts/teardown_heroku_instances.py, .github/workflows/ci_checks.yml, .github/workflows/cleanup_heroku_review_apps.yml, CHANGELOG.md, README.md, doc/integration-test-suite-setup.md
https://app.clubhouse.io/simpledotorg/story/4518/set-up-isolated-server-instances-at-a-pr-level-for-the-android-integration-tests
Note: There's a commit titled "Update documentation for instrumented test setup" which contains some documentation about the Heroku server configuration which might be useful to read first.
=> Setup isolated server instances on Heroku for CI instrumented tests

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/patients/PatientsEffectHandler.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEffect.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabViewEffectHandler.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/4653/change-patientstabscreen-to-use-mobius-view-effects
=> Change `PatientsTabScreen` to use Mobius view effects

CHANGELOG.md, app/src/main/res/values/shape.xml
This sets the corner radius of bottom sheets to 8dp
=> Change large component corner shape to 8dp

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/95.json, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration95AndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResult.kt, app/src/main/java/org/simple/clinic/overdue/callresult/Outcome.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_95.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
https://app.clubhouse.io/simpledotorg/story/4688/add-the-callresult-database-table
=> Add `CallResult` table to the app database

CHANGELOG.md, app/src/main/res/layout/screen_instant_search.xml
https://app.clubhouse.io/simpledotorg/story/4707/update-margin-for-no-patient-in-facility-text-view-in-instant-search-screen
=> Update margin for no patients in facility text view in instant search screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreen.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt, app/src/main/res/layout/screen_enterotp.xml
https://app.clubhouse.io/simpledotorg/story/4671/migrate-enterotpscreen-to-a-fragment
=> Migrate `EnterOtpScreen` to a Fragment

CHANGELOG.md, app/src/main/java/org/simple/clinic/overdue/callresult/CallResultPayload.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResultPushRequest.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResultSyncApi.kt
https://app.clubhouse.io/simpledotorg/story/4667/add-support-for-the-callresult-sync-resource-in-the-android-app
=> Add `CallResult` sync API contracts

CHANGELOG.md, app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffect.kt, app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffectHandler.kt, app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt, app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentViewEffectHandler.kt, app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/4737/change-scheduleappointmentsheet-to-use-mobius-view-effects
=> Change `ScheduleAppointmentSheet` to use Mobius view effects

CHANGELOG.md, doc/testing-delivered-stories-on-pivotal.md
https://app.clubhouse.io/simpledotorg/story/4633/update-the-pivotal-adr-to-include-clubhouse
=> Add Clubhouse overview in the Pivotal documentation

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffect.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryInit.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryModel.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheet.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheetUiActions.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUi.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUiRenderer.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdate.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/drugfrequency/SelectDrugFrequencyDialog.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/drugfrequency/country/DrugFrequencyChoiceItem.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryInitTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUiRendererTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/2915/implement-drugfrequencyfactory-drugfrequencyprovider-for-providing-drug-frequencies-label-depending-on-the-country
=> Implement providing drug frequencies label depending on the country - Final

CHANGELOG.md, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffect.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandler.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryViewEffectHandler.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/4754/change-newmedicalhistoryscreen-to-use-mobius-view-effects
=> Change `NewMedicalHistoryScreen` to use Mobius view effects

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/sync/CallResultSyncIntegrationTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResult.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResultRepository.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResultSync.kt, app/src/main/java/org/simple/clinic/overdue/callresult/di/CallResultModule.kt, app/src/main/java/org/simple/clinic/sync/SyncModule.kt, app/src/sharedTest/java/org/simple/clinic/util/TestFunctions.kt
https://app.clubhouse.io/simpledotorg/story/4667/add-support-for-the-callresult-sync-resource-in-the-android-app
The tests are currently disabled because the server side code is not merged in yet. Will raise another PR enabling them once it's available.
=> Implement the `CallResultSync` layer 

CHANGELOG.md, app/src/main/java/org/simple/clinic/appconfig/AppConfigRepository.kt, app/src/main/java/org/simple/clinic/appconfig/State.kt, app/src/main/java/org/simple/clinic/appconfig/StatesFetcher.kt, app/src/main/java/org/simple/clinic/appconfig/StatesResult.kt, app/src/main/java/org/simple/clinic/appconfig/api/StatesApi.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt, app/src/test/java/org/simple/clinic/appconfig/AppConfigRepositoryTest.kt
https://app.clubhouse.io/simpledotorg/story/4035/allow-state-selection-during-app-onboarding?vc_group_by=day&ct_workflow=all&cf_workflow=500000005
=> Fetch states for selected country deployments

CHANGELOG.md, app/build.gradle.kts, app/src/main/java/org/simple/clinic/storage/SharedPreferencesModule.kt, gradle/libs.versions.toml
https://app.clubhouse.io/simpledotorg/story/4869/replace-deprecated-platform-preferencemanager-usage-with-androidx-preference
=> Replace deprecated platform `PreferenceManager` usage with AndroidX preference

CHANGELOG.md, gradle/libs.versions.toml
**Release notes**: https://github.com/google/dagger/releases
=> Bump Dagger to v2.38.1

CHANGELOG.md, app/src/main/java/org/simple/clinic/appconfig/AppConfigModule.kt, app/src/main/java/org/simple/clinic/appconfig/AppConfigRepository.kt, app/src/main/java/org/simple/clinic/appconfig/State.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateEffect.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateEffectHandler.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateEvent.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateInit.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateModel.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateUpdate.kt, app/src/main/java/org/simple/clinic/selectstate/StatesFetchError.kt, app/src/test/java/org/simple/clinic/appconfig/AppConfigRepositoryTest.kt, app/src/test/java/org/simple/clinic/selectstate/SelectStateEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/selectstate/SelectStateInitTest.kt, app/src/test/java/org/simple/clinic/selectstate/SelectStateUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4035/allow-state-selection-during-app-onboarding
=> Implement Mobius loop for state selection screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryInit.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryModel.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryProgressState.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/DrugInfoProgressState.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryInitTest.kt
https://app.clubhouse.io/simpledotorg/story/4783/add-a-progress-state-in-customdrugentrysheet-as-it-s-loading-slowly
=> Mobius loop implementations to add a progress state in `CustomDrugEntrySheet` - 1

CHANGELOG.md, app/src/main/java/org/simple/clinic/selectstate/SelectStateEffect.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateEffectHandler.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateEvent.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateModel.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateUi.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateUiActions.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateUiRenderer.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateUpdate.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateViewEffectHandler.kt, app/src/test/java/org/simple/clinic/selectstate/SelectStateEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/selectstate/SelectStateUiRendererTest.kt, app/src/test/java/org/simple/clinic/selectstate/SelectStateUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4035/allow-state-selection-during-app-onboarding
I forgot to add this when creating the Mobius loop 😅 , next PR will wire up the Mobius loop with UI
=> Implement Mobius loop for state selection screen - 2

CHANGELOG.md, gradle/libs.versions.toml
**Release updates**: https://androidstudio.googleblog.com/2021/09/android-studio-arctic-fox-202031-patch.html
=> Bump AGP to v7.0.2

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffect.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryModel.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheet.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheetUiActions.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUi.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUiRenderer.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdate.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/drugfrequency/SelectDrugFrequencyDialog.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/drugfrequency/country/CommonDrugFrequencyProvider.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/drugfrequency/country/DrugFrequencyChoiceItem.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/drugfrequency/country/DrugFrequencyFactory.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/drugfrequency/country/DrugFrequencyProvider.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/drugfrequency/country/EthiopiaDrugFrequencyProvider.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUiRendererTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4813/refactor-logic-around-providing-drug-frequencies-label-depending-on-the-country
=> Refactor logic around providing drug frequencies label depending on the country - Final

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/EditPatientEffect.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientViewEffectHandler.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenCreatedTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenFormTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenSaveTest.kt
https://app.clubhouse.io/simpledotorg/story/4792/change-editpatientscreen-to-use-mobius-view-effects
=> Change `EditPatientScreen` to use Mobius view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/appconfig/AppConfigRepository.kt, app/src/main/java/org/simple/clinic/facilitypicker/FacilityPickerEffectHandler.kt, app/src/test/java/org/simple/clinic/facilitypicker/FacilityPickerEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/facilitypicker/FacilityPickerLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/4884/show-facilities-from-selected-state-during-sign-up
=> Show facilities from selected state during sign up

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/sync/SyncModule.kt
https://app.clubhouse.io/simpledotorg/story/4667/add-support-for-the-callresult-sync-resource-in-the-android-app
=> Add `CallResultSync` to the list of syncs based on a local feature flag

CHANGELOG.md, app/src/main/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtection.kt, app/src/main/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtectionConfigModule.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpEffect.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpEffectHandler.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpEvent.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpInit.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpModel.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreen.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpUi.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpUiRenderer.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpUpdate.kt, app/src/main/java/org/simple/clinic/enterotp/OtpEntryMode.kt, app/src/main/res/layout/screen_enterotp.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtectionTest.kt, app/src/test/java/org/simple/clinic/enterotp/EnterOtpEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/enterotp/EnterOtpInitTest.kt, app/src/test/java/org/simple/clinic/enterotp/EnterOtpLogicTest.kt, app/src/test/java/org/simple/clinic/enterotp/EnterOtpUiRendererTest.kt, app/src/test/java/org/simple/clinic/enterotp/EnterOtpUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4514/limit-incorrect-otp-entries
=> Restricting OTP entries to 5 attempts #2

app/src/main/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtection.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpEffect.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpEffectHandler.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpUpdate.kt, app/src/test/java/org/simple/clinic/enterotp/EnterOtpEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/enterotp/EnterOtpUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4840/on-resend-and-success-delete-the-otp-entries-from-preference
=> Reset OTP attempts in preferences on success and resend of OTP

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryInit.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheet.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUi.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUiRenderer.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdate.kt, app/src/main/res/layout/sheet_custom_drug_entry.xml, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUiRendererTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4783/add-a-progress-state-in-customdrugentrysheet-as-it-s-loading-slowly
=> Wire up the mobius loop with the ui for adding progress state in `CustomDrugEntrySheet` - Final

CHANGELOG.md, app/src/main/res/layout/screen_select_state.xml, app/src/main/res/layout/screen_selectcountry.xml
https://app.shortcut.com/simpledotorg/story/4974
=> Fix select country & state screen overlapping next button

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/EditMedicinesEffect.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesEffectHandler.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesEvent.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesInit.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesModel.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesUiRenderer.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesUpdate.kt, app/src/main/java/org/simple/clinic/drugs/selection/DrugListItem.kt, app/src/main/res/layout/list_prescribeddrugs_custom_drug.xml, app/src/main/res/layout/list_prescribeddrugs_protocol_drug.xml, app/src/test/java/org/simple/clinic/drugs/EditMedicineEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/drugs/EditMedicineUpdateTest.kt, app/src/test/java/org/simple/clinic/drugs/EditMedicinesInitTest.kt, app/src/test/java/org/simple/clinic/drugs/EditMedicinesUiRendererTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/EditMedicinesScreenLogicTest.kt
https://app.clubhouse.io/simpledotorg/story/4782/implement-showing-drug-frequency-in-editmedicinescreen-based-on-the-country
=> Implement showing drug frequency in `EditMedicineScreen` based on the country

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/appconfig/AppConfigRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/di/TestRetrofitModule.kt
https://app.shortcut.com/simpledotorg/story/4885/add-instrumentation-tests-for-manifest-and-states-api
=> Add integration tests for `AppConfigRepository`

CHANGELOG.md, app/src/main/res/layout/screen_edit_patient.xml, app/src/main/res/layout/screen_manual_patient_entry.xml
https://app.clubhouse.io/simpledotorg/story/5015/show-alpha-numeric-keyboard-for-national-id-text-field-in-patient-entry-and-edit-screen
=> Show alpha numeric keyboard for national ID text field in patient entry and edit screen

.github/workflows/ci_checks.yml, CHANGELOG.md
https://app.shortcut.com/simpledotorg/story/5030/update-verify-pr-description-ci-validation-check-to-shortcut-links
=> Update `verify_pr_description` CI validation check to Shortcut links

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffect.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUpdate.kt, app/src/main/java/org/simple/clinic/contactpatient/CreateReminderForAppointment.kt, app/src/main/java/org/simple/clinic/contactpatient/RecordPatientAgreedToVisit.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/4669/record-a-callresult-whenever-a-call-is-made-in-contactpatientbottomsheet
=> Record call results when updating appointments in `ContactPatientBottomSheet`

CHANGELOG.md, app/src/main/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtectionConfig.kt, app/src/main/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtectionConfigModule.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpModel.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreen.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpUi.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpUiRenderer.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtectionTest.kt, app/src/test/java/org/simple/clinic/enterotp/EnterOtpInitTest.kt, app/src/test/java/org/simple/clinic/enterotp/EnterOtpLogicTest.kt, app/src/test/java/org/simple/clinic/enterotp/EnterOtpUiRendererTest.kt, app/src/test/java/org/simple/clinic/enterotp/EnterOtpUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/4975/remove-magic-numbers-from-enterotpscreen
=> Remove magic numbers from `EnterOtpScreen`

CHANGELOG.md, app/src/main/java/org/simple/clinic/di/AppModule.kt, app/src/main/java/org/simple/clinic/teleconsultlog/medicinefrequency/MedicineFrequencySheet.kt, app/src/main/java/org/simple/clinic/teleconsultlog/medicinefrequency/MedicineFrequencySheetExtra.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicineItem.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEffect.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEffectHandler.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEvent.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesInit.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesModel.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUi.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUiActions.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUiRenderer.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUpdate.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesView.kt, app/src/test/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesInitTest.kt, app/src/test/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUiRendererTest.kt, app/src/test/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUpdateTest.kt
https://app.clubhouse.io/simpledotorg/story/4759/implement-showing-medicine-frequency-labels-depending-on-the-country-in-medicinefrequencysheet-and-teleconsultmedicinesview
=> Implement showing medicine frequency labels depending on the country - Final

CHANGELOG.md, app/src/main/java/org/simple/clinic/appconfig/CountryModule.kt
https://app.shortcut.com/simpledotorg/story/5080/fix-arrayindexoutofbounds-exception-when-parsing-old-country-object
=> Use `Object` class for parsing old `Country` json

.github/scripts/PrCommentCheck.main.kts, .github/workflows/ci_checks.yml, CHANGELOG.md
https://app.shortcut.com/simpledotorg/story/5085/use-kotlin-script-for-pr-comment-check-gh-action
=> Use Kotlin script for PR comment check GH Action

CHANGELOG.md, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryDiagnosisWithTreatment.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryQuestion.kt, app/src/main/java/org/simple/clinic/medicalhistory/OngoingMedicalHistoryEntry.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryModel.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUi.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRenderer.kt, app/src/main/res/layout/screen_new_medical_history.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRendererTest.kt
https://app.clubhouse.io/simpledotorg/story/4986/add-diabetes-treatment-question-in-medical-history-screen
=> Add diabetes treatment question in medical history screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtection.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpModel.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpScreen.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpUi.kt, app/src/main/java/org/simple/clinic/enterotp/EnterOtpUpdate.kt, app/src/test/java/org/simple/clinic/enterotp/BruteForceOtpEntryProtectionTest.kt, app/src/test/java/org/simple/clinic/enterotp/EnterOtpLogicTest.kt, app/src/test/java/org/simple/clinic/enterotp/EnterOtpUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5038/hide-keyboard-when-otp-entries-are-blocked
=> Hide keyboard when OTP entries are blocked

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/search/DrugSearchListItem.kt, app/src/main/java/org/simple/clinic/drugs/search/DrugsSearchScreen.kt, app/src/test/java/org/simple/clinic/drugs/search/DrugSearchListItemTest.kt
https://app.shortcut.com/simpledotorg/story/5043/implement-providing-drug-frequencies-label-depending-on-the-country-in-drugsearchscreen
=> Implement providing drug frequencies label depending on the country in `DrugSearchScreen`

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/selection/custom/ButtonState.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryModel.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheet.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUi.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUiRenderer.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdate.kt, app/src/main/res/layout/sheet_custom_drug_entry.xml, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUiRendererTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5045/add-progress-state-when-the-drug-is-being-added-updated
=> Add progress state when the drug is being added/updated in `CustomDrugEntrySheet`

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientModel.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUi.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiRenderer.kt, app/src/main/java/org/simple/clinic/contactpatient/views/CallPatientView.kt, app/src/main/java/org/simple/clinic/widgets/PatientStatusView.kt, app/src/main/res/drawable/ic_patient_dead_24dp.xml, app/src/main/res/layout/contactpatient_callpatient.xml, app/src/main/res/values/attrs.xml, app/src/test/java/org/simple/clinic/contactpatient/CallPatientUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/5090/show-patient-died-status-in-contact-patient-bottom-sheet
=> Show patient died status in contact patient bottom sheet

CHANGELOG.md, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffect.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEvent.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryModel.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiActions.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdate.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryViewEffectHandler.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5087/show-change-diagnosis-dialog-when-patient-is-not-diagnosed-with-htn-or-diabetes-when-registering
=> Show change diagnosis dialog when patient is not diagnosed with HTN or diabetes when registering

CHANGELOG.md, app/src/main/java/org/simple/clinic/medicalhistory/SelectOngoingDiabetesTreatmentErrorDialog.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffect.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryModel.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiActions.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdate.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryViewEffectHandler.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5137/show-ongoing-diabetes-treatment-required-dialog-in-diagnosis-screen
=> Show ongoing diabetes treatment required dialog in diagnosis screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffect.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientModel.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiActions.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUpdate.kt, app/src/main/java/org/simple/clinic/removeoverdueappointment/CancelAppointmentWithReason.kt, app/src/main/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueAppointmentScreen.kt, app/src/main/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueEffect.kt, app/src/main/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueEffectHandler.kt, app/src/main/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueModel.kt, app/src/main/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueUpdate.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUpdateTest.kt, app/src/test/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueUiRendererTest.kt, app/src/test/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/4669/record-a-callresult-whenever-a-call-is-made-in-contactpatientbottomsheet
=> Record call results when removing an appointment from the overdue list

CHANGELOG.md, app/src/main/java/org/simple/clinic/appconfig/CountryModule.kt
https://app.shortcut.com/simpledotorg/story/5158/app-not-displaying-national-id-and-proper-illustration-in-sri-lanka
=> Fix `Country` v2 migration not running

CHANGELOG.md, app/src/main/res/layout/list_medical_history_question.xml
[source](https://simpledotorg.slack.com/archives/CFHKJ5WJY/p1632375591032900)
=> Fix multiple medical history answers selection in patient summary screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryEffect.kt, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryEffectHandler.kt, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryEvent.kt, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryModel.kt, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryScreen.kt, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryUpdate.kt, app/src/main/java/org/simple/clinic/selectcountry/UiActions.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateUpdate.kt, app/src/test/java/org/simple/clinic/selectcountry/SelectCountryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/selectcountry/SelectCountryUpdateTest.kt, app/src/test/java/org/simple/clinic/selectstate/SelectStateUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/4998/show-state-selection-screen-after-country-is-selected
=> Show state selection after country is selected

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/storage/PurgeDatabaseAndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResult.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt
https://app.shortcut.com/simpledotorg/story/4705/ensure-callresult-resource-clean-up
=> Purge unnecessary call result records

CHANGELOG.md, app/src/main/java/org/simple/clinic/selectstate/SelectStateEvent.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateScreen.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateUi.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateUiRenderer.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateUpdate.kt, app/src/main/res/layout/screen_select_state.xml, app/src/test/java/org/simple/clinic/selectstate/SelectStateUiRendererTest.kt, app/src/test/java/org/simple/clinic/selectstate/SelectStateUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5226/remove-next-button-from-state-selection-screen
=> Remove next button from state selection screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryEvent.kt, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryModel.kt, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryScreen.kt, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryUi.kt, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryUiRenderer.kt, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryUpdate.kt, app/src/main/res/layout/screen_selectcountry.xml, app/src/test/java/org/simple/clinic/selectcountry/SelectCountryUiRendererTest.kt, app/src/test/java/org/simple/clinic/selectcountry/SelectCountryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5227/remove-next-button-from-the-country-selection-screen
=> Remove next button from the country selection screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/registerorlogin/AuthenticationActivity.kt, app/src/main/java/org/simple/clinic/selectcountry/SelectCountryScreen.kt, app/src/main/res/layout/screen_selectcountry.xml
https://app.shortcut.com/simpledotorg/story/5292/migrate-selectcountryscreen-to-a-fragment
=> Migrate `SelectCountryScreen` to a fragment

CHANGELOG.md, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEffect.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEffectHandler.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEvent.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesInit.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesModel.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUi.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUiRenderer.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUpdate.kt, app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesView.kt, app/src/test/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesInitTest.kt, app/src/test/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUiRendererTest.kt, app/src/test/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicinesUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5224/inject-drugfrequencytolabelmap-directly-in-teleconsultmedicinesview-instead-of-handling-it-in-the-effect-handler
=> Inject `DrugFrequencyToLabelMap` directly in `TeleconsultMedicinesView` instead of handling it in the effect handler

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffect.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheet.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheetUiActions.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdate.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5046/custom-drug-entry-sheet-ui-improvements
=> Set the cursor in the correct position whenever `CustomDrugEntrySheet` is opened 

CHANGELOG.md, app/src/main/java/org/simple/clinic/appconfig/Country.kt, app/src/main/java/org/simple/clinic/patient/businessid/BusinessId.kt, app/src/main/java/org/simple/clinic/patient/businessid/Identifier.kt, app/src/main/java/org/simple/clinic/widgets/PatientSearchResultItemView.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/patient/IdentifierDisplayTest.kt
https://app.shortcut.com/simpledotorg/story/5243/add-sri-lanka-personal-health-number-business-identifier
=> Add Sri Lanka personal health number business identifier

CHANGELOG.md, app/src/main/java/org/simple/clinic/newentry/country/SriLankaInputFieldsProvider.kt, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/5244/show-personal-health-number-text-field-in-patient-entry-edit-screens
=> Show personal health number text field in patient entry/edit screens

CHANGELOG.md, app/src/main/java/org/simple/clinic/selectstate/SelectStateEffect.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateModel.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateScreen.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateUiActions.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateUiRenderer.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateUpdate.kt, app/src/main/java/org/simple/clinic/selectstate/SelectStateViewEffectHandler.kt, app/src/test/java/org/simple/clinic/selectstate/SelectStateEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/selectstate/SelectStateUiRendererTest.kt, app/src/test/java/org/simple/clinic/selectstate/SelectStateUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5236/navigate-back-to-selectcountryscreen-from-registrationphonescreen-when-there-s-only-one-state-present-in-the-country
=> Navigate back to `SelectCountryScreen` from `RegistrationPhoneScreen` when there's only one state present

CHANGELOG.md, app/src/test/java/org/simple/clinic/mobius/CustomFirstMatchers.kt, gradle/libs.versions.toml
- Bump Mobius to v1.5.5
- Fix type matcher type in `CustomFirstMatchers`
=> Bump Mobius to v1.5.5

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt
- Rename custom drug search screen feature flag
- Enable custom drug search feature
=> Enable drug search feature flag

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/search/DrugSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsEffectHandler.kt, app/src/main/java/org/simple/clinic/util/PagerFactory.kt, app/src/main/java/org/simple/clinic/widgets/PagingItemAdapter.kt, app/src/main/res/layout/list_item_overdue_placeholder.xml, app/src/test/java/org/simple/clinic/drugs/search/DrugSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueLogicTest.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/recentpatient/AllRecentPatientsEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/5338/enable-placeholders-in-overdue-screen
=> Enable placeholders in overdue screen

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/home/HomeScreen.kt, app/src/main/java/org/simple/clinic/home/HomeScreenEffect.kt, app/src/main/java/org/simple/clinic/home/HomeScreenEffectHandler.kt, app/src/main/java/org/simple/clinic/home/HomeScreenEvent.kt, app/src/main/java/org/simple/clinic/home/HomeScreenModel.kt, app/src/main/java/org/simple/clinic/home/HomeScreenUpdate.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt, app/src/test/java/org/simple/clinic/home/HomeScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/5339/use-overdue-list-count-to-display-the-count-in-the-tab-bar
=> Use overdue list count to display the count in the tab bar

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryItemView.kt, app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryView.kt, app/src/main/res/values-am-rET/strings.xml, app/src/main/res/values-bn-rBD/strings.xml, app/src/main/res/values-bn-rIN/strings.xml, app/src/main/res/values-hi-rIN/strings.xml, app/src/main/res/values-kn-rIN/strings.xml, app/src/main/res/values-mr-rIN/strings.xml, app/src/main/res/values-om-rET/strings.xml, app/src/main/res/values-pa-rIN/strings.xml, app/src/main/res/values-si-rLK/strings.xml, app/src/main/res/values-sid-rET/strings.xml, app/src/main/res/values-so-rET/strings.xml, app/src/main/res/values-ta-rIN/strings.xml, app/src/main/res/values-ta-rLK/strings.xml, app/src/main/res/values-te-rIN/strings.xml, app/src/main/res/values-ti-rET/strings.xml, app/src/main/res/values/strings.xml
- Render drug frequency in drug summary view
- Remove `prescribeddrugsummary_item_name` string
=> Render custom drug frequency in drug summary view

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEvent.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientModel.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiRenderer.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt, app/src/test/java/org/simple/clinic/contactpatient/CallPatientUiRendererTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientInitTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5359/fetch-appointment-directly-in-contact-patient-sheet
=> Fetch appointment directly in contact patient sheet

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/HomeScreen.kt, app/src/main/java/org/simple/clinic/settings/SettingsScreen.kt, app/src/main/res/layout/screen_settings.xml
https://app.shortcut.com/simpledotorg/story/5627/migrate-settingsscreen-to-a-fragment
=> Migrate `SettingsScreen` to a Fragment

CHANGELOG.md, gradle/libs.versions.toml
=> Bump Coroutines to v1.5.2

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/overdue/download/OverdueListDownloaderIntegrationTest.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueListDownloader.kt, app/src/main/java/org/simple/clinic/util/CsvToPdfConverter.kt
https://app.shortcut.com/simpledotorg/story/5248/implement-overduelistdownloader
=> Implement `OverdueListDownloader`

.github/workflows/ci_check_pr_comment.yml, .github/workflows/ci_checks.yml, CHANGELOG.md
**docs**: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
=> Cancel in progress GH actions when new action is started with same group name

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/HomeScreen.kt, app/src/main/java/org/simple/clinic/home/HomeScreenEffect.kt, app/src/main/java/org/simple/clinic/home/HomeScreenEffectHandler.kt, app/src/main/java/org/simple/clinic/home/HomeScreenViewEffectHandler.kt, app/src/test/java/org/simple/clinic/home/HomeScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/5763/migrate-homescreen-to-use-view-effects
=> Migrate `HomeScreen` to use view effects

CHANGELOG.md, app/src/main/AndroidManifest.xml, app/src/main/java/org/simple/clinic/di/AppComponent.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueDownloadWorker.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueListDownloadFormat.kt, app/src/main/res/drawable/ic_download_notification_icon.xml, app/src/main/res/values/strings.xml, gradle/libs.versions.toml
https://app.shortcut.com/simpledotorg/story/5254/implement-overduedownloadworker-class
=> Implement `OverdueDownloadWorker` class

CHANGELOG.md, app/src/main/java/org/simple/clinic/analytics/NetworkCapabilitiesProvider.kt, app/src/main/java/org/simple/clinic/analytics/NetworkConnectivityStatus.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUiActions.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueLogicTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5626/show-no-internet-connection-dialog-when-download-share-button-is-clicked
=> Show no internet connection dialog when download/share button is clicked

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5245/ask-storage-permission-when-download-share-button-is-clicked
=> Ask storage permission when download/share button is clicked

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/OverdueListDownloadApiIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/overdue/download/OverdueListDownloaderIntegrationTest.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueDownloadWorker.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueListDownloadApi.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueListDownloader.kt
https://app.shortcut.com/simpledotorg/story/5866/add-common-download-function-for-downloading-overdue-list
=> Add common download function for downloading overdue list

.github/workflows/ci_checks.yml, CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/bloodsugar/BloodSugarRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/di/TestStorageModule.kt, app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/drugs/search/DrugRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/drugs/search/sync/DrugSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/facility/FacilityRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/medicalhistory/MedicalHistoryRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/protocolv2/ProtocolRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/rules/SaveDatabaseRule.kt, app/src/androidTest/java/org/simple/clinic/summary/addphone/MissingPhoneReminderRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultationFacilityRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/sync/AppointmentSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/BloodPressureSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/BloodSugarSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/MedicalHistorySyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/PatientSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/PrescriptionSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/ProtocolSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/ReportsSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/sync/TeleconsultationSyncIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecordRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/user/UserSessionAndroidTest.kt
https://app.shortcut.com/simpledotorg/story/5766/publish-app-databases-as-test-artifacts-for-failed-tests-in-ci-runs
=> Save databases from failed instrumentation tests as test artifacts

CHANGELOG.md, app/src/main/java/org/simple/clinic/overdue/download/OverdueListDownloader.kt
Forgot to update the file name extension when refactoring this class
=> Fix overdue list file name in `OverdueListDownloader`

CHANGELOG.md, app/src/main/java/org/simple/clinic/overdue/download/OverdueDownloadScheduler.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueDownloadWorker.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/OpenAs.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/OverdueDownloadStatus.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffect.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffectHandler.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEvent.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatModel.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatViewEffectHandler.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadUpdate.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/UiActions.kt, app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5269/implement-overdue-list-download-share-format-dialog
=> Implement overdue list download/share format dialog - 1

CHANGELOG.md, app/build.gradle.kts, app/src/debug/AndroidManifest.xml, app/src/debug/java/org/simple/clinic/di/network/HttpInterceptorsModule.kt, app/src/main/java/org/simple/clinic/ClinicApp.kt, app/src/main/java/org/simple/clinic/analytics/ResolveScreenNamesForDatadog.kt, app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/di/AppModule.kt, app/src/main/java/org/simple/clinic/navigation/v2/compat/ScreenFragmentCompat.kt, app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseBottomSheet.kt, app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseDialog.kt, app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseScreen.kt, app/src/main/java/org/simple/clinic/storage/monitoring/DatadogSqlPerformanceReportingSink.kt, app/src/release/java/org/simple/clinic/di/network/HttpInterceptorsModule.kt, build.gradle.kts, gradle.properties, gradle/libs.versions.toml
https://app.shortcut.com/simpledotorg/story/5505/enable-end-to-end-application-monitoring
=> Send application performance metrics to Datadog

CHANGELOG.md, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryQuestionView.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryModel.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUpdate.kt, app/src/test/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryLogicTest.kt, app/src/test/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5970/fix-medical-history-answers-toggle-not-switching-when-selected
=> Fix medical history answers toggle not switching when selected

CHANGELOG.md, app/src/main/java/org/simple/clinic/overdue/download/OverdueDownloadWorker.kt
https://app.shortcut.com/simpledotorg/story/6148/use-io-scheduler-for-doing-background-tasks-in-overduedownloadworker
=> Use `IO` scheduler for doing background tasks in `OverdueDownloadWorker`

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUiActions.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/OpenAs.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatDialog.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatInit.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUiRenderer.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueLogicTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt, app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatInitTest.kt, app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5872/download-share-csv-only-for-api-below-24
=> Download/Share CSV only for API below 24

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/download/OverdueListDownloaderIntegrationTest.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueDownloadWorker.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueListDownloadResult.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueListDownloader.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/DownloadFailedErrorDialog.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/NotEnoughStorageErrorDialog.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatDialog.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffect.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEvent.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUpdate.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatViewEffectHandler.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/UiActions.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/6093/show-error-dialog-when-overdue-list-download-fails
=> Show error dialog when overdue list download fails

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/TestDataModule.kt, app/src/androidTest/java/org/simple/clinic/rules/ServerAuthenticationRule.kt
https://app.shortcut.com/simpledotorg/story/6149/hardcode-a-user-for-use-in-server-integration-tests
=> Use hardcoded user in server integration tests

CHANGELOG.md, app/src/main/java/org/simple/clinic/patient/businessid/Identifier.kt
https://app.shortcut.com/simpledotorg/story/5607/occasional-crash-when-trying-to-render-business-identifiers
=> Report `StringIndexOutOfBoundsException` when building identifier display value

CHANGELOG.md, app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseDialog.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueDownloadWorker.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatDialog.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatModel.kt, app/src/main/res/layout/dialog_select_overdue_download_format.xml
https://app.shortcut.com/simpledotorg/story/6209/make-pdf-as-the-default-for-downloading-overdue-lists
=> Make PDF as the default for downloading Overdue lists

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt
https://app.shortcut.com/simpledotorg/story/6260/fix-sri-lanka-personal-health-number-not-rendering-in-the-patient-entry-and-edit-screens
=> Fix Sri Lanka personal health number not rendering in the patient entry and edit screens

CHANGELOG.md, app/src/main/java/org/simple/clinic/setup/SetupActivityModel.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityUpdate.kt, app/src/test/java/org/simple/clinic/setup/SetupActivityUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/5521/remove-unused-properties-from-setupactivitymodel
=> Remove unused properties from `SetupActivityModel`

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/EditMedicinesEffect.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesEffectHandler.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesViewEffectHandler.kt, app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesScreen.kt, app/src/test/java/org/simple/clinic/drugs/EditMedicineEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/EditMedicinesScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/6266/migrate-editmedicinescreen-to-use-view-effects
=> Migrate `EditMedicinesScreen` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeEffectHandler.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/reports/ReportsRepository.kt, app/src/test/java/org/simple/clinic/facility/change/confirm/ConfirmFacilityChangeEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/6330/fix-app-crashing-when-changing-facility-in-offline
=> Fix app crashing when changing facility while app is not connected to network

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestStorageModule.kt, app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt, app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
https://app.shortcut.com/simpledotorg/story/6246/set-up-a-performance-regression-test-suite-that-alerts-performance-regressions
=> Remove the singleton scoping for the App database in instrumented tests

CHANGELOG.md, app/src/main/java/org/simple/clinic/di/network/RetrofitModule.kt, app/src/main/java/org/simple/clinic/di/network/Timeout.kt, app/src/main/java/org/simple/clinic/di/network/TimeoutCallAdapterFactory.kt, app/src/main/java/org/simple/clinic/patient/sync/PatientSyncApi.kt
https://app.shortcut.com/simpledotorg/story/4379/add-endpoint-specific-network-timeouts
=> Add a specific endpoint network timeout

.github/workflows/benchmark_suite.yml, .github/workflows/ci_checks.yml, CHANGELOG.md, app/build.gradle.kts, app/src/androidTest/AndroidManifest.xml, app/src/androidTest/java/org/simple/clinic/NoopSmsListenerOtp.kt, app/src/androidTest/java/org/simple/clinic/TestClinicApp.kt, app/src/androidTest/java/org/simple/clinic/benchmark/BackupBenchmarkDatabase.kt, app/src/androidTest/java/org/simple/clinic/benchmark/BaseBenchmarkTest.kt, app/src/androidTest/java/org/simple/clinic/benchmark/BenchmarkTest.kt, app/src/androidTest/java/org/simple/clinic/benchmark/BenchmarkTestRule.kt, app/src/androidTest/java/org/simple/clinic/benchmark/CanaryBenchmarkTest.kt, app/src/androidTest/java/org/simple/clinic/benchmark/SelectBenchmarkTests.kt, app/src/androidTest/java/org/simple/clinic/benchmark/WaitForDatadogToUpload.kt, app/src/androidTest/java/org/simple/clinic/benchmark/patientlookup/PatientLookupBenchmark.kt, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/di/TestAppModule.kt, app/src/androidTest/java/org/simple/clinic/di/TestStorageModule.kt, build.gradle.kts, gradle/libs.versions.toml
https://app.shortcut.com/simpledotorg/story/6246/set-up-a-performance-regression-test-suite-that-alerts-performance-regressions
=> Add support for writing performance regression instrumented tests

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/help/HelpScreen.kt
https://app.shortcut.com/simpledotorg/story/6495/fix-help-screen-not-opening-on-button-click
=> Fix help screen not opening on button click

CHANGELOG.md, app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt, app/src/main/java/org/simple/clinic/summary/nextappointment/NextAppointmentCardView.kt, app/src/main/java/org/simple/clinic/summary/nextappointment/NextAppointmentEvent.kt, app/src/main/java/org/simple/clinic/summary/nextappointment/NextAppointmentModel.kt, app/src/main/java/org/simple/clinic/summary/nextappointment/NextAppointmentUi.kt, app/src/main/java/org/simple/clinic/summary/nextappointment/NextAppointmentUiRenderer.kt, app/src/main/java/org/simple/clinic/summary/nextappointment/NextAppointmentUpdate.kt, app/src/main/res/layout/patientsummary_next_appointment_card.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/summary/nextappointment/NextAppointmentInitTest.kt, app/src/test/java/org/simple/clinic/summary/nextappointment/NextAppointmentUiRendererTest.kt, app/src/test/java/org/simple/clinic/summary/nextappointment/NextAppointmentUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/6455/implement-nextappointmentcardview
=> Implement `NextAppointmentCardView`

app/src/main/java/org/simple/clinic/scanid/OpenedFrom.kt, app/src/main/java/org/simple/clinic/scanid/ScanErrorState.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdEffect.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdModel.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUi.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUiActions.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUiRenderer.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdViewEffectHandler.kt, app/src/main/res/layout/screen_scan_simple.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdScreenLogicTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdUiRendererTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/6437/adding-support-for-scanning-identifier-for-editpatientscreen
=> Adding support for scanning Identifier for `EditPatientScreen`

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt, app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryInit.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreenUi.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewRenderer.kt, app/src/main/java/org/simple/clinic/summary/nextappointment/NextAppointmentCardView.kt, app/src/main/java/org/simple/clinic/summary/nextappointment/NextAppointmentModel.kt, app/src/main/res/layout/screen_patient_summary.xml, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryInitTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryViewRendererTest.kt
https://app.shortcut.com/simpledotorg/story/6450/add-next-appointment-card-in-patient-summary-screen
=> Show next appointment card in patient summary

CHANGELOG.md, app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffect.kt, app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentModel.kt, app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt, app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUiActions.kt, app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUpdate.kt, app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentViewEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/AppointmentSheetOpenedFrom.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/nextappointment/NextAppointmentCardView.kt, app/src/main/java/org/simple/clinic/summary/nextappointment/NextAppointmentEvent.kt, app/src/main/java/org/simple/clinic/summary/nextappointment/NextAppointmentUpdate.kt, app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentInitTest.kt, app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentLogicTest.kt, app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUiRendererTest.kt, app/src/test/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/nextappointment/NextAppointmentUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/6476/refresh-appointment-in-nextappointmentcard
=> Refresh next appointment when appointment schedule or assigned facility is changed

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/6431/change-appointment-bottom-sheet-display-logic
=> Change appointment bottom sheet display logic

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityEffect.kt, app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityEvent.kt, app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityUpdate.kt, app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityView.kt, app/src/main/java/org/simple/clinic/summary/assignedfacility/UiActions.kt, app/src/main/java/org/simple/clinic/summary/nextappointment/NextAppointmentCardView.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityUpdateTest.kt
It also has a small UI fix for `NextAppointmentCardView`
=> Fix appointment not refreshing after assigned facility is changed

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/EditPatientEffect.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientEvent.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientUi.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientUpdate.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientViewEffectHandler.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/6390/implement-adding-nhid-in-patienteditscreen
=> Implement adding NHID in `PatientEditScreen` - 1

CHANGELOG.md, app/src/main/java/org/simple/clinic/facilitypicker/FacilityPickerEffect.kt, app/src/main/java/org/simple/clinic/facilitypicker/FacilityPickerEffectHandler.kt, app/src/main/java/org/simple/clinic/facilitypicker/FacilityPickerEvent.kt, app/src/main/java/org/simple/clinic/facilitypicker/FacilityPickerInit.kt, app/src/main/java/org/simple/clinic/facilitypicker/FacilityPickerModel.kt, app/src/main/java/org/simple/clinic/facilitypicker/FacilityPickerUpdate.kt, app/src/test/java/org/simple/clinic/facilitypicker/FacilityPickerLogicTest.kt
https://app.shortcut.com/simpledotorg/story/6629/stop-loading-total-facility-count-when-facility-picker-view-is-created
=> Stop loading total facility count when facility picker view is created

heroku_debugging.yml
=> Heroku CLI Debugging

.github/scripts/setup_heroku_instance.sh, .github/workflows/ci_checks.yml
https://app.shortcut.com/simpledotorg/story/6655/debug-heroku-cli-issues-via-github-actions
install buildpack-registry and switch to using the buildpacks:add command
=> Explicitly install buildpack-registry during CI workflow

CHANGELOG.md, app/build.gradle.kts, gradle/libs.versions.toml
https://app.shortcut.com/simpledotorg/story/6641/bump-datadog-sdk-version
=> Bump Datadog SDK

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt
https://app.shortcut.com/simpledotorg/story/6742/ignore-automatic-appointments-when-fetching-next-appointment-details
=> Ignore automatic appointments when fetching next appointment details

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientEvent.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientModel.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientUpdate.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientViewRenderer.kt, app/src/main/java/org/simple/clinic/editpatient/EditablePatientEntry.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt, app/src/main/res/drawable/ic_add_circle_outline_24px.xml, app/src/main/res/layout/screen_edit_patient.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/editpatient/EditPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/6391/implement-adding-bppassport-in-editpatientscreen
=> Implement adding support to scan bppassport in `EditPatientScreen`

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/EditPatientEvent.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientUpdate.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/6656/add-camera-permissions-when-clicked-on-add-bp-passport
=> Request camera permissions when `addBpPassportButton` is clicked in `EditPatientScreen`

CHANGELOG.md, app/src/main/res/layout/patientsummary_next_appointment_card.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/theme.xml, app/src/main/res/values/theme_attr.xml
https://app.shortcut.com/simpledotorg/story/6790/update-next-appointment-card-ui-specs
=> Update next appointment card UI specs

CHANGELOG.md, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUi.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUiRenderer.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/6780/change-the-title-of-scansimpleidscreen-to-either-bp-passport-or-national-health-id-depending-on-where-it-s-opened-from
=> Set toolbar title in `ScanSimpleIdScreen` based on where it's opened from

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/EditPatientEvent.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientModel.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientUi.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientUpdate.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientViewRenderer.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdUpdate.kt, app/src/main/res/layout/screen_edit_patient.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/editpatient/EditPatientInitTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenCreatedTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenFormTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenSaveTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientUpdateTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientViewRendererTest.kt, app/src/test/java/org/simple/clinic/scanid/ScanSimpleIdUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/6390/implement-adding-nhid-in-patienteditscreen
I have also fixed [this](https://app.shortcut.com/simpledotorg/story/6776/fix-when-scanned-qr-code-error-is-shown-the-progress-state-continues-to-show) bug in this PR as it was related to this implementation and a very small fix.
=> Implement adding NHID in `EditPatientScreen`

CHANGELOG.md, app/src/main/res/layout/patientsummary_assigned_facility_content.xml
https://app.shortcut.com/simpledotorg/story/6794/update-assigned-facility-ui-specs
=>  Update assigned facility UI specs

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/EditPatientModel.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientUi.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientViewRenderer.kt, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/res/layout/screen_edit_patient.xml, app/src/test/java/org/simple/clinic/editpatient/EditPatientInitTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenCreatedTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenFormTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenSaveTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientUpdateTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientViewRendererTest.kt
https://app.shortcut.com/simpledotorg/story/6393/move-adding-health-ids-from-edit-patient-behind-a-feature-flag
=> Move adding health ids from edit patient behind a feature flag

CHANGELOG.md, app/src/main/res/layout/screen_edit_patient.xml
https://app.shortcut.com/simpledotorg/story/6781/display-national-health-id-before-bp-passports-in-editpatientscreen
=> Display National Health ID before BP Passports in `EditPatientScreen`

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientUi.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientViewRenderer.kt, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/test/java/org/simple/clinic/editpatient/EditPatientViewRendererTest.kt
https://app.shortcut.com/simpledotorg/story/6779/add-a-highlight-when-a-new-india-nhid-bp-passport-is-added
This PR will be merged in after [#3402 ](https://github.com/simpledotorg/simple-android/pull/3402)
=> Add highlight when a new alternate id is added

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/benchmark/overdue/OverdueBenchmark.kt, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
https://app.shortcut.com/simpledotorg/story/6831/add-benchmark-test-for-loading-overdue-appointments-in-a-facility
=> Add benchmark for loading overdue appointments in a facility

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientModel.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientUpdate.kt, app/src/main/java/org/simple/clinic/editpatient/EditablePatientEntry.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/6760/support-scanning-list-of-bp-passports-in-editpatientscreen
=> Support scanning list of unique Bp passports in `EditPatientScreen`

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/benchmark/patientregistration/PatientRegistrationBenchmark.kt, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
https://app.shortcut.com/simpledotorg/story/6851/add-benchmark-test-for-patient-registration-queries
=> Add benchmark for patient registration DB queries

CHANGELOG.md, app/src/main/java/org/simple/clinic/scanid/scannedqrcode/ScannedQrCodeEffect.kt, app/src/main/java/org/simple/clinic/scanid/scannedqrcode/ScannedQrCodeEffectHandler.kt, app/src/main/java/org/simple/clinic/scanid/scannedqrcode/ScannedQrCodeSheet.kt, app/src/main/java/org/simple/clinic/scanid/scannedqrcode/ScannedQrCodeViewEffectHandler.kt, app/src/test/java/org/simple/clinic/scanid/scannedqrcode/ScannedQrCodeEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/6902/migrate-scannedqrcodesheet-to-use-view-effects
=> Migrate `ScannedQrCodeSheet` to use view effects

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/benchmark/bp/BloodPressureEntryBenchmark.kt, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt
https://app.shortcut.com/simpledotorg/story/6852/add-benchmark-for-bp-entry-queries
=> Add benchmark test for creating a new bp entry

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffect.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheet.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryViewEffectHandler.kt, app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/6924/migrate-customdrugentrysheet-to-use-view-effects
=> Migrate `CustomDrugEntrySheet` to user view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/settings/SettingsEffect.kt, app/src/main/java/org/simple/clinic/settings/SettingsEffectHandler.kt, app/src/main/java/org/simple/clinic/settings/SettingsScreen.kt, app/src/main/java/org/simple/clinic/settings/SettingsViewEffectHandler.kt, app/src/test/java/org/simple/clinic/settings/SettingsEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/6893/migrate-settingsscreen-to-use-view-effects
=> Migrate `SettingsScreen` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueAppointmentScreen.kt, app/src/main/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueEffect.kt, app/src/main/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueEffectHandler.kt, app/src/main/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueViewEffectHandler.kt, app/src/test/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/6939/migrate-removeoverdueappointmentscreen-to-use-view-effects
=> Migrate `RemoveOverdueAppointmentScreen` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/res/layout/patient_edit_alternate_id_view.xml, app/src/main/res/layout/patient_edit_bp_passport_view.xml, app/src/main/res/layout/screen_edit_patient.xml
https://app.shortcut.com/simpledotorg/story/6962/update-the-highlight-alignment-for-both-nhid-and-bp-passport
=> Update the highlight alignment for newly added NHID or BP passport

CHANGELOG.md, app/src/main/java/org/simple/clinic/appconfig/Country.kt, app/src/main/java/org/simple/clinic/appconfig/displayname/PlatformCountryDisplayNameFetcher.kt, app/src/main/java/org/simple/clinic/newentry/country/di/InputFieldsFactoryModule.kt, app/src/main/res/values/strings.xml
[Slack thread](https://simpledotorg.slack.com/archives/CFJMFSM8F/p1643627376130049)
=> Add support for demo country

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/99.json, app/src/androidTest/java/org/simple/clinic/SqliteHelperFunctions.kt, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration99AndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_99.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
https://app.shortcut.com/simpledotorg/story/6940/index-patientuuid-in-tables-that-are-joined-in-overdueappointment-database-view
=> Index `patientUuid` in tables that are joined in `OverdueAppointment` database view

CHANGELOG.md, app/src/main/java/org/simple/clinic/registration/name/RegistrationFullNameScreen.kt, app/src/main/java/org/simple/clinic/registration/name/RegistrationNameEffect.kt, app/src/main/java/org/simple/clinic/registration/name/RegistrationNameEffectHandler.kt, app/src/main/java/org/simple/clinic/registration/name/RegistrationNameViewEffectHandler.kt, app/src/test/java/org/simple/clinic/registration/name/RegistrationNameEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/registration/name/RegistrationNameScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/7024/migrate-registrationfullnamescreen-to-use-view-effects
=> Migrate `RegistrationFullNameScreen` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingEffect.kt, app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingEffectHandler.kt, app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingScreen.kt, app/src/main/java/org/simple/clinic/registration/register/RegistrationLoadingViewEffectHandler.kt, app/src/test/java/org/simple/clinic/registration/register/RegistrationLoadingEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/registration/register/RegistrationLoadingLogicTest.kt
https://app.shortcut.com/simpledotorg/story/6983/migrate-registrationloadingscreen-to-use-view-effects
=> Migrate `RegistrationLoadingScreen` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinEffect.kt, app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinEffectHandler.kt, app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinScreen.kt, app/src/main/java/org/simple/clinic/registration/pin/RegistrationPinViewEffectHandler.kt, app/src/test/java/org/simple/clinic/registration/pin/RegistrationPinScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/6992/migrate-registrationpinscreen-to-use-view-effects
=> Migrate `RegistrationPinScreen` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionEffect.kt, app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionEffectHandler.kt, app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreen.kt, app/src/main/java/org/simple/clinic/registration/location/RegistrationLocationPermissionViewEffectHandler.kt, app/src/test/java/org/simple/clinic/registration/location/RegistrationLocationPermissionEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/registration/location/RegistrationLocationPermissionScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/7034/migrate-registrationlocationpermissionscreen-to-use-view-effects
=> Migrate `RegistrationLocationPermissionScreen` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinEffect.kt, app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinEffectHandler.kt, app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinScreen.kt, app/src/main/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinViewEffectHandler.kt, app/src/test/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/registration/confirmpin/RegistrationConfirmPinLogicTest.kt
https://app.shortcut.com/simpledotorg/story/7057/migrate-registrationconfirmpinscreen-to-view-effects
=> Migrate `RegistrationConfirmPinScreen` to view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientViewEffectHandler.kt, app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsEffect.kt, app/src/main/java/org/simple/clinic/recentpatient/AllRecentPatientsEffectHandler.kt, app/src/main/java/org/simple/clinic/recentpatient/RecentPatientsScreen.kt, app/src/test/java/org/simple/clinic/recentpatient/AllRecentPatientsEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/7071/migrate-recentpatientsscreen-to-use-view-effects
=>  Migrate `RecentPatientsScreen` to use view effects

CHANGELOG.md, app/src/main/res/layout/screen_edit_patient.xml
https://app.shortcut.com/simpledotorg/story/7103/bug-the-x-button-in-the-edit-screen-is-broken
=> Fix the broken `backButton` in the “Edit” screen

CHANGELOG.md, gradle/libs.versions.toml
https://github.com/facebook/flipper/issues/3395
=> Revert Flipper update as it's crashing the app

CHANGELOG.md, app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionEffect.kt, app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionEffectHandler.kt, app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt, app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionViewEffectHandler.kt, app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionLogicTest.kt
https://app.shortcut.com/simpledotorg/story/7046/migrate-registrationfacilityselectionscreen-to-use-view-effects
=> Migrate `RegistrationFacilitySelectionScreen` to use view effects

CHANGELOG.md, app/src/main/AndroidManifest.xml
https://app.shortcut.com/simpledotorg/story/7128/stop-sending-user-location-information-to-mixpanel
=> Stop sending user location information to Mixpanel

CHANGELOG.md, app/src/main/java/org/simple/clinic/login/pin/LoginPinEffect.kt, app/src/main/java/org/simple/clinic/login/pin/LoginPinEffectHandler.kt, app/src/main/java/org/simple/clinic/login/pin/LoginPinScreen.kt, app/src/main/java/org/simple/clinic/login/pin/LoginPinViewEffectHandler.kt, app/src/test/java/org/simple/clinic/login/pin/LoginPinScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/7155/migrate-loginpinscreen-to-use-view-effects
=> Migrate `LoginPinScreen` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/analytics/MixpanelAnalyticsReporter.kt, app/src/main/java/org/simple/clinic/analytics/UpdateAnalyticsUserId.kt, app/src/main/java/org/simple/clinic/login/LoginUserWithOtp.kt, app/src/main/java/org/simple/clinic/plumbing/infrastructure/DatadogInfrastructure.kt, app/src/main/java/org/simple/clinic/user/registeruser/RegisterUser.kt, app/src/test/java/org/simple/clinic/analytics/AnalyticsTest.kt, app/src/test/java/org/simple/clinic/analytics/ErrorSwallowingReporterTest.kt, app/src/test/java/org/simple/clinic/analytics/UpdateAnalyticsUserIdTest.kt, app/src/test/java/org/simple/clinic/login/LoginUserWithOtpTest.kt, app/src/test/java/org/simple/clinic/user/UserSessionTest.kt, app/src/test/java/org/simple/clinic/user/registeruser/RegisterUserTest.kt, simple-platform/src/main/java/org/simple/clinic/platform/analytics/AnalyticsUser.kt
https://app.shortcut.com/simpledotorg/story/7125/stop-sending-username-to-analytics
=> Stop sending username to analytics

CHANGELOG.md, app/src/main/java/org/simple/clinic/login/applock/AppLockEffect.kt, app/src/main/java/org/simple/clinic/login/applock/AppLockEffectHandler.kt, app/src/main/java/org/simple/clinic/login/applock/AppLockScreen.kt, app/src/main/java/org/simple/clinic/login/applock/AppLockViewEffectHandler.kt, app/src/test/java/org/simple/clinic/login/applock/AppLockEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/login/applock/AppLockScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/7166/migrate-applockscreen-to-use-view-effects
=> Migrate `AppLockScreen` to use view effects

CHANGELOG.md, gradle/libs.versions.toml
This reverts commit 4ec17a78e47085b735e37cef19e9e0c5a552bd20.
=> Revert "Update dependency com.itextpdf:itext7-core to v7.2.1 (#3506)"

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/help/HelpScreen.kt, app/src/main/java/org/simple/clinic/home/help/HelpScreenEffect.kt, app/src/main/java/org/simple/clinic/home/help/HelpScreenEffectHandler.kt, app/src/main/java/org/simple/clinic/home/help/HelpScreenViewEffectHandler.kt, app/src/test/java/org/simple/clinic/home/help/HelpScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/7199/migrate-helpscreen-to-view-effects
=> Migrate `HelpScreen` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/ContactType.kt, app/src/main/java/org/simple/clinic/appupdate/AppUpdateHelpContact.kt, app/src/main/java/org/simple/clinic/appupdate/AppUpdateModule.kt, app/src/main/java/org/simple/clinic/di/AppModule.kt, app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt, app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt
https://app.shortcut.com/simpledotorg/story/7222/implement-criticalappupdatedialog
=> Provide `AppUpdateHelpContact` based on the `Country`

CHANGELOG.md, app/src/main/java/org/simple/clinic/di/AppModule.kt, app/src/main/java/org/simple/clinic/settings/AppVersionFetcher.kt, app/src/main/java/org/simple/clinic/settings/SettingsEffect.kt, app/src/main/java/org/simple/clinic/settings/SettingsEffectHandler.kt, app/src/main/java/org/simple/clinic/settings/SettingsInit.kt, app/src/main/java/org/simple/clinic/settings/SettingsModel.kt, app/src/main/java/org/simple/clinic/settings/SettingsScreen.kt, app/src/test/java/org/simple/clinic/settings/SettingsEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/settings/SettingsInitTest.kt, app/src/test/java/org/simple/clinic/settings/SettingsUiRendererTest.kt, app/src/test/java/org/simple/clinic/settings/SettingsUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/7373/refactor-appversionfetcher-to-get-packageinfo-for-application-id-internally
=> Provide `PackageInfo` as dependency for `AppVersionFetcher`

CHANGELOG.md, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateDialogUpdate.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateEffect.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateEffectHandler.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateEvent.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateInit.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateModel.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateUi.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateUiRenderer.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateViewEffectHandler.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/UiActions.kt, app/src/test/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateDialogUpdateTest.kt, app/src/test/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateInitTest.kt, app/src/test/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/7222/implement-criticalappupdatedialog
=> Add `CriticalAppUpdateDialog` - 1

CHANGELOG.md, app/proguard-rules.pro
https://app.shortcut.com/simpledotorg/story/7391/fix-sandbox-build-failing-in-bitrise
=> Fix R8 build error when generating release artifacts

CHANGELOG.md, app/src/main/java/org/simple/clinic/Globals.kt, app/src/main/java/org/simple/clinic/appupdate/AppUpdateConfig.kt, app/src/main/java/org/simple/clinic/appupdate/AppUpdateModule.kt, app/src/main/java/org/simple/clinic/appupdate/AppUpdateNudgePriority.kt, app/src/main/java/org/simple/clinic/appupdate/AppUpdateState.kt, app/src/main/java/org/simple/clinic/appupdate/CheckAppUpdateAvailability.kt, app/src/main/java/org/simple/clinic/appupdate/UpdateInfo.kt, app/src/main/java/org/simple/clinic/appupdate/UpdateManager.kt, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/settings/AppVersionFetcher.kt, app/src/test/java/org/simple/clinic/appupdate/CheckAppUpdateAvailabilityTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsLogicTest.kt, app/src/test/java/org/simple/clinic/settings/SettingsEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/7225/add-support-for-prioritised-nudges-in-checkappupdateavailability
=> Add support for prioritised nudges in `CheckAppUpdateAvailability`

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt
https://app.shortcut.com/simpledotorg/story/7613/display-patient-search-results-in-alphabetical-order
=> Display patient search results in alphabetical order

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/di/TestAppModule.kt, app/src/androidTest/java/org/simple/clinic/drugstockreminders/DrugStockReminderApiIntegrationTest.kt, app/src/main/java/org/simple/clinic/di/AppModule.kt, app/src/main/java/org/simple/clinic/drugstockreminders/DrugStockReminder.kt, app/src/main/java/org/simple/clinic/drugstockreminders/DrugStockReminderApiModule.kt, app/src/main/java/org/simple/clinic/drugstockreminders/DrugStockReport.kt, app/src/test/java/org/simple/clinic/drugstockreminders/DrugStockReminderTest.kt
https://app.shortcut.com/simpledotorg/story/7406/add-drugstockreminder-api-support
=> Adding API support for `DrugStockReminder` - 2

CHANGELOG.md, app/src/main/java/org/simple/clinic/appupdate/CheckAppUpdateAvailability.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateDialogUpdate.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateEffect.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateEffectHandler.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateEvent.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateInit.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateModel.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateUi.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateUiRenderer.kt, app/src/test/java/org/simple/clinic/appupdate/CheckAppUpdateAvailabilityTest.kt, app/src/test/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateDialogUpdateTest.kt, app/src/test/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateInitTest.kt, app/src/test/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/7222/implement-criticalappupdatedialog
=> Render app update nudge reason on critical app update dialog

.github/scripts/TriggerBitriseRelease.main.kts, .github/workflows/ci_checks.yml, .github/workflows/trigger_demo_release.yml, CHANGELOG.md
https://app.shortcut.com/simpledotorg/story/7729/add-gh-action-to-trigger-a-demo-release-on-bitrise-when-release-branch-is-created
=> Add GH Action to trigger a demo release on Bitrise when release branch is created

CHANGELOG.md, app/src/main/java/org/simple/clinic/ContactType.kt, app/src/main/java/org/simple/clinic/Globals.kt, app/src/main/java/org/simple/clinic/appupdate/AppUpdateHelpContact.kt, app/src/main/java/org/simple/clinic/appupdate/AppUpdateNotificationWorker.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateDialog.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateDialogUpdate.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateModel.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateUi.kt, app/src/main/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateUiRenderer.kt, app/src/main/java/org/simple/clinic/appupdate/dialog/AppUpdateDialog.kt, app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt, app/src/main/java/org/simple/clinic/settings/SettingsScreen.kt, app/src/main/res/layout/dialog_critical_app_update.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, app/src/test/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateDialogUpdateTest.kt, app/src/test/java/org/simple/clinic/appupdate/criticalupdatedialog/CriticalAppUpdateUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/7222/implement-criticalappupdatedialog
=> Wire `CriticalAppUpdateDialog` Mobius loop with UI

.github/workflows/trigger_demo_release.yml, CHANGELOG.md
I forgot to pass the app slug to the script 🤦🏾‍♂️
=> Pass Simple Bitrise app slug to `TriggerBitriseRelease` script

.github/scripts/TriggerBitriseRelease.main.kts, .github/workflows/trigger_demo_release.yml, CHANGELOG.md
https://app.shortcut.com/simpledotorg/story/7750/fix-trigger-demo-release-workflow-running-on-every-newly-created-branch
=> Fix `trigger_demo_release` workflow running on every newly created branch

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/patients/PatientsEffectHandler.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEffect.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEvent.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabModel.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUi.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUiActions.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUiRenderer.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUpdate.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabViewEffectHandler.kt, app/src/main/res/layout/app_update_card.xml, app/src/main/res/layout/screen_patients.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/home/patients/PatientsEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsLogicTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsTabUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsTabUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/7223/implement-the-ui-for-critical-update-card-in-patienttabscreen
=> Implement critical update card in `PatientTabScreen`

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/patients/PatientsEffectHandler.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsInit.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEffect.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEvent.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabModel.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUiActions.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabViewEffectHandler.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsInitTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsLogicTest.kt
https://app.shortcut.com/simpledotorg/story/7236/implement-showing-app-update-nudges-based-on-the-priority-in-patienttabscreen
=> Implement showing app update nudges based on the priority in `PatientTabScreen` - 1

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesScreen.kt
https://app.shortcut.com/simpledotorg/story/7740/fix-recycler-view-crash-when-refilling-drugs
=> Fix recycler view crash when refilling drugs

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/patients/PatientsTabModel.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUi.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUiRenderer.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUpdate.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsLogicTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsTabUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsTabUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/7236/implement-showing-app-update-nudges-based-on-the-priority-in-patienttabscreen
=> Implement showing app update nudges based on the priority in `PatientTabScreen`

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt
https://app.shortcut.com/simpledotorg/story/7769/show-the-clinical-decision-support-banner-in-summary-screen-when-newest-bp-entry-is-high-for-the-patient
=> Add a query to check whether the latest BP entry is high for the patient

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/drugstockreminders/DrugStockReminderApiIntegrationTest.kt, app/src/main/java/org/simple/clinic/di/AppComponent.kt, app/src/main/java/org/simple/clinic/di/DateFormatter.kt, app/src/main/java/org/simple/clinic/di/DateFormatterModule.kt, app/src/main/java/org/simple/clinic/drugstockreminders/DrugStockReminder.kt, app/src/main/java/org/simple/clinic/drugstockreminders/DrugStockReminderApiModule.kt, app/src/main/java/org/simple/clinic/drugstockreminders/DrugStockWorker.kt, app/src/main/java/org/simple/clinic/main/TypedPreference.kt, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/7407/implement-the-drug-stock-api
=> Implementing the support for `DrugStockReminder` API

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryInit.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewRenderer.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryInitTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryViewRendererTest.kt
https://app.shortcut.com/simpledotorg/story/7778/add-feature-flag-for-clinical-decision-support-alerts
=> Add feature flag for clinical decision support alerts

CHANGELOG.md, app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
Updated the query condition for systolic and diastolic to greater than or equal to
=> Update `isNewestBpEntryHigh` query

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt
@msasikanth It would be great if you could merge this in before the release tomorrow?
=> Add remote config key for `NotifyAppUpdateAvailableV2` feature flag

.github/scripts/CutReleaseBranch.main.kts, .github/workflows/cut_release_branch.yml, CHANGELOG.md
https://app.shortcut.com/simpledotorg/story/7738/cut-release-branch-every-2-weeks-on-github-repo
=> Add GitHub action to cut a release branch

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/HomeScreen.kt
https://app.shortcut.com/simpledotorg/story/7936/increase-max-character-limit-in-overdue-tab-badge
=> Increase max character limit in overdue tab badge

CHANGELOG.md, app/src/main/java/org/simple/clinic/sync/SyncModule.kt
https://app.shortcut.com/simpledotorg/story/7898/sync-reports-and-progress-data-before-patient-sync
=> Sync reports and progress data before patient sync

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/benchmark/patientregistration/PatientRegistrationBenchmark.kt, app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/storage/DeleteSyncGroupDatabaseAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/storage/PurgeDatabaseAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/sync/PatientSyncIntegrationTest.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenCreatedTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenFormTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientScreenSaveTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditPatientViewRendererTest.kt, app/src/test/java/org/simple/clinic/editpatient/EditablePatientEntryTest.kt, app/src/test/java/org/simple/clinic/patient/PatientAgeDetailsTest.kt, app/src/test/java/org/simple/clinic/recentpatient/AllRecentPatientsEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/recentpatient/AllRecentPatientsUpdateTest.kt, app/src/test/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryViewRendererTest.kt
https://app.shortcut.com/simpledotorg/story/4484/remove-the-age-class
=> Replace `age` and `dateOfBirth` in `TestData` factory methods with `PatientAgeDetails`

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/patients/PatientsEffectHandler.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsInit.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEffect.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEvent.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabModel.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUpdate.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsInitTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsLogicTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsTabUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/7408/check-drug-stock-report-status-when-app-is-opened
=> Check drug stock report status when app is opened

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugstockreminders/DrugStockNotificationScheduler.kt, app/src/main/java/org/simple/clinic/drugstockreminders/DrugStockWorker.kt
https://app.shortcut.com/simpledotorg/story/7462/handle-scheduling-of-drug-stock-reminder-api
=> Handle scheduling of `DrugStock` API to run on 1st of every month at 8 AM

CHANGELOG.md, app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewEffect.kt, app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewEffectHandler.kt, app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinScreen.kt, app/src/main/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewViewEffectHandler.kt, app/src/test/java/org/simple/clinic/forgotpin/createnewpin/ForgotPinCreateNewPinScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/7200/migrate-forgotpincreateneweffecthandler-to-view-effects
=> Migrate `ForgotPinCreateNewEffectHandler` to view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsInit.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsInitTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsLogicTest.kt
https://app.shortcut.com/simpledotorg/story/7412/add-feature-flag-to-support-drug-stock-reminders
=> Add a feature flag for monthly drug stock report reminders

CHANGELOG.md, app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinEffect.kt, app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinEffectHandler.kt, app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreen.kt, app/src/main/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinViewEffectHandler.kt, app/src/test/java/org/simple/clinic/forgotpin/confirmpin/ForgotPinConfirmPinScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/7977/migrate-forgotpinconfirmpineffecthandler-to-use-view-effects
=> Migrate `ForgotPinConfirmPinEffectHandler` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/editpatient/deletepatient/DeletePatientEffect.kt, app/src/main/java/org/simple/clinic/editpatient/deletepatient/DeletePatientEffectHandler.kt, app/src/main/java/org/simple/clinic/editpatient/deletepatient/DeletePatientScreen.kt, app/src/main/java/org/simple/clinic/editpatient/deletepatient/DeletePatientViewEffectHandler.kt, app/src/test/java/org/simple/clinic/editpatient/deletepatient/DeletePatientEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/7979/migrate-deletepatienteffecthandler-to-use-view-effects
=> Migrate `DeletePatientEffectHandler` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockEffect.kt, app/src/main/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockEffectHandler.kt, app/src/main/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockEvent.kt, app/src/main/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockInit.kt, app/src/main/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockModel.kt, app/src/main/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockScreen.kt, app/src/main/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockScreenUiRenderer.kt, app/src/main/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockUi.kt, app/src/main/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockUpdate.kt, app/src/main/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockWebViewClient.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEffect.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEvent.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUiActions.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUpdate.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabViewEffectHandler.kt, app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt, app/src/main/res/layout/drug_stock_reminder_card.xml, app/src/main/res/layout/screen_enter_drug_stock.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockInitTest.kt, app/src/test/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockScreenUiRendererTest.kt, app/src/test/java/org/simple/clinic/drugstockreminders/enterdrugstock/EnterDrugStockUpdateTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsTabUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/7411/open-webview-when-clicked-on-enter-drug-stock
=> Handle opening of webView when enter drug stock button clicked

CHANGELOG.md, app/src/main/java/org/simple/clinic/appupdate/AppUpdateState.kt, app/src/main/java/org/simple/clinic/appupdate/CheckAppUpdateAvailability.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsEffectHandler.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEvent.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabModel.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUpdate.kt, app/src/test/java/org/simple/clinic/appupdate/CheckAppUpdateAvailabilityTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsLogicTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsTabUpdateTest.kt, app/src/test/java/org/simple/clinic/settings/SettingsEffectHandlerTest.kt
[https://github.com/simpledotorg/simple-android/pull/3811#discussion_r863452482](https://github.com/simpledotorg/simple-android/pull/3811#discussion_r863452482)
=> Add `appStaleness` as a parameter in `AppUpdateState.ShowAppUpdate`

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUiRenderer.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsTabUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/7646/show-critical-update-card-if-in-case-it-clashes-with-drug-stock-reminder-card
=> Show critical update card if in case it clashes with drug stock reminder card

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryInit.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryModule.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewRenderer.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryInitTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryViewRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8158/enable-cdss-alerts-only-in-pilot-facilities
=> Enable CDSS alerts only in pilot facilities

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/overdue/callresult/CallResultRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResult.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResultRepository.kt
https://app.shortcut.com/simpledotorg/story/8167/add-query-to-fetch-call-result-for-the-appointment
=> Add query to fetch call result for the appointment

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffect.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEvent.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientModel.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUpdate.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResult.kt, app/src/main/java/org/simple/clinic/overdue/callresult/Outcome.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8168/show-call-result-status-for-the-appointment-in-contactpatientbottomsheet
=> Show call result status for the appointment in `ContactPatientBottomSheet` - 1

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewRenderer.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryViewRendererTest.kt
**Story:** https://app.shortcut.com/simpledotorg/story/8257/don-t-show-cdss-alert-for-new-patient-registrations
=> Don't show CDSS alert for newly registered patients

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt
https://app.shortcut.com/simpledotorg/story/8255/fix-cdss-alert-hiding-when-multiple-bps-are-added-on-the-same-day
=> Fix CDSS alert hiding when multiple BPs are added on the same day

CHANGELOG.md, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryModel.kt, app/src/main/res/values-si-rLK/strings.xml
**Story:** 
https://app.shortcut.com/simpledotorg/story/8249/edit-text-on-the-disease-page-of-the-android-app-and-enable-for-sri-lanka
=> Show ongoing hypertension treatment question for Sri Lanka

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
https://app.shortcut.com/simpledotorg/story/8259/don-t-show-a-cdss-alert-if-the-patient-has-an-appointment-overdue-for-more-than-2-days
=> Add query to load latest scheduled appointment for the patient

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientModel.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUi.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiRenderer.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUpdate.kt, app/src/test/java/org/simple/clinic/contactpatient/CallPatientUiRendererTest.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientUpdateTest.kt, app/src/test/java/org/simple/clinic/contactpatient/SetAppointmentReminderUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8168/show-call-result-status-for-the-appointment-in-contactpatientbottomsheet
=> Show call result status for the appointment in `ContactPatientBottomSheet` - 2

app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8259/don-t-show-a-cdss-alert-if-the-patient-has-an-appointment-overdue-for-more-than-2-days
=> Load latest scheduled appointment in summary screen if CDSS pilot is enabled for facility

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewRenderer.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryViewRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8259/don-t-show-a-cdss-alert-if-the-patient-has-an-appointment-overdue-for-more-than-2-days
=> Don't show CDSS alert for patient if appointment is more than 2 days overdue

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/views/CallPatientView.kt, app/src/main/res/layout/contactpatient_callpatient.xml
https://app.shortcut.com/simpledotorg/story/8166/redesign-contactpatientbottomsheet-ui
=> Redesign `ContactPatientBottomSheet` UI

CHANGELOG.md, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://github.com/simpledotorg/simple-android/pull/3856#discussion_r877981233
=> Fix test name in `PatientSummaryUpdateTest`

app/src/main/res/layout/contactpatient_callpatient.xml
https://app.shortcut.com/simpledotorg/story/8166/redesign-contactpatientbottomsheet-ui
=> Redesign `ContactPatientBottomSheet` UI - #2

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentNew.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentModule.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
https://app.shortcut.com/simpledotorg/story/8325/add-query-to-load-all-overdue-appointments
=> Add query to load all overdue appointments for a facility

app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItem.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment_Old.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUiActions.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueViewEffectHandler.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentModule.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt, app/src/sharedTest/java/org/simple/clinic/TestData.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueLogicTest.kt
This PR also rename `OverdueAppointmentNew` to `OverdueAppointment`
=> Rename `OverdueAppointment` to `OverdueAppointment_Old`

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/patients/PatientsInit.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsInitTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsLogicTest.kt
https://app.shortcut.com/simpledotorg/story/8361/enable-drug-stock-only-for-india
=> Enable monthly drug stock reminders only in India

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt
https://app.shortcut.com/simpledotorg/story/8327/load-overdue-appointments-and-break-down-into-different-sections-based-on-states
=> Remove overdue appointments list from `OverdueModel`

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueLogicTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8327/load-overdue-appointments-and-break-down-into-different-sections-based-on-states
=> Use `LoadOverdueAppointments_old` to load overdue appointments

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientInit.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientModel.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUiRenderer.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientUpdate.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt
https://app.shortcut.com/simpledotorg/story/8169/show-call-result-section-by-default-in-contactpatientbottomsheet
=> Show call result section by default in `ContactPatientBottomSheet`

CHANGELOG.md, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/8400/overdue-screen-ui-enhancements
=> Rename agreed to visit call result text

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/8400/overdue-screen-ui-enhancements
=> Rename remind to call later call result text

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUi.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUiRenderer.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8410/show-progress-bar-when-loading-all-overdue-appointments
=> Show progress bar when loading all overdue appointments

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/8339/implement-overdue-list-item-adapter
=> Implement `OverdueAppointmentListItemNew` adapter #1

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentSections.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUi.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUiRenderer.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8436/add-wrapper-class-for-overdue-appointment-sections
=> Add wrapper class for overdue appointment sections

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
https://app.shortcut.com/simpledotorg/story/8438/load-appointments-with-a-reminder-when-loading-all-overdue-appointments-for-a-facility
=> Load appointments with a reminder when loading all overdue appointments for a facility

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt
https://app.shortcut.com/simpledotorg/story/8444/link-overdue-list-adapter-to-the-recyclerview
=> Link overdue list adapter to the recyclerview

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt, app/src/main/res/layout/list_item_divider.xml
https://app.shortcut.com/simpledotorg/story/8339/implement-overdue-list-item-adapter
=> Implement `OverdueAppointmentListItemNew` adapter #2

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt
https://app.shortcut.com/simpledotorg/story/8461/fix-views-flashing-in-the-overdue-list
=> Fix views flashing in the overdue list

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUi.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUiRenderer.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8340/when-there-s-no-overdue-appointment-show-no-patients-overdue
=> When there's no overdue appointment, show no patients overdue

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentModule.kt, app/src/main/java/org/simple/clinic/overdue/PendingAppointmentsConfig.kt
https://app.shortcut.com/simpledotorg/story/8460/add-pending-list-size-for-the-default-see-less-state-as-a-remote-config
=> Add pending list size for the default state as a firebase remote config

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/storage/PurgeDatabaseAndroidTest.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt
https://app.shortcut.com/simpledotorg/story/8452/do-not-purge-the-latest-cancelled-appointments
=> Purge old appointments that are synced

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/HomeScreen.kt, app/src/main/java/org/simple/clinic/home/report/ReportsScreen.kt, app/src/main/java/org/simple/clinic/home/report/ReportsWebViewClient.kt, app/src/main/java/org/simple/clinic/widgets/Views.kt
https://app.shortcut.com/simpledotorg/story/8483/fix-progress-page-not-handling-system-back-clicks
=> Fix progress page not handling system back clicks

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt, app/src/main/java/org/simple/clinic/widgets/Views.kt, app/src/main/res/layout/list_item_overdue_list_section_header.xml
https://app.shortcut.com/simpledotorg/story/8485/fix-inconsistent-overdue-section-header-ui
=> Fix inconsistent overdue section header UI

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentsListStates.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8486/restore-expanded-collapsed-states-of-overdue-sections
=> Use `OverdueListSectionStates` to update overdue section states in `OverdueModel`

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUi.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUiRenderer.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8486/restore-expanded-collapsed-states-of-overdue-sections
=> Use `OverdueListSectionStates` to check overdue section states in `OverdueAppointmentListItemNew`

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/res/layout/list_item_search_overdue_patient_button.xml, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/8518/add-search-button-in-overdue-patients-list
=> Add search button in overdue patients list

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/103.json, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration103AndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/patient/PatientAddress.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_103.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
https://app.shortcut.com/simpledotorg/story/8519/implement-search-query-for-overdue-patients
=> Implement FTS table for PatientAddress

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
https://app.shortcut.com/simpledotorg/story/8519/implement-search-query-for-overdue-patients
=> Define overdue appointment query as a `const` in `OverdueAppointment`

CHANGELOG.md, app/src/main/java/org/simple/clinic/di/AppModule.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModule.kt
https://app.shortcut.com/simpledotorg/story/8520/display-search-history-in-overdue-search-screen
=> Provide overdue search history string set from preferences

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModel.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8520/display-search-history-in-overdue-search-screen
=> Add effect to load overdue search history

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModel.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8520/display-search-history-in-overdue-search-screen
=> Show overdue search history when search query is empty

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8536/save-search-history-when-starting-a-search
=> Validate search query when overdue search query is changed

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/di/TestAppModule.kt, app/src/androidTest/java/org/simple/clinic/home/overdue/search/OverdueSearchHistoryTest.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchConfig.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchHistory.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchValidatorTest.kt
https://app.shortcut.com/simpledotorg/story/8542/add-overduesearchhistory-class
=> Implement `OverdueSearchHistory`

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8536/save-search-history-when-starting-a-search
=> Save search query to overdue search history when search query is valid

CHANGELOG.md, app/lint.xml, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt, app/src/main/res/drawable/ic_search_history.xml, app/src/main/res/layout/screen_overdue_search.xml, app/src/main/res/layout/view_overdue_search_history.xml, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/8535/add-layout-for-overdue-search-screen
=> Add layout for overdue search screen

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/104.json, app/src/androidTest/java/org/simple/clinic/benchmark/overdue/OverdueBenchmark.kt, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration104AndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_104.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt
https://app.shortcut.com/simpledotorg/story/8519/implement-search-query-for-overdue-patients
=> Implement query to search overdue patients

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchConfig.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchValidatorTest.kt
https://app.shortcut.com/simpledotorg/story/8527/show-search-results-in-overdue-search-screen
=> Search for overdue patients when search query is valid

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModel.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8527/show-search-results-in-overdue-search-screen
=> Show search results when overdue search results are loaded

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueAppointmentSearchListItem.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt
https://app.shortcut.com/simpledotorg/story/8528/show-no-patients-found-view-when-there-are-no-search-results-in-the-overdue-search-screen
=> Implement overdue search results adapter

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8599/prefill-search-query-when-the-search-history-item-is-clicked
=> Prefill search query when the search history item is clicked

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModel.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiActions.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchViewEffectHandler.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8598/implement-view-effects-to-show-overdue-search-results
=> Implement view effects to show overdue search results

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt
https://app.shortcut.com/simpledotorg/story/8531/wire-mobius-loop-with-overdue-screen-ui
=> Wire Mobius loop with overdue search screen UI

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiActions.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchViewEffectHandler.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8605/prefill-search-query-when-search-history-item-is-clicked
=> Prefill search query when search history item is clicked

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModel.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchProgressState.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8601/don-t-show-no-patients-found-error-view-when-search-query-is-empty
=> Don't show no patients found error view when search query is empty

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiActions.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchViewEffectHandler.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8605/prefill-search-query-when-search-history-item-is-clicked
=> Prefill search query when search history item is clicked in overdue search screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueAppointmentSearchListItem.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiActions.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchViewEffectHandler.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8603/highlight-search-results-with-the-matched-search-query
=> Highlight search results with the matched search query

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt
=> Increase overdue search query text field debounce time

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugstockreminders/DrugStockReport.kt, app/src/main/java/org/simple/clinic/drugstockreminders/DrugStockReportPayload.kt
https://app.shortcut.com/simpledotorg/story/8305/fix-jsondataexception-ie-parsing-the-drug-stock-response
=> Fix `JSONDataException` when parsing the drug stock response

CHANGELOG.md, app/src/main/java/org/simple/clinic/overdue/AppointmentSyncApi.kt
https://simpledotorg.slack.com/archives/CFHKJ5WJY/p1656487769682529?thread_ts=1656389171.937609&cid=CFHKJ5WJY
=> Bump resync token for appointment sync API

CHANGELOG.md, app/build.gradle.kts, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModel.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiActions.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchViewEffectHandler.kt, app/src/main/java/org/simple/clinic/util/PagerFactory.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt, gradle/libs.versions.toml
=> Use UI renderer to render overdue search results

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt, sharedTestCode/src/main/java/org/simple/sharedTestCode/TestData.kt
https://app.shortcut.com/simpledotorg/story/8625/add-query-to-fetch-required-information-for-generating-overdue-patients-csv
=> Add query to fetch required information for generating overdue patients CSV

CHANGELOG.md, app/src/main/java/org/simple/clinic/overdue/download/OverdueListDownloader.kt
This is done in preparation for this [story](https://app.shortcut.com/simpledotorg/story/8651/save-generated-overdue-patients-csv-to-a-file)
=> Refactor `OverdueListDownloader`

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt, app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewRenderer.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryViewRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8644/fix-cdss-alert-not-dismissing-after-medicine-is-updated
=> Fix CDSS alert not dismissing after modifying medicines

CHANGELOG.md, app/src/main/java/org/simple/clinic/scanid/ScanSimpleIdScreen.kt
=> Set target aspect ration and rotation for QR code scanner preview

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/download/OverdueListDownloaderIntegrationTest.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueListDownloader.kt
https://app.shortcut.com/simpledotorg/story/8651/use-overduelistdownloader-for-generating-overdue-patients-csv-or-pdf-using-overduecsvgenerator
=> Use `OverdueListDownloader` for generating overdue patients CSV or PDF using `OverdueCsvGenerator`

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueAppointmentSearchListItem.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/res/layout/list_item_overdue_patient.xml
https://app.shortcut.com/simpledotorg/story/8628/show-a-checkbox-when-select-overdue-patients-feature-flag-is-enable
=> Show a checkbox when select overdue patients feature flag is enable

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItemNew.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUi.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUiRenderer.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8655/handle-selected-state-in-overdue-screen
=> Handle selected overdue appointments state in overdue screen

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/download/OverdueListDownloaderIntegrationTest.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueDownloadScheduler.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueDownloadWorker.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueListDownloader.kt
https://app.shortcut.com/simpledotorg/story/8665/add-support-for-selected-overdue-appointments-download
=> Add support for selected overdue appointments download

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueModel.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUi.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUiRenderer.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/main/res/layout/screen_overdue.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, app/src/test/java/org/simple/clinic/home/overdue/OverdueUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8658/show-selected-overdue-appointments-count-in-overdue-screen
=> Show selected overdue appointments count in overdue screen

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/download/OverdueCsvGeneratorTest.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueCsvGenerator.kt
https://app.shortcut.com/simpledotorg/story/8679/handle-nullable-fields-when-generating-overdue-csv-from-database
=> Handle nullable fields when generating overdue CSV from database

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8656/add-support-for-selected-download-and-share-in-overdue-screen
=> [1/2] Add support for selected download and share in overdue screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUiActions.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueViewEffectHandler.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/OpenAs.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffect.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffectHandler.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatInit.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUiRenderer.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt, app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatInitTest.kt, app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUiRendererTest.kt, app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8656/add-support-for-selected-download-and-share-in-overdue-screen
=> [2/2] Add support for selected download and share in overdue screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModel.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/main/res/layout/screen_overdue_search.xml, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8668/show-selected-overdue-appointments-count-in-overdue-search-screen
=> Show selected overdue appointments count in overdue search screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/overdue/OverdueAppointmentSelector.kt, app/src/test/java/org/simple/clinic/overdue/OverdueAppointmentSelectorTest.kt
https://app.shortcut.com/simpledotorg/story/8713/implement-overdueappointmentselector
=> Implement `OverdueAppointmentSelector`

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/main/java/org/simple/clinic/overdue/OverdueAppointmentSelector.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueDownloadScheduler.kt, app/src/main/java/org/simple/clinic/overdue/download/OverdueDownloadWorker.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffect.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffectHandler.kt, app/src/main/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt, app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/overdue/download/formatdialog/SelectOverdueDownloadFormatUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8716/use-overdue-appointment-selector-to-fetch-selected-ids-in-overdue-list-download-worker
=> Use overdue appointment selector to fetch selected ids in overdue download worker

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUiActions.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueUpdate.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueViewEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModel.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/OverdueUpdateTest.kt
=> Remove unnecessary code in overdue screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8650/continue-with-current-action-when-not-now-is-clicked-in-measurement-warning-dialog
=> Continue with current action when not now is clicked in measurement warning dialog

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiActions.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchViewEffectHandler.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8657/add-support-for-selected-download-and-share-in-overdue-search-screen
=> Add support for select and download in overdue search screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueButtonType.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiActions.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchViewEffectHandler.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8657/add-support-for-selected-download-and-share-in-overdue-search-screen
=> Add support for select and share in overdue search screen

CHANGELOG.md, app/src/main/res/layout/list_item_overdue_patient.xml
https://app.shortcut.com/simpledotorg/story/8693/update-overdue-patient-card-spacings
=> Update overdue patient card spacings

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueAppointmentSearchListItem.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/main/res/layout/list_item_search_overdue_select_all_button.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8677/add-support-for-selecting-all-overdue-appointment-search-results
=> Add support for selecting all overdue appointment search results

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
https://app.shortcut.com/simpledotorg/story/8771/search-results-appointments-are-not-getting-fully-downloaded-shared-selected
=> Implement `AppointmentRepository#searchOverduePatientsImmediate`

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueButtonType.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8771/fix-search-results-appointments-not-getting-fully-downloaded-shared-selected
=> Fix search results appointments not getting fully downloaded/shared/selected

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueAppointmentSearchListItem.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8771/fix-search-results-appointments-not-getting-fully-downloaded-shared-selected
=> Remove unused code from overdue search

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt
=> Add overdue patients select and download feature flag key

CHANGELOG.md, app/src/main/java/org/simple/clinic/widgets/Views.kt
https://app.shortcut.com/simpledotorg/story/8491/fix-app-crashing-when-editing-patient-details
=> Fix app crashing when editing patient details

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueAppointmentSearchListItem.kt
https://app.shortcut.com/simpledotorg/story/8787/fix-overdue-search-not-displaying-no-patients-found-error-view
=> Fix overdue search not displaying no patients found error view

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt
https://app.shortcut.com/simpledotorg/story/8791/update-select-and-download-feature-flag-key-to-v2
=> Update select and download feature flag key to v2

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt
=> Add overdue search v2 feature flag

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
https://app.shortcut.com/simpledotorg/story/8768/implement-type-ahead-search-suggestions-for-overdue-search
=> Implement query to fetch village and patient names in the facility

CHANGELOG.md, app/src/main/java/org/simple/clinic/widgets/ChipInputAutoCompleteTextView.kt, app/src/main/res/layout/view_chip_text_input.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/theme_overlay.xml
https://app.shortcut.com/simpledotorg/story/8821/add-custom-text-field-component-with-chip-input
=> Add custom text field component with chip input

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchModel.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt, app/src/main/res/layout/screen_overdue_search.xml, app/src/main/res/layout/view_overdue_search_suggestion.xml, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8769/display-search-suggestions-in-the-overdue-search-screen
=> Display search suggestions after loading in overdue search screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEvent.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchInit.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchInitTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8768/implement-type-ahead-search-suggestions-for-overdue-search
=> Load village and patient names when overdue search screen is created

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffect.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUi.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiActions.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdate.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchViewEffectHandler.kt, app/src/main/java/org/simple/clinic/util/PagerFactory.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8830/fix-overdue-search-not-searching-on-query-changes
=> Fix overdue search not searching on query changes

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/res/layout/screen_overdue_search.xml
https://app.shortcut.com/simpledotorg/story/8835/show-chip-input-text-view-in-overdue-search-when-overdue-v2-search-is-enabled
=> Show chip input text view in overdue search when overdue v2 search is enabled

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/benchmark/overdue/OverdueBenchmark.kt, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandler.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/8770/implement-overdue-search-query-to-support-multiple-search-inputs
=> Add overdue search query for supporting multiple search inputs

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/drugs/PrescriptionRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt, app/src/main/java/org/simple/clinic/drugs/PrescriptionRepository.kt
https://app.shortcut.com/simpledotorg/story/8890/run-prescription-refill-queries-in-a-transaction
=> Run prescription refill queries in a transaction

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/EditMedicinesEffectHandler.kt, app/src/test/java/org/simple/clinic/drugs/EditMedicineEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/EditMedicinesScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/8890/run-prescription-refill-queries-in-a-transaction
=> Use `PrescriptionRepository#refill` to refill prescriptions from edit medicines screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordEffectHandler.kt, app/src/test/java/org/simple/clinic/teleconsultlog/teleconsultrecord/screen/TeleconsultRecordEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/8890/run-prescription-refill-queries-in-a-transaction
=> Use `PrescriptionRepository#refillForTeleconsulation` to refill prescriptions from teleconsult screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreen.kt, app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenEffect.kt, app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenEffectHandler.kt, app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenEvent.kt, app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenInit.kt, app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenUpdate.kt, app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenViewEffectHandler.kt, app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUpdateTest.kt, app/src/test/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenInitTest.kt, app/src/test/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/7992/migrate-bloodsugarhistoryscreeneffecthandler-to-use-view-effects
=> Migrate `BloodSugarHistoryScreen` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffect.kt, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffectHandler.kt, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEvent.kt, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenInit.kt, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUpdate.kt, app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenInitTest.kt, app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/7985/migrate-bloodpressurehistoryscreeneffecthandler-to-use-view-effects
=> Add separate effects for loading and showing blood pressure history

CHANGELOG.md, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreen.kt, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffect.kt, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffectHandler.kt, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryViewEffectHandler.kt, app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/7985/migrate-bloodpressurehistoryscreeneffecthandler-to-use-view-effects
=> Migrate `BloodPressureHistoryScreenEffectHandler` to use view effect

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffect.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientEffectHandler.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientViewEffectHandler.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/7984/migrate-contactpatienteffecthandler-to-use-view-effects
=> Migrate `ContactPatientBottomSheet` to use view effects

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/updatephone/UpdatePhoneNumberDialog.kt
https://app.shortcut.com/simpledotorg/story/8917/migrate-updatephonenumberdialog-to-basedialog
=> Migrate `UpdatePhoneNumberDialog` to `BaseDialog`

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/addphone/AddPhoneNumberDialog.kt
https://app.shortcut.com/simpledotorg/story/8916/migrate-addphonenumberdialog-to-basedialog
=> Migrate `AddPhoneNumberDialog` to `BaseDialog`

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRenderer.kt, app/src/test/java/org/simple/clinic/home/overdue/search/OverdueSearchUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/8923/fix-download-share-button-showing-in-overdue-search-screen-outside-india
=> Fix download/share button showing in overdue search screen outside India

CHANGELOG.md, app/src/main/java/org/simple/clinic/navigation/v2/fragments/BaseDialog.kt, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt, app/src/main/java/org/simple/clinic/registration/phone/loggedout/LoggedOutOfDeviceDialog.kt
https://app.shortcut.com/simpledotorg/story/8914/migrate-loggedoutofdevicedialog-to-basedialog
=> Migrate `LoggedOutOfDeviceDialog` to `BaseDialog`

CHANGELOG.md, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntrySheet.kt, app/src/main/java/org/simple/clinic/bloodsugar/unitselection/BloodSugarUnitSelectionDialog.kt
https://app.shortcut.com/simpledotorg/story/8903/migrate-bloodsugarunitselectiondialog-to-basedialog
=> Migrate `BloodSugarUnitSelectionDialog` to use `BaseDialog`

CHANGELOG.md, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntrySheet.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/confirmremovebloodsugar/ConfirmRemoveBloodSugarDialog.kt
https://app.shortcut.com/simpledotorg/story/8902/migrate-confirmremovebloodsugardialog-to-basedialog
=> Migrate `ConfirmRemoveBloodSugarDialog` to `BaseDialog`

CHANGELOG.md, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryQuestion.kt, app/src/main/java/org/simple/clinic/medicalhistory/OngoingMedicalHistoryEntry.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRenderer.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryView.kt, app/src/main/res/values-en-rLK/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRendererTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryLogicTest.kt, app/src/test/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/8959/fix-hypertension-treatment-question-showing-sri-lanka-translation-in-india
Most of the changes are related to converting `MedicalHistoryQuestion` enum class to a sealed class. Important change is `IsOnHypertensionTreatment` question requires an country code to select the appropriate question string.
=> Fix hypertension treatment question showing Sri Lanka translation in India

CHANGELOG.md, app/src/main/res/layout/medicalhistory_summary_view.xml, app/src/main/res/layout/patientsummary_assigned_facility_content.xml, app/src/main/res/layout/patientsummary_next_appointment_card.xml
https://app.shortcut.com/simpledotorg/story/8958/fix-spacing-in-the-patient-summary-cards
=> Fix spacing in the patient summary cards

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt
https://app.shortcut.com/simpledotorg/story/9051/fix-overdue-count-in-the-app-not-matching-with-the-count-from-the-dashboard
=> Fix overdue count in the app not matching with the count from the dashboard

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentRepository.kt
https://app.shortcut.com/simpledotorg/story/8956/fix-appointment-sheet-showing-after-follow-up-visit-is-added
=> Fix appointment sheet showing after follow-up visit is added

CHANGELOG.md, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchInit.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchInitTest.kt
https://app.shortcut.com/simpledotorg/story/9121/fix-id-search-from-the-scan-screen-not-working
=> Fix ID search not working from scan screen

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/105.json, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration105AndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResult.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_105.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt, app/src/test/java/org/simple/clinic/contactpatient/ContactPatientEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueEffectHandlerTest.kt, sharedTestCode/src/main/java/org/simple/sharedTestCode/TestData.kt
https://app.shortcut.com/simpledotorg/story/9058/add-sync-support-for-pulling-overdue-call-results
=> Add `patientId` and `facilityId` columns in `CallResult` table 

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/sync/CallResultSyncIntegrationTest.kt, app/src/main/java/org/simple/clinic/main/TypedPreference.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResult.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResultPayload.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResultPullResponse.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResultRepository.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResultSync.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResultSyncApi.kt, app/src/main/java/org/simple/clinic/overdue/callresult/di/CallResultModule.kt
https://app.shortcut.com/simpledotorg/story/9058/add-sync-support-for-pulling-overdue-call-results
=> Add sync support for pulling overdue call results

app/src/main/java/org/simple/clinic/plumbing/infrastructure/MixpanelInfrastructure.kt
This was missed in the previous PR that enable tracking automatic events on Mixpanel
=> Enable tracking automatic events on Mixpanel

CHANGELOG.md, app/src/main/java/org/simple/clinic/ReleaseClinicApp.kt, app/src/main/java/org/simple/clinic/analytics/MixpanelAnalyticsReporter.kt
https://app.shortcut.com/simpledotorg/story/9052/reduce-number-of-events-pushed-to-mixpanel
=> Sample events sent to Mixpanel

.github/workflows/maestro_tests.yml, CHANGELOG.md
https://app.shortcut.com/simpledotorg/story/9184/add-ui-test-for-login-flow
=> Add github action to verify maestro tests

.github/workflows/maestro_tests.yml, CHANGELOG.md
https://app.shortcut.com/simpledotorg/story/9184/add-ui-test-for-login-flow
=> Add github action to verify maestro tests (#4245)

.github/workflows/maestro_tests.yml, CHANGELOG.md, app/build.gradle.kts, app/src/main/res/layout/screen_selectcountry.xml, gradle.properties, uiFlows/login_flow.yaml
https://app.shortcut.com/simpledotorg/story/9184/add-ui-test-for-login-flow
=> Add github action to run maestro UI test

.github/workflows/maestro_tests.yml
https://app.shortcut.com/simpledotorg/story/9184/add-ui-test-for-login-flow
=> Fix multiline in yaml file of Maestro gtihub action script

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientLineListRow.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
https://app.shortcut.com/simpledotorg/story/9216/add-query-to-generate-patient-line-list-data
=> Add query to fetch patient line list data

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientLineListRow.kt
Added missing fields in `PatientLineListRow`. These fields are required for generating the patient line list CSV
=> Add missing fields in `PatientLineListRow`

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/patient/download/PatientLineListDownloaderTest.kt, app/src/main/java/org/simple/clinic/patient/download/PatientLineListDownloadResult.kt, app/src/main/java/org/simple/clinic/patient/download/PatientLineListDownloader.kt, app/src/main/java/org/simple/clinic/patient/download/PatientLineListFileFormat.kt
https://app.shortcut.com/simpledotorg/story/9218/implement-downloader-for-patient-line-list
=> Add patient line list downloader

CHANGELOG.md, app/src/main/java/org/simple/clinic/di/AppComponent.kt, app/src/main/java/org/simple/clinic/patient/download/PatientLineListScheduler.kt, app/src/main/java/org/simple/clinic/patient/download/PatientLinetListDownloadWorker.kt, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/9219/add-background-worker-for-downloading-patient-line-list
=> Add background worker for downloading patient line list

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/patient/download/PatientLineListCsvGeneratorTest.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/patient/download/PatientLineListCsvGenerator.kt, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/9273/use-paginated-data-for-generating-patient-line-list
=> Use paginated data for generating patient line list CSV

CHANGELOG.md, app/src/main/java/org/simple/clinic/util/CsvToPdfConverter.kt
https://app.shortcut.com/simpledotorg/story/9273/use-paginated-data-for-generating-patient-line-list
=> Enable large table support when converting CSV to PDF

CHANGELOG.md, app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt, app/src/main/java/org/simple/clinic/patient/download/formatdialog/SelectLineListFormatDialog.kt, app/src/main/java/org/simple/clinic/patient/download/formatdialog/SelectLineListFormatModel.kt, app/src/main/res/layout/dialog_select_line_list_format.xml, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/9221/add-patient-line-list-download-dialog
=> Add select line list format dialog

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsEffectHandler.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsInit.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEffect.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabEvent.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabModel.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUi.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUiActions.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUiRenderer.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabUpdate.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabViewEffectHandler.kt, app/src/main/res/drawable/ic_download_24dp.xml, app/src/main/res/layout/item_patient_line_list_download_card.xml, app/src/main/res/layout/recent_patients.xml, app/src/main/res/layout/screen_patients.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/home/patients/PatientsEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsInitTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsLogicTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsTabUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/patients/PatientsTabUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/9222/add-patient-line-list-download-card-in-patientstabscreen
=> Add patient line list download card in patients screen

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt
https://app.shortcut.com/simpledotorg/story/9281/fix-patient-line-list-not-showing-assigned-facility-name
=> Fix patient line list not showing assigned facility name

CHANGELOG.md, app/src/main/java/org/simple/clinic/patient/Patient.kt
- Filter out deleted patients
- Use latest phone number that is not deleted
- Use latest recorded BP
=> Update patient line list query

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt
https://app.shortcut.com/simpledotorg/story/9348/enable-patient-line-list-download-only-in-india
=> Enable patient line list feature for Indian users only

CHANGELOG.md, app/src/main/res/layout/screen_select_facility.xml
https://app.shortcut.com/simpledotorg/story/9361/show-all-the-facilities-in-the-state-when-changing-assigned-facility-for-a-patient
=> Show all facilities in the state when changing assigned or appointment facility

CHANGELOG.md, app/build.gradle.kts, app/lint.xml, app/src/main/AndroidManifest.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/theme_overlay.xml, app/src/tamilNadu/res/values/styles.xml, app/src/tamilNadu/res/values/theme.xml, app/src/tamilNadu/res/values/theme_overlay.xml
https://app.shortcut.com/simpledotorg/story/9358/update-color-scheme-to-support-thanks-app
=> Add color scheme for Tamil Nadu app

CHANGELOG.md, app/src/main/AndroidManifest.xml, app/src/main/java/org/simple/clinic/home/HomeScreen.kt, app/src/main/java/org/simple/clinic/home/HomeScreenEvent.kt, app/src/main/java/org/simple/clinic/home/HomeScreenUpdate.kt, app/src/test/java/org/simple/clinic/home/HomeScreenUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/9380/request-notification-permission-on-devices-running-android-13
=> Request notification permission on devices running Android 13

CHANGELOG.md, app/build.gradle.kts, app/src/tamilnadu/google-services.json
https://app.shortcut.com/simpledotorg/story/9355/add-a-product-flavour-for-thanks-app
=> Add product flavor to support Tamil Nadu app

CHANGELOG.md, app/src/main/java/org/simple/clinic/patient/onlinelookup/api/LookupPatientOnline.kt
Added custom message to make it easy to identify this in our Sentry logs
=> Update patient lookup exception message when reporting

CHANGELOG.md, app/src/debug/java/org/simple/clinic/registration/RegistrationConfigModule.kt, app/src/main/java/org/simple/clinic/registration/RegistrationConfig.kt, app/src/main/java/org/simple/clinic/registration/RegistrationModule.kt, app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionEffect.kt, app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt, app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionUiActions.kt, app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionUpdate.kt, app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionViewEffectHandler.kt, app/src/production/java/org/simple/clinic/registration/RegistrationConfigModule.kt, app/src/sandbox/java/org/simple/clinic/registration/RegistrationConfigModule.kt, app/src/security/java/org/simple/clinic/registration/RegistrationConfigModule.kt, app/src/staging/java/org/simple/clinic/registration/RegistrationConfigModule.kt, app/src/tamilNadu/java/org/simple/clinic/registration/RegistrationConfigModule.kt, app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionLogicTest.kt, app/src/test/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/9478/hide-intro-video-screen-for-tamil-nadu-app
=> Show intro video screen based on registration config flag

doc/ui-testing-with-maestro.md
Add document for UI testing with Maestro framework
=> Add document for UI testing with Maestro

CHANGELOG.md, app/src/tamilNadu/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/9498/update-app-name-to-dph-thanks
=> Update Tamil Nadu app name

renovate.json5
Set renovate dependency update check frequency to monthly
=> Set dependency update check frequency to monthly

CHANGELOG.md, app/src/debug/res/values-hi-rIN/strings.xml, app/src/debug/res/values-pa/strings.xml, app/src/debug/res/values/strings.xml, app/src/main/res/values-am-rET/strings.xml, app/src/main/res/values-bn-rBD/strings.xml, app/src/main/res/values-bn-rIN/strings.xml, app/src/main/res/values-hi-rIN/strings.xml, app/src/main/res/values-kn-rIN/strings.xml, app/src/main/res/values-mr-rIN/strings.xml, app/src/main/res/values-om-rET/strings.xml, app/src/main/res/values-pa-rIN/strings.xml, app/src/main/res/values-si-rLK/strings.xml, app/src/main/res/values-sid-rET/strings.xml, app/src/main/res/values-so-rET/strings.xml, app/src/main/res/values-ta-rIN/strings.xml, app/src/main/res/values-ta-rLK/strings.xml, app/src/main/res/values-te-rIN/strings.xml, app/src/main/res/values-ti-rET/strings.xml, app/src/main/res/values/strings.xml
Remove `app_name` form translated strings and make it untranslatable
=> Make app name untranslatable

CHANGELOG.md, doc/mobius/implementing-a-new-screen.md
https://app.shortcut.com/simpledotorg/story/9765/update-adding-a-new-screen-document
=> Update adding a new screen document

CHANGELOG.md, app/src/main/java/org/simple/clinic/bloodsugar/unitselection/BloodSugarUnitSelectionDialog.kt, app/src/main/java/org/simple/clinic/bloodsugar/unitselection/BloodSugarUnitSelectionEffect.kt, app/src/main/java/org/simple/clinic/bloodsugar/unitselection/BloodSugarUnitSelectionEffectHandler.kt, app/src/main/java/org/simple/clinic/bloodsugar/unitselection/BloodSugarUnitSelectionViewEffectHandler.kt, app/src/test/java/org/simple/clinic/bloodsugar/unitselection/BloodSugarUnitSelectionEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/7991/migrate-bloodsugarunitselectioneffecthandler-to-use-view-effects
=> Migrate `BloodSugarUnitSelectionDialog` to use view effects

doc/mobius/implementing-a-new-screen.md
https://app.shortcut.com/simpledotorg/story/9765/update-adding-a-new-screen-document
=> Update adding a new screen document #2

.github/workflows/benchmark_suite.yml, .github/workflows/ci_checks.yml, .github/workflows/maestro_tests.yml, .github/workflows/trigger_release.yml, CHANGELOG.md
Fix Heroku integration with the CI.
=> Fix Heroku integration with the CI.

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/sync/QuestionnaireResponseSyncIntegrationTest.kt, app/src/main/java/org/simple/clinic/main/TypedPreference.kt, app/src/main/java/org/simple/clinic/questionnaireresponse/QuestionnaireResponse.kt, app/src/main/java/org/simple/clinic/questionnaireresponse/di/QuestionnaireResponseModule.kt, app/src/main/java/org/simple/clinic/questionnaireresponse/sync/QuestionnaireResponsePullResponse.kt, app/src/main/java/org/simple/clinic/questionnaireresponse/sync/QuestionnaireResponsePushRequest.kt, app/src/main/java/org/simple/clinic/questionnaireresponse/sync/QuestionnaireResponseSync.kt, app/src/main/java/org/simple/clinic/questionnaireresponse/sync/QuestionnaireResponseSyncApi.kt, app/src/test/java/org/simple/clinic/monthlyscreeningreports/form/QuestionnaireEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/monthlyscreeningreports/form/QuestionnaireEntryInitTest.kt, app/src/test/java/org/simple/clinic/monthlyscreeningreports/form/QuestionnaireEntryUiRendererTest.kt, app/src/test/java/org/simple/clinic/monthlyscreeningreports/form/QuestionnaireEntryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/9558/add-sync-resource-for-questionnaire-responseapi
=> Questionnaire response sync resource added

app/src/main/res/layout/patients_tab_link_view.xml, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/10244/move-enter-drug-stock-to-the-link-section
=> Strings added for monthly drug stock report

app/src/main/java/org/simple/clinic/monthlyscreeningreports/complete/MonthlyScreeningReportCompleteScreen.kt, app/src/main/java/org/simple/clinic/monthlyscreeningreports/form/QuestionnaireEntryScreen.kt, app/src/main/java/org/simple/clinic/monthlyscreeningreports/list/MonthlyScreeningReportItem.kt, app/src/main/res/layout/patients_tab_link_view.xml, app/src/main/res/layout/screen_monthly_screening_report_complete.xml, app/src/main/res/layout/screen_questionnaire_entry_form.xml, app/src/main/res/values-am-rET/strings.xml, app/src/main/res/values-bn-rBD/strings.xml, app/src/main/res/values-bn-rIN/strings.xml, app/src/main/res/values-hi-rIN/strings.xml, app/src/main/res/values-kn-rIN/strings.xml, app/src/main/res/values-mr-rIN/strings.xml, app/src/main/res/values-om-rET/strings.xml, app/src/main/res/values-pa-rIN/strings.xml, app/src/main/res/values-si-rLK/strings.xml, app/src/main/res/values-sid-rET/strings.xml, app/src/main/res/values-so-rET/strings.xml, app/src/main/res/values-ta-rIN/strings.xml, app/src/main/res/values-ta-rLK/strings.xml, app/src/main/res/values-te-rIN/strings.xml, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/10244/move-enter-drug-stock-to-the-link-section
=> Strings added for monthly supplies report

app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt, app/src/main/java/org/simple/clinic/util/moshi/MapWithAnyValueTypeMoshiAdapter.kt, app/src/main/java/org/simple/clinic/util/room/MapRoomTypeConverter.kt, gradle/libs.versions.toml
https://app.shortcut.com/simpledotorg/story/10252/form-response-is-sent-as-float-decimal-for-int-types
=> Stopped unwanted conversion of int values to decimal

CHANGELOG.md, app/src/main/java/org/simple/clinic/settings/SettingsModule.kt
https://app.shortcut.com/simpledotorg/story/10374/add-spanish-language-change-button-to-mobile-app
=> Added Espanol language in supported languages

.github/scripts/setup_heroku_instance.sh, .github/workflows/auto_request_review.yml, .github/workflows/ci_checks.yml, .github/workflows/cleanup_heroku_review_apps.yml, .github/workflows/cut_release_branch.yml, .github/workflows/trigger_release.yml
https://app.shortcut.com/simpledotorg/story/10317/pin-floating-versions-across-server-mobile
=> Pin floating versions

app/src/main/res/layout/screen_monthly_reports.xml, app/src/main/res/values-am-rET/strings.xml
Monthly screening report translations update for Amharic language.
=> Monthly screening report translations update

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt
https://app.shortcut.com/simpledotorg/story/10567/enable-clinical-decision-support-for-all-facilities-in-ethiopia
=> Enable clinical decision support for all facilities in Ethiopia

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/sync/SyncModule.kt
https://app.shortcut.com/simpledotorg/story/10661/remove-feature-flag-from-the-code-for-questionnaire-sync-api-s
=> Remove firebase config logic for loading questionnaire's api

CHANGELOG.md, app/src/main/java/org/simple/clinic/bloodsugar/unitselection/BloodSugarUnitSelectionDialog.kt
https://app.shortcut.com/simpledotorg/story/10675/fix-blood-sugars-saving-twice-when-blood-sugar-unit-is-updated
=> Fix blood sugar saving twice when blood sugar measurement unit is changed

CHANGELOG.md, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffect.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntrySheet.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUi.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryUiActions.kt, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryViewEffectHandler.kt, app/src/test/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntryEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/7994/migrate-bloodsugarentryeffecthandler-to-use-view-effects
=> Migrate `BloodSugarEntryEffectHandler` to use view effect

CHANGELOG.md, app/build.gradle.kts, app/src/androidTest/java/org/simple/clinic/appconfig/SelectedCountryPersistenceAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/di/TestStorageModule.kt, app/src/androidTest/java/org/simple/clinic/rules/ServerAuthenticationRule.kt, app/src/androidTest/java/org/simple/clinic/rules/ServerRegistrationAtFacilityRule.kt, app/src/androidTest/java/org/simple/clinic/storage/DatabaseEncryptionTest.kt, app/src/androidTest/java/org/simple/clinic/storage/DatabaseEncryptorTest.kt, app/src/androidTest/java/org/simple/clinic/user/RegisterUserServerIntegrationTest.kt, app/src/androidTest/java/org/simple/clinic/user/UserDaoAndroidTest.kt, app/src/main/java/org/simple/clinic/ClinicApp.kt, app/src/main/java/org/simple/clinic/Globals.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityEffect.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityEffectHandler.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityEvent.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityInit.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityUpdate.kt, app/src/main/java/org/simple/clinic/storage/DatabaseEncryption.kt, app/src/main/java/org/simple/clinic/storage/DatabaseEncryptor.kt, app/src/main/java/org/simple/clinic/storage/EncryptionModule.kt, app/src/main/java/org/simple/clinic/storage/SharedPreferencesModule.kt, app/src/main/java/org/simple/clinic/storage/StorageModule.kt, app/src/main/java/org/simple/clinic/user/UserSession.kt, app/src/test/java/org/simple/clinic/setup/SetupActivityEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/setup/SetupActivityInitTest.kt, app/src/test/java/org/simple/clinic/setup/SetupActivityUpdateTest.kt, gradle/libs.versions.toml
https://app.shortcut.com/simpledotorg/story/10755/encrypt-app-database
=> Add support for database encryption

CHANGELOG.md, app/src/main/java/org/simple/clinic/contactpatient/RemoveAppointmentReason.kt, app/src/main/java/org/simple/clinic/overdue/AppointmentCancelReason.kt, app/src/main/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueEffect.kt, app/src/main/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueEffectHandler.kt, app/src/main/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueUpdate.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/removeoverdueappointment/RemoveOverdueUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/10033/include-new-result-of-call-option-refused-to-come-back-app-side
=> Add "refused to come back" appointment cancel reason

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/di/TestAppModule.kt, app/src/main/java/org/simple/clinic/analytics/UpdateAnalyticsUserId.kt, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/plumbing/infrastructure/DatadogInfrastructure.kt, app/src/main/java/org/simple/clinic/plumbing/infrastructure/Infrastructure.kt, app/src/main/java/org/simple/clinic/plumbing/infrastructure/MixpanelInfrastructure.kt, app/src/main/java/org/simple/clinic/plumbing/infrastructure/SentryInfrastructure.kt, app/src/main/java/org/simple/clinic/plumbing/infrastructure/UpdateInfrastructureUserDetails.kt, app/src/main/java/org/simple/clinic/settings/SettingsEffect.kt, app/src/main/java/org/simple/clinic/settings/SettingsEffectHandler.kt, app/src/main/java/org/simple/clinic/settings/SettingsEvent.kt, app/src/main/java/org/simple/clinic/settings/SettingsScreen.kt, app/src/main/java/org/simple/clinic/settings/SettingsUpdate.kt, app/src/main/java/org/simple/clinic/settings/SettingsViewEffectHandler.kt, app/src/main/java/org/simple/clinic/settings/UiActions.kt, app/src/main/java/org/simple/clinic/user/UserSession.kt, app/src/main/res/layout/screen_settings.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/plumbing/infrastructure/FakeInfrastructure.kt, app/src/test/java/org/simple/clinic/plumbing/infrastructure/UpdateInfrastructureUserDetailsTest.kt, app/src/test/java/org/simple/clinic/settings/SettingsEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/settings/SettingsUpdateTest.kt, app/src/test/java/org/simple/clinic/user/UserSessionTest.kt
https://app.shortcut.com/simpledotorg/story/9989/add-option-to-logout-of-the-app-in-settings
=> Add option to logout of the app in settings

CHANGELOG.md, app/src/main/java/org/simple/clinic/settings/SettingsEffect.kt, app/src/main/java/org/simple/clinic/settings/SettingsEffectHandler.kt, app/src/main/java/org/simple/clinic/settings/SettingsEvent.kt, app/src/main/java/org/simple/clinic/settings/SettingsInit.kt, app/src/main/java/org/simple/clinic/settings/SettingsModel.kt, app/src/main/java/org/simple/clinic/settings/SettingsScreen.kt, app/src/main/java/org/simple/clinic/settings/SettingsUi.kt, app/src/main/java/org/simple/clinic/settings/SettingsUiRenderer.kt, app/src/main/java/org/simple/clinic/settings/SettingsUpdate.kt, app/src/main/res/drawable/ic_lock_16dp.xml, app/src/main/res/layout/screen_settings.xml, app/src/test/java/org/simple/clinic/settings/SettingsEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/settings/SettingsInitTest.kt, app/src/test/java/org/simple/clinic/settings/SettingsUiRendererTest.kt, app/src/test/java/org/simple/clinic/settings/SettingsUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/10890/display-icon-to-indicate-app-database-encryption-status-in-settings
=> Display icon to indicate app database encryption status in settings

CHANGELOG.md, app/src/main/java/org/simple/clinic/monthlyreports/form/QuestionnaireEntryScreen.kt, app/src/main/java/org/simple/clinic/monthlyreports/form/compose/QuestionnaireInputField.kt, app/src/main/java/org/simple/clinic/monthlyreports/form/compose/util/TextFieldUtil.kt, app/src/main/java/org/simple/clinic/widgets/montyeardatepicker/MonthYearPickerDialog.kt, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/10889/add-date-picker-component-to-questionnaire-forms
=> Add month and year picker dialog for Compose forms

CHANGELOG.md, app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt, app/src/main/java/org/simple/clinic/monthlyreports/form/compose/QuestionnaireDateInputField.kt, app/src/main/java/org/simple/clinic/monthlyreports/form/compose/QuestionnaireInputField.kt, app/src/main/java/org/simple/clinic/monthlyreports/form/compose/QuestionnaireInputGroup.kt, app/src/main/java/org/simple/clinic/questionnaire/component/InputFieldComponentData.kt, app/src/main/java/org/simple/clinic/questionnaire/component/properties/InputFieldType.kt, app/src/main/java/org/simple/clinic/questionnaire/component/properties/InputFieldValidations.kt, app/src/main/java/org/simple/clinic/questionnaire/component/properties/InputFieldViewType.kt, app/src/main/java/org/simple/clinic/widgets/montyeardatepicker/MonthYearPickerDialog.kt, sharedTestCode/src/main/java/org/simple/sharedTestCode/TestData.kt
https://app.shortcut.com/simpledotorg/story/10889/add-date-picker-component-to-questionnaire-forms
=> Add support for date input field for Compose forms

CHANGELOG.md, app/src/main/java/org/simple/clinic/home/patients/links/PatientsTabLinkEffect.kt, app/src/main/java/org/simple/clinic/home/patients/links/PatientsTabLinkEffectHandler.kt, app/src/main/java/org/simple/clinic/home/patients/links/PatientsTabLinkEvent.kt, app/src/main/java/org/simple/clinic/home/patients/links/PatientsTabLinkModel.kt, app/src/main/java/org/simple/clinic/home/patients/links/PatientsTabLinkUi.kt, app/src/main/java/org/simple/clinic/home/patients/links/PatientsTabLinkUiActions.kt, app/src/main/java/org/simple/clinic/home/patients/links/PatientsTabLinkUiRenderer.kt, app/src/main/java/org/simple/clinic/home/patients/links/PatientsTabLinkUpdate.kt, app/src/main/java/org/simple/clinic/home/patients/links/PatientsTabLinkView.kt, app/src/main/java/org/simple/clinic/monthlyreports/form/QuestionnaireEntryScreen.kt, app/src/main/java/org/simple/clinic/monthlyreports/list/MonthlyReportsScreen.kt, app/src/main/java/org/simple/clinic/questionnaire/QuestionnaireResponseSections.kt, app/src/main/java/org/simple/clinic/questionnaire/QuestionnaireSections.kt, app/src/main/java/org/simple/clinic/questionnaire/QuestionnaireType.kt, app/src/main/java/org/simple/clinic/questionnaire/sync/QuestionnaireSyncApi.kt, app/src/main/res/layout/patients_tab_link_view.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/home/patients/links/PatientsTabLinkEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/home/patients/links/PatientsTabLinkUiRendererTest.kt, app/src/test/java/org/simple/clinic/home/patients/links/PatientsTabLinkUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/10917/show-drug-stock-report-link-in-patients-tab
=> Add link to report drug stock in patients tab

CHANGELOG.md, app/src/main/java/org/simple/clinic/di/AppModule.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityEffect.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityEffectHandler.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityEvent.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityInit.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityUpdate.kt, app/src/main/java/org/simple/clinic/storage/StorageModule.kt, app/src/main/java/org/simple/clinic/util/MinimumMemoryChecker.kt, app/src/test/java/org/simple/clinic/setup/SetupActivityEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/setup/SetupActivityInitTest.kt, app/src/test/java/org/simple/clinic/setup/SetupActivityUpdateTest.kt, sharedTestCode/src/main/java/org/simple/sharedTestCode/util/TestMinimumMemoryChecker.kt
https://app.shortcut.com/simpledotorg/story/10954/add-memory-check-to-turn-on-encryption
=> Add minimum memory check to support database encryption

app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt, app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt, app/src/main/java/org/simple/clinic/facility/Facility.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResult.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/protocol/Protocol.kt, app/src/main/java/org/simple/clinic/questionnaireresponse/QuestionnaireResponse.kt, app/src/main/java/org/simple/clinic/summary/teleconsultation/sync/TeleconsultationFacilityInfo.kt, app/src/main/java/org/simple/clinic/teleconsultlog/teleconsultrecord/TeleconsultRecord.kt
https://app.shortcut.com/simpledotorg/story/11104/fix-sql-cipher-timeout-exception
=> Use raw SQL queries for UPDATE & DELETE queries that use multiple IDs as param

app/src/test/java/org/simple/clinic/mobius/EffectHandlerTestCase.kt, gradle/libs.versions.toml, renovate.json5
=> Update Kotlin, KSP and Compose Compiler

app/build.gradle.kts, gradle.properties, gradle/libs.versions.toml
=> Migrate Dagger from KAPT to KSP

CHANGELOG.md, app/src/main/java/org/simple/clinic/bloodsugar/entry/BloodSugarEntrySheet.kt, app/src/main/java/org/simple/clinic/contactpatient/ContactPatientBottomSheet.kt, app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntrySheet.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeSheet.kt, app/src/main/java/org/simple/clinic/facility/change/FacilityChangeScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/scheduleappointment/ScheduleAppointmentSheet.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, gradle/wrapper/gradle-wrapper.properties
https://app.shortcut.com/simpledotorg/story/11418/move-fragment-result-listener-to-oncreate-from-onviewcreated
=> Setup fragment result listener in `onCreate` instead of `onViewCreated`

CHANGELOG.md, app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeEffect.kt, app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeEffectHandler.kt, app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeEvent.kt, app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeInit.kt, app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeModel.kt, app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeSheet.kt, app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeUi.kt, app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeUiRenderer.kt, app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeUpdate.kt, app/src/main/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeViewEffectHandler.kt, app/src/main/java/org/simple/clinic/facility/alertchange/UiActions.kt, app/src/test/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeInitTest.kt, app/src/test/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeUiRendererTest.kt, app/src/test/java/org/simple/clinic/facility/alertchange/AlertFacilityChangeUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/11507/fix-app-crashing-when-closing-alert-facility-change-sheet
=> Migrate alert facility change sheet to use Mobius loop

CHANGELOG.md, app/src/main/java/org/simple/clinic/consent/onboarding/OnboardingConsentScreenFragment.kt, app/src/main/java/org/simple/clinic/di/AppModule.kt, app/src/main/java/org/simple/clinic/login/applock/AppLockEffect.kt, app/src/main/java/org/simple/clinic/login/applock/AppLockEffectHandler.kt, app/src/main/java/org/simple/clinic/login/applock/AppLockEvent.kt, app/src/main/java/org/simple/clinic/login/applock/AppLockModel.kt, app/src/main/java/org/simple/clinic/login/applock/AppLockScreen.kt, app/src/main/java/org/simple/clinic/login/applock/AppLockUiActions.kt, app/src/main/java/org/simple/clinic/login/applock/AppLockUpdate.kt, app/src/main/java/org/simple/clinic/login/applock/AppLockViewEffectHandler.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/login/applock/AppLockEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/login/applock/AppLockScreenLogicTest.kt, app/src/test/java/org/simple/clinic/login/applock/AppLockUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/11558/add-consent-dialog-for-existing-users
=> Show data protection consent dialog after entering app lock pin for existing users

.github/scripts/create_heroku_app.sh, .github/scripts/setup_heroku_instance.sh, .github/workflows/ci_checks.yml
https://app.shortcut.com/simpledotorg/story/10796/improve-android-ci-workflow-performance
=> Improve Android CI performance by deploying server and building test APKs in parallel

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/113.json, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration113AndroidTest.kt, app/src/debug/java/org/simple/clinic/FakeDataGenerationReceiver.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/patient/onlinelookup/api/LookupPatientOnline.kt, app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_113.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt, sharedTestCode/src/main/java/org/simple/sharedTestCode/TestData.kt
https://app.shortcut.com/simpledotorg/story/12436/add-ispatienteligbleforreassignment-to-patient-model
=> Add `isPatientEligibleForReassignment` to `Patient` model

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
https://app.shortcut.com/simpledotorg/story/12440/check-and-update-patient-eligibility-status-when-new-blood-pressure-is-created
=> Add function in `PatientRepository` to check if a patient is eligible for reassignment

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEffect.kt, app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryEvent.kt, app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntrySheet.kt, app/src/main/java/org/simple/clinic/bp/entry/BloodPressureEntryUpdate.kt, app/src/main/java/org/simple/clinic/bp/entry/OpenAs.kt, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreen.kt, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenUiActions.kt, app/src/main/java/org/simple/clinic/bp/history/BloodPressureHistoryViewEffectHandler.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewUiActions.kt, app/src/main/java/org/simple/clinic/summary/bloodpressures/view/BloodPressureSummaryView.kt, app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryLogicTest.kt, app/src/test/java/org/simple/clinic/bp/entry/BloodPressureEntryUpdateTest.kt, app/src/test/java/org/simple/clinic/bp/entry/BloodPressureValidationMockDateValidatorTest.kt, app/src/test/java/org/simple/clinic/bp/entry/BloodPressureValidationTest.kt, app/src/test/java/org/simple/clinic/bp/history/BloodPressureHistoryScreenEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/bloodpressures/BloodPressureSummaryViewEffectHandlerTest.kt
https://app.shortcut.com/simpledotorg/story/12440/check-and-update-patient-eligibility-status-when-new-blood-pressure-is-created
=> Update `Patient#isEligibleForReassignment` on BP creation

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/114.json, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration114AndroidTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItem.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchResultsItemType.kt, app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt, app/src/main/java/org/simple/clinic/patient/RecentPatient.kt, app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientItem.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_114.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt, app/src/main/java/org/simple/clinic/widgets/PatientSearchResultItemView.kt, app/src/main/res/drawable/ic_facility_reassignment.xml, app/src/main/res/layout/list_item_overdue_patient.xml, app/src/main/res/layout/recent_patient_item_view.xml, app/src/main/res/layout/view_patient_facility_reassignment_list_item.xml, app/src/main/res/layout/view_patient_search_result.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsLogicTest.kt, sharedTestCode/src/main/java/org/simple/sharedTestCode/TestData.kt
https://app.shortcut.com/simpledotorg/story/12443/show-patient-eligibility-status-in-the-ui
=> Add facility reassignment view to list item

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/summary/ClickAction.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewEffectHandler.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/12525/show-patient-reassignment-sheet-when-done-back-is-clicked-in-patientsummary
=> Show patient reassignment sheet when done/back is clicked in `PatientSummary`

app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewEffectHandler.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/12525/show-patient-reassignment-sheet-when-done-back-is-clicked-in-patientsummary
=> Show patient reassignment sheet on back/done click in `PatientSummaryScreen` - Final

app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItem.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchResultsItemType.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsUiRenderer.kt, app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientItem.kt, app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientsView.kt, app/src/test/java/org/simple/clinic/instantsearch/InstantSearchResultsItemTypeTest.kt, app/src/test/java/org/simple/clinic/recentpatientsview/LatestRecentPatientsLogicTest.kt
https://app.shortcut.com/simpledotorg/story/12537/hide-patient-reassignment-status-in-list-item-when-feature-flag-is-disabled
=> Hide patient reassignment status in list item when feature flag is disabled

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt
https://app.shortcut.com/simpledotorg/story/12588/update-ispatienteligibleforreassignment-query-to-only-check-for-amlodipine-in-prescriptions
=> Check if patient is only prescribed amlodipine in `isPatientEligibleForReassignment`

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/115.json, app/src/androidTest/java/org/simple/clinic/overdue/AppointmentRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration115AndroidTest.kt, app/src/debug/java/org/simple/clinic/FakeDataGenerationReceiver.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/di/network/NetworkModule.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointment.kt, app/src/main/java/org/simple/clinic/home/overdue/OverdueAppointmentListItem.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchResultsItemType.kt, app/src/main/java/org/simple/clinic/patient/Answer.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/patient/PatientSearchResult.kt, app/src/main/java/org/simple/clinic/patient/RecentPatient.kt, app/src/main/java/org/simple/clinic/patient/onlinelookup/api/LookupPatientOnline.kt, app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt, app/src/main/java/org/simple/clinic/recentpatientsview/RecentPatientItem.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_115.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt, sharedTestCode/src/main/java/org/simple/sharedTestCode/TestData.kt
https://app.shortcut.com/simpledotorg/story/12589/change-iseligibleforreassignment-type-to-answer-in-patient-table
=> Change `isEligibleForReassignment` type to `Answer` in `Patient` table

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/patient/PatientRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/patient/PatientRepository.kt, app/src/main/java/org/simple/clinic/patient/sync/PatientPayload.kt, app/src/main/java/org/simple/clinic/patient/sync/PatientSync.kt, sharedTestCode/src/main/java/org/simple/sharedTestCode/TestData.kt
https://app.shortcut.com/simpledotorg/story/12516/add-iseligibleforreassignment-to-patientpayload
=> Add `eligibleForReassignment` to `PatientPayload`

app/src/main/java/org/simple/clinic/summary/DiagnosisWarningResult.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/prescribeddrugs/DrugSummaryView.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/12756/nudge-users-to-mark-diabetes-diagnosis-if-diabetes-medicines-are-added
=> Nudge users to mark diabetes diagnosis if diabetes medicines are added

app/src/debug/google-services.json, app/src/main/java/org/simple/clinic/drugs/DiagnosisWarningPrescriptions.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesEffect.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesEffectHandler.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesEvent.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesModel.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesUpdate.kt, app/src/main/java/org/simple/clinic/drugs/EditMedicinesViewEffectHandler.kt, app/src/main/java/org/simple/clinic/drugs/PrescriptionModule.kt, app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesScreen.kt, app/src/main/java/org/simple/clinic/drugs/selection/EditMedicinesUiActions.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryEffectHandler.kt, app/src/test/java/org/simple/clinic/drugs/EditMedicineEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/drugs/EditMedicineUpdateTest.kt, app/src/test/java/org/simple/clinic/drugs/EditMedicinesInitTest.kt, app/src/test/java/org/simple/clinic/drugs/EditMedicinesUiRendererTest.kt, app/src/test/java/org/simple/clinic/drugs/selection/EditMedicinesScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryLogicTest.kt
https://app.shortcut.com/simpledotorg/story/12758/check-diagnosis-prescriptions-when-exiting-prescriptions-screen
=> Check diagnosis prescriptions when exiting prescriptions screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/drugs/EditMedicinesUpdate.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewEffectHandler.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/drugs/EditMedicineUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/12755/nudge-users-to-mark-htn-diagnosis-if-htn-medicines-are-added
=> Nudge users to mark HTN diagnosis if HTN medicines are added

CHANGELOG.md, app/build.gradle.kts, gradle/libs.versions.toml
https://developer.android.com/guide/playcore#playcore-migration
=> Migrate from Play Core to Play App Update dependency

app/build.gradle.kts, build.gradle.kts, common-ui/build.gradle.kts, gradle.properties, gradle/libs.versions.toml, lint/build.gradle.kts, mobius-base/build.gradle.kts, mobius-migration/build.gradle.kts, settings.gradle.kts, sharedTestCode/build.gradle.kts, simple-platform/build.gradle.kts, simple-visuals/build.gradle.kts
https://app.shortcut.com/simpledotorg/story/12908/migrate-to-using-gradle-plugin-block
=> Migrate to using Gradle plugin block

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/bp/BloodPressureRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureRepository.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/13326/check-patient-statin-nudge-status-when-summary-screen-is-opened
=> Check statin nudge status in patient summary screen

CHANGELOG.md, app/src/main/java/org/simple/clinic/ClinicApp.kt, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/remoteconfig/UpdateFacilityRemoteConfig.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/13365/add-facilities-feature-flag-for-statin-nudge
=> Add feature flag for statin nudge

app/src/main/java/org/simple/clinic/consent/onboarding/OnboardingConsentScreen.kt, app/src/main/java/org/simple/clinic/consent/onboarding/OnboardingConsentViewModel.kt, app/src/main/java/org/simple/clinic/onboarding/OnboardingScreen.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityComponent.kt, app/src/main/java/org/simple/clinic/splash/SplashScreen.kt, common-ui/src/main/java/org/simple/clinic/common/ui/components/FilledButtonWithFrame.kt
https://app.shortcut.com/simpledotorg/story/13784/migrate-onboarding-flow-to-compose-ui
=> Use `MobiusViewModel` in `OnboardingConsentScreen`

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/storage/PurgeDatabaseAndroidTest.kt, app/src/debug/java/org/simple/clinic/setup/SetupActivityConfigModule.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/bloodsugar/BloodSugarMeasurement.kt, app/src/main/java/org/simple/clinic/bp/BloodPressureMeasurement.kt, app/src/main/java/org/simple/clinic/drugs/PrescribedDrug.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt, app/src/main/java/org/simple/clinic/overdue/Appointment.kt, app/src/main/java/org/simple/clinic/overdue/callresult/CallResult.kt, app/src/main/java/org/simple/clinic/patient/Patient.kt, app/src/main/java/org/simple/clinic/questionnaire/Questionnaire.kt, app/src/main/java/org/simple/clinic/questionnaireresponse/QuestionnaireResponse.kt
https://app.shortcut.com/simpledotorg/story/13773/database-maintenance-screen-is-being-shown-every-time-app-is-opened-on-certain-devices
=> Fix app displaying database maintenance screen often during app startup

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/FakeMinimumMemoryChecker.kt, app/src/androidTest/java/org/simple/clinic/di/TestAppModule.kt, app/src/androidTest/java/org/simple/clinic/storage/DatabaseEncryptorTest.kt, app/src/main/java/org/simple/clinic/ClinicApp.kt, app/src/main/java/org/simple/clinic/di/AppModule.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityEffect.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityEffectHandler.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityEvent.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityInit.kt, app/src/main/java/org/simple/clinic/setup/SetupActivityUpdate.kt, app/src/main/java/org/simple/clinic/storage/DatabaseEncryptor.kt, app/src/test/java/org/simple/clinic/setup/SetupActivityEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/setup/SetupActivityInitTest.kt, app/src/test/java/org/simple/clinic/setup/SetupActivityUpdateTest.kt
Story details: https://app.shortcut.com/simpledotorg/story/14055
=> fix: [sc-14055] Fix app not closing all screens when user is unauthorized on certain devices

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/settings/SettingsScreenTest.kt, app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreen.kt, app/src/main/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenEffectHandler.kt, app/src/test/java/org/simple/clinic/bloodsugar/history/BloodSugarHistoryScreenEffectHandlerTest.kt
Story details: https://app.shortcut.com/simpledotorg/story/14112
=> fix: [sc-14112] Fix app crashing occasionally when viewing all blood sugar history

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt
Story details: https://app.shortcut.com/simpledotorg/story/14136
=> fix: [sc-14136] Fix app crashing occasionally when pressing back in patient summary screen

.github/workflows/ci_checks.yml, CHANGELOG.md, app/build.gradle.kts, gradle.properties
Story details: https://app.shortcut.com/simpledotorg/story/14173
=> chore: [sc-14173] Upload generated mapping file to Sentry

CHANGELOG.md, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryQuestion.kt, app/src/main/java/org/simple/clinic/medicalhistory/OngoingMedicalHistoryEntry.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryModel.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUi.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRenderer.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryModel.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUi.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUiRenderer.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryView.kt, app/src/main/res/layout/medicalhistory_summary_view.xml, app/src/main/res/layout/screen_new_medical_history.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryInitTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRendererTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryLogicTest.kt, app/src/test/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/14245/add-option-current-smoker-to-patient-history-for-non-lab-based-cv-risk-calculator
=> Add Current smoker question to patient enrolment and summary screen for statin nudge facilities

CHANGELOG.md, app/schemas/org.simple.clinic.AppDatabase/118.json, app/src/androidTest/java/org/simple/clinic/cvdrisk/CVDRiskRepositoryAndroidTest.kt, app/src/androidTest/java/org/simple/clinic/di/TestAppComponent.kt, app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration118AndroidTest.kt, app/src/androidTest/java/org/simple/clinic/sync/CVDRiskSyncIntegrationTest.kt, app/src/main/java/org/simple/clinic/AppDatabase.kt, app/src/main/java/org/simple/clinic/cvdrisk/CVDRisk.kt, app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskModule.kt, app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskRepository.kt, app/src/main/java/org/simple/clinic/cvdrisk/sync/CVDRiskPayload.kt, app/src/main/java/org/simple/clinic/cvdrisk/sync/CVDRiskPullResponse.kt, app/src/main/java/org/simple/clinic/cvdrisk/sync/CVDRiskPushRequest.kt, app/src/main/java/org/simple/clinic/cvdrisk/sync/CVDRiskSync.kt, app/src/main/java/org/simple/clinic/cvdrisk/sync/CVDRiskSyncApi.kt, app/src/main/java/org/simple/clinic/main/TypedPreference.kt, app/src/main/java/org/simple/clinic/storage/migrations/Migration_118.kt, app/src/main/java/org/simple/clinic/storage/migrations/RoomMigrationsModule.kt, app/src/main/java/org/simple/clinic/sync/SyncModule.kt, sharedTestCode/src/main/java/org/simple/sharedTestCode/TestData.kt
https://app.shortcut.com/simpledotorg/story/14259/add-cv-risk-score-to-android-app-sync-module?team_id=1&iteration_ids=14091
=> Add `CVDRisk` sync resource

app/src/main/java/org/simple/clinic/patientattribute/sync/PatientAttributePayload.kt, app/src/main/java/org/simple/clinic/patientattribute/sync/PatientAttributeSync.kt
https://app.shortcut.com/simpledotorg/story/14405/change-patient-attribute-height-and-weight-to-float?vc_group_by=day&ct_workflow=all&cf_workflow=500000031
=> Change `PatientAttributes` height and weight type to float

app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskCalculationSheet.kt, app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskCalculator.kt, app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskInput.kt, app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskModule.kt, app/src/test/java/org/simple/clinic/cvdrisk/CVDRiskCalculatorTest.kt, sharedTestCode/src/main/java/org/simple/sharedTestCode/TestData.kt
https://app.shortcut.com/simpledotorg/story/14050/save-cv-risk-score-json-model-to-database
=> Add CVD Risk Calculation sheet

CHANGELOG.md, app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt, app/src/main/java/org/simple/clinic/patientattribute/entry/BMIEntryEffect.kt, app/src/main/java/org/simple/clinic/patientattribute/entry/BMIEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/patientattribute/entry/BMIEntryEvent.kt, app/src/main/java/org/simple/clinic/patientattribute/entry/BMIEntryModel.kt, app/src/main/java/org/simple/clinic/patientattribute/entry/BMIEntrySheet.kt, app/src/main/java/org/simple/clinic/patientattribute/entry/BMIEntryUi.kt, app/src/main/java/org/simple/clinic/patientattribute/entry/BMIEntryUiRenderer.kt, app/src/main/java/org/simple/clinic/patientattribute/entry/BMIEntryUpdate.kt, app/src/main/res/drawable/background_bmi.xml, app/src/main/res/layout/sheet_bmi_reading.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/patientattribute/entry/BMIEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/patientattribute/entry/BMIEntryUiRendererTest.kt, app/src/test/java/org/simple/clinic/patientattribute/entry/BMIEntryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/14386/add-bmi-entry-sheet?vc_group_by=day&ct_workflow=all&cf_workflow=500000031
=> Add BMI entry sheet

app/src/main/java/org/simple/clinic/patientattribute/BMIReading.kt, app/src/main/java/org/simple/clinic/patientattribute/entry/BMIEntryUiRenderer.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/compose/StatinNudgeView.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/14054/update-statin-nudge-design-in-patient-summary-screen-to-display-risk-scale
=> Add smoking and bmi buttons to statin nudge

CHANGELOG.md, app/src/main/java/org/simple/clinic/cvdrisk/StatinInfo.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/compose/StatinNudgeView.kt, app/src/main/res/values/strings.xml, common-ui/src/main/java/org/simple/clinic/common/ui/theme/SimpleColors.kt
https://app.shortcut.com/simpledotorg/story/14054/update-statin-nudge-design-in-patient-summary-screen-to-display-risk-scale
=> Update statin nudge risk scale V2

CHANGELOG.md, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryView.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/14501/add-statin-phase-2-remote-config?vc_group_by=day&ct_workflow=all&cf_workflow=500000031
=> Add statin phase 2 remote config

CHANGELOG.md, lint/src/main/java/org/simple/clinic/lint/ImageSrcDetector.kt, lint/src/test/java/org/simple/clinic/lint/CardViewDetectorTest.kt, lint/src/test/java/org/simple/clinic/lint/ImageSrcDetectorTest.kt, lint/src/test/java/org/simple/clinic/lint/TextViewTextSizeDetectorTest.kt
This fixes broken test in `ImageSrcDetectorTest`
=> Add display name to `ImageView#src` lint fix

CHANGELOG.md, app/src/main/res/values-bn-rBD/strings.xml
https://app.shortcut.com/simpledotorg/story/14636/add-statin-phase-2-translations-for-bangla-sinhala-and-tamil-sri-lanka
=> Add Statin v2 translations for `bn-BD`

CHANGELOG.md, app/src/main/res/values-si-rLK/strings.xml, app/src/main/res/values-ta-rLK/strings.xml
https://app.shortcut.com/simpledotorg/story/14636/add-statin-phase-2-translations-for-bangla-sinhala-and-tamil-sri-lanka?team_id=1&iteration_ids=14465&iteration_ids=14489
=> Update statin phase 2 translations for `si-LK` and `ta-LK`

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, common-ui/src/main/res/values/styles.xml, common-ui/src/main/res/values/theme_overlay.xml
https://app.shortcut.com/simpledotorg/story/14639/statin-phase-2-bug-fixes
=> Fix smoking status dialog UI

CHANGELOG.md, app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskModule.kt, app/src/main/java/org/simple/clinic/feature/Feature.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryView.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/14659/fix-the-naming-for-feature-flags?vc_group_by=day&ct_workflow=all&cf_workflow=500000031
=> Rename statin nudge v2 feature flags

.github/workflows/ci_checks.yml, CHANGELOG.md, build.gradle.kts, gradle/libs.versions.toml, mobius-base/build.gradle.kts
**Story:** https://app.shortcut.com/simpledotorg/story/14667/clean-up-gh-actions-on-simple-android-repo
=> Clean up GH actions on Simple Android repo

CHANGELOG.md, app/src/main/java/org/simple/clinic/main/TheActivityComponent.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt, app/src/main/java/org/simple/clinic/summary/addcholesterol/CholesterolEntryEffect.kt, app/src/main/java/org/simple/clinic/summary/addcholesterol/CholesterolEntryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/addcholesterol/CholesterolEntryEvent.kt, app/src/main/java/org/simple/clinic/summary/addcholesterol/CholesterolEntryModel.kt, app/src/main/java/org/simple/clinic/summary/addcholesterol/CholesterolEntrySaveState.kt, app/src/main/java/org/simple/clinic/summary/addcholesterol/CholesterolEntrySheet.kt, app/src/main/java/org/simple/clinic/summary/addcholesterol/CholesterolEntryUi.kt, app/src/main/java/org/simple/clinic/summary/addcholesterol/CholesterolEntryUiActions.kt, app/src/main/java/org/simple/clinic/summary/addcholesterol/CholesterolEntryUiRenderer.kt, app/src/main/java/org/simple/clinic/summary/addcholesterol/CholesterolEntryUpdate.kt, app/src/main/java/org/simple/clinic/summary/addcholesterol/CholesterolEntryViewEffectHandler.kt, app/src/main/res/layout/sheet_cholesterol_entry.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/summary/addcholesterol/CholesterolEntryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/addcholesterol/CholesterolEntryUiRendererTest.kt, app/src/test/java/org/simple/clinic/summary/addcholesterol/CholesterolEntryUpdateTest.kt
**Story:** https://app.shortcut.com/simpledotorg/story/14623/add-cholesterol-entry-sheet
=> Add `CholesterolEntrySheet`

app/src/main/java/org/simple/clinic/cvdrisk/StatinInfo.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewRenderer.kt, app/src/main/java/org/simple/clinic/summary/addcholesterol/CholesterolEntrySheet.kt, app/src/main/java/org/simple/clinic/summary/compose/StatinNudgeView.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryViewRendererTest.kt
**Story:** https://app.shortcut.com/simpledotorg/story/14629/update-statin-nudge-design-for-lab-based-cvd-risk-score
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #5283 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #5282
=> Update statin nudge view copy

app/src/main/java/org/simple/clinic/cvdrisk/StatinInfo.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt, app/src/main/java/org/simple/clinic/medicalhistory/sync/MedicalHistoryPayload.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewEffectHandler.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
**Story:** https://app.shortcut.com/simpledotorg/story/14632/calculate-lab-based-cvd-risk-score-when-conditions-are-met
=> Calculate and load lab-based statin info if lab based statin nudge feature flag is enabled

.github/docker/simple-server.compose.yml, .github/workflows/ci_checks.yml
**Story:** https://app.shortcut.com/simpledotorg/story/14932/upload-docker-logs-at-end-of-integration-test-run-on-ci
=> Extract and upload Docker logs in CI checks

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/compose/StatinNudgeView.kt
https://app.shortcut.com/simpledotorg/story/15468/update-statin-lab-nudge-min-threshold-to-20
=> Increase lab based risk threshold to 20%

CHANGELOG.md, app/build.gradle.kts, app/src/main/java/org/simple/clinic/drugs/search/DrugsSearchScreen.kt, app/src/main/java/org/simple/clinic/editpatient/EditPatientScreen.kt, app/src/main/java/org/simple/clinic/facility/change/FacilityChangeScreen.kt, app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt, app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt, app/src/main/java/org/simple/clinic/main/TheActivity.kt, app/src/main/java/org/simple/clinic/newentry/PatientEntryScreen.kt, app/src/main/java/org/simple/clinic/onboarding/OnboardingScreen.kt, app/src/main/java/org/simple/clinic/registerorlogin/AuthenticationActivity.kt, app/src/main/java/org/simple/clinic/registration/facility/RegistrationFacilitySelectionScreen.kt, app/src/main/java/org/simple/clinic/scheduleappointment/facilityselection/FacilitySelectionScreen.kt, app/src/main/java/org/simple/clinic/settings/changelanguage/ChangeLanguageScreen.kt, app/src/main/java/org/simple/clinic/setup/SetupActivity.kt, app/src/main/java/org/simple/clinic/util/FragmentExt.kt, app/src/main/java/org/simple/clinic/widgets/BottomSheetActivity.kt, gradle/libs.versions.toml
**Story:** https://app.shortcut.com/simpledotorg/story/15545/enable-edge-to-edge-support-on-all-versions-of-android
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #5428 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #5408
=> Enable edge-to-edge support on all versions of Android

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/assignedfacility/AssignedFacilityView.kt, app/src/main/java/org/simple/clinic/summary/assignedfacility/ui/AssignedFacility.kt, common-ui/src/main/java/org/simple/clinic/common/ui/components/Button.kt, gradle.properties
https://app.shortcut.com/simpledotorg/story/15919/migrate-follow-up-appointment-container-to-jetpack-compose?team_id=1&iteration_ids=15786
=> Migrate `AssignedFacilityView` to compose

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/widgets/compose/PatientStatusView.kt, app/src/main/res/layout/screen_patient_summary.xml
https://app.shortcut.com/simpledotorg/story/15922/migrate-patient-status-view-to-jetpack-compose
=> Migrate patient status view to Jetpack Compose

CHANGELOG.md, gradle/libs.versions.toml
https://app.shortcut.com/simpledotorg/story/16099/update-sqllite-android-to-latest-version?team_id=1&iteration_ids=15786&iteration_ids=16015
=> Bump sqlite-android version to 3.49.0

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/summary/statin/StatinNudgeTest.kt, app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskRange.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/compose/StatinNudgeDescription.kt, app/src/main/java/org/simple/clinic/summary/compose/StatinNudgeView.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/16207/update-the-non-lab-based-threshold-value-to-20-for-sri-lanka?team_id=1&iteration_ids=16152
=> Update statin risk threshold to 20% for sri Lanka

CHANGELOG.md, app/src/androidTest/java/org/simple/clinic/summary/statin/StatinNudgeTest.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEffect.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryEvent.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryModel.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUiActions.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryUpdate.kt, app/src/main/java/org/simple/clinic/summary/PatientSummaryViewEffectHandler.kt, app/src/main/java/org/simple/clinic/summary/compose/StatinNudgeView.kt, app/src/main/res/values-am-rET/strings.xml, app/src/main/res/values-bn-rBD/strings.xml, app/src/main/res/values-bn-rIN/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-hi-rIN/strings.xml, app/src/main/res/values-kn-rIN/strings.xml, app/src/main/res/values-mr-rIN/strings.xml, app/src/main/res/values-om-rET/strings.xml, app/src/main/res/values-pa-rIN/strings.xml, app/src/main/res/values-si-rLK/strings.xml, app/src/main/res/values-sid-rET/strings.xml, app/src/main/res/values-so-rET/strings.xml, app/src/main/res/values-ta-rIN/strings.xml, app/src/main/res/values-ta-rLK/strings.xml, app/src/main/res/values-te-rIN/strings.xml, app/src/main/res/values-ti-rET/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/summary/PatientSummaryEffectHandlerTest.kt, app/src/test/java/org/simple/clinic/summary/PatientSummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/16286/update-tobacco-options-in-smoker-dialog
=> Update smoking dialog to a multi-choice tobacco dialog

CHANGELOG.md, app/src/main/java/org/simple/clinic/summary/PatientSummaryScreen.kt, app/src/main/res/values/strings.xml
https://app.shortcut.com/simpledotorg/story/16332/changes-smoker-to-smokes?team_id=1&iteration_ids=16152
=> Rename `Smoker` to `Smokes`

app/src/androidTest/java/org/simple/clinic/medicalhistory/MedicalHistoryRepositoryAndroidTest.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistory.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryQuestion.kt, app/src/main/java/org/simple/clinic/medicalhistory/MedicalHistoryRepository.kt, app/src/main/java/org/simple/clinic/medicalhistory/OngoingMedicalHistoryEntry.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryModel.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUi.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRenderer.kt, app/src/main/java/org/simple/clinic/medicalhistory/ui/TobaccoQuestion.kt, app/src/main/java/org/simple/clinic/patient/onlinelookup/api/LookupPatientOnline.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryModel.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUi.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUiRenderer.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryView.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/ui/MedicalHistorySummary.kt, app/src/main/res/layout/screen_new_medical_history.xml, app/src/main/res/values-bn-rBD/strings.xml, app/src/main/res/values-si-rLK/strings.xml, app/src/main/res/values-ta-rLK/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryInitTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreenLogicTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRendererTest.kt, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdateTest.kt, app/src/test/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryLogicTest.kt, app/src/test/java/org/simple/clinic/summary/medicalhistory/MedicalHistorySummaryUpdateTest.kt
https://app.shortcut.com/simpledotorg/story/16405/update-ui-to-include-smoking-and-smokeless-tobacco-options?team_id=1&iteration_ids=16420
=> Update UI to include Smokeless tobacco option in medical history questions

app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryScreen.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUi.kt, app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRenderer.kt, app/src/main/java/org/simple/clinic/medicalhistory/ui/HistoryContainer.kt, app/src/main/java/org/simple/clinic/summary/medicalhistory/ui/MedicalHistorySummary.kt, app/src/main/res/layout/screen_new_medical_history.xml, app/src/main/res/values-am-rET/strings.xml, app/src/main/res/values-bn-rBD/strings.xml, app/src/main/res/values-bn-rIN/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-hi-rIN/strings.xml, app/src/main/res/values-kn-rIN/strings.xml, app/src/main/res/values-mr-rIN/strings.xml, app/src/main/res/values-om-rET/strings.xml, app/src/main/res/values-pa-rIN/strings.xml, app/src/main/res/values-si-rLK/strings.xml, app/src/main/res/values-sid-rET/strings.xml, app/src/main/res/values-so-rET/strings.xml, app/src/main/res/values-ta-rIN/strings.xml, app/src/main/res/values-ta-rLK/strings.xml, app/src/main/res/values-te-rIN/strings.xml, app/src/main/res/values-ti-rET/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUiRendererTest.kt
https://app.shortcut.com/simpledotorg/story/16596/migrate-history-questions-to-ui-compose?team_id=1&iteration_ids=16550
=> Migrate new medical history question container to jetpack compose

app/src/main/java/org/simple/clinic/medicalhistory/newentry/NewMedicalHistoryUpdate.kt, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneModel.kt, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUpdate.kt
https://app.shortcut.com/simpledotorg/story/16445/prevent-users-to-click-next-button-when-a-call-is-already-in-queue
=> Prevent multiple user lookup api calls 

CHANGELOG.md, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneScreen.kt, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUi.kt, app/src/main/java/org/simple/clinic/registration/phone/RegistrationPhoneUiRenderer.kt, app/src/test/java/org/simple/clinic/registration/phone/RegistrationPhoneScreenLogicTest.kt
https://app.shortcut.com/simpledotorg/story/16651/create-jetpack-compose-button-with-loading-and-enable-disable-state?team_id=1&iteration_ids=16689
https://github.com/user-attachments/assets/9dd0f044-9c8a-44f6-a34a-bed655c08c4e
=> Hide next button when registration is going
